// Audemars Piguet collections, filters, and SEO data

const AP_COLLECTION_ASSET_BASE = '/brand-assets/audemars-piguet/collections';
const AP_PAGE_ASSET_BASE = '/brand-assets/audemars-piguet/page';

const COLLECTION_IMAGES = {
  royalOak: `${AP_COLLECTION_ASSET_BASE}/audemars-piguet-royal-oak-collection.png`,
  royalOakOffshore: `${AP_COLLECTION_ASSET_BASE}/audemars-piguet-royal-oak-offshore-collection.png`,
  royalOakConcept: `${AP_COLLECTION_ASSET_BASE}/audemars-piguet-royal-oak-concept-collection.png`,
  code1159: `${AP_COLLECTION_ASSET_BASE}/audemars-piguet-code-1159-collection.png`,
};

export const AP_PAGE_IMAGES = {
  hero: `${AP_PAGE_ASSET_BASE}/ap-hero.png`,
  story: `${AP_PAGE_ASSET_BASE}/ap-story.webp`,
  royalOakGuide: `${AP_PAGE_ASSET_BASE}/ap-royal-oak-guide.webp`,
  royalOakOffshoreGuide: `${AP_PAGE_ASSET_BASE}/ap-royal-oak-offshore-guide.avif`,
  preOwnedGuide: `${AP_PAGE_ASSET_BASE}/ap-pre-owned-guide.webp`,
  priceGuide: `${AP_PAGE_ASSET_BASE}/ap-price-guide.jpg`,
};

export const AP_HERO_IMAGE = AP_PAGE_IMAGES.hero;
export const AP_STORY_IMAGE = AP_PAGE_IMAGES.story;

export const AP_COLLECTIONS = [
  { id: 1, name: 'Royal Oak', slug: 'royal-oak', image: COLLECTION_IMAGES.royalOak, shortDescription_en: 'The iconic octagonal integrated bracelet sports watch designed by Gerald Genta in 1972 — AP\u2019s signature collection with Tapisserie dials and refined finishing.', shortDescription_de: 'Die ikonische achtkantige Luxus-Sportuhr mit integriertem Armband, entworfen von Gerald Genta 1972 — APs signatur Kollektion mit Tapisserie-Zifferblättern und verfeinelter Oberflächenbearbeitung.' },
  { id: 2, name: 'Royal Oak Offshore', slug: 'royal-oak-offshore', image: COLLECTION_IMAGES.royalOakOffshore, shortDescription_en: 'A bolder, sportier, and larger interpretation of the Royal Oak, launched in 1993 with robust construction and a strong, assertive wrist presence.', shortDescription_de: 'Eine kühnere, sportlichere und größere Interpretation der Royal Oak, 1993 lanciert mit robuster Konstruktion und einer starken, markanten Handgelenkspräsenz.' },
  { id: 3, name: 'Royal Oak Concept', slug: 'royal-oak-concept', image: COLLECTION_IMAGES.royalOakConcept, shortDescription_en: 'A technical and futuristic line of high-complication AP watches, featuring tourbillons, GMTs, and avant-garde materials and case architecture.', shortDescription_de: 'Eine technische und futuristische Linie von hochkomplizierten AP-Uhren mit Tourbillons, GMTs und avantgardistischen Materialien und Gehäusearchitekturen.' },
  { id: 4, name: 'Code 11.59', slug: 'code-1159', image: COLLECTION_IMAGES.code1159, shortDescription_en: 'A modern round-case collection revealed in 2019, offering complications, dressier character, and refined finishes alongside the Royal Oak families.', shortDescription_de: 'Eine moderne Rundgehäuse-Kollektion, die 2019 vorgestellt wurde, mit Komplikationen, eleganterem Charakter und verfeinerten Oberflächen neben den Royal Oak-Familien.' },
];

export const AP_CASE_MATERIALS = ['Stainless Steel', 'Rose Gold', 'Yellow Gold', 'White Gold', 'Platinum', 'Titanium', 'Ceramic', 'Black Ceramic', 'White Ceramic', 'Carbon', 'Two-tone / Bicolor', 'Gem-set'];
export const AP_SHAPES = ['Octagonal', 'Round', 'Tonneau / Concept-style case'];
export const AP_MOVEMENTS = ['Automatic', 'Self-winding', 'Manual-winding', 'Chronograph', 'Quartz', 'Tourbillon'];
export const AP_COMPLICATIONS = ['Chronograph', 'Perpetual Calendar', 'Tourbillon', 'GMT', 'Minute repeater / Supersonnerie', 'Date', 'Time only'];
export const AP_FEATURES = ['Integrated bracelet', 'Openworked / Skeleton', 'Tapisserie dial', 'Chronograph', 'Perpetual calendar', 'Tourbillon', 'GMT', 'Extra-thin', 'Frosted gold', 'Ceramic case', 'Limited edition', 'Boutique edition', 'Full set', 'Collector model'];
export const AP_DIAL_COLORS = ['Black', 'Blue', 'Green', 'Grey', 'White', 'Silver', 'Brown', 'Anthracite', 'Champagne', 'Mother of Pearl', 'Skeleton / Openworked', 'Purple', 'Salmon'];
export const AP_BRACELETS = ['Steel bracelet', 'Titanium bracelet', 'Gold bracelet', 'Rubber strap', 'Leather strap', 'Alligator leather', 'Integrated bracelet', 'Textile'];
export const AP_CASE_SIZES = ['34 mm', '37 mm', '38 mm', '39 mm', '41 mm', '42 mm', '43 mm', '44 mm'];
export const AP_AVAILABILITY = ['In Stock', 'Reserved', 'Coming Soon', 'Sold'];
export const AP_BOX_PAPERS = ['Box included', 'Papers included', 'Full set'];
export const AP_TYPES = ['New', 'Pre-Owned', 'Vintage'];

export const AP_QUICK_FILTERS = [
  { label_en: 'Royal Oak', label_de: 'Royal Oak', link: '/audemars-piguet/royal-oak', filter: { collection: 'Royal Oak' } },
  { label_en: 'Royal Oak Offshore', label_de: 'Royal Oak Offshore', link: '/audemars-piguet/royal-oak-offshore', filter: { collection: 'Royal Oak Offshore' } },
  { label_en: 'Royal Oak Concept', label_de: 'Royal Oak Concept', link: '/audemars-piguet/royal-oak-concept', filter: { collection: 'Royal Oak Concept' } },
  { label_en: 'Code 11.59', label_de: 'Code 11.59', link: '/audemars-piguet/code-1159', filter: { collection: 'Code 11.59' } },
  { label_en: 'Pre-Owned AP', label_de: 'Gebrauchte AP', link: '/audemars-piguet-gebraucht', filter: { preOwned: true } },
];

export const AP_SEO_CARDS = [
  { title_en: 'Audemars Piguet Watch', title_de: 'Audemars Piguet Uhr', description_en: 'Explore Audemars Piguet watches at Kariv Glamour with transparent product details, reference numbers and a premium collector-focused shopping experience.', description_de: 'Entdecken Sie Audemars Piguet Uhren bei Kariv Glamour mit transparenten Produktdetails, Referenznummern und einem premium sammlerorientierten Einkaufserlebnis.', link: '/audemars-piguet-uhr', image: AP_PAGE_IMAGES.hero },
  { title_en: 'Audemars Piguet Watches', title_de: 'Audemars Piguet Uhren', description_en: 'Browse the full Audemars Piguet collection including Royal Oak, Royal Oak Offshore, Royal Oak Concept and Code 11.59.', description_de: 'Stöbern Sie durch die gesamte Audemars Piguet Kollektion inklusive Royal Oak, Royal Oak Offshore, Royal Oak Concept und Code 11.59.', link: '/audemars-piguet-uhren', image: AP_PAGE_IMAGES.story },
  { title_en: 'Audemars Piguet Royal Oak', title_de: 'Audemars Piguet Royal Oak', description_en: 'Discover the iconic Audemars Piguet Royal Oak with its octagonal bezel, integrated bracelet and signature Tapisserie dial.', description_de: 'Entdecken Sie die ikonische Audemars Piguet Royal Oak mit ihrer achtkantigen Lünette, dem integrierten Armband und dem markanten Tapisserie-Zifferblatt.', link: '/audemars-piguet/royal-oak', image: AP_PAGE_IMAGES.royalOakGuide },
  { title_en: 'Audemars Piguet Royal Oak Offshore', title_de: 'Audemars Piguet Royal Oak Offshore', description_en: 'Browse Royal Oak Offshore watches — bolder, sportier, and larger interpretations of the legendary Royal Oak.', description_de: 'Stöbern Sie durch Royal Oak Offshore Uhren — kühnere, sportlichere und größere Interpretationen der legendären Royal Oak.', link: '/audemars-piguet/royal-oak-offshore', image: AP_PAGE_IMAGES.royalOakOffshoreGuide },
  { title_en: 'Audemars Piguet Watches for Men', title_de: 'Audemars Piguet Uhren Herren', description_en: 'Discover Audemars Piguet watches for men, from the Royal Oak to the Royal Oak Offshore and Code 11.59.', description_de: 'Entdecken Sie Audemars Piguet Uhren für Herren, von der Royal Oak bis zur Royal Oak Offshore und Code 11.59.', link: '/audemars-piguet-uhr-herren', image: AP_PAGE_IMAGES.priceGuide },
  { title_en: 'Pre-Owned Audemars Piguet', title_de: 'Audemars Piguet gebraucht', description_en: 'Explore pre-owned Audemars Piguet watches with transparent condition grading, box and papers information and product-specific details.', description_de: 'Entdecken Sie gebrauchte Audemars Piguet Uhren mit transparenter Zustandsbewertung, Box und Papiere Informationen und produktspezifischen Details.', link: '/audemars-piguet-gebraucht', image: AP_PAGE_IMAGES.preOwnedGuide },
];

export const AP_READ_MORE = [
  { title_en: 'Audemars Piguet Story', title_de: 'Audemars Piguet Story', description_en: 'Explore AP\u2019s heritage of bold case architecture, integrated bracelet design, high-end finishing and complications.', description_de: 'Entdecken Sie APs Erbe von kühner Gehäusearchitektur, integriertem Armbanddesign, hochwertiger Oberflächenbearbeitung und Komplikationen.', link: '/audemars-piguet/story', image: AP_PAGE_IMAGES.story },
  { title_en: 'Royal Oak Guide', title_de: 'Royal Oak Guide', description_en: 'Learn what makes the Royal Oak one of the most iconic luxury sports watches in watchmaking history.', description_de: 'Erfahren Sie, was die Royal Oak zu einer der ikonischsten Luxus-Sportuhren der Uhrmachergeschichte macht.', link: '/audemars-piguet/royal-oak', image: AP_PAGE_IMAGES.royalOakGuide },
  { title_en: 'Royal Oak Offshore Guide', title_de: 'Royal Oak Offshore Guide', description_en: 'Discover the Royal Oak Offshore — a bolder, sportier interpretation of the legendary Royal Oak since 1993.', description_de: 'Entdecken Sie die Royal Oak Offshore — eine kühnere, sportlichere Interpretation der legendären Royal Oak seit 1993.', link: '/audemars-piguet/royal-oak-offshore', image: AP_PAGE_IMAGES.royalOakOffshoreGuide },
  { title_en: 'Pre-Owned AP Guide', title_de: 'Gebrauchte AP Guide', description_en: 'Understand condition, box and papers, service history and what to check before buying a used Audemars Piguet.', description_de: 'Verstehen Sie Zustand, Box und Papiere, Service-Historie und worauf Sie vor dem Kauf einer gebrauchten Audemars Piguet achten sollten.', link: '/audemars-piguet-gebraucht', image: AP_PAGE_IMAGES.preOwnedGuide },
  { title_en: 'AP Price Guide', title_de: 'AP Preis-Guide', description_en: 'Understand Audemars Piguet pricing across collections, materials, complications and reference numbers.', description_de: 'Verstehen Sie die Audemars Piguet Preisstruktur über Kollektionen, Materialien, Komplikationen und Referenznummern hinweg.', link: '/audemars-piguet-uhr-preis', image: AP_PAGE_IMAGES.priceGuide },
];

export const AP_INTERNAL_LINKS = [
  {
    title_en: 'Popular AP Searches', title_de: 'Beliebte AP Suchen',
    links: [
      { label_en: 'Audemars Piguet Watch', label_de: 'Audemars Piguet Uhr', to: '/audemars-piguet-uhr' },
      { label_en: 'Audemars Piguet Watches', label_de: 'Audemars Piguet Uhren', to: '/audemars-piguet-uhren' },
      { label_en: 'Audemars Piguet Watches for Men', label_de: 'Audemars Piguet Uhren Herren', to: '/audemars-piguet-uhr-herren' },
      { label_en: 'Audemars Piguet Watches for Women', label_de: 'Audemars Piguet Uhren Damen', to: '/audemars-piguet-uhr-damen' },
      { label_en: 'Pre-Owned Audemars Piguet', label_de: 'Audemars Piguet gebraucht', to: '/audemars-piguet-gebraucht' },
      { label_en: 'Audemars Piguet with box and papers', label_de: 'Audemars Piguet mit Box und Papieren', to: '/guides' },
    ],
  },
  {
    title_en: 'AP Collections', title_de: 'AP Kollektionen',
    links: [
      { label_en: 'Royal Oak', label_de: 'Royal Oak', to: '/audemars-piguet/royal-oak' },
      { label_en: 'Royal Oak Offshore', label_de: 'Royal Oak Offshore', to: '/audemars-piguet/royal-oak-offshore' },
      { label_en: 'Royal Oak Concept', label_de: 'Royal Oak Concept', to: '/audemars-piguet/royal-oak-concept' },
      { label_en: 'Code 11.59', label_de: 'Code 11.59', to: '/audemars-piguet/code-1159' },
    ],
  },
  {
    title_en: 'Product-Specific Pages', title_de: 'Produktspezifische Seiten',
    links: [
      { label_en: 'Buy Audemars Piguet', label_de: 'Audemars Piguet kaufen', to: '/audemars-piguet-kaufen' },
      { label_en: 'Buy Audemars Piguet Watch', label_de: 'Audemars Piguet Uhr kaufen', to: '/audemars-piguet-uhr-kaufen' },
      { label_en: 'Buy Royal Oak', label_de: 'Royal Oak kaufen', to: '/audemars-piguet-royal-oak-kaufen' },
      { label_en: 'Buy Royal Oak Offshore', label_de: 'Royal Oak Offshore kaufen', to: '/audemars-piguet-royal-oak-offshore-kaufen' },
      { label_en: 'Buy Code 11.59', label_de: 'Code 11.59 kaufen', to: '/audemars-piguet-code-1159-kaufen' },
    ],
  },
  {
    title_en: 'Related Watch Categories', title_de: 'Verwandte Uhrenkategorien',
    links: [
      { label_en: 'Certified Pre-Owned Watches', label_de: 'Zertifizierte gebrauchte Uhren', to: '/shop?isCertifiedPreOwned=true' },
      { label_en: 'Men\u2019s watches', label_de: 'Herrenuhren', to: '/shop?gender=Men' },
      { label_en: 'Women\u2019s watches', label_de: 'Damenuhren', to: '/shop?gender=Women' },
      { label_en: 'Chronograph Watches', label_de: 'Chronographen', to: '/shop' },
      { label_en: 'Luxury Sports Watches', label_de: 'Luxus-Sportuhren', to: '/shop' },
      { label_en: 'Tourbillon Watches', label_de: 'Tourbillon-Uhren', to: '/shop' },
      { label_en: 'Limited Edition Watches', label_de: 'Limitierte Auflagen', to: '/shop' },
    ],
  },
  {
    title_en: 'Related Luxury Watch Brands', title_de: 'Verwandte Luxusuhren-Marken',
    links: [
      { label_en: 'Rolex watches', label_de: 'Rolex Uhren', to: '/brands/rolex' },
      { label_en: 'Patek Philippe watches', label_de: 'Patek Philippe Uhren', to: '/brands/patek-philippe' },
      { label_en: 'Hublot watches', label_de: 'Hublot Uhren', to: '/brands/hublot' },
      { label_en: 'Breitling watches', label_de: 'Breitling Uhren', to: '/brands/breitling' },
      { label_en: 'Omega watches', label_de: 'Omega Uhren', to: '/brands/omega' },
      { label_en: 'Cartier watches', label_de: 'Cartier Uhren', to: '/brands/cartier' },
    ],
  },
];

export const AP_FAQS = [
  { q_en: 'Where can I buy an Audemars Piguet watch online?', q_de: 'Wo kann ich online eine Audemars Piguet Uhr kaufen?', a_en: "You can buy Audemars Piguet watches online at Kariv Glamour. Browse new and <a href='/audemars-piguet-gebraucht'>pre-owned AP watches</a> with transparent product details, reference numbers and condition grading.", a_de: "Sie können Audemars Piguet Uhren online bei Kariv Glamour kaufen. Stöbern Sie durch neue und <a href='/audemars-piguet-gebraucht'>gebrauchte AP-Uhren</a> mit transparenten Produktdetails, Referenznummern und Zustandsbewertung." },
  { q_en: 'Is it safe to buy a pre-owned Audemars Piguet watch?', q_de: 'Ist es sicher, eine gebrauchte Audemars Piguet Uhr zu kaufen?', a_en: "Yes. Buying <a href='/audemars-piguet-gebraucht'>pre-owned Audemars Piguet</a> from Kariv Glamour includes clear condition grading, <a href='/guides'>box and papers</a> information, and <a href='/buyer-protection'>buyer protection</a> for eligible purchases.", a_de: "Ja. Der Kauf von <a href='/audemars-piguet-gebraucht'>gebrauchten Audemars Piguet</a> Uhren bei Kariv Glamour umfasst klare Zustandsbewertung, <a href='/guides'>Box und Papiere</a> Informationen und <a href='/buyer-protection'>Käuferschutz</a> für berechtigte Käufe." },
  { q_en: 'What are the most popular Audemars Piguet collections?', q_de: 'Was sind die beliebtesten Audemars Piguet Kollektionen?', a_en: "The main Audemars Piguet collections are the <a href='/audemars-piguet/royal-oak'>Royal Oak</a>, <a href='/audemars-piguet/royal-oak-offshore'>Royal Oak Offshore</a>, <a href='/audemars-piguet/royal-oak-concept'>Royal Oak Concept</a>, and <a href='/audemars-piguet/code-1159'>Code 11.59</a>.", a_de: "Die wichtigsten Audemars Piguet Kollektionen sind die <a href='/audemars-piguet/royal-oak'>Royal Oak</a>, <a href='/audemars-piguet/royal-oak-offshore'>Royal Oak Offshore</a>, <a href='/audemars-piguet/royal-oak-concept'>Royal Oak Concept</a> und <a href='/audemars-piguet/code-1159'>Code 11.59</a>." },
  { q_en: 'What is the difference between Royal Oak and Royal Oak Offshore?', q_de: 'Was ist der Unterschied zwischen Royal Oak und Royal Oak Offshore?', a_en: "The <a href='/audemars-piguet/royal-oak'>Royal Oak</a> is the original 1972 integrated bracelet sports watch with a refined, versatile character, while the <a href='/audemars-piguet/royal-oak-offshore'>Royal Oak Offshore</a> launched in 1993 as a bolder, sportier, and larger interpretation.", a_de: "Die <a href='/audemars-piguet/royal-oak'>Royal Oak</a> ist die originale Luxus-Sportuhr von 1972 mit integriertem Armband und einem verfeinerten, vielseitigen Charakter, während die <a href='/audemars-piguet/royal-oak-offshore'>Royal Oak Offshore</a> 1993 als kühnere, sportlichere und größere Interpretation lanciert wurde." },
  { q_en: 'What is the Audemars Piguet Code 11.59 collection?', q_de: 'Was ist die Audemars Piguet Code 11.59 Kollektion?', a_en: "<a href='/audemars-piguet/code-1159'>Code 11.59</a> is a modern round-case collection revealed in 2019, offering complications, dressier character, and refined finishes alongside the Royal Oak families.", a_de: "<a href='/audemars-piguet/code-1159'>Code 11.59</a> ist eine moderne Rundgehäuse-Kollektion, die 2019 vorgestellt wurde, mit Komplikationen, eleganterem Charakter und verfeinerten Oberflächen neben den Royal Oak-Familien." },
  { q_en: 'What is the Royal Oak Concept line?', q_de: 'Was ist die Royal Oak Concept Linie?', a_en: "The <a href='/audemars-piguet/royal-oak-concept'>Royal Oak Concept</a> is a technical and futuristic line of high-complication AP watches featuring tourbillons, GMTs, and avant-garde materials and case architecture.", a_de: "Die <a href='/audemars-piguet/royal-oak-concept'>Royal Oak Concept</a> ist eine technische und futuristische Linie von hochkomplizierten AP-Uhren mit Tourbillons, GMTs und avantgardistischen Materialien und Gehäusearchitekturen." },
  { q_en: 'How much does an Audemars Piguet watch cost?', q_de: 'Wie viel kostet eine Audemars Piguet Uhr?', a_en: "Audemars Piguet prices vary widely depending on collection, material, complication, and reference. Visit our <a href='/audemars-piguet-uhr-preis'>AP price guide</a> to learn more about pricing across collections.", a_de: "Audemars Piguet Preise variieren stark je nach Kollektion, Material, Komplikation und Referenz. Besuchen Sie unseren <a href='/audemars-piguet-uhr-preis'>AP Preis-Guide</a>, um mehr über die Preisstruktur der Kollektionen zu erfahren." },
  { q_en: 'Can I sell my Audemars Piguet watch?', q_de: 'Kann ich meine Audemars Piguet Uhr verkaufen?', a_en: "Yes. If you want to sell your Audemars Piguet watch, visit our <a href='/sell-trade'>sell and trade page</a> for a professional valuation and transparent process.", a_de: "Ja. Wenn Sie Ihre Audemars Piguet Uhr verkaufen möchten, besuchen Sie unsere <a href='/sell-trade'>Verkaufs- und Tauschseite</a> für eine professionelle Bewertung und einen transparenten Prozess." },
];

export const AP_SEO_PAGES = {
  'audemars-piguet-uhr': { h1_en: 'Audemars Piguet Watch', h1_de: 'Audemars Piguet Uhr', title_en: 'Audemars Piguet Watch | Kariv Glamour', title_de: 'Audemars Piguet Uhr | Kariv Glamour', description_en: 'Explore Audemars Piguet watches at Kariv Glamour with transparent product information.', description_de: 'Entdecken Sie Audemars Piguet Uhren bei Kariv Glamour mit transparenter Produktinformation.', intro_en: 'Explore Audemars Piguet watches at Kariv Glamour — with clear product details, reference numbers and condition grading.', intro_de: 'Erkunden Sie Audemars Piguet Uhren bei Kariv Glamour \u2013 mit klaren Produktdetails, Referenznummern und Zustandsbewertung.', filter: {} },
  'audemars-piguet-uhren': { h1_en: 'Audemars Piguet Watches', h1_de: 'Audemars Piguet Uhren', title_en: 'Audemars Piguet Watches | Kariv Glamour', title_de: 'Audemars Piguet Uhren | Kariv Glamour', description_en: 'Audemars Piguet watches at Kariv Glamour — Royal Oak, Royal Oak Offshore, Royal Oak Concept and Code 11.59.', description_de: 'Audemars Piguet Uhren bei Kariv Glamour \u2013 Royal Oak, Royal Oak Offshore, Royal Oak Concept und Code 11.59.', intro_en: 'Browse Audemars Piguet watches by collection, material, movement, case size, condition and price.', intro_de: 'St\u00f6bern Sie durch Audemars Piguet Uhren nach Kollektion, Material, Uhrwerk, Geh\u00e4usegr\u00f6\u00dfe, Zustand und Preis.', filter: {} },
  'audemars-piguet-uhr-herren': { h1_en: 'Audemars Piguet Watches for Men', h1_de: 'Audemars Piguet Uhren Herren', title_en: 'Audemars Piguet Watches for Men | Kariv Glamour', title_de: 'Audemars Piguet Uhr Herren | Kariv Glamour', description_en: 'Audemars Piguet watches for men at Kariv Glamour — Royal Oak and Royal Oak Offshore for men.', description_de: 'Audemars Piguet Uhr Herren bei Kariv Glamour \u2013 Royal Oak und Royal Oak Offshore f\u00fcr M\u00e4nner.', intro_en: 'Discover Audemars Piguet watches for men — from the iconic Royal Oak to the Royal Oak Offshore and Code 11.59.', intro_de: 'Entdecken Sie Audemars Piguet Uhren f\u00fcr Herren \u2013 von der ikonischen Royal Oak bis zur Royal Oak Offshore und Code 11.59.', filter: { gender: 'Men' } },
  'audemars-piguet-uhr-damen': { h1_en: 'Audemars Piguet Watches for Women', h1_de: 'Audemars Piguet Uhren Damen', title_en: 'Audemars Piguet Watches for Women | Kariv Glamour', title_de: 'Audemars Piguet Uhr Damen | Kariv Glamour', description_en: 'Audemars Piguet watches for women at Kariv Glamour — elegant AP models in smaller case sizes.', description_de: 'Audemars Piguet Uhr Damen bei Kariv Glamour \u2013 elegante AP Modelle in kleineren Geh\u00e4usegr\u00f6\u00dfen.', intro_en: 'Discover Audemars Piguet watches for women, including smaller Royal Oak models and elegant variants.', intro_de: 'Entdecken Sie Audemars Piguet Uhren f\u00fcr Damen, darunter kleinere Royal Oak Modelle und elegante Varianten.', filter: { gender: 'Women' } },
  'audemars-piguet-gebraucht': { h1_en: 'Pre-Owned Audemars Piguet', h1_de: 'Audemars Piguet gebraucht', title_en: 'Pre-Owned Audemars Piguet | Kariv Glamour', title_de: 'Audemars Piguet gebraucht | Kariv Glamour', description_en: 'Pre-owned Audemars Piguet watches at Kariv Glamour with transparent condition grading.', description_de: 'Gebrauchte Audemars Piguet Uhren bei Kariv Glamour mit transparenter Zustandsbewertung.', intro_en: 'Discover pre-owned Audemars Piguet watches with clear condition grading, box and papers information and detailed product data.', intro_de: 'Entdecken Sie gebrauchte Audemars Piguet Uhren mit klarer Zustandsbewertung, Box und Papers Informationen und detaillierten Produktdaten.', filter: {} },
  'audemars-piguet-kaufen': { h1_en: 'Buy Audemars Piguet', h1_de: 'Audemars Piguet kaufen', title_en: 'Buy Audemars Piguet | Kariv Glamour', title_de: 'Audemars Piguet kaufen | Kariv Glamour', description_en: 'Buy Audemars Piguet at Kariv Glamour — new and pre-owned AP models.', description_de: 'Audemars Piguet kaufen bei Kariv Glamour \u2013 neue und gebrauchte AP Modelle.', intro_en: 'Buy Audemars Piguet at Kariv Glamour: new and pre-owned models with transparent product information.', intro_de: 'Audemars Piguet kaufen bei Kariv Glamour: neue und gebrauchte Modelle mit transparenter Produktinformation.', filter: {} },
  'audemars-piguet-uhr-kaufen': { h1_en: 'Buy Audemars Piguet Watch', h1_de: 'Audemars Piguet Uhr kaufen', title_en: 'Buy Audemars Piguet Watch | Kariv Glamour', title_de: 'Audemars Piguet Uhr kaufen | Kariv Glamour', description_en: 'Buy Audemars Piguet watch at Kariv Glamour — Royal Oak, Royal Oak Offshore and more models.', description_de: 'Audemars Piguet Uhr kaufen bei Kariv Glamour \u2013 Royal Oak, Royal Oak Offshore und weitere Modelle.', intro_en: 'Buy Audemars Piguet watches at Kariv Glamour — discover models like Royal Oak, Royal Oak Offshore, Royal Oak Concept and Code 11.59.', intro_de: 'Audemars Piguet Uhr kaufen bei Kariv Glamour \u2013 entdecken Sie Modelle wie Royal Oak, Royal Oak Offshore, Royal Oak Concept und Code 11.59.', filter: {} },
  'audemars-piguet-gebraucht-kaufen': { h1_en: 'Buy Pre-Owned Audemars Piguet', h1_de: 'Audemars Piguet gebraucht kaufen', title_en: 'Buy Pre-Owned Audemars Piguet | Kariv Glamour', title_de: 'Audemars Piguet gebraucht kaufen | Kariv Glamour', description_en: 'Buy pre-owned Audemars Piguet at Kariv Glamour with clear condition grading.', description_de: 'Audemars Piguet gebraucht kaufen bei Kariv Glamour mit klarer Zustandsbewertung.', intro_en: 'Buy pre-owned Audemars Piguet at Kariv Glamour — with condition grading, box and papers and detailed product data.', intro_de: 'Audemars Piguet gebraucht kaufen bei Kariv Glamour \u2013 mit Zustandsbewertung, Box und Papers und detaillierten Produktdaten.', filter: {} },
  'audemars-piguet-royal-oak-kaufen': { h1_en: 'Buy Audemars Piguet Royal Oak', h1_de: 'Audemars Piguet Royal Oak kaufen', title_en: 'Buy Audemars Piguet Royal Oak | Kariv Glamour', title_de: 'Audemars Piguet Royal Oak kaufen | Kariv Glamour', description_en: 'Buy Audemars Piguet Royal Oak at Kariv Glamour — the iconic luxury sports watch.', description_de: 'Audemars Piguet Royal Oak kaufen bei Kariv Glamour \u2013 die ikonische Luxus-Sportuhr.', intro_en: 'Buy Audemars Piguet Royal Oak at Kariv Glamour — the iconic integrated luxury sports watch with octagonal bezel and Tapisserie dial.', intro_de: 'Audemars Piguet Royal Oak kaufen bei Kariv Glamour \u2013 die ikonische integrierte Luxus-Sportuhr mit Achtkantl\u00fcnette und Tapisserie-Zifferblatt.', filter: { collection: 'Royal Oak' } },
  'audemars-piguet-royal-oak-offshore-kaufen': { h1_en: 'Buy Audemars Piguet Royal Oak Offshore', h1_de: 'Audemars Piguet Royal Oak Offshore kaufen', title_en: 'Buy Audemars Piguet Royal Oak Offshore | Kariv Glamour', title_de: 'Audemars Piguet Royal Oak Offshore kaufen | Kariv Glamour', description_en: 'Buy Audemars Piguet Royal Oak Offshore at Kariv Glamour — sporty and bold.', description_de: 'Audemars Piguet Royal Oak Offshore kaufen bei Kariv Glamour \u2013 sportlich und markant.', intro_en: 'Buy Audemars Piguet Royal Oak Offshore at Kariv Glamour — a sportier, bolder interpretation of the Royal Oak since 1993.', intro_de: 'Audemars Piguet Royal Oak Offshore kaufen bei Kariv Glamour \u2013 eine sportlichere, markantere Interpretation der Royal Oak seit 1993.', filter: { collection: 'Royal Oak Offshore' } },
  'audemars-piguet-code-1159-kaufen': { h1_en: 'Buy Audemars Piguet Code 11.59', h1_de: 'Audemars Piguet Code 11.59 kaufen', title_en: 'Buy Audemars Piguet Code 11.59 | Kariv Glamour', title_de: 'Audemars Piguet Code 11.59 kaufen | Kariv Glamour', description_en: 'Buy Audemars Piguet Code 11.59 at Kariv Glamour — modern round-case collection.', description_de: 'Audemars Piguet Code 11.59 kaufen bei Kariv Glamour \u2013 moderne Rundgeh\u00e4use-Kollektion.', intro_en: 'Buy Audemars Piguet Code 11.59 at Kariv Glamour — a modern round-case collection with complications and elegant character.', intro_de: 'Audemars Piguet Code 11.59 kaufen bei Kariv Glamour \u2013 eine moderne Rundgeh\u00e4use-Kollektion mit Komplikationen und elegantem Charakter.', filter: { collection: 'Code 11.59' } },
  'audemars-piguet-uhr-preis': { h1_en: 'Audemars Piguet Watch Price', h1_de: 'Audemars Piguet Uhr Preis', title_en: 'Audemars Piguet Watch Price | Kariv Glamour', title_de: 'Audemars Piguet Uhr Preis | Kariv Glamour', description_en: 'Understanding Audemars Piguet prices — collections, materials, complications and reference numbers.', description_de: 'Audemars Piguet Preise verstehen \u2013 Kollektionen, Materialien, Komplikationen und Referenznummern.', intro_en: 'Audemars Piguet watch prices vary depending on collection, material, complication and reference. Learn more about the AP pricing structure.', intro_de: 'Audemars Piguet Uhr Preise variieren je nach Kollektion, Material, Komplikation und Referenz. Erfahren Sie mehr \u00fcber die Preisstruktur von AP Uhren.', isGuide: true },
  'was-kostet-eine-audemars-piguet-uhr': { h1_en: 'How Much Does an Audemars Piguet Watch Cost?', h1_de: 'Was kostet eine Audemars Piguet Uhr?', title_en: 'How Much Does an Audemars Piguet Watch Cost | Kariv Glamour', title_de: 'Was kostet eine Audemars Piguet Uhr | Kariv Glamour', description_en: 'How much does an Audemars Piguet watch cost? Prices and influencing factors explained.', description_de: 'Was kostet eine Audemars Piguet Uhr? Preise und Einflussfaktoren erkl\u00e4rt.', intro_en: 'How much does an Audemars Piguet watch cost? Prices depend on collection, material, complication and availability.', intro_de: 'Was kostet eine Audemars Piguet Uhr? Die Preise h\u00e4ngen von Kollektion, Material, Komplikation und Verf\u00fcgbarkeit ab.', isGuide: true },
  'audemars-piguet-teuerste-uhr': { h1_en: 'Most Expensive Audemars Piguet Watch', h1_de: 'Audemars Piguet teuerste Uhr', title_en: 'Most Expensive Audemars Piguet Watch | Kariv Glamour', title_de: 'Audemars Piguet teuerste Uhr | Kariv Glamour', description_en: 'The most expensive Audemars Piguet watches and what determines their value.', description_de: 'Die teuersten Audemars Piguet Uhren und was ihren Wert bestimmt.', intro_en: 'The most expensive Audemars Piguet watches are often limited pieces, highly complicated tourbillons or historical references. Learn what determines their value.', intro_de: 'Die teuersten Audemars Piguet Uhren sind oft limitierte St\u00fccke, hochkomplizierte Tourbillons oder historische Referenzen. Erfahren Sie, was ihren Wert bestimmt.', isGuide: true },
  'welche-audemars-piguet-kaufen': { h1_en: 'Which Audemars Piguet to Buy?', h1_de: 'Welche Audemars Piguet kaufen?', title_en: 'Which Audemars Piguet to Buy | Kariv Glamour', title_de: 'Welche Audemars Piguet kaufen | Kariv Glamour', description_en: 'Audemars Piguet buying guide — compare Royal Oak, Royal Oak Offshore, Royal Oak Concept and Code 11.59.', description_de: 'Audemars Piguet Kaufberatung \u2013 vergleichen Sie Royal Oak, Royal Oak Offshore, Royal Oak Concept und Code 11.59.', intro_en: 'Which Audemars Piguet watch is right for you? Compare collections, features and case sizes to make the right decision.', intro_de: 'Welche Audemars Piguet Uhr passt zu Ihnen? Vergleichen Sie Kollektionen, Funktionen und Geh\u00e4usegr\u00f6\u00dfen, um die richtige Entscheidung zu treffen.', isGuide: true },
  'audemars-piguet-story': { h1_en: 'Audemars Piguet Story', h1_de: 'Audemars Piguet Story', title_en: 'Audemars Piguet Story | Kariv Glamour', title_de: 'Audemars Piguet Story | Kariv Glamour', description_en: 'The Audemars Piguet Story — bold case architecture, integrated bracelet design and high-end finishing.', description_de: 'Die Audemars Piguet Story \u2013 bold case architecture, integrated bracelet design und high-end finishing.', intro_en: 'Audemars Piguet is known for bold case architecture, integrated bracelet design, high-end finishing and complications — from the iconic Royal Oak to the Code 11.59 collection.', intro_de: 'Audemars Piguet ist bekannt f\u00fcr bold case architecture, integrated bracelet design, high-end finishing und Komplikationen \u2013 von der ikonischen Royal Oak bis zur Code 11.59 Kollektion.', isGuide: true },
};
