const CZECH_AUTH_COPY = {
  "Welcome back": "Vítejte zpět",
  "Log in to your account": "Přihlaste se ke svému účtu",
  "Don't have an account?": "Ještě nemáte účet?",
  "Create one": "Vytvořit účet",
  "Continue with Google": "Pokračovat přes Google",
  "or": "nebo",
  "Email": "E-mail",
  "Password": "Heslo",
  "Forgot password?": "Zapomněli jste heslo?",
  "Logging in...": "Přihlašování…",
  "Log in": "Přihlásit se",
  "Additional verification is required for this account.": "Tento účet vyžaduje dodatečné ověření.",
  "Invalid email or password": "Nesprávný e-mail nebo heslo",
  "Passwords do not match": "Hesla se neshodují",
  "Registration failed": "Registrace se nezdařila",
  "Verification incomplete — please try again.": "Ověření nebylo dokončeno. Zkuste to prosím znovu.",
  "Invalid verification code": "Neplatný ověřovací kód",
  "Code sent": "Kód byl odeslán",
  "Check your email for the new code.": "Nový kód najdete ve svém e-mailu.",
  "Failed to resend code": "Kód se nepodařilo znovu odeslat",
  "Verify your email": "Ověřte svůj e-mail",
  "Verifying...": "Ověřování…",
  "Verify": "Ověřit",
  "Didn't receive the code?": "Kód vám nepřišel?",
  "Resend": "Odeslat znovu",
  "Create your account": "Vytvořte si účet",
  "Sign up to get started": "Začněte registrací",
  "Already have an account?": "Již máte účet?",
  "Confirm Password": "Potvrdit heslo",
  "Creating account...": "Vytváření účtu…",
  "Create account": "Vytvořit účet",
  "Verification incomplete — please check the code and try again.": "Ověření nebylo dokončeno. Zkontrolujte kód a zkuste to znovu.",
  "Failed to reset password": "Heslo se nepodařilo obnovit",
  "Missing email": "Chybí e-mail",
  "Request a reset code first": "Nejprve požádejte o kód pro obnovení",
  "Request a new code": "Požádat o nový kód",
  "Please request a password reset code first.": "Nejprve požádejte o kód pro obnovení hesla.",
  "New password": "Nové heslo",
  "Reset code": "Kód pro obnovení",
  "New Password": "Nové heslo",
  "Resetting...": "Obnovování…",
  "Reset password": "Obnovit heslo",
  "We'll send you a link to reset it": "Zašleme vám kód pro obnovení hesla",
  "Back to log in": "Zpět k přihlášení",
  "If an account exists with that email, you'll receive a code shortly.": "Pokud účet s tímto e-mailem existuje, brzy obdržíte kód.",
  "Enter code": "Zadat kód",
  "Email address": "E-mailová adresa",
  "Sending...": "Odesílání…",
  "Send reset link": "Odeslat kód pro obnovení"
};

export function getAuthText(locale, text) {
  return locale === 'cs' ? CZECH_AUTH_COPY[text] || text : text;
}
