// Reference/collection identifiers remain untouched for catalogue filtering.
// These are the Czech descriptions of the existing local collection cards.
export const CZECH_COLLECTION_DESCRIPTIONS = {
  rolex: {
    'Land-Dweller': 'Moderní kolekce Rolex s integrovaným náramkem a progresivním hodinářským charakterem.',
    'Air-King': 'Výrazné Rolex inspirované letectvím, přesností, čitelností a objevováním.',
    'Cosmograph Daytona': 'Legendární chronograf Rolex spojený s motorsportem, rychlostí a sběratelským zájmem.',
    Datejust: 'Nadčasová klasika Rolex známá každodenní elegancí, univerzálností a trvalým designem.',
    'Lady-Datejust': 'Jemně proporčně řešená kolekce Rolex s elegantním dámským charakterem.',
    'Day-Date': 'Prestižní ikona Rolex spojená s drahými kovy a nadčasovým výrazem.',
    Deepsea: 'Profesionální potápěčské Rolex navržené pro mimořádné podvodní zatížení.',
    Explorer: 'Odolné přístrojové Rolex inspirované dobrodružstvím, vytrvalostí a horským průzkumem.',
    'Explorer II': 'Praktické Rolex zaměřené na průzkum, čitelnost a zobrazení druhého časového pásma.',
    'GMT-Master II': 'Cestovní Rolex pro přehledné zobrazení více časových pásem.',
    'Oyster Perpetual': 'Čisté vyjádření hodinářství Rolex spojující střídmý design s každodenní odolností.',
    'Sea-Dweller': 'Profesionální potápěčské Rolex s důrazem na hloubku, pevnost a technický výkon.',
    'Sky-Dweller': 'Sofistikované cestovní Rolex kombinující roční kalendář se zobrazením dvou časových pásem.',
    Submariner: 'Jedny z nejznámějších luxusních potápěčských hodinek, ceněné pro odolnost a nadčasový design.',
    'Yacht-Master': 'Námořně inspirované sportovní Rolex spojující eleganci, funkčnost a luxus.',
    'Yacht-Master II': 'Technický regatový chronograf Rolex vytvořený pro závodní plachtění.',
    '1908': 'Společenská kolekce spojující eleganci, tradici a moderní hodinářství Rolex.',
    Milgauss: 'Výrazný ukončený model Rolex se sběratelským zájmem na trhu použitých hodinek.',
  },
  patekPhilippe: {
    Nautilus: 'Sportovně elegantní ikona s výrazným tvarem pouzdra, známými provedeními integrovaného náramku a silným sběratelským zájmem.',
    Aquanaut: 'Současná sportovní kolekce Patek Philippe s uvolněným charakterem, moderními proporcemi a každodenní univerzálností.',
    Cubitus: 'Výrazná moderní kolekce Patek Philippe s designem inspirovaným čtvercem a současnou elegancí.',
    Calatrava: 'Nadčasové společenské hodinky známé čistotou, elegancí, jemnými proporcemi a klasickým kulatým pouzdrem.',
    Complications: 'Sofistikovaná kolekce s užitečnými i poetickými funkcemi, jako jsou kalendáře, cestovní čas a měsíční fáze.',
    'Grand Complications': 'Náročné hodinářství Patek Philippe s věčnými kalendáři, minutovými repeticemi, chronografy a pokročilou mechanikou.',
    'Twenty~4': 'Kolekce pro elegantní každodenní nošení s dámskými proporcemi a moderní univerzálností.',
    'Golden Ellipse': 'Designová ikona Patek Philippe s harmonickým eliptickým pouzdrem a jemnou elegancí.',
    Gondolo: 'Tvarovaná pouzdra inspirovaná art deco, geometrickými liniemi a klasickou elegancí.',
    'Grandmaster Chime': 'Jedno z nejsložitějších děl Patek Philippe, spojené s mimořádným mechanickým mistrovstvím a sběratelským významem.',
    'Pocket Watches': 'Kapesní hodinky pro zájemce o tradiční měření času a historii hodinářství.',
    'Rare Handcrafts': 'Vzácné umělecky zpracované kusy ukazující rytí, smaltování a osazování drahokamů.',
  },
  omega: {
    Seamaster: 'Kolekce Omega inspirovaná oceánem, potápěčskými hodinkami, námořním designem a odolností pro běžný den.',
    Speedmaster: 'Legendární chronografická rodina Omega spojená se závoděním, kosmickým výzkumem a odkazem Moonwatch.',
    Constellation: 'Elegantní Omega s charakteristickými detaily pouzdra, stylem integrovaného náramku a kultivovaným každodenním výrazem.',
    'De Ville': 'Společenská rodina Omega zaměřená na eleganci, klasický styl a propracované hodinářství.',
    'Seamaster Aqua Terra 150M': 'Univerzální Seamaster spojující sport, eleganci a každodenní pohodlí s jemným námořním charakterem.',
    'Seamaster Diver 300M': 'Známé potápěčské Omega s charakteristickým designem, profesionálním původem a moderním výrazem.',
    'Seamaster Planet Ocean': 'Technická potápěčská kolekce inspirovaná námořním dědictvím Omega, robustní konstrukcí a moderními materiály.',
    'Seamaster Planet Ocean GMT': 'Cestovní Planet Ocean spojující potápěčský charakter se zobrazením druhého časového pásma.',
    'Seamaster Planet Ocean Worldtimer': 'Planet Ocean se světovým časem pro cestovatele, kteří oceňují čitelnost více pásem i sportovní konstrukci.',
    'Seamaster Planet Ocean Ultra Deep': 'Technicky výrazná řada Seamaster zaměřená na mimořádné podvodní zatížení.',
    'Seamaster Heritage Models': 'Historicky inspirované reference připomínající námořní a potápěčské dědictví Omega.',
    'Speedmaster Moonwatch Professional': 'Ikonický chronograf s historickou vazbou na kosmický výzkum a nadčasovým přístrojovým designem.',
    'Speedmaster Dark Side of the Moon': 'Výrazná řada Speedmaster s keramickou konstrukcí, tmavšími tóny a moderním technickým charakterem.',
    'Speedmaster 38 mm': 'Proporčně menší interpretace Speedmasteru s univerzálním každodenním charakterem.',
    'Speedmaster Two Counters': 'Designová rodina Speedmaster s vyváženou kompozicí chronografu a dvěma pomocnými číselníky.',
    'Speedmaster Calibre 321': 'Sběratelsky zaměřená řada oživující historický kalibr 321 a dobové detaily.',
    Globemaster: 'Sofistikovaná Omega s klasickými designovými odkazy, důrazem na přesnost a elegantním dokončením.',
    'De Ville Ladymatic': 'Dámská kolekce Omega spojující eleganci, jemné detaily a kultivovaný luxus.',
    'De Ville Trésor': 'Štíhlá a elegantní kolekce De Ville se společenským charakterem a jemnými proporcemi.',
    'De Ville Prestige': 'Klasické společenské Omega pro nadčasovou každodenní eleganci.',
    'De Ville Tourbillon': 'Náročné hodinářství v rodině De Ville pro zájemce o výjimečné mechanické konstrukce.',
  },
  cartier: {
    Tank: 'Ikona Cartier s obdélníkovými liniemi, římskými číslicemi, jemnými proporcemi a nadčasovou elegancí.',
    'Santos de Cartier': 'Průkopnický design Cartier s výraznou geometrií, viditelnými šrouby a každodenní elegancí.',
    'Panthère de Cartier': 'Elegantní Cartier se šperkovým náramkem, jemnými proporcemi a plynulým usazením na zápěstí.',
    'Ballon Bleu de Cartier': 'Kulatá kolekce Cartier s oblým pouzdrem, výrazným detailem korunky a měkkými liniemi.',
    'Pasha de Cartier': 'Výrazná kolekce Cartier s kulatým pouzdrem, osobitostí a moderním luxusním charakterem.',
    Baignoire: 'Oválný design Cartier se sochařskou elegancí a jemnými dámskými proporcemi.',
    'Cartier Crash': 'Nezaměnitelný design Cartier s asymetrickým pouzdrem a výrazným sběratelským zájmem.',
    'Santos-Dumont': 'Štíhlá a elegantní interpretace příběhu Santos v klasickém stylu Cartier.',
    'Tank Française': 'Interpretace Tanku s integrovaným náramkem a jemnou každodenní elegancí.',
    'Tank Must': 'Čisté a přístupné vyjádření designového jazyka Cartier Tank.',
    'Tank Louis Cartier': 'Klasický Tank spojený s elegancí Cartier a společenským stylem.',
    'Tank Américaine': 'Zakřivený obdélníkový Tank s prodlouženými proporcemi a výrazným usazením na zápěstí.',
    Tortue: 'Tvarovaná rodina Cartier s elegantními křivkami a historicky inspirovanou vytříbeností.',
    'La Panthère de Cartier': 'Kolekce spojující hodinářský design s charakteristickou elegancí motivu pantera.',
    Tressage: 'Šperkově inspirovaná kolekce Cartier s výrazným vizuálním charakterem.',
    'Reflection de Cartier': 'Sochařský design Cartier se šperkovou přítomností a současnou elegancí.',
    'Rotonde de Cartier': 'Kulatá rodina Cartier spojená s klasickým designem a propracovaným hodinářstvím.',
    'Coussin de Cartier': 'Měkce tvarovaný polštářový design Cartier se šperkovým charakterem.',
  },
  hublot: {
    'Big Bang': 'Výrazná sportovní rodina Hublot známá robustním pouzdrem, moderními materiály a otevřenými číselníky.',
    'Big Bang Original': 'Řada spojená s původní výraznou architekturou Big Bang a luxusně sportovní identitou Hublot.',
    'Big Bang Unico': 'Technická řada Big Bang se skeletovaným chronografickým designem a moderní konstrukcí.',
    'Spirit of Big Bang': 'Sudovité pouzdro Hublot kombinující výraznou architekturu, zakřivení a technické hodinářství.',
    'Square Bang': 'Čtvercová kolekce Hublot s moderní geometrií a výraznou přítomností pouzdra.',
    'Classic Fusion': 'Čistší a střídmější kolekce Hublot kombinující moderní materiály s jemnější elegancí.',
    'Classic Fusion 3-Hands': 'Jednoduché a univerzální Classic Fusion zaměřené na přehledné zobrazení času.',
    'Classic Fusion Chronograph': 'Sportovnější Classic Fusion s chronografem a vyváženým moderním designem.',
    'Classic Fusion Moonphase': 'Elegantní Classic Fusion s komplikací měsíční fáze a jemně řešeným číselníkem.',
    'Classic Fusion Partnerships': 'Kategorie speciálních, limitovaných a partnerských modelů Classic Fusion podle dostupné nabídky.',
    'Exceptional Timepieces': 'Vzácné Hublot, složité komplikace, speciální materiály a limitované edice pro sběratele.',
  },
  breitling: {
    Navitimer: 'Ikonická letecká rodina Breitling známá chronografy, kruhovým logaritmickým pravítkem a historií od roku 1952.',
    Chronomat: 'Univerzální sportovní chronograf s charakteristickými úchyty lunety a všestranným charakterem.',
    Superocean: 'Moderní potápěčská kolekce Breitling pro vodní aktivity a aktivní životní styl.',
    'Superocean Heritage': 'Historicky inspirovaná potápěčská řada s kořeny v SuperOcean z roku 1957, kombinující retro vzhled se současnou konstrukcí.',
    Avenger: 'Výrazná pilotní a profesionální kolekce s robustní konstrukcí a leteckým charakterem.',
    'Classic AVI': 'Letecká kolekce inspirovaná přístroji kokpitů padesátých a šedesátých let a pilotními chronografy.',
    Premier: 'Elegantní chronografická kolekce propojující společenský styl s historií Breitling.',
    'Lady Premier': 'Dámská kolekce Breitling s elegantním designem a menšími, jemnými proporcemi.',
    'Top Time': 'Retro závodní a sportovní chronografy s historicky inspirovaným designem.',
    Professional: 'Přístrojově zaměřené Breitling zahrnující Aerospace, Emergency, Exospace B55 a Endurance Pro.',
  },
  audemarsPiguet: {
    'Royal Oak': 'Sportovní ikona s osmihrannou lunetou a integrovaným náramkem podle návrhu Géralda Genty z roku 1972, známá číselníky Tapisserie a jemným dokončením.',
    'Royal Oak Offshore': 'Větší a sportovnější interpretace Royal Oak uvedená v roce 1993, s robustní konstrukcí a výrazným usazením.',
    'Royal Oak Concept': 'Technická a futuristická řada AP s náročnými komplikacemi, tourbillony, GMT a avantgardní konstrukcí.',
    'Code 11.59': 'Moderní kolekce s kulatým pouzdrem představená v roce 2019, nabízející komplikace a společenský charakter.',
  },
  grandSeiko: {
    Heritage: 'Jádro Grand Seiko: vyvážený design a základní hodinářské hodnoty, včetně známých Snowflake a Shunbun.',
    Elegance: 'Společenské hodinky s jemným designem, štíhlými proporcemi a formálním charakterem.',
    Sport: 'Modely GMT, potápěčské hodinky a chronografy s konstrukcí zaměřenou na aktivní nošení.',
    'Evolution 9': 'Moderní designový jazyk s pokročilými strojky, lepší čitelností a propracovaným leštěním Zaratsu.',
    Masterpiece: 'Vzácné řemeslně zpracované hodinky v drahých kovech pro náročné sběratele Grand Seiko.',
  },
  iwc: {
    "Pilot's Watches": 'Letecky inspirované IWC známé čitelností, technickým designem a pilotními chronografy.',
    Portugieser: 'Kolekce IWC s elegantními proporcemi, čistými číselníky, chronografy, ročními kalendáři a složitými komplikacemi.',
    Portofino: 'Klasické společenské IWC zaměřené na jednoduchost, štíhlou eleganci a univerzální automatické modely.',
    Ingenieur: 'Sportovní IWC s technickým charakterem, známými integrovanými náramky a každodenní použitelností.',
    Aquatimer: 'Potápěčská rodina IWC zaměřená na podvodní použití, sport a robustní konstrukci.',
  },
  jaegerLeCoultre: {
    Reverso: 'Nejznámější design Jaeger-LeCoultre s otočným obdélníkovým pouzdrem a charakterem art deco.',
    'Master Ultra Thin': 'Kolekce zaměřená na štíhlé proporce, čistý design, měsíční fáze, věčné kalendáře a společenskou eleganci.',
    'Master Control': 'Klasická kulatá pouzdra s technickou elegancí, automatickými strojky, chronografy a kalendářními funkcemi.',
    Polaris: 'Moderní sportovní kolekce nabízející neformální eleganci, dobrou čitelnost a každodenní univerzálnost.',
    'Rendez-Vous': 'Elegantní dámská kolekce s jemnými proporcemi, měsíčními fázemi a šperkovým dokončením.',
    Duometre: 'Náročné hodinářství zaměřené na pokročilé komplikace, přesnost a technické zkušenosti Jaeger-LeCoultre.',
    Atmos: 'Luxusní stolní hodiny a hodinářské objekty pro sběratele se zájmem i mimo náramkové hodinky.',
    'Master Compressor': 'Ukončená sportovní rodina Jaeger-LeCoultre zajímavá pro zájemce o použité a sběratelské modely.',
  },
  tagHeuer: {
    Carrera: 'Závodně inspirovaná kolekce TAG Heuer známá chronografy, čistým sportovně společenským designem a motorsportem.',
    'Formula 1': 'Sportovní kolekce TAG Heuer se závodním charakterem, quartzovými i automatickými možnostmi a chronografy.',
    Aquaracer: 'Robustní potápěčská a dobrodružná kolekce TAG Heuer včetně modelů 300M pro vodní a sportovní aktivity.',
    Monaco: 'Čtvercová ikona TAG Heuer spojená se závodní historií, výrazným designem a chronografy.',
    Connected: 'Chytré hodinky TAG Heuer včetně Calibre E5 se sportovními, golfovými, běžeckými a dalšími digitálními funkcemi.',
    'Connected Calibre E5': 'Generace chytrých hodinek TAG Heuer s funkcemi pro sport, golf, běh a další aktivity v pouzdrech 40 a 45 mm.',
    Link: 'Elegantní kolekce TAG Heuer známá integrovaným náramkem a plynulým každodenním stylem.',
    Monza: 'Historicky inspirovaná řada TAG Heuer s výraznou motorsportovní identitou a sběratelskými edicemi.',
  },
  tudor: {
    'Black Bay': 'Známá rodina Tudor s historicky inspirovaným potápěčským designem, GMT, chronografy a moderním přístrojovým charakterem.',
    Pelagos: 'Profesionálně zaměřená potápěčská kolekce Tudor s technickými materiály a dobrou čitelností.',
    'Tudor Royal': 'Univerzální Tudor s integrovaným náramkem, variantami dne a data a různými velikostmi.',
    Ranger: 'Čistě navržené terénní hodinky s odolnou jednoduchostí, čitelností a přístrojovým charakterem.',
    '1926': 'Klasická kolekce Tudor s elegantními proporcemi, automatickými strojky a každodenní použitelností.',
    'Clair de Rose': 'Dámská kolekce Tudor s jemnými velikostmi pouzdra a elegantními číselníky.',
  },
  panerai: {
    Luminor: 'Známá rodina Panerai s výrazným polštářovým pouzdrem, ochranným můstkem korunky a svítícím číselníkem.',
    'Luminor Marina': 'Podrodina Luminoru s malou sekundovou ručkou a klasickou identitou Panerai.',
    Radiomir: 'Historická kolekce s polštářovými pouzdry, tradičními drátovými nožkami u některých variant a vojenskou inspirací.',
    Submersible: 'Technická potápěčská kolekce Panerai s otočnými lunetami, výraznými materiály a sportovním designem.',
    'Luminor Due': 'Štíhlejší a jemnější kolekce Panerai s lehčími proporcemi a univerzálnějšími velikostmi.',
  },
  bvlgari: {
    Serpenti: 'Šperková kolekce Bvlgari s hadím motivem, ovinutými náramky u některých variant a drahokamovými detaily.',
    'Octo Finissimo': 'Moderní rodina Bvlgari s ultratenkou architekturou, římsky inspirovanou geometrií a mechanickými inovacemi.',
    'Octo Roma': 'Elegantní Octo s měkčí geometrií, automatickými strojky a klasičtějším výrazem římského designu.',
    'Bulgari Bulgari': 'Charakteristická řada Bvlgari s gravírovanou lunetou a čistým luxusním stylem.',
    Lvcea: 'Elegantní dámská kolekce Bvlgari se šperkovými detaily, jemnými proporcemi a každodenní použitelností.',
    Aluminium: 'Neformální sportovní Bvlgari s lehkými materiály, výraznými kontrasty a moderním charakterem.',
    'High Jewellery Watches': 'Vzácné hodinky s drahokamy a šperkařským zpracováním pro náročné sběratele.',
  },
  girardPerregaux: {
    Laureato: 'Sportovně elegantní rodina Girard-Perregaux s osmihrannou lunetou, integrovaným náramkem a vyváženými proporcemi.',
    '1966': 'Jemná společenská kolekce s kulatými pouzdry, mechanickou elegancí, kalendáři a měsíční fází.',
    'Vintage 1945': 'Kolekce Girard-Perregaux inspirovaná art deco s obdélníkovými pouzdry a zakřivenou geometrií.',
    Bridges: 'Hodinářská kolekce s charakteristickou architekturou můstků a strojkem viditelným ze strany číselníku.',
    "Cat's Eye": 'Dámské náročné hodinářství s oválnými pouzdry, drahokamovými detaily a jemnými komplikacemi.',
    'Legacy / Vintage Models': 'Starší a ukončené modely Girard-Perregaux, vzácné reference a zvláštní komplikace pro sběratele.',
  },
};
