// Seller legal names and public names are never translated.
const copy = {
  en: {
    soldBy: 'Sold by', verified: 'Professional dealer · Verified by Kariv Glamour',
    unresolved: 'Seller information awaiting verification. This watch cannot be ordered yet.',
    owned: 'Sold directly by Kariv Glamour s.r.o. Kariv Glamour is the contractual seller for this watch.',
    thirdParty: 'Kariv Glamour operates the marketplace and facilitates the transaction. The identified professional dealer is the contractual seller responsible for this watch and the applicable statutory conformity rights.',
    reviews: 'Reviews', noReviews: 'No approved reviews yet', listings: 'Available watches', about: 'About the dealer',
    contact: 'Company and contact information', registration: 'Company registration', vat: 'VAT ID',
    policies: 'Free EU shipping applies. See the shipping, returns and warranty terms for this purchase.',
    shipping: 'Shipping', returns: 'Returns', warranty: 'Warranty', protection: 'Buyer protection',
    legacy: 'Seller details were not recorded with this older order. Contact Kariv support to confirm the contractual seller.',
    mixed: 'Items are grouped by seller. Each watch is ordered separately through the existing checkout.',
    signIn: 'Sign in to review', purchaseRequired: 'A verified purchase from this dealer is required to write a review.',
    newest: 'Newest', highest: 'Highest rated', lowest: 'Lowest rated', more: 'Show more reviews',
    edit: 'Edit review', remove: 'Delete review', pending: 'Your review is awaiting administrator approval.',
    stars: 'Select rating', star: 'stars', demo: 'Demonstration profile', unavailable: 'No watches currently available.',
  },
  de: {
    soldBy: 'Verkauft von', verified: 'Gewerblicher Händler · Von Kariv Glamour verifiziert',
    unresolved: 'Die Verkäuferangaben werden noch geprüft. Diese Uhr kann derzeit nicht bestellt werden.',
    owned: 'Direktverkauf durch Kariv Glamour s.r.o. Kariv Glamour ist der vertragliche Verkäufer dieser Uhr.',
    thirdParty: 'Kariv Glamour betreibt den Marktplatz und vermittelt die Transaktion. Der genannte gewerbliche Händler ist der vertragliche Verkäufer und für diese Uhr sowie die gesetzlichen Mängelrechte verantwortlich.',
    reviews: 'Bewertungen', noReviews: 'Noch keine freigegebenen Bewertungen', listings: 'Verfügbare Uhren', about: 'Über den Händler',
    contact: 'Unternehmens- und Kontaktangaben', registration: 'Handelsregisternummer', vat: 'USt-IdNr.',
    policies: 'Der Versand innerhalb der EU ist kostenlos. Es gelten die Versand-, Rückgabe- und Garantiebedingungen dieses Kaufs.',
    shipping: 'Versand', returns: 'Rückgabe', warranty: 'Gewährleistung', protection: 'Käuferschutz',
    legacy: 'Bei dieser älteren Bestellung wurden keine Verkäuferangaben gespeichert. Bitte lassen Sie sich den vertraglichen Verkäufer vom Kariv-Support bestätigen.',
    mixed: 'Artikel sind nach Verkäufer gruppiert. Jede Uhr wird im bestehenden Bestellprozess einzeln bestellt.',
    signIn: 'Zum Bewerten anmelden', purchaseRequired: 'Für eine Bewertung ist ein verifizierter Kauf bei diesem Händler erforderlich.',
    newest: 'Neueste', highest: 'Beste Bewertung', lowest: 'Niedrigste Bewertung', more: 'Weitere Bewertungen',
    edit: 'Bewertung bearbeiten', remove: 'Bewertung löschen', pending: 'Ihre Bewertung wartet auf die Freigabe durch die Administration.',
    stars: 'Bewertung wählen', star: 'Sterne', demo: 'Demonstrationsprofil', unavailable: 'Derzeit keine Uhren verfügbar.',
  },
  cs: {
    soldBy: 'Prodává', verified: 'Profesionální prodejce · Ověřeno Kariv Glamour',
    unresolved: 'Údaje o prodejci čekají na ověření. Tyto hodinky zatím nelze objednat.',
    owned: 'Přímý prodej společností Kariv Glamour s.r.o. Kariv Glamour je smluvním prodejcem těchto hodinek.',
    thirdParty: 'Kariv Glamour provozuje tržiště a zprostředkovává transakci. Uvedený profesionální prodejce je smluvním prodávajícím odpovědným za tyto hodinky a příslušná zákonná práva z vadného plnění.',
    reviews: 'Recenze', noReviews: 'Zatím žádné schválené recenze', listings: 'Dostupné hodinky', about: 'O prodejci',
    contact: 'Údaje o společnosti a kontakty', registration: 'IČO / registrační číslo', vat: 'DIČ',
    policies: 'Doprava v rámci EU je zdarma. Pro tento nákup platí podmínky dopravy, vrácení a záruk.',
    shipping: 'Doprava', returns: 'Vrácení', warranty: 'Záruky', protection: 'Ochrana kupujícího',
    legacy: 'U této starší objednávky nebyly údaje o prodejci zaznamenány. Smluvního prodejce vám potvrdí podpora Kariv.',
    mixed: 'Položky jsou seskupeny podle prodejce. Každé hodinky se objednávají samostatně v rámci stávající pokladny.',
    signIn: 'Přihlásit se a hodnotit', purchaseRequired: 'Pro napsání recenze je nutný ověřený nákup u tohoto prodejce.',
    newest: 'Nejnovější', highest: 'Nejvyšší hodnocení', lowest: 'Nejnižší hodnocení', more: 'Další recenze',
    edit: 'Upravit recenzi', remove: 'Smazat recenzi', pending: 'Vaše recenze čeká na schválení administrátorem.',
    stars: 'Vyberte hodnocení', star: 'hvězdiček', demo: 'Ukázkový profil', unavailable: 'Momentálně nejsou k dispozici žádné hodinky.',
  },
};
export const marketplaceCopy = locale => copy[locale] || copy.en;
