import { applyCzechSeoPages, applyCzechBrandContent } from './czechBrandData.js';
import { applyCzechBrandFaqs } from './czechBrandFaqs.js';

// Patek Philippe theme colors
export const PATEK_THEME = {
  navy: '#1A2B4A',
  navyDark: '#0F1D33',
  navyLight: '#2A3F6B',
  champagne: '#C5A069',
  champagneLight: '#D4BC8E',
  roseGold: '#C9A87C',
  ivory: '#F8F5EF',
  cream: '#FDFBF6',
  graphite: '#2D2926',
  silver: '#BCC6CC',
};

const PATEK_ASSET_BASE = '/brand-assets/patek-philippe';
const PATEK_COLLECTION_ASSET_BASE = `${PATEK_ASSET_BASE}/collections`;

const COLLECTION_IMAGES = {
  nautilus: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-nautilus-collection.png`,
  aquanaut: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-aquanaut-collection.png`,
  cubitus: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-cubitus-collection.png`,
  calatrava: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-calatrava-collection.png`,
  complications: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-complications-collection.png`,
  grandComplications: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-grand-complications-collection.png`,
  twenty4: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-twenty-4-collection.png`,
  goldenEllipse: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-golden-ellipse-collection.png`,
  gondolo: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-gondolo-collection.png`,
  grandmasterChime: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-grandmaster-chime-collection.png`,
  pocketWatches: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-pocket-watches-collection.png`,
  rareHandcrafts: `${PATEK_COLLECTION_ASSET_BASE}/patek-philippe-rare-handcrafts-collection.png`,
};

export const PATEK_LOGO = `${PATEK_ASSET_BASE}/patek-philippe-logo.webp`;
export const PATEK_HERO_IMAGE = `${PATEK_ASSET_BASE}/patek-philippe-watches-to-buy.jpg`;

const IMG = {
  aquanaut: `${PATEK_ASSET_BASE}/buy-patek-philippe-aquanaut.webp`,
  calatrava: `${PATEK_ASSET_BASE}/buy-patek-philippe-calatrava.jpg`,
  cubitus: `${PATEK_ASSET_BASE}/buy-patek-philippe-cubitus.jpg`,
  grandComplications: `${PATEK_ASSET_BASE}/buy-patek-philippe-grand-complications.jpg`,
  nautilus: `${PATEK_ASSET_BASE}/buy-patek-philippe-nautilus.webp`,
  watches: `${PATEK_ASSET_BASE}/buy-patek-philippe-watches.jpg`,
  boxPapers: `${PATEK_ASSET_BASE}/patek-philippe-boxes-and-papers.jpg`,
  buyingGuide: `${PATEK_ASSET_BASE}/patek-philippe-buying-guide.jpg`,
  buyingWatchGuide: `${PATEK_ASSET_BASE}/patek-philippe-buying-watch-guide.webp`,
  grandComplicationsGuide: `${PATEK_ASSET_BASE}/patek-philippe-grand-complications-guide.jpg`,
  nautilusGuide: `${PATEK_ASSET_BASE}/patek-philippe-nautilus-guide.jpg`,
  watchmaking: `${PATEK_ASSET_BASE}/patek-philippe-watchmaking.jpg`,
  story: `${PATEK_ASSET_BASE}/patek-philippe-story.jpg`,
  watchesToBuy: `${PATEK_ASSET_BASE}/patek-philippe-watches-to-buy.jpg`,
  preOwned: `${PATEK_ASSET_BASE}/pre-owned-patek-philippe.jpg`,
  maintenance: `${PATEK_ASSET_BASE}/patek-philippe-maintenance.webp`,
};

// Patek Philippe Collections
export const PATEK_COLLECTIONS = [
  { id: 'nautilus', name: 'Nautilus', slug: 'nautilus', description_en: 'A modern luxury sports icon known for its distinctive case shape, integrated bracelet, and strong collector demand.', description_de: 'Ein modernes Luxus-Sportuhr-Icon, bekannt für seine markante Gehäuseform, das integrierte Armband und die starke Sammlernachfrage.', image: COLLECTION_IMAGES.nautilus, displayOrder: 1 },
  { id: 'aquanaut', name: 'Aquanaut', slug: 'aquanaut', description_en: 'A contemporary and sporty Patek Philippe collection with a relaxed character, modern proportions, and everyday versatility.', description_de: 'Eine zeitgenössische und sportliche Patek Philippe Kollektion mit entspanntem Charakter, modernen Proportionen und alltäglicher Vielseitigkeit.', image: COLLECTION_IMAGES.aquanaut, displayOrder: 2 },
  { id: 'cubitus', name: 'Cubitus', slug: 'cubitus', description_en: 'A bold modern Patek Philippe collection with a distinctive square-inspired design and elegant contemporary appeal.', description_de: 'Eine mutige moderne Patek Philippe Kollektion mit einem markanten, von Quadraten inspirierten Design und eleganter zeitgenössischer Anziehungskraft.', image: COLLECTION_IMAGES.cubitus, displayOrder: 3 },
  { id: 'calatrava', name: 'Calatrava', slug: 'calatrava', description_en: 'A timeless dress watch collection known for purity, elegance, refined proportions, and classic round case design.', description_de: 'Eine zeitlose Dress-Watch-Kollektion, bekannt für Reinheit, Eleganz, verfeinerte Proportionen und klassisches rundes Gehäusedesign.', image: COLLECTION_IMAGES.calatrava, displayOrder: 4 },
  { id: 'complications', name: 'Complications', slug: 'complications', description_en: 'A sophisticated collection for collectors who appreciate useful and poetic watch functions such as calendars, travel time, and moon phases.', description_de: 'Eine anspruchsvolle Kollektion für Sammler, die nützliche und poetische Uhrfunktionen wie Kalender, Travel Time und Mondphasen schätzen.', image: COLLECTION_IMAGES.complications, displayOrder: 5 },
  { id: 'grand-complications', name: 'Grand Complications', slug: 'grand-complications', description_en: 'The highest expression of Patek Philippe watchmaking, created for collectors drawn to perpetual calendars, minute repeaters, chronographs, and advanced mechanical artistry.', description_de: 'Die höchste Ausdrucksform der Patek Philippe Uhrmacherei, geschaffen für Sammler, die von ewigen Kalendern, Minutenrepetierern, Chronographen und fortgeschrittener mechanischer Kunstfertigkeit fasziniert sind.', image: COLLECTION_IMAGES.grandComplications, displayOrder: 6 },
  { id: 'twenty-4', name: 'Twenty~4', slug: 'twenty-4', description_en: 'A refined collection created for elegant daily wear, with feminine proportions and modern versatility.', description_de: 'Eine verfeinerte Kollektion für eleganten täglichen Gebrauch, mit femininen Proportionen und moderner Vielseitigkeit.', image: COLLECTION_IMAGES.twenty4, displayOrder: 7 },
  { id: 'golden-ellipse', name: 'Golden Ellipse', slug: 'golden-ellipse', description_en: 'A distinctive Patek Philippe design icon recognized for its harmonious elliptical case and refined elegance.', description_de: 'Ein markantes Patek Philippe Design-Icon, bekannt für sein harmonisches elliptisches Gehäuse und verfeinerte Eleganz.', image: COLLECTION_IMAGES.goldenEllipse, displayOrder: 8 },
  { id: 'gondolo', name: 'Gondolo', slug: 'gondolo', description_en: 'A shaped-watch collection inspired by Art Deco design, geometric lines, and classic elegance.', description_de: 'Eine Shaped-Watch-Kollektion, inspiriert von Art-Deco-Design, geometrischen Linien und klassischer Eleganz.', image: COLLECTION_IMAGES.gondolo, displayOrder: 9 },
  { id: 'grandmaster-chime', name: 'Grandmaster Chime', slug: 'grandmaster-chime', description_en: 'One of the most complicated and prestigious Patek Philippe creations, associated with exceptional mechanical mastery and collector significance.', description_de: 'Eine der kompliziertesten und prestigeträchtigsten Patek Philippe Kreationen, verbunden mit außergewöhnlicher mechanischer Meisterschaft und Sammlerbedeutung.', image: COLLECTION_IMAGES.grandmasterChime, displayOrder: 10 },
  { id: 'pocket-watches', name: 'Pocket Watches', slug: 'pocket-watches', description_en: 'A heritage-focused category for collectors interested in traditional timekeeping and historical watchmaking.', description_de: 'Eine heritage-orientierte Kategorie für Sammler, die sich für traditionelle Zeitmessung und historische Uhrmacherei interessieren.', image: COLLECTION_IMAGES.pocketWatches, displayOrder: 11 },
  { id: 'rare-handcrafts', name: 'Rare Handcrafts', slug: 'rare-handcrafts', description_en: 'A highly artistic category for rare collectible pieces that showcase decorative crafts such as engraving, enameling, and gem-setting.', description_de: 'Eine hochgradig künstlerische Kategorie für seltene Sammlerstücke, die dekorative Handwerkskünste wie Gravur, Email und Edelsteinbesatz präsentieren.', image: COLLECTION_IMAGES.rareHandcrafts, displayOrder: 12 },
];

// Quick filter chips for product grid
export const PATEK_QUICK_FILTERS = [
  { label: 'Patek Philippe Nautilus', link: '/patek-philippe-nautilus-kaufen', filter: { collection: 'Nautilus' } },
  { label: 'Patek Philippe Aquanaut', link: '/patek-philippe-aquanaut-kaufen', filter: { collection: 'Aquanaut' } },
  { label: 'Patek Philippe Calatrava', link: '/patek-philippe-calatrava-kaufen', filter: { collection: 'Calatrava' } },
  { label: 'Patek Philippe Cubitus', link: '/patek-philippe-cubitus-kaufen', filter: { collection: 'Cubitus' } },
  { label: 'Patek Philippe Grand Complications', link: '/patek-philippe-grand-complications-kaufen', filter: { collection: 'Grand Complications' } },
  { label: 'Patek Philippe Complications', link: '/patek-philippe-complications-kaufen', filter: { collection: 'Complications' } },
  { label: 'Patek Philippe Twenty~4', link: '/patek-philippe-twenty-4-kaufen', filter: { collection: 'Twenty~4' } },
  { label: 'Pre-Owned Patek Philippe', link: '/patek-philippe-gebraucht-kaufen', filter: { preOwned: true } },
  { label: 'Patek Philippe with Box and Papers', link: '/watch-guides/box-and-papers', filter: { fullSet: true } },
];

// Complication filter options
export const PATEK_COMPLICATIONS = [
  'Time only', 'Date', 'Moon phase', 'Annual calendar', 'Perpetual calendar',
  'Chronograph', 'Split-seconds chronograph', 'Travel Time', 'World Time',
  'Minute repeater', 'Tourbillon', 'Grand complication',
];

// SEO Cards
export const PATEK_SEO_CARDS = [
  { title_en: 'Buy Patek Philippe', title_de: 'Patek Philippe kaufen', description_en: 'Explore Patek Philippe watches through Kariv Glamour with refined product presentation, transparent details, and a premium shopping experience.', description_de: 'Entdecken Sie Patek Philippe Uhren bei Kariv Glamour mit verfeinerter Produktpräsentation, transparenten Details und einem Premium-Einkaufserlebnis.', link: '/patek-philippe-kaufen', image: IMG.watches },
  { title_en: 'Buy Pre-Owned Patek Philippe', title_de: 'Patek Philippe gebraucht kaufen', description_en: 'Discover pre-owned Patek Philippe watches with clear condition grading, box and papers information, service history details, and collector-focused product data.', description_de: 'Entdecken Sie gebrauchte Patek Philippe Uhren mit klarer Zustandsbewertung, Box- und Papiere-Informationen, Service-Historie und sammlerorientierten Produktdaten.', link: '/patek-philippe-gebraucht-kaufen', image: IMG.preOwned },
  { title_en: 'Buy Patek Philippe Nautilus', title_de: 'Patek Philippe Nautilus kaufen', description_en: 'Browse Patek Philippe Nautilus watches, one of the most recognizable luxury sports watch families in modern collecting.', description_de: 'Stöbern Sie durch Patek Philippe Nautilus Uhren, eine der erkennbarsten Luxus-Sportuhren-Familien im modernen Sammeln.', link: '/patek-philippe-nautilus-kaufen', image: IMG.nautilus },
  { title_en: 'Buy Patek Philippe Aquanaut', title_de: 'Patek Philippe Aquanaut kaufen', description_en: 'Explore Patek Philippe Aquanaut watches, known for their modern sporty character and strong collector interest.', description_de: 'Entdecken Sie Patek Philippe Aquanaut Uhren, bekannt für ihren modernen sportlichen Charakter und starkes Sammlerinteresse.', link: '/patek-philippe-aquanaut-kaufen', image: IMG.aquanaut },
  { title_en: 'Buy Patek Philippe Calatrava', title_de: 'Patek Philippe Calatrava kaufen', description_en: 'Shop Patek Philippe Calatrava watches, admired for classic elegance, pure lines, and dress-watch refinement.', description_de: 'Shoppen Sie Patek Philippe Calatrava Uhren, bewundert für klassische Eleganz, reine Linien und Dress-Watch-Raffinesse.', link: '/patek-philippe-calatrava-kaufen', image: IMG.calatrava },
  { title_en: 'Buy Patek Philippe Cubitus', title_de: 'Patek Philippe Cubitus kaufen', description_en: 'Discover the Patek Philippe Cubitus collection, a contemporary expression of shaped-case design and modern elegance.', description_de: 'Entdecken Sie die Patek Philippe Cubitus Kollektion, ein zeitgenössischer Ausdruck von Shaped-Case-Design und moderner Eleganz.', link: '/patek-philippe-cubitus-kaufen', image: IMG.cubitus },
  { title_en: 'Buy Patek Philippe Grand Complications', title_de: 'Patek Philippe Grand Complications kaufen', description_en: 'Explore Patek Philippe Grand Complications for collectors drawn to advanced mechanical watchmaking and rare horological artistry.', description_de: 'Entdecken Sie Patek Philippe Grand Complications für Sammler, die von fortgeschrittener mechanischer Uhrmacherei und seltener horologischer Kunstfertigkeit fasziniert sind.', link: '/patek-philippe-grand-complications-kaufen', image: IMG.grandComplications },
  { title_en: 'Which Patek Philippe to Buy?', title_de: 'Welche Patek Philippe kaufen?', description_en: 'Read the Patek Philippe buying guide to compare collections, references, materials, complications, and ownership considerations.', description_de: 'Lesen Sie die Patek Philippe Kaufberatung, um Kollektionen, Referenzen, Materialien, Komplikationen und Besitzüberlegungen zu vergleichen.', link: '/welche-patek-philippe-kaufen', image: IMG.buyingWatchGuide },
];

// Editorial sections data (Story, Watchmaking, Maintenance)
export const PATEK_EDITORIAL_SECTIONS = [
  {
    id: 'patek-story',
    eyebrow_cs: 'Odkaz značky',
    title_cs: 'Příběh značky Patek Philippe',
    description_cs: 'Patek Philippe patří k nejuznávanějším jménům vysokého hodinářství. Jeho tradice vyrůstá ze ženevského řemesla a rodinného vlastnictví napříč generacemi. Od prvních kapesních hodinek po ikonický Nautilus a mimořádné Grand Complications jde o příběh výjimečného řemesla, sběratelské prestiže a vytrvalého důrazu na jemné hodinářství. Kariv Glamour tento odkaz představuje pečlivým výběrem hodinek Patek Philippe, doplněným transparentními údaji a odbornými informacemi.',
    cta_cs: 'Přečíst příběh Patek Philippe',
    eyebrow_en: 'Heritage', eyebrow_de: 'Erbe',
    title_en: 'The Patek Philippe Story', title_de: 'Die Patek Philippe Geschichte',
    description_en: 'Patek Philippe stands as one of the most revered names in haute horlogerie, with a heritage rooted in Geneva watchmaking and a legacy shaped by family ownership across generations. From the earliest pocket watches to the iconic Nautilus and the extraordinary Grand Complications, the Patek Philippe story is one of rare craftsmanship, collector prestige, and an unwavering commitment to fine watchmaking. At Kariv Glamour, we celebrate this heritage by offering carefully selected Patek Philippe timepieces, each presented with full transparency and expert insight.',
    description_de: 'Patek Philippe ist einer der respektiertesten Namen der Haute Horlogerie, mit einem Erbe, das in der Genfer Uhrmacherei verwurzelt ist und einer Legacy, die durch Familienbesitz über Generationen geprägt wurde. Von den frühesten Taschenuhren bis zur ikonischen Nautilus und den außergewöhnlichen Grand Complications — die Patek Philippe Geschichte ist eine von seltener Handwerkskunst, Sammlerprestige und unerschütterlichem Engagement für feine Uhrmacherei. Bei Kariv Glamour feiern wir dieses Erbe mit sorgfältig ausgewählten Patek Philippe Zeitmessern, die jeweils mit voller Transparenz und fachkundiger Einsicht präsentiert werden.',
    cta_en: 'Read the Patek Philippe Story', cta_de: 'Die Patek Philippe Geschichte lesen',
    link: '/patek-philippe/story',
    image: IMG.story,
    internalLinks: [
      { text_en: 'Patek Philippe heritage', text_de: 'Patek Philippe Erbe', link: '/patek-philippe/story' },
      { text_en: 'Geneva watchmaking', text_de: 'Genfer Uhrmacherei', link: '/patek-philippe/watchmaking' },
      { text_en: 'collector prestige', text_de: 'Sammlerprestige', link: '/welche-patek-philippe-kaufen' },
      { text_en: 'rare craftsmanship', text_de: 'seltene Handwerkskunst', link: '/patek-philippe/rare-handcrafts' },
      { text_en: 'Grand Complications', text_de: 'Grand Complications', link: '/patek-philippe-grand-complications-kaufen' },
    ],
  },
  {
    id: 'patek-watchmaking',
    eyebrow_cs: 'Řemeslné mistrovství',
    title_cs: 'Hodinářství Patek Philippe',
    description_cs: 'Hodinářství Patek Philippe představuje vrchol jemného mechanického řemesla: ručně dokončované strojky, propracovaná pouzdra a mimořádnou škálu komplikací. Od jednoduchých hodinek Calatrava ukazujících čas po věčné kalendáře, minutové repetice a tourbillony vyjadřuje každý kus důraz na přesnost a tradici. Pro sběratele jsou důležité referenční číslo, typ strojku, materiál pouzdra i období výroby — společně tvoří příběh konkrétních hodinek. Kariv Glamour vám pomáhá těmto souvislostem porozumět a nakupovat s jistotou.',
    cta_cs: 'Objevit hodinářství Patek Philippe',
    eyebrow_en: 'Craftsmanship', eyebrow_de: 'Handwerkskunst',
    title_en: 'Patek Philippe Watchmaking', title_de: 'Patek Philippe Uhrmacherei',
    description_en: 'Patek Philippe watchmaking represents the pinnacle of fine mechanical artistry, combining hand-finished movements, exquisite case design, and an extraordinary range of complications. From simple time-only Calatrava watches to perpetual calendars, minute repeaters, and tourbillons, each timepiece reflects a deep commitment to precision and tradition. Collectors value Patek Philippe for its reference numbers, movement types, case materials, and production periods, all of which contribute to the story behind every watch. At Kariv Glamour, we help you understand the craftsmanship behind each Patek Philippe, so you can make an informed and confident decision.',
    description_de: 'Die Patek Philippe Uhrmacherei repräsentiert den Höhepunkt feiner mechanischer Kunstfertigkeit, mit hand-finierten Werken, exquisitem Gehäusedesign und einer außergewöhnlichen Vielfalt an Komplikationen. Von einfachen Time-Only-Calatrava-Uhren bis zu ewigen Kalendern, Minutenrepetierern und Tourbillons — jeder Zeitmesser spiegelt ein tiefes Engagement für Präzision und Tradition wider. Sammler schätzen Patek Philippe für seine Referenznummern, Werktypen, Gehäusematerialien und Produktionszeiträume, die alle zur Geschichte hinter jeder Uhr beitragen. Bei Kariv Glamour helfen wir Ihnen, die Handwerkskunst hinter jeder Patek Philippe zu verstehen, damit Sie eine informierte und zuversichtliche Entscheidung treffen können.',
    cta_en: 'Explore Patek Philippe Watchmaking', cta_de: 'Patek Philippe Uhrmacherei entdecken',
    link: '/patek-philippe/watchmaking',
    image: IMG.watchmaking,
    internalLinks: [
      { text_en: 'complications', text_de: 'Komplikationen', link: '/patek-philippe/complications' },
      { text_en: 'Grand Complications', text_de: 'Grand Complications', link: '/patek-philippe/grand-complications' },
      { text_en: 'manual-winding and self-winding movements', text_de: 'Handaufzugs- und Automatikwerke', link: '/watch-guides/mechanical-vs-quartz-watches' },
      { text_en: 'case materials', text_de: 'Gehäusematerialien', link: '/watch-guides/watch-case-materials' },
      { text_en: 'reference numbers', text_de: 'Referenznummern', link: '/watch-guides/watch-reference-number-guide' },
    ],
  },
  {
    id: 'patek-maintenance',
    eyebrow_cs: 'Péče',
    title_cs: 'Údržba hodinek Patek Philippe',
    description_cs: 'Správná péče pomáhá uchovat krásu, spolehlivost a hodnotu hodinek Patek Philippe. Základem je pravidelný servis kvalifikovaným odborníkem, kontrola vodotěsnosti, bezpečné uložení a ochrana před nárazy i magnetickým polem. Kožené řemínky chraňte před vlhkostí a potem; složité hodinky vyžadují zvláštní pozornost. U použitých a sběratelských kusů je důležité uchovat krabičku, doklady, archivní výpis, servisní záznamy a původní faktury. Kariv Glamour nabízí informace pro uvážlivou péči o vaše hodinky.',
    cta_cs: 'Více o údržbě Patek Philippe',
    eyebrow_en: 'Care', eyebrow_de: 'Pflege',
    title_en: 'Patek Philippe Maintenance', title_de: 'Patek Philippe Wartung',
    description_en: 'Proper care preserves the beauty, reliability, and value of a Patek Philippe watch. Regular servicing by qualified professionals, water resistance checks, safe storage, and avoiding shocks and magnetic exposure are all essential. Leather straps should be protected from moisture and perspiration, while complicated watches require special attention. For pre-owned and collectible Patek Philippe watches, preserving the box, papers, archives extract, service documents, and original invoices is especially important for long-term value. Kariv Glamour provides guidance to help you maintain your timepiece with confidence.',
    description_de: 'Die richtige Pflege erhält die Schönheit, Zuverlässigkeit und den Wert einer Patek Philippe Uhr. Regelmäßige Wartung durch qualifizierte Fachleute, Wasserdichtigkeitsprüfungen, sichere Aufbewahrung und das Vermeiden von Stößen und magnetischer Exposition sind wesentlich. Lederarmbänder sollten vor Feuchtigkeit und Schweiß geschützt werden, während komplizierte Uhren besondere Aufmerksamkeit erfordern. Für gebrauchte und sammelbare Patek Philippe Uhren ist die Erhaltung von Box, Papieren, Archives Extract, Service-Dokumenten und Originalrechnungen besonders wichtig für den langfristigen Wert. Kariv Glamour bietet Beratung, um Ihre Uhr zuverlässig zu pflegen.',
    cta_en: 'Learn About Patek Philippe Maintenance', cta_de: 'Mehr über Patek Philippe Wartung erfahren',
    link: '/patek-philippe/maintenance',
    image: IMG.maintenance,
    internalLinks: [
      { text_en: 'service history', text_de: 'Service-Historie', link: '/watch-guides/service-history' },
      { text_en: 'box and papers', text_de: 'Box und Papiere', link: '/watch-guides/box-and-papers' },
      { text_en: 'archives extract', text_de: 'Archives Extract', link: '/patek-philippe-archives-extract-guide' },
      { text_en: 'condition grading', text_de: 'Zustandsbewertung', link: '/condition-grading' },
      { text_en: 'pre-owned Patek Philippe', text_de: 'gebrauchte Patek Philippe', link: '/patek-philippe-gebraucht-kaufen' },
    ],
  },
];

// Read More carousel cards
export const PATEK_READ_MORE = [
  { title_en: 'Patek Philippe Story', title_de: 'Patek Philippe Geschichte', description_en: 'Explore the heritage, family legacy, and collector appeal behind one of the most respected names in fine watchmaking.', description_de: 'Entdecken Sie das Erbe, die Familienlegacy und die Sammleranziehungskraft hinter einem der respektiertesten Namen der feinen Uhrmacherei.', link: '/patek-philippe/story', image: IMG.story },
  { title_en: 'Patek Philippe Watchmaking', title_de: 'Patek Philippe Uhrmacherei', description_en: 'Learn about movements, complications, finishing, materials, and the details that define Patek Philippe watchmaking.', description_de: 'Erfahren Sie über Werke, Komplikationen, Finissierung, Materialien und die Details, die Patek Philippe Uhrmacherei definieren.', link: '/patek-philippe/watchmaking', image: IMG.watchmaking },
  { title_en: 'Patek Philippe Maintenance', title_de: 'Patek Philippe Wartung', description_en: 'Understand how to care for a Patek Philippe watch and preserve its condition, documentation, and long-term appeal.', description_de: 'Verstehen Sie, wie Sie eine Patek Philippe Uhr pflegen und ihren Zustand, ihre Dokumentation und ihren langfristigen Wert erhalten.', link: '/patek-philippe/maintenance', image: IMG.maintenance },
  { title_en: 'Patek Philippe Buying Guide', title_de: 'Patek Philippe Kaufberatung', description_en: 'Compare popular Patek Philippe collections and learn what to check before buying new, pre-owned, or vintage models.', description_de: 'Vergleichen Sie beliebte Patek Philippe Kollektionen und erfahren Sie, worauf Sie vor dem Kauf neuer, gebraucher oder Vintage-Modelle achten sollten.', link: '/welche-patek-philippe-kaufen', image: IMG.buyingGuide },
  { title_en: 'Box, Papers and Archives Extract', title_de: 'Box, Papiere und Archives Extract', description_en: 'Learn why original documentation, archives extract, service history, and purchase records matter when buying Patek Philippe.', description_de: 'Erfahren Sie, warum Originaldokumentation, Archives Extract, Service-Historie und Kaufaufzeichnungen beim Patek Philippe Kauf wichtig sind.', link: '/patek-philippe-archives-extract-guide', image: IMG.boxPapers },
  { title_en: 'Patek Philippe Nautilus Guide', title_de: 'Patek Philippe Nautilus Guide', description_en: 'Explore the design, demand, and buying considerations behind the Patek Philippe Nautilus collection.', description_de: 'Entdecken Sie Design, Nachfrage und Kaufüberlegungen hinter der Patek Philippe Nautilus Kollektion.', link: '/patek-philippe-nautilus-kaufen', image: IMG.nautilusGuide },
  { title_en: 'Patek Philippe Grand Complications Guide', title_de: 'Patek Philippe Grand Complications Guide', description_en: 'Learn why Grand Complications represent the highest level of mechanical artistry and collector interest.', description_de: 'Erfahren Sie, warum Grand Complications die höchste Stufe mechanischer Kunstfertigkeit und Sammlerinteresse repräsentieren.', link: '/patek-philippe-grand-complications-kaufen', image: IMG.grandComplicationsGuide },
];

// Internal linking hub
export const PATEK_INTERNAL_LINKS = {
  popularSearches: [
    { text_en: 'Buy Patek Philippe', text_de: 'Patek Philippe kaufen', link: '/patek-philippe-kaufen' },
    { text_en: 'Buy Pre-Owned Patek Philippe', text_de: 'Patek Philippe gebraucht kaufen', link: '/patek-philippe-gebraucht-kaufen' },
    { text_en: 'Buy a Patek Philippe Watch', text_de: 'Patek Philippe Uhr kaufen', link: '/patek-philippe-uhr-kaufen' },
    { text_en: 'Patek Philippe for Men', text_de: 'Patek Philippe für Herren', link: '/patek-philippe-herren' },
    { text_en: 'Patek Philippe for Women', text_de: 'Patek Philippe für Damen', link: '/patek-philippe-damen' },
    { text_en: 'Patek Philippe with Box and Papers', text_de: 'Patek Philippe mit Box und Papieren', link: '/watch-guides/box-and-papers' },
    { text_en: 'Patek Philippe Archives Extract Guide', text_de: 'Patek Philippe Archives Extract Guide', link: '/patek-philippe-archives-extract-guide' },
  ],
  iconicCollections: [
    { text_en: 'Buy Patek Philippe Nautilus', text_de: 'Patek Philippe Nautilus kaufen', link: '/patek-philippe-nautilus-kaufen' },
    { text_en: 'Buy Patek Philippe Aquanaut', text_de: 'Patek Philippe Aquanaut kaufen', link: '/patek-philippe-aquanaut-kaufen' },
    { text_en: 'Buy Patek Philippe Calatrava', text_de: 'Patek Philippe Calatrava kaufen', link: '/patek-philippe-calatrava-kaufen' },
    { text_en: 'Buy Patek Philippe Cubitus', text_de: 'Patek Philippe Cubitus kaufen', link: '/patek-philippe-cubitus-kaufen' },
    { text_en: 'Buy Patek Philippe Twenty~4', text_de: 'Patek Philippe Twenty~4 kaufen', link: '/patek-philippe-twenty-4-kaufen' },
    { text_en: 'Buy Patek Philippe Golden Ellipse', text_de: 'Patek Philippe Golden Ellipse kaufen', link: '/patek-philippe-golden-ellipse-kaufen' },
    { text_en: 'Buy Patek Philippe Gondolo', text_de: 'Patek Philippe Gondolo kaufen', link: '/patek-philippe-gondolo-kaufen' },
  ],
  complicationsGuides: [
    { text_en: 'Patek Philippe Complications', text_de: 'Patek Philippe Complications', link: '/patek-philippe/complications' },
    { text_en: 'Patek Philippe Grand Complications', text_de: 'Patek Philippe Grand Complications', link: '/patek-philippe-grand-complications-kaufen' },
    { text_en: 'Perpetual Calendar Watches', text_de: 'Ewige Kalender Uhren', link: '/collections/perpetual-calendar-watches' },
    { text_en: 'Annual Calendar Watches', text_de: 'Jahreskalender Uhren', link: '/collections/annual-calendar-watches' },
    { text_en: 'Moon Phase Watches', text_de: 'Mondphasen Uhren', link: '/collections/moon-phase-watches' },
    { text_en: 'World Time Watches', text_de: 'Weltzeit Uhren', link: '/collections/world-time-watches' },
    { text_en: 'Minute Repeater Watches', text_de: 'Minutenrepetierer Uhren', link: '/collections/minute-repeater-watches' },
    { text_en: 'Chronograph Watches', text_de: 'Chronographen Uhren', link: '/collections/chronograph-watches' },
  ],
  learningGuides: [
    { text_en: 'Which Patek Philippe to Buy?', text_de: 'Welche Patek Philippe kaufen?', link: '/welche-patek-philippe-kaufen' },
    { text_en: 'Patek Philippe New or Pre-Owned?', text_de: 'Patek Philippe neu oder gebraucht kaufen?', link: '/patek-philippe-neu-oder-gebraucht' },
    { text_en: 'Patek Philippe Archives Extract Guide', text_de: 'Patek Philippe Archives Extract Guide', link: '/patek-philippe-archives-extract-guide' },
    { text_en: 'Patek Philippe Maintenance and Care', text_de: 'Patek Philippe Wartung und Pflege', link: '/patek-philippe/maintenance' },
    { text_en: 'Patek Philippe Story', text_de: 'Patek Philippe Geschichte', link: '/patek-philippe/story' },
    { text_en: 'Patek Philippe Watchmaking', text_de: 'Patek Philippe Uhrmacherei', link: '/patek-philippe/watchmaking' },
  ],
  relatedBrands: [
    { text_en: 'Rolex watches', text_de: 'Rolex Uhren', link: '/brands/rolex' },
    { text_en: 'Audemars Piguet watches', text_de: 'Audemars Piguet Uhren', link: '/brands/audemars-piguet' },
    { text_en: 'Hublot watches', text_de: 'Hublot Uhren', link: '/brands/hublot' },
    { text_en: 'Grand Seiko watches', text_de: 'Grand Seiko Uhren', link: '/brands/grand-seiko' },
    { text_en: 'Girard-Perregaux watches', text_de: 'Girard-Perregaux Uhren', link: '/brands/girard-perregaux' },
    { text_en: 'Jaeger-LeCoultre watches', text_de: 'Jaeger-LeCoultre Uhren', link: '/brands/jaeger-lecoultre' },
    { text_en: 'Cartier watches', text_de: 'Cartier Uhren', link: '/brands/cartier' },
    { text_en: 'Omega watches', text_de: 'Omega Uhren', link: '/brands/omega' },
  ],
  relatedCategories: [
    { text_en: 'Certified Pre-Owned Watches', text_de: 'Zertifizierte gebrauchte Uhren', link: '/certified-pre-owned' },
    { text_en: 'Vintage Watches', text_de: 'Vintage Uhren', link: '/vintage-watches' },
    { text_en: 'Men\u2019s Luxury Watches', text_de: 'Herren-Luxusuhren', link: '/mens-watches' },
    { text_en: 'Women\u2019s Luxury Watches', text_de: 'Damen-Luxusuhren', link: '/womens-watches' },
    { text_en: 'Dress Watches', text_de: 'Dress-Watches', link: '/collections/dress-watches' },
    { text_en: 'Luxury Sports Watches', text_de: 'Luxus-Sportuhren', link: '/collections/luxury-sports-watches' },
    { text_en: 'Complication Watches', text_de: 'Komplikationsuhren', link: '/collections/complication-watches' },
    { text_en: 'Investment-Conscious Watches', text_de: 'Investitionsorientierte Uhren', link: '/collections/collectible-watches' },
  ],
};

// FAQ
export const PATEK_FAQS = [
  {
    question_en: 'Where can I buy a Patek Philippe watch online?',
    question_de: 'Wo kann ich eine Patek Philippe Uhr online kaufen?',
    answer_en: 'You can explore and buy Patek Philippe watches online through Kariv Glamour, where each timepiece is presented with transparent product details, clear condition grading, and reference number visibility. Browse our Patek Philippe collection to discover available models, or visit our pre-owned Patek Philippe page for previously owned timepieces.',
    answer_de: 'Sie können Patek Philippe Uhren online bei Kariv Glamour entdecken und kaufen, wo jeder Zeitmesser mit transparenten Produktdetails, klarer Zustandsbewertung und Referenznummern-Sichtbarkeit präsentiert wird. Stöbern Sie durch unsere Patek Philippe Kollektion, um verfügbare Modelle zu entdecken, oder besuchen Sie unsere Seite für gebrauchte Patek Philippe Uhren.',
  },
  {
    question_en: 'Is it safe to buy a pre-owned Patek Philippe?',
    question_de: 'Ist es sicher, eine gebrauchte Patek Philippe zu kaufen?',
    answer_en: 'Yes. When you buy a pre-owned Patek Philippe from Kariv Glamour, each watch is carefully reviewed and presented with clear condition grading, box and papers information, and service history where available. We do not sell replica or counterfeit watches, and every product page provides the details you need to make a confident decision.',
    answer_de: 'Ja. Wenn Sie eine gebrauchte Patek Philippe bei Kariv Glamour kaufen, wird jede Uhr sorgfältig geprüft und mit klarer Zustandsbewertung, Box- und Papiere-Informationen und Service-Historie (sofern verfügbar) präsentiert. Wir verkaufen keine Replika- oder Fälschungsuhren, und jede Produktseite bietet die Details, die Sie für eine zuversichtliche Entscheidung benötigen.',
  },
  {
    question_en: 'What does "box and papers" mean when buying a Patek Philippe?',
    question_de: 'Was bedeutet „Box und Papiere" beim Kauf einer Patek Philippe?',
    answer_en: 'Box and papers refers to the original presentation box and warranty documents that accompany a Patek Philippe watch. Having the original box and papers can enhance collectability and resale value. Learn more in our box and papers guide.',
    answer_de: 'Box und Papiere bezieht sich auf die originale Präsentationsbox und die Garantiedokumente, die eine Patek Philippe Uhr begleiten. Originalbox und -papiere können die Sammelbarkeit und den Wiederverkaufswert steigern. Erfahren Sie mehr in unserem Box-und-Papiere-Guide.',
  },
  {
    question_en: 'What is a Patek Philippe Archives Extract?',
    question_de: 'Was ist ein Patek Philippe Archives Extract?',
    answer_en: 'A Patek Philippe Archives Extract is an official document from the manufacturer that provides details about a specific watch, such as its production date, reference, and original configuration. It can add significant value and confidence for collectors. Learn more in our Patek Philippe Archives Extract Guide.',
    answer_de: 'Ein Patek Philippe Archives Extract ist ein offizielles Dokument der Manufaktur, das Details über eine bestimmte Uhr liefert, wie Produktionsdatum, Referenz und Originalkonfiguration. Es kann erheblichen Wert und Vertrauen für Sammler schaffen. Erfahren Sie mehr in unserem Patek Philippe Archives Extract Guide.',
  },
  {
    question_en: 'Which Patek Philippe should I buy first?',
    question_de: 'Welche Patek Philippe sollte ich zuerst kaufen?',
    answer_en: 'The right first Patek Philippe depends on your lifestyle, taste, and budget. The Calatrava is a timeless dress watch, while the Nautilus is an iconic sports model. Read our Patek Philippe buying guide for a detailed comparison of popular collections and references.',
    answer_de: 'Die richtige erste Patek Philippe hängt von Ihrem Lebensstil, Geschmack und Budget ab. Die Calatrava ist eine zeitlose Dress-Watch, während die Nautilus ein ikonisches Sportmodell ist. Lesen Sie unsere Patek Philippe Kaufberatung für einen detaillierten Vergleich beliebter Kollektionen und Referenzen.',
  },
  {
    question_en: 'What is the difference between Nautilus and Aquanaut?',
    question_de: 'Was ist der Unterschied zwischen Nautilus und Aquanaut?',
    answer_en: 'The Nautilus is a luxury sports watch with an integrated bracelet and a distinctive porthole-inspired case, while the Aquanaut has a more contemporary, sporty character with a composite strap and a relaxed design. Both are highly sought after by collectors. Explore Nautilus and Aquanaut collections to compare.',
    answer_de: 'Die Nautilus ist eine Luxus-Sportuhr mit integriertem Armband und einem markanten, von einem Bullauge inspirierten Gehäuse, während die Aquanaut einen zeitgenössischeren, sportlicheren Charakter mit einem Komposit-Armband und entspanntem Design hat. Beide sind bei Sammlern sehr begehrt. Erkunden Sie die Nautilus- und Aquanaut-Kollektionen, um zu vergleichen.',
  },
  {
    question_en: 'What is the difference between Calatrava and Grand Complications?',
    question_de: 'Was ist der Unterschied zwischen Calatrava und Grand Complications?',
    answer_en: 'The Calatrava is a pure dress watch collection focused on elegance and simplicity, while Grand Complications represent the highest level of Patek Philippe watchmaking, featuring advanced functions such as perpetual calendars, minute repeaters, and tourbillons. Explore Calatrava and Grand Complications to find the right model for you.',
    answer_de: 'Die Calatrava ist eine reine Dress-Watch-Kollektion, die auf Eleganz und Einfachheit fokussiert ist, während Grand Complications die höchste Stufe der Patek Philippe Uhrmacherei repräsentieren, mit fortgeschrittenen Funktionen wie ewigen Kalendern, Minutenrepetierern und Tourbillons. Erkunden Sie Calatrava und Grand Complications, um das richtige Modell für Sie zu finden.',
  },
  {
    question_en: 'Why are some Patek Philippe models difficult to find?',
    question_de: 'Warum sind einige Patek Philippe Modelle schwer zu finden?',
    answer_en: 'Certain Patek Philippe models are produced in limited quantities or experience exceptionally high demand, making them difficult to find. At Kariv Glamour, we curate a selection of available Patek Philippe watches, including sought-after references in the pre-owned market.',
    answer_de: 'Bestimmte Patek Philippe Modelle werden in limitierten Stückzahlen produziert oder erfahren eine außergewöhnlich hohe Nachfrage, was sie schwer auffindbar macht. Bei Kariv Glamour kuratieren wir eine Auswahl verfügbarer Patek Philippe Uhren, einschließlich begehrter Referenzen auf dem Gebrauchtmarkt.',
  },
  {
    question_en: 'Does Kariv Glamour sell Patek Philippe watches?',
    question_de: 'Verkauft Kariv Glamour Patek Philippe Uhren?',
    answer_en: 'Yes. Kariv Glamour offers a curated selection of Patek Philippe watches, including new, pre-owned, and vintage models. Each watch is presented with transparent product information, condition grading, and reference number visibility. Kariv Glamour is an independent retailer and is not an official Patek Philippe authorized dealer.',
    answer_de: 'Ja. Kariv Glamour bietet eine kuratierte Auswahl an Patek Philippe Uhren, einschließlich neuer, gebrauchter und Vintage-Modelle. Jede Uhr wird mit transparenter Produktinformation, Zustandsbewertung und Referenznummern-Sichtbarkeit präsentiert. Kariv Glamour ist ein unabhängiger Händler und kein offizieller Patek Philippe autorisierter Händler.',
  },
  {
    question_en: 'What should I check before buying a used Patek Philippe?',
    question_de: 'Worauf sollte ich vor dem Kauf einer gebrauchten Patek Philippe achten?',
    answer_en: 'Before buying a used Patek Philippe, check the condition grading, reference number, year of production, box and papers status, archives extract availability, service history, and authenticity. Our condition grading guide provides detailed information to help you evaluate each timepiece.',
    answer_de: 'Vor dem Kauf einer gebrauchten Patek Philippe sollten Sie die Zustandsbewertung, Referenznummer, Produktionsjahr, Box- und Papiere-Status, Archives Extract Verfügbarkeit, Service-Historie und Authentizität prüfen. Unser Zustandsbewertungs-Guide bietet detaillierte Informationen, um jeden Zeitmesser zu bewerten.',
  },
  {
    question_en: 'Are Patek Philippe watches good for collectors?',
    question_de: 'Sind Patek Philippe Uhren gut für Sammler?',
    answer_en: 'Yes. Patek Philippe is widely regarded as one of the most collectible watch brands in the world, admired for its rarity, craftsmanship, and long-standing heritage. Reference numbers, complications, materials, and documentation all play a role in collector value. Read our Patek Philippe buying guide to learn more.',
    answer_de: 'Ja. Patek Philippe wird weithin als eine der sammlerwürdigsten Uhrenmarken der Welt angesehen, bewundert für ihre Seltenheit, Handwerkskunst und langjähriges Erbe. Referenznummern, Komplikationen, Materialien und Dokumentation spielen alle eine Rolle beim Sammlerwert. Lesen Sie unsere Patek Philippe Kaufberatung, um mehr zu erfahren.',
  },
  {
    question_en: 'Can I return a Patek Philippe watch purchased online?',
    question_de: 'Kann ich eine online gekaufte Patek Philippe Uhr zurückgeben?',
    answer_en: 'Yes. Kariv Glamour offers a return policy for eligible purchases. Please review our returns and refunds page for full details on return conditions and process.',
    answer_de: 'Ja. Kariv Glamour bietet eine Rückgaberichtlinie für berechtigte Käufe. Bitte lesen Sie unsere Rückgaben- und Rückerstattungsseite für vollständige Details zu Rückgabebedingungen und -prozess.',
  },
];

// Trust points
export const PATEK_TRUST_POINTS = [
  { text_en: 'Transparent product descriptions', text_de: 'Transparente Produktbeschreibungen' },
  { text_en: 'Clear condition grading', text_de: 'Klare Zustandsbewertung' },
  { text_en: 'Box and papers information', text_de: 'Box- und Papiere-Informationen' },
  { text_en: 'Reference number visibility', text_de: 'Referenznummern-Sichtbarkeit' },
  { text_en: 'Archives extract information where available', text_de: 'Archives Extract Informationen, sofern verfügbar' },
  { text_en: 'Service history visibility where available', text_de: 'Service-Historie-Sichtbarkeit, sofern verfügbar' },
  { text_en: 'Secure checkout', text_de: 'Sicherer Checkout' },
  { text_en: 'Insured shipping', text_de: 'Versicherter Versand' },
  { text_en: 'Customer support before purchase', text_de: 'Kundensupport vor dem Kauf' },
  { text_en: 'No replica or counterfeit watches', text_de: 'Keine Replika- oder Fälschungsuhren' },
];

export const PATEK_TRUST_LINKS = [
  { text_en: 'Authentication Process', text_de: 'Authentifizierungsprozess', link: '/authentication-process' },
  { text_en: 'Condition Grading', text_de: 'Zustandsbewertung', link: '/condition-grading' },
  { text_en: 'Box and Papers Guide', text_de: 'Box-und-Papiere-Guide', link: '/watch-guides/box-and-papers' },
  { text_en: 'Archives Extract Guide', text_de: 'Archives Extract Guide', link: '/patek-philippe-archives-extract-guide' },
  { text_en: 'Returns and Refunds', text_de: 'Rückgaben und Rückerstattungen', link: '/legal/returns-refund-policy' },
  { text_en: 'Shipping Policy', text_de: 'Versandrichtlinie', link: '/legal/shipping-policy' },
  { text_en: 'Contact Customer Service', text_de: 'Kundenservice kontaktieren', link: '/customer-service' },
];

// SEO Landing pages content
export const PATEK_SEO_PAGES = {
  'patek-philippe-kaufen': {
    title_de: 'Patek Philippe kaufen | Neue & gebrauchte Patek Philippe Uhren | Kariv Glamour',
    title_en: 'Buy Patek Philippe | New & Pre-Owned Patek Philippe Watches | Kariv Glamour',
    description_de: 'Entdecken Sie Patek Philippe Uhren bei Kariv Glamour. Kaufen Sie neue, gebrauchte und vintage Patek Philippe Modelle wie Nautilus, Aquanaut, Calatrava, Cubitus, Twenty~4 und Grand Complications mit transparenter Produktinformation.',
    description_en: 'Discover Patek Philippe watches at Kariv Glamour. Buy new, pre-owned, and vintage Patek Philippe models like Nautilus, Aquanaut, Calatrava, Cubitus, Twenty~4, and Grand Complications with transparent product information.',
    h1_de: 'Patek Philippe kaufen bei Kariv Glamour',
    h1_en: 'Buy Patek Philippe at Kariv Glamour',
    intro_de: 'Bei Kariv Glamour können Sie Patek Philippe Uhren online kaufen — mit transparenter Produktinformation, klarer Zustandsbewertung und einem verfeinerten Einkaufserlebnis. Entdecken Sie neue, gebrauchte und vintage Patek Philippe Modelle von den bedeutendsten Kollektionen der Manufaktur.',
    intro_en: 'At Kariv Glamour, you can buy Patek Philippe watches online — with transparent product information, clear condition grading, and a refined shopping experience. Discover new, pre-owned, and vintage Patek Philippe models from the manufacturer\u2019s most significant collections.',
    collectionFilter: null,
  },
  'patek-philippe-gebraucht-kaufen': {
    title_de: 'Patek Philippe gebraucht kaufen | Pre-Owned Patek Philippe | Kariv Glamour',
    title_en: 'Buy Pre-Owned Patek Philippe | Pre-Owned Patek Philippe | Kariv Glamour',
    description_de: 'Patek Philippe gebraucht kaufen bei Kariv Glamour. Entdecken Sie geprüfte pre-owned Patek Philippe Uhren mit klarer Zustandsbewertung, Box und Papiere Informationen und detaillierter Produktpräsentation.',
    description_en: 'Buy pre-owned Patek Philippe at Kariv Glamour. Discover verified pre-owned Patek Philippe watches with clear condition grading, box and papers information, and detailed product presentation.',
    h1_de: 'Patek Philippe gebraucht kaufen',
    h1_en: 'Buy Pre-Owned Patek Philippe',
    intro_de: 'Wenn Sie eine Patek Philippe gebraucht kaufen möchten, bietet Kariv Glamour eine kuratierte Auswahl an pre-owned Zeitmessern. Jede Uhr wird mit klarer Zustandsbewertung, Box und Papiere Informationen, Archives Extract Verfügbarkeit und Referenznummern-Sichtbarkeit präsentiert.',
    intro_en: 'If you want to buy a pre-owned Patek Philippe, Kariv Glamour offers a curated selection of pre-owned timepieces. Each watch is presented with clear condition grading, box and papers information, archives extract availability, and reference number visibility.',
    collectionFilter: { isCertifiedPreOwned: true },
  },
  'patek-philippe-uhr-kaufen': {
    title_de: 'Patek Philippe Uhr kaufen | Patek Philippe Uhren online | Kariv Glamour',
    title_en: 'Buy a Patek Philippe Watch | Patek Philippe Watches Online | Kariv Glamour',
    description_de: 'Patek Philippe Uhr kaufen bei Kariv Glamour. Entdecken Sie Patek Philippe Uhren — von der Nautilus bis zur Calatrava — mit transparenter Produktinformation und klarer Zustandsbewertung.',
    description_en: 'Buy a Patek Philippe watch at Kariv Glamour. Discover Patek Philippe watches — from the Nautilus to the Calatrava — with transparent product information and clear condition grading.',
    h1_de: 'Patek Philippe Uhr kaufen',
    h1_en: 'Buy a Patek Philippe Watch',
    intro_de: 'Entdecken Sie Patek Philippe Uhren bei Kariv Glamour. Von der ikonischen Nautilus über die elegante Calatrava bis zu den Grand Complications — jede Uhr wird mit transparenter Produktinformation und klarer Zustandsbewertung präsentiert.',
    intro_en: 'Discover Patek Philippe watches at Kariv Glamour. From the iconic Nautilus to the elegant Calatrava and the Grand Complications — each watch is presented with transparent product information and clear condition grading.',
    collectionFilter: null,
  },
  'patek-philippe-nautilus-kaufen': {
    title_de: 'Patek Philippe Nautilus kaufen | Neue & gebrauchte Nautilus | Kariv Glamour',
    title_en: 'Buy Patek Philippe Nautilus | New & Pre-Owned Nautilus | Kariv Glamour',
    description_de: 'Patek Philippe Nautilus kaufen bei Kariv Glamour. Entdecken Sie eine der begehrtesten Luxus-Sportuhren der Welt, bekannt für ihre markante Gehäuseform und integriertes Armband.',
    description_en: 'Buy Patek Philippe Nautilus at Kariv Glamour. Discover one of the most coveted luxury sports watches in the world, known for its distinctive case shape and integrated bracelet.',
    h1_de: 'Patek Philippe Nautilus kaufen',
    h1_en: 'Buy Patek Philippe Nautilus',
    intro_de: 'Die Patek Philippe Nautilus ist eine der begehrtesten Luxus-Sportuhren der Welt. Bei Kariv Glamour können Sie die Nautilus kaufen — mit transparenter Produktinformation, klarer Zustandsbewertung und Referenznummern-Sichtbarkeit.',
    intro_en: 'The Patek Philippe Nautilus is one of the most coveted luxury sports watches in the world. At Kariv Glamour, you can buy the Nautilus — with transparent product information, clear condition grading, and reference number visibility.',
    collectionFilter: { collection: 'Nautilus' },
  },
  'patek-philippe-aquanaut-kaufen': {
    title_de: 'Patek Philippe Aquanaut kaufen | Neue & gebrauchte Aquanaut | Kariv Glamour',
    title_en: 'Buy Patek Philippe Aquanaut | New & Pre-Owned Aquanaut | Kariv Glamour',
    description_de: 'Patek Philippe Aquanaut kaufen bei Kariv Glamour. Entdecken Sie die moderne, sportliche Patek Philippe Kollektion mit entspanntem Charakter und starker Sammlernachfrage.',
    description_en: 'Buy Patek Philippe Aquanaut at Kariv Glamour. Discover the modern, sporty Patek Philippe collection with a relaxed character and strong collector demand.',
    h1_de: 'Patek Philippe Aquanaut kaufen',
    h1_en: 'Buy Patek Philippe Aquanaut',
    intro_de: 'Die Patek Philippe Aquanaut ist eine moderne, sportliche Kollektion mit entspanntem Charakter und starker Sammlernachfrage. Bei Kariv Glamour können Sie die Aquanaut kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Patek Philippe Aquanaut is a modern, sporty collection with a relaxed character and strong collector demand. At Kariv Glamour, you can buy the Aquanaut — with transparent product information.',
    collectionFilter: { collection: 'Aquanaut' },
  },
  'patek-philippe-calatrava-kaufen': {
    title_de: 'Patek Philippe Calatrava kaufen | Neue & gebrauchte Calatrava | Kariv Glamour',
    title_en: 'Buy Patek Philippe Calatrava | New & Pre-Owned Calatrava | Kariv Glamour',
    description_de: 'Patek Philippe Calatrava kaufen bei Kariv Glamour. Shoppen Sie die Calatrava — bewundert für klassische Eleganz, reine Linien und Dress-Watch-Raffinesse.',
    description_en: 'Buy Patek Philippe Calatrava at Kariv Glamour. Shop the Calatrava — admired for classic elegance, pure lines, and dress-watch refinement.',
    h1_de: 'Patek Philippe Calatrava kaufen',
    h1_en: 'Buy Patek Philippe Calatrava',
    intro_de: 'Die Patek Philippe Calatrava ist die reinste Ausdrucksform der Dress-Watch-Eleganz. Bei Kariv Glamour können Sie die Calatrava kaufen — mit transparenter Produktinformation und klarer Zustandsbewertung.',
    intro_en: 'The Patek Philippe Calatrava is the purest expression of dress-watch elegance. At Kariv Glamour, you can buy the Calatrava — with transparent product information and clear condition grading.',
    collectionFilter: { collection: 'Calatrava' },
  },
  'patek-philippe-cubitus-kaufen': {
    title_de: 'Patek Philippe Cubitus kaufen | Neue & gebrauchte Cubitus | Kariv Glamour',
    title_en: 'Buy Patek Philippe Cubitus | New & Pre-Owned Cubitus | Kariv Glamour',
    description_de: 'Patek Philippe Cubitus kaufen bei Kariv Glamour. Entdecken Sie die Cubitus Kollektion — ein zeitgenössischer Ausdruck von Shaped-Case-Design und moderner Eleganz.',
    description_en: 'Buy Patek Philippe Cubitus at Kariv Glamour. Discover the Cubitus collection — a contemporary expression of shaped-case design and modern elegance.',
    h1_de: 'Patek Philippe Cubitus kaufen',
    h1_en: 'Buy Patek Philippe Cubitus',
    intro_de: 'Die Patek Philippe Cubitus ist ein zeitgenössischer Ausdruck von Shaped-Case-Design und moderner Eleganz. Bei Kariv Glamour können Sie die Cubitus kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Patek Philippe Cubitus is a contemporary expression of shaped-case design and modern elegance. At Kariv Glamour, you can buy the Cubitus — with transparent product information.',
    collectionFilter: { collection: 'Cubitus' },
  },
  'patek-philippe-grand-complications-kaufen': {
    title_de: 'Patek Philippe Grand Complications kaufen | Kariv Glamour',
    title_en: 'Buy Patek Philippe Grand Complications | Kariv Glamour',
    description_de: 'Patek Philippe Grand Complications kaufen bei Kariv Glamour. Entdecken Sie die höchste Ausdrucksform der Patek Philippe Uhrmacherei für Sammler, die von fortgeschrittener mechanischer Kunstfertigkeit fasziniert sind.',
    description_en: 'Buy Patek Philippe Grand Complications at Kariv Glamour. Discover the highest expression of Patek Philippe watchmaking for collectors drawn to advanced mechanical artistry.',
    h1_de: 'Patek Philippe Grand Complications kaufen',
    h1_en: 'Buy Patek Philippe Grand Complications',
    intro_de: 'Patek Philippe Grand Complications repräsentieren die höchste Ausdrucksform der Uhrmacherei. Bei Kariv Glamour können Sie Grand Complications kaufen — mit transparenter Produktinformation und klarer Zustandsbewertung.',
    intro_en: 'Patek Philippe Grand Complications represent the highest expression of watchmaking. At Kariv Glamour, you can buy Grand Complications — with transparent product information and clear condition grading.',
    collectionFilter: { collection: 'Grand Complications' },
  },
  'patek-philippe-complications-kaufen': {
    title_de: 'Patek Philippe Complications kaufen | Kariv Glamour',
    title_en: 'Buy Patek Philippe Complications | Kariv Glamour',
    description_de: 'Patek Philippe Complications kaufen bei Kariv Glamour. Entdecken Sie eine anspruchsvolle Kollektion für Sammler, die nützliche und poetische Uhrfunktionen schätzen.',
    description_en: 'Buy Patek Philippe Complications at Kariv Glamour. Discover a sophisticated collection for collectors who appreciate useful and poetic watch functions.',
    h1_de: 'Patek Philippe Complications kaufen',
    h1_en: 'Buy Patek Philippe Complications',
    intro_de: 'Die Patek Philippe Complications Kollektion vereint nützliche und poetische Funktionen wie Kalender, Travel Time und Mondphasen. Bei Kariv Glamour können Sie Complications kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Patek Philippe Complications collection combines useful and poetic functions such as calendars, travel time, and moon phases. At Kariv Glamour, you can buy Complications — with transparent product information.',
    collectionFilter: { collection: 'Complications' },
  },
  'patek-philippe-twenty-4-kaufen': {
    title_de: 'Patek Philippe Twenty~4 kaufen | Kariv Glamour',
    title_en: 'Buy Patek Philippe Twenty~4 | Kariv Glamour',
    description_de: 'Patek Philippe Twenty~4 kaufen bei Kariv Glamour. Entdecken Sie eine verfeinerte Kollektion für eleganten täglichen Gebrauch mit femininen Proportionen und moderner Vielseitigkeit.',
    description_en: 'Buy Patek Philippe Twenty~4 at Kariv Glamour. Discover a refined collection for elegant daily wear with feminine proportions and modern versatility.',
    h1_de: 'Patek Philippe Twenty~4 kaufen',
    h1_en: 'Buy Patek Philippe Twenty~4',
    intro_de: 'Die Patek Philippe Twenty~4 ist eine verfeinerte Kollektion für eleganten täglichen Gebrauch. Bei Kariv Glamour können Sie die Twenty~4 kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Patek Philippe Twenty~4 is a refined collection for elegant daily wear. At Kariv Glamour, you can buy the Twenty~4 — with transparent product information.',
    collectionFilter: { collection: 'Twenty~4' },
  },
  'patek-philippe-golden-ellipse-kaufen': {
    title_de: 'Patek Philippe Golden Ellipse kaufen | Kariv Glamour',
    title_en: 'Buy Patek Philippe Golden Ellipse | Kariv Glamour',
    description_de: 'Patek Philippe Golden Ellipse kaufen bei Kariv Glamour. Entdecken Sie ein markantes Patek Philippe Design-Icon, bekannt für sein harmonisches elliptisches Gehäuse und verfeinerte Eleganz.',
    description_en: 'Buy Patek Philippe Golden Ellipse at Kariv Glamour. Discover a distinctive Patek Philippe design icon, known for its harmonious elliptical case and refined elegance.',
    h1_de: 'Patek Philippe Golden Ellipse kaufen',
    h1_en: 'Buy Patek Philippe Golden Ellipse',
    intro_de: 'Die Patek Philippe Golden Ellipse ist ein Design-Icon, bekannt für ihr harmonisches elliptisches Gehäuse. Bei Kariv Glamour können Sie die Golden Ellipse kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Patek Philippe Golden Ellipse is a design icon, known for its harmonious elliptical case. At Kariv Glamour, you can buy the Golden Ellipse — with transparent product information.',
    collectionFilter: { collection: 'Golden Ellipse' },
  },
  'patek-philippe-gondolo-kaufen': {
    title_de: 'Patek Philippe Gondolo kaufen | Kariv Glamour',
    title_en: 'Buy Patek Philippe Gondolo | Kariv Glamour',
    description_de: 'Patek Philippe Gondolo kaufen bei Kariv Glamour. Entdecken Sie eine Shaped-Watch-Kollektion, inspiriert von Art-Deco-Design, geometrischen Linien und klassischer Eleganz.',
    description_en: 'Buy Patek Philippe Gondolo at Kariv Glamour. Discover a shaped-watch collection inspired by Art Deco design, geometric lines, and classic elegance.',
    h1_de: 'Patek Philippe Gondolo kaufen',
    h1_en: 'Buy Patek Philippe Gondolo',
    intro_de: 'Die Patek Philippe Gondolo ist eine Shaped-Watch-Kollektion, inspiriert von Art-Deco-Design. Bei Kariv Glamour können Sie die Gondolo kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Patek Philippe Gondolo is a shaped-watch collection inspired by Art Deco design. At Kariv Glamour, you can buy the Gondolo — with transparent product information.',
    collectionFilter: { collection: 'Gondolo' },
  },
  'patek-philippe-herren': {
    title_de: 'Patek Philippe für Herren kaufen | Herren Patek Philippe Uhren | Kariv Glamour',
    title_en: 'Buy Patek Philippe for Men | Men\u2019s Patek Philippe Watches | Kariv Glamour',
    description_de: 'Patek Philippe für Herren kaufen bei Kariv Glamour. Entdecken Sie Patek Philippe Herrenuhren — von der Nautilus bis zur Calatrava — mit transparenter Produktinformation.',
    description_en: 'Buy Patek Philippe for men at Kariv Glamour. Discover Patek Philippe men\u2019s watches — from the Nautilus to the Calatrava — with transparent product information.',
    h1_de: 'Patek Philippe für Herren',
    h1_en: 'Patek Philippe for Men',
    intro_de: 'Entdecken Sie Patek Philippe Uhren für Herren bei Kariv Glamour. Von der sportlichen Nautilus bis zur eleganten Calatrava — jede Uhr wird mit transparenter Produktinformation präsentiert.',
    intro_en: 'Discover Patek Philippe watches for men at Kariv Glamour. From the sporty Nautilus to the elegant Calatrava — each watch is presented with transparent product information.',
    collectionFilter: { gender: 'Men' },
  },
  'patek-philippe-damen': {
    title_de: 'Patek Philippe für Damen kaufen | Damen Patek Philippe Uhren | Kariv Glamour',
    title_en: 'Buy Patek Philippe for Women | Women\u2019s Patek Philippe Watches | Kariv Glamour',
    description_de: 'Patek Philippe für Damen kaufen bei Kariv Glamour. Entdecken Sie Patek Philippe Damenuhren — von der Twenty~4 bis zur Golden Ellipse — mit transparenter Produktinformation.',
    description_en: 'Buy Patek Philippe for women at Kariv Glamour. Discover Patek Philippe women\u2019s watches — from the Twenty~4 to the Golden Ellipse — with transparent product information.',
    h1_de: 'Patek Philippe für Damen',
    h1_en: 'Patek Philippe for Women',
    intro_de: 'Entdecken Sie Patek Philippe Uhren für Damen bei Kariv Glamour. Von der Twenty~4 bis zur Golden Ellipse — jede Uhr wird mit transparenter Produktinformation präsentiert.',
    intro_en: 'Discover Patek Philippe watches for women at Kariv Glamour. From the Twenty~4 to the Golden Ellipse — each watch is presented with transparent product information.',
    collectionFilter: { gender: 'Women' },
  },
  'welche-patek-philippe-kaufen': {
    title_de: 'Welche Patek Philippe kaufen? | Patek Philippe Kaufberatung | Kariv Glamour',
    title_en: 'Which Patek Philippe to Buy? | Patek Philippe Buying Guide | Kariv Glamour',
    description_de: 'Welche Patek Philippe kaufen? Lesen Sie die Patek Philippe Kaufberatung bei Kariv Glamour, um Kollektionen, Referenzen, Materialien, Komplikationen und Besitzüberlegungen zu vergleichen.',
    description_en: 'Which Patek Philippe to buy? Read the Patek Philippe buying guide at Kariv Glamour to compare collections, references, materials, complications, and ownership considerations.',
    h1_de: 'Welche Patek Philippe kaufen?',
    h1_en: 'Which Patek Philippe to Buy?',
    intro_de: 'Die Wahl der richtigen Patek Philippe hängt von Ihrem Lebensstil, Geschmack und Budget ab. Die Calatrava ist ein zeitloser Dress-Watch, die Nautilus eine ikonische Sportuhr. Dieser Guide hilft Ihnen, die richtige Entscheidung zu treffen.',
    intro_en: 'The right Patek Philippe depends on your lifestyle, taste, and budget. The Calatrava is a timeless dress watch, while the Nautilus is an iconic sports model. This guide helps you make the right decision.',
    collectionFilter: null,
    isGuide: true,
  },
  'patek-philippe-neu-oder-gebraucht': {
    title_de: 'Patek Philippe neu oder gebraucht kaufen? | Kariv Glamour',
    title_en: 'Patek Philippe New or Pre-Owned? | Kariv Glamour',
    description_de: 'Patek Philippe neu oder gebraucht kaufen? Vergleichen Sie die Vor- und Nachteile beider Optionen bei Kariv Glamour, um die richtige Entscheidung zu treffen.',
    description_en: 'Patek Philippe new or pre-owned? Compare the pros and cons of both options at Kariv Glamour to make the right decision.',
    h1_de: 'Patek Philippe neu oder gebraucht kaufen?',
    h1_en: 'Patek Philippe New or Pre-Owned?',
    intro_de: 'Sollten Sie eine Patek Philippe neu oder gebraucht kaufen? Beide Optionen haben Vor- und Nachteile. Eine neue Patek Philippe bietet volle Garantie und unbenutzten Zustand, während eine gebrauchte Patek Philippe oft Zugang zu diskontinuierten Referenzen und einem anderen Preis-Leistungs-Verhältnis bietet.',
    intro_en: 'Should you buy a Patek Philippe new or pre-owned? Both options have pros and cons. A new Patek Philippe offers full warranty and unused condition, while a pre-owned Patek Philippe often provides access to discontinued references and a different price-to-performance ratio.',
    collectionFilter: null,
    isGuide: true,
  },
  'patek-philippe-archives-extract-guide': {
    title_de: 'Patek Philippe Archives Extract Guide | Kariv Glamour',
    title_en: 'Patek Philippe Archives Extract Guide | Kariv Glamour',
    description_de: 'Patek Philippe Archives Extract Guide bei Kariv Glamour. Erfahren Sie, warum das Archives Extract, Originaldokumente, Service-Historie und Kaufaufzeichnungen beim Patek Philippe Kauf wichtig sind.',
    description_en: 'Patek Philippe Archives Extract Guide at Kariv Glamour. Learn why the archives extract, original documents, service history, and purchase records matter when buying Patek Philippe.',
    h1_de: 'Patek Philippe Archives Extract Guide',
    h1_en: 'Patek Philippe Archives Extract Guide',
    intro_de: 'Ein Patek Philippe Archives Extract ist ein offizielles Dokument der Manufaktur, das Details über eine bestimmte Uhr liefert, wie Produktionsdatum, Referenz und Originalkonfiguration. Es kann erheblichen Wert und Vertrauen für Sammler schaffen.',
    intro_en: 'A Patek Philippe Archives Extract is an official document from the manufacturer that provides details about a specific watch, such as its production date, reference, and original configuration. It can add significant value and confidence for collectors.',
    collectionFilter: null,
    isGuide: true,
  },
  'patek-philippe-story': {
    title_de: 'Die Patek Philippe Geschichte | Erbe & Geschichte | Kariv Glamour',
    title_en: 'The Patek Philippe Story | Heritage & History | Kariv Glamour',
    description_de: 'Entdecken Sie die Patek Philippe Geschichte bei Kariv Glamour. Erfahren Sie über das Erbe, die Familienlegacy und die Sammleranziehungskraft hinter einem der respektiertesten Namen der feinen Uhrmacherei.',
    description_en: 'Discover the Patek Philippe story at Kariv Glamour. Learn about the heritage, family legacy, and collector appeal behind one of the most respected names in fine watchmaking.',
    h1_de: 'Die Patek Philippe Geschichte',
    h1_en: 'The Patek Philippe Story',
    intro_de: 'Patek Philippe ist einer der respektiertesten Namen der Haute Horlogerie, mit einem Erbe, das in der Genfer Uhrmacherei verwurzelt ist. Von den frühesten Taschenuhren bis zur ikonischen Nautilus und den außergewöhnlichen Grand Complications — die Patek Philippe Geschichte ist eine von seltener Handwerkskunst, Sammlerprestige und unerschütterlichem Engagement für feine Uhrmacherei.',
    intro_en: 'Patek Philippe is one of the most revered names in haute horlogerie, with a heritage rooted in Geneva watchmaking. From the earliest pocket watches to the iconic Nautilus and the extraordinary Grand Complications — the Patek Philippe story is one of rare craftsmanship, collector prestige, and an unwavering commitment to fine watchmaking.',
    collectionFilter: null,
    isGuide: true,
  },
  'patek-philippe-watchmaking': {
    title_de: 'Patek Philippe Uhrmacherei | Handwerkskunst & Präzision | Kariv Glamour',
    title_en: 'Patek Philippe Watchmaking | Craftsmanship & Precision | Kariv Glamour',
    description_de: 'Erfahren Sie über Patek Philippe Uhrmacherei bei Kariv Glamour. Werke, Komplikationen, Finissierung, Materialien und die Details, die Patek Philippe Uhren definieren.',
    description_en: 'Learn about Patek Philippe watchmaking at Kariv Glamour. Movements, complications, finishing, materials, and the details that define Patek Philippe watches.',
    h1_de: 'Patek Philippe Uhrmacherei',
    h1_en: 'Patek Philippe Watchmaking',
    intro_de: 'Patek Philippe Uhrmacherei repräsentiert den Höhepunkt feiner mechanischer Kunstfertigkeit, mit hand-finierten Werken, exquisitem Gehäusedesign und einer außergewöhnlichen Vielfalt an Komplikationen. Von einfachen Time-Only-Calatrava-Uhren bis zu ewigen Kalendern, Minutenrepetierern und Tourbillons.',
    intro_en: 'Patek Philippe watchmaking represents the pinnacle of fine mechanical artistry, with hand-finished movements, exquisite case design, and an extraordinary range of complications. From simple time-only Calatrava watches to perpetual calendars, minute repeaters, and tourbillons.',
    collectionFilter: null,
    isGuide: true,
  },
  'patek-philippe-maintenance': {
    title_de: 'Patek Philippe Wartung | Pflege & Service | Kariv Glamour',
    title_en: 'Patek Philippe Maintenance | Care & Servicing | Kariv Glamour',
    description_de: 'Patek Philippe Wartung und Pflege bei Kariv Glamour. Erfahren Sie, wie Sie eine Patek Philippe Uhr pflegen und ihren Zustand, ihre Dokumentation und ihren langfristigen Wert erhalten.',
    description_en: 'Patek Philippe maintenance and care at Kariv Glamour. Learn how to care for a Patek Philippe watch and preserve its condition, documentation, and long-term value.',
    h1_de: 'Patek Philippe Wartung',
    h1_en: 'Patek Philippe Maintenance',
    intro_de: 'Die richtige Pflege erhält die Schönheit, Zuverlässigkeit und den Wert einer Patek Philippe Uhr. Regelmäßige Wartung, Wasserdichtigkeitsprüfungen, sichere Aufbewahrung und das Vermeiden von Stößen und magnetischer Exposition sind wesentlich. Für gebrauchte und sammelbare Uhren ist die Erhaltung von Box, Papieren, Archives Extract und Service-Dokumenten besonders wichtig.',
    intro_en: 'Proper care preserves the beauty, reliability, and value of a Patek Philippe watch. Regular servicing, water resistance checks, safe storage, and avoiding shocks and magnetic exposure are essential. For pre-owned and collectible watches, preserving the box, papers, archives extract, and service documents is especially important.',
    collectionFilter: null,
    isGuide: true,
  },
};

applyCzechSeoPages(PATEK_SEO_PAGES, 'Patek Philippe', 'patekPhilippe');
applyCzechBrandFaqs(PATEK_FAQS, 'patekPhilippe');
applyCzechBrandContent('patekPhilippe', PATEK_COLLECTIONS, PATEK_QUICK_FILTERS, PATEK_SEO_CARDS, PATEK_READ_MORE, PATEK_INTERNAL_LINKS, PATEK_EDITORIAL_SECTIONS, PATEK_TRUST_POINTS, PATEK_TRUST_LINKS);
