// Rolex theme colors
export const ROLEX_THEME = {
  emerald: '#0B4D3C',
  emeraldDark: '#063528',
  emeraldLight: '#1A6B54',
  gold: '#C5A572',
  goldLight: '#D4BC8E',
  ivory: '#FAF7F2',
  warmWhite: '#FDFBF7',
  charcoal: '#1C1C1C',
  brownCharcoal: '#2A2018',
};

const ROLEX_ASSET_BASE = '/brand-assets/rolex';

export const ROLEX_LOGO = `${ROLEX_ASSET_BASE}/rolex-logo.svg`;
export const ROLEX_HERO_IMAGE = `${ROLEX_ASSET_BASE}/rolex-green-background-crown.jpg`;

// Legacy fallbacks for collection cards. Dashboard collection records override these.
const COLLECTION_FALLBACKS = {
  watch1: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
  watch2: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=80',
  watch3: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=800&q=80',
  watch4: 'https://images.unsplash.com/photo-1524592094714-0f06555e7420?auto=format&fit=crop&w=800&q=80',
  watch5: 'https://images.unsplash.com/photo-1495856458515-0637183dbd1e?auto=format&fit=crop&w=800&q=80',
  watch6: 'https://images.unsplash.com/photo-1606293459339-aaa4e5e9b1f4?auto=format&fit=crop&w=800&q=80',
  watch7: 'https://images.unsplash.com/photo-1612817159949-195b6119e6d5?auto=format&fit=crop&w=800&q=80',
  watch8: 'https://images.unsplash.com/photo-1639024471283-0350c0f7a7e6?auto=format&fit=crop&w=800&q=80',
};

const IMG = {
  buyRolexWatch: `${ROLEX_ASSET_BASE}/buy-rolex-watch.avif`,
  preOwnedRolex: `${ROLEX_ASSET_BASE}/pre-owned-rolex-watches.avif`,
  maintenance: `${ROLEX_ASSET_BASE}/rolex-watch-maintenance.avif`,
  watchmaking: `${ROLEX_ASSET_BASE}/rolex-watchmaking.avif`,
  datejustGroup: `${ROLEX_ASSET_BASE}/buy-rolex-datejust-watches.jpg`,
  datejustLifestyle: `${ROLEX_ASSET_BASE}/buy-rolex-datejust.webp`,
  daytonaLifestyle: `${ROLEX_ASSET_BASE}/buy-rolex-daytona.webp`,
  gmtMasterGroup: `${ROLEX_ASSET_BASE}/buy-rolex-gmt-master-ii-watches.jpg`,
  gmtMasterLifestyle: `${ROLEX_ASSET_BASE}/buy-rolex-gmt-master-ii.jpg`,
  submarinerLifestyle: `${ROLEX_ASSET_BASE}/buy-rolex-submariner.jpg`,
  dialMacro: `${ROLEX_ASSET_BASE}/buy-rolex.jpg`,
  preOwnedLuxury: `${ROLEX_ASSET_BASE}/pre-owned-luxury-rolex-watch.webp`,
  boxPapers: `${ROLEX_ASSET_BASE}/rolex-box-and-papers.webp`,
  daytonaGuide: `${ROLEX_ASSET_BASE}/rolex-daytona-guide.jpg`,
  legacy: `${ROLEX_ASSET_BASE}/rolex-legacy.jpg`,
  service: `${ROLEX_ASSET_BASE}/rolex-premium-service-maintenance.jpg`,
  submarinerGuide: `${ROLEX_ASSET_BASE}/rolex-submariner-guide.jpg`,
  story: `${ROLEX_ASSET_BASE}/the-rolex-story.jpg`,
  buyingGuide: `${ROLEX_ASSET_BASE}/which-rolex-watch-to-buy.jpg`,
};

// Rolex Collections
export const ROLEX_COLLECTIONS = [
  { id: 'land-dweller', name: 'Land-Dweller', slug: 'land-dweller', description_en: 'A modern Rolex collection with integrated bracelet design and forward-looking watchmaking character.', description_de: 'Eine moderne Rolex Kollektion mit integriertem Armbanddesign und zukunftsorientiertem Uhrmachercharakter.', image: COLLECTION_FALLBACKS.watch1, displayOrder: 1 },
  { id: 'air-king', name: 'Air-King', slug: 'air-king', description_en: 'A distinctive aviation-inspired Rolex made for those drawn to precision, legibility, and exploration.', description_de: 'Eine markante, von der Luftfahrt inspirierte Rolex für alle, die Präzision, Ablesbarkeit und Entdeckergeist schätzen.', image: COLLECTION_FALLBACKS.watch2, displayOrder: 2 },
  { id: 'daytona', name: 'Cosmograph Daytona', slug: 'daytona', description_en: 'The legendary Rolex chronograph associated with motorsport, speed, and high collectability.', description_de: 'Der legendäre Rolex Chronograph, assoziiert mit Motorsport, Geschwindigkeit und hoher Sammlerbegehrlichkeit.', image: COLLECTION_FALLBACKS.watch3, displayOrder: 3 },
  { id: 'datejust', name: 'Datejust', slug: 'datejust', description_en: 'A timeless Rolex classic known for everyday elegance, versatility, and enduring design.', description_de: 'Ein zeitloser Rolex Klassiker, bekannt für alltägliche Eleganz, Vielseitigkeit und beständiges Design.', image: COLLECTION_FALLBACKS.watch4, displayOrder: 4 },
  { id: 'lady-datejust', name: 'Lady-Datejust', slug: 'lady-datejust', description_en: 'A refined Rolex collection designed with elegant proportions and feminine sophistication.', description_de: 'Eine verfeinerte Rolex Kollektion mit eleganten Proportionen und femininer Raffinesse.', image: COLLECTION_FALLBACKS.watch5, displayOrder: 5 },
  { id: 'day-date', name: 'Day-Date', slug: 'day-date', description_en: 'A prestigious Rolex icon, often associated with precious metals, status, and timeless authority.', description_de: 'Eine prestigeträchtige Rolex Ikone, oft assoziiert mit Edelmetallen, Status und zeitloser Autorität.', image: COLLECTION_FALLBACKS.watch6, displayOrder: 6 },
  { id: 'deepsea', name: 'Deepsea', slug: 'deepsea', description_en: 'A professional Rolex diving watch built for extreme underwater performance.', description_de: 'Eine professionelle Rolex Taucheruhr, gebaut für extreme Unterwasserleistung.', image: COLLECTION_FALLBACKS.watch7, displayOrder: 7 },
  { id: 'explorer', name: 'Explorer', slug: 'explorer', description_en: 'A robust Rolex tool watch inspired by adventure, endurance, and mountain exploration.', description_de: 'Eine robuste Rolex Tool-Watch, inspiriert von Abenteuer, Ausdauer und Bergexploration.', image: COLLECTION_FALLBACKS.watch8, displayOrder: 8 },
  { id: 'explorer-ii', name: 'Explorer II', slug: 'explorer-ii', description_en: 'A practical Rolex watch designed for exploration, legibility, and second-time-zone functionality.', description_de: 'Eine praktische Rolex Uhr, konzipiert für Exploration, Ablesbarkeit und Zweitzeitzonen-Funktionalität.', image: COLLECTION_FALLBACKS.watch1, displayOrder: 9 },
  { id: 'gmt-master-ii', name: 'GMT-Master II', slug: 'gmt-master-ii', description_en: 'A cosmopolitan Rolex travel watch designed to display multiple time zones with ease.', description_de: 'Eine kosmopolitische Rolex Reisewatch, konzipiert für die einfache Anzeige mehrerer Zeitzonen.', image: COLLECTION_FALLBACKS.watch2, displayOrder: 10 },
  { id: 'oyster-perpetual', name: 'Oyster Perpetual', slug: 'oyster-perpetual', description_en: 'The purest expression of Rolex watchmaking, combining clean design and everyday durability.', description_de: 'Die reinste Ausdrucksform der Rolex Uhrmacherei, die klares Design und alltägliche Haltbarkeit vereint.', image: COLLECTION_FALLBACKS.watch3, displayOrder: 11 },
  { id: 'sea-dweller', name: 'Sea-Dweller', slug: 'sea-dweller', description_en: 'A professional diver\u2019s Rolex built for serious depth, strength, and performance.', description_de: 'Eine professionelle Taucher-Rolex, gebaut für ernsthafte Tiefe, Stärke und Leistung.', image: COLLECTION_FALLBACKS.watch4, displayOrder: 12 },
  { id: 'sky-dweller', name: 'Sky-Dweller', slug: 'sky-dweller', description_en: 'A sophisticated Rolex travel watch combining annual calendar functionality with dual-time display.', description_de: 'Eine anspruchsvolle Rolex Reisewatch, die Jahreskalender-Funktionalität mit Dual-Zeitanzeige vereint.', image: COLLECTION_FALLBACKS.watch5, displayOrder: 13 },
  { id: 'submariner', name: 'Submariner', slug: 'submariner', description_en: 'One of the world\u2019s most recognized luxury dive watches, admired for its strength and timeless design.', description_de: 'Eine der weltweit bekanntesten Luxus-Taucheruhren, bewundert für ihre Stärke und zeitloses Design.', image: COLLECTION_FALLBACKS.watch6, displayOrder: 14 },
  { id: 'yacht-master', name: 'Yacht-Master', slug: 'yacht-master', description_en: 'A nautical-inspired Rolex sports watch blending elegance, functionality, and luxury.', description_de: 'Eine nautisch inspirierte Rolex Sportuhr, die Eleganz, Funktionalität und Luxus vereint.', image: COLLECTION_FALLBACKS.watch7, displayOrder: 15 },
  { id: 'yacht-master-ii', name: 'Yacht-Master II', slug: 'yacht-master-ii', description_en: 'A highly technical Rolex regatta chronograph created for competitive sailing.', description_de: 'Ein hochtechnischer Rolex Regatta-Chronograph, geschaffen für den Segelwettbewerb.', image: COLLECTION_FALLBACKS.watch8, displayOrder: 16 },
  { id: '1908', name: '1908', slug: '1908', description_en: 'A refined dress watch collection that reflects Rolex elegance, heritage, and modern watchmaking.', description_de: 'Eine verfeinerte Dress-Watch-Kollektion, die Rolex Eleganz, Erbe und moderne Uhrmacherei widerspiegelt.', image: COLLECTION_FALLBACKS.watch1, displayOrder: 17 },
  { id: 'milgauss', name: 'Milgauss', slug: 'milgauss', description_en: 'A distinctive discontinued Rolex model with strong collector interest in the pre-owned market.', description_de: 'Ein markantes eingestelltes Rolex Modell mit starkem Sammlerinteresse auf dem Gebrauchtmarkt.', image: COLLECTION_FALLBACKS.watch2, displayOrder: 18 },
];

// Quick filter chips for product grid
export const ROLEX_QUICK_FILTERS = [
  { label_en: 'Rolex Submariner', label_de: 'Rolex Submariner', link: '/rolex-submariner-kaufen' },
  { label_en: 'Rolex Daytona', label_de: 'Rolex Daytona', link: '/rolex-daytona-kaufen' },
  { label_en: 'Rolex Datejust', label_de: 'Rolex Datejust', link: '/rolex-datejust-kaufen' },
  { label_en: 'Rolex GMT-Master II', label_de: 'Rolex GMT-Master II', link: '/rolex-gmt-master-ii-kaufen' },
  { label_en: 'Rolex Day-Date', label_de: 'Rolex Day-Date', link: '/rolex-day-date-kaufen' },
  { label_en: 'Rolex Oyster Perpetual', label_de: 'Rolex Oyster Perpetual', link: '/rolex-oyster-perpetual-kaufen' },
  { label_en: 'Pre-Owned Rolex', label_de: 'Gebrauchte Rolex', link: '/rolex-gebraucht-kaufen' },
  { label_en: 'Rolex with Box and Papers', label_de: 'Rolex mit Box und Papieren', link: '/rolex-box-papers-guide' },
];

// SEO Cards
export const ROLEX_SEO_CARDS = [
  { title_en: 'Buy Rolex', title_de: 'Rolex kaufen', description_en: 'Explore Rolex watches available through Kariv Glamour, with transparent product details and a refined online shopping experience.', description_de: 'Entdecken Sie bei Kariv Glamour verfügbare Rolex Uhren mit transparenten Produktdetails und einem verfeinerten Online-Einkaufserlebnis.', link: '/rolex-kaufen', image: IMG.dialMacro },
  { title_en: 'Buy Pre-Owned Rolex', title_de: 'Rolex gebraucht kaufen', description_en: 'Discover pre-owned Rolex watches with clear condition grading, box and papers information, and detailed product presentation.', description_de: 'Entdecken Sie gebrauchte Rolex Uhren mit klarer Zustandsbewertung, Box- und Papiere-Informationen und detaillierter Produktpräsentation.', link: '/rolex-gebraucht-kaufen', image: IMG.preOwnedLuxury },
  { title_en: 'Used Rolex Watches', title_de: 'Gebrauchte Rolex Uhren', description_en: 'Browse used Rolex watches across popular collections such as Datejust, Submariner, Daytona, GMT-Master II and Oyster Perpetual.', description_de: 'Stöbern Sie durch gebrauchte Rolex Uhren beliebter Kollektionen wie Datejust, Submariner, Daytona, GMT-Master II und Oyster Perpetual.', link: '/gebrauchte-rolex-uhren', image: IMG.preOwnedRolex },
  { title_en: 'Buy Rolex Submariner', title_de: 'Rolex Submariner kaufen', description_en: 'Explore one of the most iconic Rolex dive watches, known for its robust design and timeless appeal.', description_de: 'Entdecken Sie eine der ikonischsten Rolex Taucheruhren, bekannt für robustes Design und zeitlose Anziehungskraft.', link: '/rolex-submariner-kaufen', image: IMG.submarinerLifestyle },
  { title_en: 'Buy Rolex Daytona', title_de: 'Rolex Daytona kaufen', description_en: 'Discover Rolex Daytona watches, the legendary chronograph associated with motorsport and collectability.', description_de: 'Entdecken Sie Rolex Daytona Uhren, den legendären Chronographen, assoziiert mit Motorsport und Sammlerbegehrlichkeit.', link: '/rolex-daytona-kaufen', image: IMG.daytonaLifestyle },
  { title_en: 'Buy Rolex Datejust', title_de: 'Rolex Datejust kaufen', description_en: 'Shop Rolex Datejust watches, a versatile classic suitable for daily wear, formal style, and long-term ownership.', description_de: 'Shoppen Sie Rolex Datejust Uhren, ein vielseitiger Klassiker für täglichen Gebrauch, formellen Stil und langfristigen Besitz.', link: '/rolex-datejust-kaufen', image: IMG.datejustGroup },
  { title_en: 'Buy Rolex GMT-Master II', title_de: 'Rolex GMT-Master II kaufen', description_en: 'Explore Rolex GMT-Master II watches, designed for travelers and collectors who appreciate multi-time-zone functionality.', description_de: 'Entdecken Sie Rolex GMT-Master II Uhren, konzipiert für Reisende und Sammler, die Multizeitzone-Funktionalität schätzen.', link: '/rolex-gmt-master-ii-kaufen', image: IMG.gmtMasterGroup },
  { title_en: 'Which Rolex to Buy?', title_de: 'Welche Rolex kaufen?', description_en: 'Read the Rolex buying guide to understand which Rolex model may suit your lifestyle, taste, and collecting goals.', description_de: 'Lesen Sie die Rolex Kaufberatung, um zu verstehen, welches Rolex Modell zu Ihrem Lebensstil, Geschmack und Sammlerzielen passt.', link: '/welche-rolex-kaufen', image: IMG.buyingGuide },
];

// Editorial sections data (Story, Watchmaking, Maintenance)
export const ROLEX_EDITORIAL_SECTIONS = [
  {
    id: 'rolex-story',
    eyebrow_en: 'Heritage', eyebrow_de: 'Erbe',
    title_en: 'The Rolex Story', title_de: 'Die Rolex Story',
    description_en: 'Rolex has shaped the world of fine watchmaking for over a century, combining relentless innovation with an unmistakable design language. From the first waterproof Oyster case to the professional tool watches that accompanied explorers, divers, and aviators, the Rolex story is one of precision, prestige, and cultural recognition. At Kariv Glamour, we celebrate this heritage by offering carefully selected Rolex timepieces, each presented with full transparency and expert insight.',
    description_de: 'Rolex hat die Welt der feinen Uhrmacherei für über ein Jahrhundert geprägt und unermüdliche Innovation mit einer unverkennbaren Designsprache verbunden. Vom ersten wasserdichten Oyster-Gehäuse bis zu den professionellen Tool-Watches, die Entdecker, Taucher und Piloten begleiteten — die Rolex Story ist eine von Präzision, Prestige und kultureller Anerkennung. Bei Kariv Glamour feiern wir dieses Erbe mit sorgfältig ausgewählten Rolex Zeitmessern, die mit voller Transparenz und fachkundiger Einsicht präsentiert werden.',
    cta_en: 'Read the Rolex Story', cta_de: 'Die Rolex Story lesen',
    link: '/rolex/story', image: IMG.story,
    internalLinks: [
      { text_en: 'Rolex heritage', text_de: 'Rolex Erbe', link: '/rolex/story' },
      { text_en: 'professional watches', text_de: 'professionelle Uhren', link: '/rolex/submariner' },
      { text_en: 'classic Rolex design', text_de: 'klassisches Rolex Design', link: '/rolex/datejust' },
    ],
  },
  {
    id: 'rolex-watchmaking',
    eyebrow_en: 'Craftsmanship', eyebrow_de: 'Handwerkskunst',
    title_en: 'Rolex Watchmaking', title_de: 'Rolex Uhrmacherei',
    description_en: 'Rolex watchmaking stands for precision, robust case construction, and reliable automatic movements. From the legendary Oyster case to carefully selected materials, bracelets, and bezels, every component is engineered for longevity and performance. At Kariv Glamour, we help you understand the craftsmanship behind each Rolex, so you can make an informed and confident decision.',
    description_de: 'Rolex Uhrmacherei steht für Präzision, robuste Gehäusekonstruktion und zuverlässige automatische Werke. Vom legendären Oyster-Gehäuse bis zu sorgfältig ausgewählten Materialien, Armbändern und Lünetten — jede Komponente ist für Langlebigkeit und Leistung konstruiert. Bei Kariv Glamour helfen wir Ihnen, die Handwerkskunst hinter jeder Rolex zu verstehen, damit Sie eine informierte und zuversichtliche Entscheidung treffen können.',
    cta_en: 'Explore Rolex Watchmaking', cta_de: 'Rolex Uhrmacherei entdecken',
    link: '/rolex/watchmaking', image: IMG.watchmaking,
    internalLinks: [
      { text_en: 'Oyster case', text_de: 'Oyster-Gehäuse', link: '/rolex/watchmaking' },
      { text_en: 'automatic movements', text_de: 'automatische Werke', link: '/watch-guides/mechanical-vs-quartz-watches' },
      { text_en: 'materials', text_de: 'Materialien', link: '/watch-guides/watch-case-materials' },
      { text_en: 'bracelets', text_de: 'Armbänder', link: '/watch-guides/watch-bracelet-guide' },
    ],
  },
  {
    id: 'rolex-maintenance',
    eyebrow_en: 'Care', eyebrow_de: 'Pflege',
    title_en: 'Rolex Maintenance', title_de: 'Rolex Wartung',
    description_en: 'Proper care preserves the beauty, reliability, and value of a Rolex watch. Regular servicing, water resistance checks, bracelet and case care, careful storage, and avoiding shocks, magnets, and unauthorized modifications all contribute to long-term performance. For pre-owned Rolex watches, documentation and service history are especially important. Kariv Glamour provides guidance to help you maintain your timepiece with confidence.',
    description_de: 'Die richtige Pflege erhält die Schönheit, Zuverlässigkeit und den Wert einer Rolex Uhr. Regelmäßige Wartung, Wasserdichtigkeitsprüfungen, Armband- und Gehäusepflege, sorgfältige Aufbewahrung und das Vermeiden von Stößen, Magneten und unbefugten Modifikationen tragen zur langfristigen Leistung bei. Für gebrauchte Rolex Uhren sind Dokumentation und Service-Historie besonders wichtig. Kariv Glamour bietet Orientierung, damit Sie Ihren Zeitmesser zuversichtlich pflegen können.',
    cta_en: 'Learn About Rolex Maintenance', cta_de: 'Mehr über Rolex Wartung erfahren',
    link: '/rolex/maintenance', image: IMG.service,
    internalLinks: [
      { text_en: 'service history', text_de: 'Service-Historie', link: '/watch-guides/service-history' },
      { text_en: 'box and papers', text_de: 'Box und Papiere', link: '/rolex-box-papers-guide' },
      { text_en: 'condition grading', text_de: 'Zustandsbewertung', link: '/condition-grading' },
      { text_en: 'pre-owned Rolex', text_de: 'gebrauchte Rolex', link: '/rolex-gebraucht-kaufen' },
    ],
  },
];

// Read More carousel cards
export const ROLEX_READ_MORE = [
  { title_en: 'Rolex Story', title_de: 'Rolex Story', description_en: 'Explore the heritage, milestones, and enduring appeal behind one of the world\u2019s most recognized watchmakers.', description_de: 'Entdecken Sie das Erbe, die Meilensteine und die bleibende Anziehungskraft hinter einem der bekanntesten Uhrmacher der Welt.', link: '/rolex/story', image: IMG.story },
  { title_en: 'Rolex Watchmaking', title_de: 'Rolex Uhrmacherei', description_en: 'Learn about the precision, materials, movements, and design principles that shape Rolex watches.', description_de: 'Erfahren Sie mehr über Präzision, Materialien, Werke und Designprinzipien, die Rolex Uhren formen.', link: '/rolex/watchmaking', image: IMG.watchmaking },
  { title_en: 'Rolex Maintenance', title_de: 'Rolex Wartung', description_en: 'Understand how to care for a Rolex watch and preserve its condition, reliability, and long-term value.', description_de: 'Verstehen Sie, wie Sie eine Rolex Uhr pflegen und ihren Zustand, ihre Zuverlässigkeit und ihren langfristigen Wert erhalten.', link: '/rolex/maintenance', image: IMG.maintenance },
  { title_en: 'Rolex Buying Guide', title_de: 'Rolex Kaufberatung', description_en: 'Compare popular Rolex collections and learn what to check before buying a new or pre-owned Rolex.', description_de: 'Vergleichen Sie beliebte Rolex Kollektionen und erfahren Sie, worauf Sie vor dem Kauf einer neuen oder gebrauchten Rolex achten sollten.', link: '/welche-rolex-kaufen', image: IMG.buyingGuide },
  { title_en: 'Box and Papers', title_de: 'Box und Papiere', description_en: 'Learn why original box, warranty card, service documents, and purchase history matter when buying a Rolex.', description_de: 'Erfahren Sie, warum Originalbox, Garantiekarte, Servicedokumente und Kaufhistorie beim Rolex Kauf wichtig sind.', link: '/rolex-box-papers-guide', image: IMG.boxPapers },
  { title_en: 'Rolex Submariner Guide', title_de: 'Rolex Submariner Guide', description_en: 'Explore the design, appeal, and buying considerations behind the Rolex Submariner.', description_de: 'Entdecken Sie Design, Anziehungskraft und Überlegungen zum Kauf der Rolex Submariner.', link: '/rolex-submariner-kaufen', image: IMG.submarinerGuide },
  { title_en: 'Rolex Daytona Guide', title_de: 'Rolex Daytona Guide', description_en: 'Learn why the Rolex Daytona remains one of the most desired chronographs in luxury watch collecting.', description_de: 'Erfahren Sie, warum die Rolex Daytona einer der begehrtesten Chronographen im Luxusuhren-Sammeln bleibt.', link: '/rolex-daytona-kaufen', image: IMG.daytonaGuide },
];

// Internal linking hub
export const ROLEX_INTERNAL_LINKS = {
  popularSearches: [
    { text_en: 'Buy Rolex', text_de: 'Rolex kaufen', link: '/rolex-kaufen' },
    { text_en: 'Buy Pre-Owned Rolex', text_de: 'Rolex gebraucht kaufen', link: '/rolex-gebraucht-kaufen' },
    { text_en: 'Used Rolex Watches', text_de: 'Gebrauchte Rolex Uhren', link: '/gebrauchte-rolex-uhren' },
    { text_en: 'Rolex for Men', text_de: 'Rolex für Herren', link: '/rolex-herren' },
    { text_en: 'Rolex for Women', text_de: 'Rolex für Damen', link: '/rolex-damen' },
    { text_en: 'Rolex with Box and Papers', text_de: 'Rolex mit Box und Papieren', link: '/rolex-box-papers-guide' },
  ],
  iconicModels: [
    { text_en: 'Buy Rolex Submariner', text_de: 'Rolex Submariner kaufen', link: '/rolex-submariner-kaufen' },
    { text_en: 'Buy Rolex Daytona', text_de: 'Rolex Daytona kaufen', link: '/rolex-daytona-kaufen' },
    { text_en: 'Buy Rolex Datejust', text_de: 'Rolex Datejust kaufen', link: '/rolex-datejust-kaufen' },
    { text_en: 'Buy Rolex GMT-Master II', text_de: 'Rolex GMT-Master II kaufen', link: '/rolex-gmt-master-ii-kaufen' },
    { text_en: 'Buy Rolex Day-Date', text_de: 'Rolex Day-Date kaufen', link: '/rolex-day-date-kaufen' },
    { text_en: 'Buy Rolex Oyster Perpetual', text_de: 'Rolex Oyster Perpetual kaufen', link: '/rolex-oyster-perpetual-kaufen' },
  ],
  learningGuides: [
    { text_en: 'Which Rolex to Buy?', text_de: 'Welche Rolex kaufen?', link: '/welche-rolex-kaufen' },
    { text_en: 'Rolex New or Pre-Owned?', text_de: 'Rolex neu oder gebraucht?', link: '/rolex-neu-oder-gebraucht' },
    { text_en: 'Rolex Box and Papers Guide', text_de: 'Rolex Box und Papiere Guide', link: '/rolex-box-papers-guide' },
    { text_en: 'Rolex Maintenance and Care', text_de: 'Rolex Wartung und Pflege', link: '/rolex/maintenance' },
    { text_en: 'Rolex Story', text_de: 'Rolex Story', link: '/rolex/story' },
    { text_en: 'Rolex Watchmaking', text_de: 'Rolex Uhrmacherei', link: '/rolex/watchmaking' },
  ],
  relatedBrands: [
    { text_en: 'Patek Philippe watches', text_de: 'Patek Philippe Uhren', link: '/brands/patek-philippe' },
    { text_en: 'Omega watches', text_de: 'Omega Uhren', link: '/brands/omega' },
    { text_en: 'Cartier watches', text_de: 'Cartier Uhren', link: '/brands/cartier' },
    { text_en: 'Audemars Piguet watches', text_de: 'Audemars Piguet Uhren', link: '/brands/audemars-piguet' },
    { text_en: 'Breitling watches', text_de: 'Breitling Uhren', link: '/brands/breitling' },
    { text_en: 'Tudor watches', text_de: 'Tudor Uhren', link: '/brands/tudor' },
  ],
  relatedCategories: [
    { text_en: 'Certified Pre-Owned Watches', text_de: 'Zertifizierte gebrauchte Uhren', link: '/certified-pre-owned' },
    { text_en: 'Vintage Watches', text_de: 'Vintage Uhren', link: '/vintage-watches' },
    { text_en: 'Men\u2019s Luxury Watches', text_de: 'Herren-Luxusuhren', link: '/mens-watches' },
    { text_en: 'Women\u2019s Luxury Watches', text_de: 'Damen-Luxusuhren', link: '/womens-watches' },
    { text_en: 'Dive Watches', text_de: 'Taucheruhren', link: '/collections/dive-watches' },
    { text_en: 'Chronograph Watches', text_de: 'Chronographen-Uhren', link: '/collections/chronograph-watches' },
    { text_en: 'Travel / GMT Watches', text_de: 'Reise- / GMT-Uhren', link: '/collections/gmt-watches' },
    { text_en: 'Dress Watches', text_de: 'Dress-Watches', link: '/collections/dress-watches' },
  ],
};

// FAQ
export const ROLEX_FAQS = [
  {
    question_en: 'Where can I buy a Rolex online?',
    question_de: 'Wo kann ich eine Rolex online kaufen?',
    answer_en: 'You can buy a Rolex online through Kariv Glamour, where each timepiece is presented with transparent product details, clear condition grading, and reference number visibility. Browse our Rolex collection to explore available models, or visit our pre-owned Rolex page for previously owned timepieces.',
    answer_de: 'Sie können eine Rolex online bei Kariv Glamour kaufen, wo jeder Zeitmesser mit transparenten Produktdetails, klarer Zustandsbewertung und Referenznummern-Sichtbarkeit präsentiert wird. Stöbern Sie durch unsere Rolex Kollektion, um verfügbare Modelle zu entdecken, oder besuchen Sie unsere Seite für gebrauchte Rolex Uhren.',
  },
  {
    question_en: 'Is it safe to buy a pre-owned Rolex?',
    question_de: 'Ist es sicher, eine gebrauchte Rolex zu kaufen?',
    answer_en: 'Yes. When you buy a pre-owned Rolex from Kariv Glamour, each watch is carefully reviewed and presented with clear condition grading, box and papers information, and service history where available. We do not sell replica or counterfeit watches, and every product page provides the details you need to make a confident decision.',
    answer_de: 'Ja. Wenn Sie eine gebrauchte Rolex bei Kariv Glamour kaufen, wird jede Uhr sorgfältig geprüft und mit klarer Zustandsbewertung, Box- und Papiere-Informationen und Service-Historie (sofern verfügbar) präsentiert. Wir verkaufen keine Replika- oder Fälschungsuhren, und jede Produktseite bietet die Details, die Sie für eine zuversichtliche Entscheidung benötigen.',
  },
  {
    question_en: 'What does "box and papers" mean when buying a Rolex?',
    question_de: 'Was bedeutet „Box und Papiere" beim Kauf einer Rolex?',
    answer_en: 'Box and papers refers to the original presentation box and warranty documents that accompany a Rolex watch. Having the original box and papers can enhance collectability and resale value. Learn more in our Rolex Box and Papers Guide.',
    answer_de: 'Box und Papiere bezieht sich auf die originale Präsentationsbox und die Garantiedokumente, die eine Rolex Uhr begleiten. Der Besitz der Originalbox und -papiere kann die Sammlerbegehrlichkeit und den Wiederverkaufswert steigern. Erfahren Sie mehr in unserem Rolex Box-und-Papiere-Guide.',
  },
  {
    question_en: 'Which Rolex should I buy first?',
    question_de: 'Welche Rolex sollte ich zuerst kaufen?',
    answer_en: 'The right first Rolex depends on your lifestyle, taste, and budget. The Datejust is a versatile classic, while the Submariner is an iconic sports watch. Read our Rolex buying guide for a detailed comparison of popular models.',
    answer_de: 'Die richtige erste Rolex hängt von Ihrem Lebensstil, Geschmack und Budget ab. Die Datejust ist ein vielseitiger Klassiker, während die Submariner eine ikonische Sportuhr ist. Lesen Sie unsere Rolex Kaufberatung für einen detaillierten Vergleich beliebter Modelle.',
  },
  {
    question_en: 'What is the difference between Rolex Datejust and Day-Date?',
    question_de: 'Was ist der Unterschied zwischen Rolex Datejust und Day-Date?',
    answer_en: 'The Rolex Datejust displays the date, while the Day-Date displays both the day and the date. The Day-Date is traditionally crafted in precious metals and is often considered the more prestigious model. Explore Datejust and Day-Date collections to compare.',
    answer_de: 'Die Rolex Datejust zeigt das Datum an, während die Day-Date sowohl den Wochentag als auch das Datum anzeigt. Die Day-Date wird traditionell aus Edelmetallen gefertigt und gilt oft als das prestigeträchtigere Modell. Erkunden Sie die Datejust- und Day-Date-Kollektionen, um zu vergleichen.',
  },
  {
    question_en: 'What is the difference between Rolex Submariner and Sea-Dweller?',
    question_de: 'Was ist der Unterschied zwischen Rolex Submariner und Sea-Dweller?',
    answer_en: 'Both are professional diving watches, but the Sea-Dweller is built for greater depth ratings and more extreme underwater use. The Submariner is more versatile for everyday wear. Compare the Submariner and Sea-Dweller to find the right model for you.',
    answer_de: 'Beide sind professionelle Taucheruhren, aber die Sea-Dweller ist für größere Tiefraten und extremere Unterwassernutzung gebaut. Die Submariner ist vielseitiger für den täglichen Gebrauch. Vergleichen Sie die Submariner und Sea-Dweller, um das richtige Modell für Sie zu finden.',
  },
  {
    question_en: 'Why are some Rolex models difficult to find?',
    question_de: 'Warum sind einige Rolex Modelle schwer zu finden?',
    answer_en: 'Certain Rolex models are produced in limited quantities or experience high demand, making them harder to find at retail. At Kariv Glamour, we curate a selection of available Rolex watches, including sought-after references in the pre-owned market.',
    answer_de: 'Bestimmte Rolex Modelle werden in limitierten Stückzahlen produziert oder erleben eine hohe Nachfrage, was sie im Einzelhandel schwerer auffindbar macht. Bei Kariv Glamour kuratieren wir eine Auswahl verfügbarer Rolex Uhren, einschließlich begehrter Referenzen auf dem Gebrauchtmarkt.',
  },
  {
    question_en: 'Does Kariv Glamour sell Rolex watches?',
    question_de: 'Verkauft Kariv Glamour Rolex Uhren?',
    answer_en: 'Yes. Kariv Glamour offers a curated selection of Rolex watches, including new, pre-owned, and vintage models. Each watch is presented with transparent product information, condition grading, and reference number visibility.',
    answer_de: 'Ja. Kariv Glamour bietet eine kuratierte Auswahl an Rolex Uhren, einschließlich neuer, gebrauchter und Vintage-Modelle. Jede Uhr wird mit transparenter Produktinformation, Zustandsbewertung und Referenznummern-Sichtbarkeit präsentiert.',
  },
  {
    question_en: 'Can I return a Rolex purchased online?',
    question_de: 'Kann ich eine online gekaufte Rolex zurückgeben?',
    answer_en: 'Yes. Kariv Glamour offers a return policy for eligible purchases. Please review our Returns and Refunds page for full details on return conditions and process.',
    answer_de: 'Ja. Kariv Glamour bietet eine Rückgaberichtlinie für berechtigte Käufe. Bitte lesen Sie unsere Rückgaben- und Rückerstattungsseite für vollständige Details zu Rückgabebedingungen und -prozess.',
  },
  {
    question_en: 'What should I check before buying a used Rolex?',
    question_de: 'Worauf sollte ich vor dem Kauf einer gebrauchten Rolex achten?',
    answer_en: 'Before buying a used Rolex, check the condition grading, reference number, year of production, box and papers status, service history, and authenticity. Our condition grading guide provides detailed information to help you evaluate each timepiece.',
    answer_de: 'Vor dem Kauf einer gebrauchten Rolex sollten Sie die Zustandsbewertung, Referenznummer, Produktionsjahr, Box- und Papiere-Status, Service-Historie und Authentizität prüfen. Unser Zustandsbewertungs-Guide bietet detaillierte Informationen, um jeden Zeitmesser zu bewerten.',
  },
];

// Trust points
export const ROLEX_TRUST_POINTS = [
  { text_en: 'Transparent product descriptions', text_de: 'Transparente Produktbeschreibungen' },
  { text_en: 'Clear condition grading', text_de: 'Klare Zustandsbewertung' },
  { text_en: 'Box and papers information', text_de: 'Box- und Papiere-Informationen' },
  { text_en: 'Reference number visibility', text_de: 'Referenznummern-Sichtbarkeit' },
  { text_en: 'Secure checkout', text_de: 'Sicherer Checkout' },
  { text_en: 'Insured shipping', text_de: 'Versicherter Versand' },
  { text_en: 'Customer support before purchase', text_de: 'Kundensupport vor dem Kauf' },
  { text_en: 'No replica or counterfeit watches', text_de: 'Keine Replika- oder Fälschungsuhren' },
];

export const ROLEX_TRUST_LINKS = [
  { text_en: 'Authentication Process', text_de: 'Authentifizierungsprozess', link: '/authentication' },
  { text_en: 'Condition Grading', text_de: 'Zustandsbewertung', link: '/condition-grading' },
  { text_en: 'Returns and Refunds', text_de: 'Rückgaben und Rückerstattungen', link: '/returns-and-refunds' },
  { text_en: 'Shipping Policy', text_de: 'Versandrichtlinie', link: '/shipping-policy' },
  { text_en: 'Contact Customer Service', text_de: 'Kundenservice kontaktieren', link: '/customer-service' },
];

// SEO Landing pages content
export const ROLEX_SEO_PAGES = {
  'rolex-kaufen': {
    title_de: 'Rolex kaufen | Neue & gebrauchte Rolex Uhren | Kariv Glamour',
    title_en: 'Buy Rolex | New & Pre-Owned Rolex Watches | Kariv Glamour',
    description_de: 'Entdecken Sie Rolex Uhren bei Kariv Glamour. Kaufen Sie neue, gebrauchte und vintage Rolex Modelle wie Submariner, Daytona, Datejust, GMT-Master II, Day-Date und Oyster Perpetual mit transparenter Produktinformation.',
    description_en: 'Discover Rolex watches at Kariv Glamour. Buy new, pre-owned, and vintage Rolex models like Submariner, Daytona, Datejust, GMT-Master II, Day-Date, and Oyster Perpetual with transparent product information.',
    h1_de: 'Rolex kaufen bei Kariv Glamour',
    h1_en: 'Buy Rolex at Kariv Glamour',
    intro_de: 'Bei Kariv Glamour können Sie Rolex Uhren online kaufen — mit transparenter Produktinformation, klarer Zustandsbewertung und einem verfeinerten Einkaufserlebnis. Entdecken Sie neue, gebrauchte und vintage Rolex Modelle von den ikonischsten Kollektionen der Manufaktur.',
    intro_en: 'At Kariv Glamour, you can buy Rolex watches online — with transparent product information, clear condition grading, and a refined shopping experience. Discover new, pre-owned, and vintage Rolex models from the manufacturer\u2019s most iconic collections.',
    collectionFilter: null,
  },
  'rolex-gebraucht-kaufen': {
    title_de: 'Rolex gebraucht kaufen | Pre-Owned Rolex Uhren | Kariv Glamour',
    title_en: 'Buy Pre-Owned Rolex | Pre-Owned Rolex Watches | Kariv Glamour',
    description_de: 'Rolex gebraucht kaufen bei Kariv Glamour. Entdecken Sie geprüfte pre-owned Rolex Uhren mit klarer Zustandsbewertung, Box und Papiere Informationen und detaillierter Produktpräsentation.',
    description_en: 'Buy pre-owned Rolex at Kariv Glamour. Discover verified pre-owned Rolex watches with clear condition grading, box and papers information, and detailed product presentation.',
    h1_de: 'Rolex gebraucht kaufen',
    h1_en: 'Buy Pre-Owned Rolex',
    intro_de: 'Wenn Sie eine Rolex gebraucht kaufen möchten, bietet Kariv Glamour eine kuratierte Auswahl an pre-owned Zeitmessern. Jede Uhr wird mit klarer Zustandsbewertung, Box und Papiere Informationen und Referenznummern-Sichtbarkeit präsentiert.',
    intro_en: 'If you want to buy a pre-owned Rolex, Kariv Glamour offers a curated selection of pre-owned timepieces. Each watch is presented with clear condition grading, box and papers information, and reference number visibility.',
    collectionFilter: { isCertifiedPreOwned: true },
  },
  'gebrauchte-rolex-uhren': {
    title_de: 'Gebrauchte Rolex Uhren | Used Rolex Watches | Kariv Glamour',
    title_en: 'Used Rolex Watches | Pre-Owned Rolex | Kariv Glamour',
    description_de: 'Browse gebrauchte Rolex Uhren bei Kariv Glamour. Datejust, Submariner, Daytona, GMT-Master II und Oyster Perpetual — mit transparenter Zustandsbewertung und Referenznummern.',
    description_en: 'Browse used Rolex watches at Kariv Glamour. Datejust, Submariner, Daytona, GMT-Master II and Oyster Perpetual — with transparent condition grading and reference numbers.',
    h1_de: 'Gebrauchte Rolex Uhren',
    h1_en: 'Used Rolex Watches',
    intro_de: 'Stöbern Sie durch gebrauchte Rolex Uhren bei Kariv Glamour. Von der Datejust über die Submariner bis zur Daytona — jede Uhr wird mit transparenter Zustandsbewertung und vollständigen Produktinformationen präsentiert.',
    intro_en: 'Browse used Rolex watches at Kariv Glamour. From the Datejust to the Submariner to the Daytona — each watch is presented with transparent condition grading and complete product information.',
    collectionFilter: { isCertifiedPreOwned: true },
  },
  'rolex-submariner-kaufen': {
    title_de: 'Rolex Submariner kaufen | Neue & gebrauchte Submariner | Kariv Glamour',
    title_en: 'Buy Rolex Submariner | New & Pre-Owned Submariner | Kariv Glamour',
    description_de: 'Rolex Submariner kaufen bei Kariv Glamour. Entdecken Sie eine der ikonischsten Rolex Taucheruhren, bekannt für robustes Design und zeitlose Anziehungskraft.',
    description_en: 'Buy Rolex Submariner at Kariv Glamour. Discover one of the most iconic Rolex dive watches, known for its robust design and timeless appeal.',
    h1_de: 'Rolex Submariner kaufen',
    h1_en: 'Buy Rolex Submariner',
    intro_de: 'Die Rolex Submariner ist eine der bekanntesten Luxus-Taucheruhren der Welt. Bei Kariv Glamour können Sie die Submariner kaufen — mit transparenter Produktinformation und klarer Zustandsbewertung.',
    intro_en: 'The Rolex Submariner is one of the world\u2019s best-known luxury dive watches. At Kariv Glamour, you can buy the Submariner — with transparent product information and clear condition grading.',
    collectionFilter: { collection: 'Submariner' },
  },
  'rolex-daytona-kaufen': {
    title_de: 'Rolex Daytona kaufen | Cosmograph Daytona | Kariv Glamour',
    title_en: 'Buy Rolex Daytona | Cosmograph Daytona | Kariv Glamour',
    description_de: 'Rolex Daytona kaufen bei Kariv Glamour. Entdecken Sie den legendären Rolex Chronographen, assoziiert mit Motorsport, Geschwindigkeit und hoher Sammlerbegehrlichkeit.',
    description_en: 'Buy Rolex Daytona at Kariv Glamour. Discover the legendary Rolex chronograph, associated with motorsport, speed, and high collectability.',
    h1_de: 'Rolex Daytona kaufen',
    h1_en: 'Buy Rolex Daytona',
    intro_de: 'Die Rolex Cosmograph Daytona ist einer der begehrtesten Chronographen der Welt. Bei Kariv Glamour können Sie die Daytona kaufen — mit transparenter Produktinformation und klarer Zustandsbewertung.',
    intro_en: 'The Rolex Cosmograph Daytona is one of the most coveted chronographs in the world. At Kariv Glamour, you can buy the Daytona — with transparent product information and clear condition grading.',
    collectionFilter: { collection: 'Daytona' },
  },
  'rolex-datejust-kaufen': {
    title_de: 'Rolex Datejust kaufen | Neue & gebrauchte Datejust | Kariv Glamour',
    title_en: 'Buy Rolex Datejust | New & Pre-Owned Datejust | Kariv Glamour',
    description_de: 'Rolex Datejust kaufen bei Kariv Glamour. Shoppen Sie die Datejust — ein vielseitiger Klassiker für täglichen Gebrauch, formellen Stil und langfristigen Besitz.',
    description_en: 'Buy Rolex Datejust at Kariv Glamour. Shop the Datejust — a versatile classic for daily wear, formal style, and long-term ownership.',
    h1_de: 'Rolex Datejust kaufen',
    h1_en: 'Buy Rolex Datejust',
    intro_de: 'Die Rolex Datejust ist ein zeitloser Klassiker, der sich für täglichen Gebrauch, formellen Stil und langfristigen Besitz eignet. Bei Kariv Glamour können Sie die Datejust kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Rolex Datejust is a timeless classic suitable for daily wear, formal style, and long-term ownership. At Kariv Glamour, you can buy the Datejust — with transparent product information.',
    collectionFilter: { collection: 'Datejust' },
  },
  'rolex-gmt-master-ii-kaufen': {
    title_de: 'Rolex GMT-Master II kaufen | Travel GMT Watches | Kariv Glamour',
    title_en: 'Buy Rolex GMT-Master II | Travel GMT Watches | Kariv Glamour',
    description_de: 'Rolex GMT-Master II kaufen bei Kariv Glamour. Entdecken Sie Rolex GMT-Master II Uhren, konzipiert für Reisende und Sammler, die Multizeitzone-Funktionalität schätzen.',
    description_en: 'Buy Rolex GMT-Master II at Kariv Glamour. Discover Rolex GMT-Master II watches, designed for travelers and collectors who appreciate multi-time-zone functionality.',
    h1_de: 'Rolex GMT-Master II kaufen',
    h1_en: 'Buy Rolex GMT-Master II',
    intro_de: 'Die Rolex GMT-Master II ist ein kosmopolitisches Reisewerkzeug, das mehrere Zeitzonen anzeigt. Bei Kariv Glamour können Sie die GMT-Master II kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Rolex GMT-Master II is a cosmopolitan travel watch that displays multiple time zones. At Kariv Glamour, you can buy the GMT-Master II — with transparent product information.',
    collectionFilter: { collection: 'GMT-Master II' },
  },
  'rolex-day-date-kaufen': {
    title_de: 'Rolex Day-Date kaufen | Präsidenten-Uhr | Kariv Glamour',
    title_en: 'Buy Rolex Day-Date | President Watch | Kariv Glamour',
    description_de: 'Rolex Day-Date kaufen bei Kariv Glamour. Entdecken Sie die prestigeträchtige Rolex Ikone, oft assoziiert mit Edelmetallen, Status und zeitloser Autorität.',
    description_en: 'Buy Rolex Day-Date at Kariv Glamour. Discover the prestigious Rolex icon, often associated with precious metals, status, and timeless authority.',
    h1_de: 'Rolex Day-Date kaufen',
    h1_en: 'Buy Rolex Day-Date',
    intro_de: 'Die Rolex Day-Date ist eine prestigeträchtige Ikone, traditionell in Edelmetallen gefertigt. Bei Kariv Glamour können Sie die Day-Date kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Rolex Day-Date is a prestigious icon, traditionally crafted in precious metals. At Kariv Glamour, you can buy the Day-Date — with transparent product information.',
    collectionFilter: { collection: 'Day-Date' },
  },
  'rolex-oyster-perpetual-kaufen': {
    title_de: 'Rolex Oyster Perpetual kaufen | Kariv Glamour',
    title_en: 'Buy Rolex Oyster Perpetual | Kariv Glamour',
    description_de: 'Rolex Oyster Perpetual kaufen bei Kariv Glamour. Die reinste Ausdrucksform der Rolex Uhrmacherei — sauberes Design und alltägliche Zuverlässigkeit.',
    description_en: 'Buy Rolex Oyster Perpetual at Kariv Glamour. The purest expression of Rolex watchmaking — clean design and everyday reliability.',
    h1_de: 'Rolex Oyster Perpetual kaufen',
    h1_en: 'Buy Rolex Oyster Perpetual',
    intro_de: 'Die Rolex Oyster Perpetual ist die reinste Ausdrucksform der Rolex Uhrmacherei. Bei Kariv Glamour können Sie die Oyster Perpetual kaufen — mit transparenter Produktinformation.',
    intro_en: 'The Rolex Oyster Perpetual is the purest expression of Rolex watchmaking. At Kariv Glamour, you can buy the Oyster Perpetual — with transparent product information.',
    collectionFilter: { collection: 'Oyster Perpetual' },
  },
  'rolex-herren': {
    title_de: 'Rolex für Herren kaufen | Herren Rolex Uhren | Kariv Glamour',
    title_en: 'Buy Rolex for Men | Men\u2019s Rolex Watches | Kariv Glamour',
    description_de: 'Rolex für Herren kaufen bei Kariv Glamour. Entdecken Sie Rolex Herrenuhren — von der Submariner bis zur Datejust — mit transparenter Produktinformation.',
    description_en: 'Buy Rolex for men at Kariv Glamour. Discover Rolex men\u2019s watches — from the Submariner to the Datejust — with transparent product information.',
    h1_de: 'Rolex für Herren',
    h1_en: 'Rolex for Men',
    intro_de: 'Entdecken Sie Rolex Uhren für Herren bei Kariv Glamour. Von professionellen Tool-Watches bis zu eleganten Klassikern — jede Uhr wird mit transparenter Produktinformation präsentiert.',
    intro_en: 'Discover Rolex watches for men at Kariv Glamour. From professional tool watches to elegant classics — each watch is presented with transparent product information.',
    collectionFilter: { gender: 'Men' },
  },
  'rolex-damen': {
    title_de: 'Rolex für Damen kaufen | Damen Rolex Uhren | Kariv Glamour',
    title_en: 'Buy Rolex for Women | Women\u2019s Rolex Watches | Kariv Glamour',
    description_de: 'Rolex für Damen kaufen bei Kariv Glamour. Entdecken Sie Rolex Damenuhren — von der Lady-Datejust bis zur Oyster Perpetual — mit transparenter Produktinformation.',
    description_en: 'Buy Rolex for women at Kariv Glamour. Discover Rolex women\u2019s watches — from the Lady-Datejust to the Oyster Perpetual — with transparent product information.',
    h1_de: 'Rolex für Damen',
    h1_en: 'Rolex for Women',
    intro_de: 'Entdecken Sie Rolex Uhren für Damen bei Kariv Glamour. Von der Lady-Datejust bis zur Oyster Perpetual — jede Uhr wird mit transparenter Produktinformation präsentiert.',
    intro_en: 'Discover Rolex watches for women at Kariv Glamour. From the Lady-Datejust to the Oyster Perpetual — each watch is presented with transparent product information.',
    collectionFilter: { gender: 'Women' },
  },
  'welche-rolex-kaufen': {
    title_de: 'Welche Rolex kaufen? | Rolex Kaufberatung | Kariv Glamour',
    title_en: 'Which Rolex to Buy? | Rolex Buying Guide | Kariv Glamour',
    description_de: 'Welche Rolex kaufen? Lesen Sie den Rolex Kaufberatung bei Kariv Glamour, um zu verstehen, welches Rolex Modell zu Ihrem Lebensstil, Geschmack und Sammlerzielen passt.',
    description_en: 'Which Rolex to buy? Read the Rolex buying guide at Kariv Glamour to understand which Rolex model suits your lifestyle, taste, and collecting goals.',
    h1_de: 'Welche Rolex kaufen?',
    h1_en: 'Which Rolex to Buy?',
    intro_de: 'Die Wahl der richtigen Rolex hängt von Ihrem Lebensstil, Geschmack und Budget ab. Die Datejust ist ein vielseitiger Klassiker, die Submariner eine ikonische Sportuhr. Dieser Guide hilft Ihnen, die richtige Entscheidung zu treffen.',
    intro_en: 'The right Rolex depends on your lifestyle, taste, and budget. The Datejust is a versatile classic, while the Submariner is an iconic sports watch. This guide helps you make the right decision.',
    collectionFilter: null,
    isGuide: true,
  },
  'rolex-neu-oder-gebraucht': {
    title_de: 'Rolex neu oder gebraucht kaufen? | Kariv Glamour',
    title_en: 'Rolex New or Pre-Owned? | Kariv Glamour',
    description_de: 'Rolex neu oder gebraucht kaufen? Vergleichen Sie die Vor- und Nachteile beider Optionen bei Kariv Glamour, um die richtige Entscheidung für Ihre Bedürfnisse zu treffen.',
    description_en: 'Rolex new or pre-owned? Compare the pros and cons of both options at Kariv Glamour to make the right decision for your needs.',
    h1_de: 'Rolex neu oder gebraucht kaufen?',
    h1_en: 'Rolex New or Pre-Owned?',
    intro_de: 'Sollten Sie eine Rolex neu oder gebraucht kaufen? Beide Optionen haben Vor- und Nachteile. Eine neue Rolex bietet volle Garantie und unbenutzten Zustand, während eine gebrauchte Rolex oft ein besseres Preis-Leistungs-Verhältnis und Zugang zu diskontinuierten Modellen bietet.',
    intro_en: 'Should you buy a Rolex new or pre-owned? Both options have pros and cons. A new Rolex offers full warranty and unused condition, while a pre-owned Rolex often provides better value and access to discontinued models.',
    collectionFilter: null,
    isGuide: true,
  },
  'rolex-box-papers-guide': {
    title_de: 'Rolex Box und Papiere Guide | Kariv Glamour',
    title_en: 'Rolex Box and Papers Guide | Kariv Glamour',
    description_de: 'Rolex Box und Papiere Guide bei Kariv Glamour. Erfahren Sie, warum Originalbox, Garantiekarte, Servicedokumente und Kaufhistorie beim Rolex Kauf wichtig sind.',
    description_en: 'Rolex Box and Papers Guide at Kariv Glamour. Learn why the original box, warranty card, service documents, and purchase history matter when buying a Rolex.',
    h1_de: 'Rolex Box und Papiere Guide',
    h1_en: 'Rolex Box and Papers Guide',
    intro_de: 'Box und Papiere bezieht sich auf die Original-Präsentationsbox und Garantiedokumente, die eine Rolex Uhr begleiten. Der Besitz der Originalbox und Papiere kann die Sammlerbegehrlichkeit und den Wiederverkaufswert steigern.',
    intro_en: 'Box and papers refers to the original presentation box and warranty documents that accompany a Rolex watch. Having the original box and papers can enhance collectability and resale value.',
    collectionFilter: null,
    isGuide: true,
  },
  'rolex-story': {
    title_de: 'Die Rolex Story | Erbe & Geschichte | Kariv Glamour',
    title_en: 'The Rolex Story | Heritage & History | Kariv Glamour',
    description_de: 'Entdecken Sie die Rolex Story bei Kariv Glamour. Erfahren Sie über das Erbe, Meilensteine und die bleibende Anziehungskraft hinter einem der bekanntesten Uhrmacher der Welt.',
    description_en: 'Discover the Rolex Story at Kariv Glamour. Learn about the heritage, milestones, and enduring appeal behind one of the world\u2019s most recognized watchmakers.',
    h1_de: 'Die Rolex Story',
    h1_en: 'The Rolex Story',
    intro_de: 'Rolex hat die Welt der feinen Uhrmacherei für über ein Jahrhundert geprägt. Von der ersten wasserdichten Oyster-Gehäuse bis zu den professionellen Tool-Watches, die Entdecker, Taucher und Piloten begleiteten — die Rolex Story ist eine von Präzision, Prestige und kultureller Anerkennung.',
    intro_en: 'Rolex has shaped the world of fine watchmaking for over a century. From the first waterproof Oyster case to the professional tool watches that accompanied explorers, divers, and aviators — the Rolex story is one of precision, prestige, and cultural recognition.',
    collectionFilter: null,
    isGuide: true,
  },
  'rolex-watchmaking': {
    title_de: 'Rolex Uhrmacherei | Handwerkskunst & Präzision | Kariv Glamour',
    title_en: 'Rolex Watchmaking | Craftsmanship & Precision | Kariv Glamour',
    description_de: 'Erfahren Sie über Rolex Uhrmacherei bei Kariv Glamour. Präzision, Materialien, Werke und Designprinzipien, die Rolex Uhren formen.',
    description_en: 'Learn about Rolex watchmaking at Kariv Glamour. Precision, materials, movements, and design principles that shape Rolex watches.',
    h1_de: 'Rolex Uhrmacherei',
    h1_en: 'Rolex Watchmaking',
    intro_de: 'Rolex Uhrmacherei steht für Präzision, robuste Gehäusekonstruktion und zuverlässige automatische Werke. Vom legendären Oyster-Gehäuse bis zu sorgfältig ausgewählten Materialien, Armbändern und Lünetten — jede Komponente ist für Langlebigkeit und Leistung konstruiert.',
    intro_en: 'Rolex watchmaking stands for precision, robust case construction, and reliable automatic movements. From the legendary Oyster case to carefully selected materials, bracelets, and bezels — every component is engineered for longevity and performance.',
    collectionFilter: null,
    isGuide: true,
  },
  'rolex-maintenance': {
    title_de: 'Rolex Wartung | Pflege & Service | Kariv Glamour',
    title_en: 'Rolex Maintenance | Care & Servicing | Kariv Glamour',
    description_de: 'Rolex Wartung und Pflege bei Kariv Glamour. Erfahren Sie, wie Sie eine Rolex Uhr pflegen und ihren Zustand, ihre Zuverlässigkeit und langfristigen Wert erhalten.',
    description_en: 'Rolex maintenance and care at Kariv Glamour. Learn how to care for a Rolex watch and preserve its condition, reliability, and long-term value.',
    h1_de: 'Rolex Wartung',
    h1_en: 'Rolex Maintenance',
    intro_de: 'Die richtige Pflege erhält die Schönheit, Zuverlässigkeit und den Wert einer Rolex Uhr. Regelmäßige Wartung, Wasserdichtigkeitsprüfungen, Armband- und Gehäusepflege, sorgfältige Aufbewahrung und das Vermeiden von Stößen, Magneten und unbefugten Modifikationen tragen zur langfristigen Leistung bei.',
    intro_en: 'Proper care preserves the beauty, reliability, and value of a Rolex watch. Regular servicing, water resistance checks, bracelet and case care, careful storage, and avoiding shocks, magnets, and unauthorized modifications all contribute to long-term performance.',
    collectionFilter: null,
    isGuide: true,
  },
};
