import { bilingual as b } from './sources.js';

// Original buyer-focused commentary. Historical claims are attached to primary sources.
export const BRAND_RESEARCH = {
  rolex: {
    sources: ['rolexHistory', 'rolexCare'],
    history: b('Rolex’s familiar families began as different answers to everyday and professional needs: the Datejust arrived in 1945, the Submariner in 1953 and the GMT-Master in 1955. Their continued names should not obscure how much cases, bracelets and movements have changed between generations.', 'Die bekannten Rolex-Familien entstanden für unterschiedliche Alltags- und Berufsanforderungen: die Datejust 1945, die Submariner 1953 und die GMT-Master 1955. Der fortgeführte Name darf nicht darüber hinwegtäuschen, wie stark sich Gehäuse, Bänder und Werke zwischen den Generationen verändert haben.'),
    choose: b('Start with the function you will actually use. Compare Datejust and Oyster Perpetual for everyday wear, Submariner for a diving-style timing bezel, GMT-Master II for travel and Daytona for elapsed-time measurement. A chronograph is not a second-time-zone display. A dress cuff, wrist size and preference for a date window often narrow the choice more effectively than popularity.', 'Beginnen Sie mit der Funktion, die Sie wirklich nutzen: Datejust und Oyster Perpetual für den Alltag, Submariner mit Tauchzeitlünette, GMT-Master II für Reisen und Daytona für Kurzzeitmessungen. Ein Chronograph zeigt nicht automatisch eine zweite Zeitzone. Hemdmanschette, Handgelenk und der Wunsch nach einem Datum helfen oft mehr als Popularität.'),
    inspect: b('On a pre-owned Rolex, examine case symmetry, bezel condition, bracelet articulation and the clasp rather than judging only the dial photograph. Ask which dial, hands or bracelet parts were replaced. A later genuine service component can be suitable for daily wear while being less attractive to a buyer seeking period originality.', 'Prüfen Sie bei einer gebrauchten Rolex Gehäusesymmetrie, Lünette, Bandbeweglichkeit und Schließe statt nur das Zifferblattfoto. Fragen Sie nach ersetzten Zifferblättern, Zeigern oder Bandteilen. Ein echtes späteres Serviceteil kann für den Alltag sinnvoll sein, aber für Sammler mit Originalitätsanspruch weniger interessant.'),
  },
  patekPhilippe: {
    sources: ['patekHistory', 'patekAquanaut', 'patekCollection'],
    history: b('The Nautilus entered Patek Philippe’s collection in 1976; the Aquanaut followed in 1997. These sports-oriented designs sit beside shaped dress watches and calendar complications, rather than defining the entire manufacture. Understanding that breadth helps avoid equating Patek Philippe exclusively with two highly visible names.', 'Die Nautilus kam 1976 in die Kollektion von Patek Philippe, die Aquanaut folgte 1997. Diese sportlichen Entwürfe stehen neben Formuhren und Kalenderkomplikationen; sie definieren nicht die gesamte Manufaktur. Diese Vielfalt hilft, Patek Philippe nicht auf zwei besonders bekannte Namen zu reduzieren.'),
    choose: b('A Calatrava belongs on a shortlist for restrained dress-watch proportions; Nautilus and Aquanaut appeal for their distinctive case and strap or bracelet combinations. For Complications and Grand Complications, choose the function first, then check how it is set and serviced. Do not assume every Patek is automatic: movement type is a reference-level fact.', 'Für zurückhaltende Dresswatch-Proportionen gehört die Calatrava auf die Liste; Nautilus und Aquanaut bieten markante Gehäuse- und Bandkombinationen. Bei Complications und Grand Complications sollte zuerst die Funktion feststehen, danach ihre Bedienung und Wartung. Nicht jede Patek ist automatisch: Die Werkart hängt von der Referenz ab.'),
    inspect: b('Check bracelet length, fitted strap length, original clasp and the exact paperwork before comparing prices. A cut strap or missing integrated-bracelet links can create a meaningful replacement expense. For calendar watches, request a functional demonstration by someone familiar with the calibre instead of experimenting with correctors yourself.', 'Prüfen Sie Bandlänge, zugeschnittene Armbänder, Originalschließe und Unterlagen vor dem Preisvergleich. Ein gekürztes Band oder fehlende Glieder können erhebliche Ersatzkosten verursachen. Lassen Sie Kalenderfunktionen von einer mit dem Kaliber vertrauten Person vorführen, statt selbst mit Korrektoren zu experimentieren.'),
  },
  omega: {
    sources: ['omegaCertification', 'omegaTechnology', 'metas'],
    history: b('Omega’s modern technical story includes the adoption of the Co-Axial escapement and, from 2015, Master Chronometer certification. These developments describe different things: one concerns movement architecture, the other a testing framework. Neither label should be assumed to apply to every older Omega.', 'Zur modernen Technikgeschichte von Omega gehören die Einführung der Co-Axial-Hemmung und seit 2015 die Master-Chronometer-Zertifizierung. Sie beschreiben unterschiedliche Dinge: Werkarchitektur einerseits, ein Prüfverfahren andererseits. Keines der Merkmale darf pauschal auf ältere Omega-Uhren übertragen werden.'),
    choose: b('Use the Speedmaster range when comparing chronographs, and distinguish the Moonwatch from other Speedmaster movements and sizes. Within Seamaster, a Diver 300M, Planet Ocean and Aqua Terra are not interchangeable buying choices. The Aqua Terra can suit a less overtly sporting wardrobe, while Constellation and De Ville broaden the dressier options.', 'Vergleichen Sie Chronographen innerhalb der Speedmaster-Reihe und unterscheiden Sie die Moonwatch von anderen Werken und Größen. Bei Seamaster sind Diver 300M, Planet Ocean und Aqua Terra keine austauschbaren Kaufoptionen. Die Aqua Terra passt auch zu weniger sportlicher Kleidung; Constellation und De Ville erweitern die eleganteren Möglichkeiten.'),
    inspect: b('Ask for the complete reference, not just “Seamaster” or “Moonwatch”. Check bezel operation, chronograph reset alignment where fitted, bracelet fit and recorded service work. Sapphire and acrylic crystals, different movements and bracelet generations can materially alter the ownership experience even when photographs look similar.', 'Fragen Sie nach der vollständigen Referenz statt nur nach „Seamaster“ oder „Moonwatch“. Prüfen Sie Lünette, gegebenenfalls Chronographen-Nullstellung, Bandsitz und dokumentierte Wartung. Saphir- und Acrylglas, verschiedene Werke und Bandgenerationen können das Trageerlebnis stark verändern, obwohl Fotos ähnlich wirken.'),
  },
  cartier: {
    sources: ['cartier'],
    history: b('Cartier traces the Santos design to 1904 and the Tank to 1917. Their importance lies in case shape and proportion, not simply in adding complications. A rectangular or square watch should therefore be compared by length, width and wrist coverage rather than by a round-watch diameter alone.', 'Cartier führt den Santos-Entwurf auf 1904 und die Tank auf 1917 zurück. Ihre Bedeutung liegt in Form und Proportion, nicht nur in zusätzlichen Komplikationen. Rechteckige oder quadratische Uhren sollten daher anhand von Länge, Breite und Auflage am Handgelenk verglichen werden, nicht allein wie eine runde Uhr nach Durchmesser.'),
    choose: b('Compare Tank for a rectangular silhouette, Santos for a more architectural square form, Panthère for its bracelet-led jewellery character and Ballon Bleu for a rounder case. Select the exact size and movement after choosing the shape. A small quartz Cartier can be an intentional design choice, not an inferior substitute for a larger mechanical watch.', 'Vergleichen Sie Tank für eine rechteckige Silhouette, Santos für eine markante quadratische Form, Panthère für ihren Schmuck- und Bandcharakter und Ballon Bleu für ein runderes Gehäuse. Größe und Werk wählen Sie danach. Eine kleine Quarz-Cartier kann eine bewusste Designentscheidung sein, keine minderwertige Alternative zu einer größeren mechanischen Uhr.'),
    inspect: b('Look closely at polished case edges, the crown, bracelet flexibility and clasp closure. On strap models, confirm whether the buckle is included and whether the fitted strap actually suits your wrist. On quartz references, ask about the last battery replacement and inspection rather than accepting “needs a battery” as a diagnosis.', 'Achten Sie auf polierte Gehäusekanten, Krone, Bandbeweglichkeit und Schließfunktion. Bei Lederbändern sollten Schließe und passende Länge bestätigt werden. Fragen Sie bei Quarzreferenzen nach Batteriewechsel und Prüfung; „braucht nur eine Batterie“ ist keine verlässliche Fehlerdiagnose.'),
  },
  hublot: {
    sources: ['hublot'],
    history: b('Hublot connects its fusion approach with its 1980 beginnings and the Big Bang launch in 2005. The useful distinction for shoppers is between a recognisable design language and the very different materials and movements sold within it. “Big Bang” alone is not a complete technical specification.', 'Hublot verbindet seinen Fusionsgedanken mit den Anfängen 1980 und der Einführung der Big Bang 2005. Für Käufer ist wichtig, die erkennbare Gestaltung von den sehr unterschiedlichen Materialien und Werken innerhalb der Reihe zu trennen. „Big Bang“ allein ist keine technische Spezifikation.'),
    choose: b('Classic Fusion offers a calmer starting point, while Big Bang places greater emphasis on layered construction and visible mechanical detail. Compare Unico, Spirit of Big Bang and Square Bang by shape, thickness and actual complication rather than treating them as colour variants. Try the full case-and-strap combination on a wrist similar to yours.', 'Classic Fusion ist ein ruhigerer Ausgangspunkt; Big Bang betont mehrschichtigen Aufbau und sichtbare Technik. Vergleichen Sie Unico, Spirit of Big Bang und Square Bang nach Form, Höhe und tatsächlicher Komplikation statt als bloße Farbvarianten. Entscheidend ist die gesamte Gehäuse-Band-Kombination am Handgelenk.'),
    inspect: b('Request close-ups of ceramic or composite edges, exposed screws, strap attachment points and the clasp. Scratches, chips and strap ageing are different condition issues and should be described separately. Confirm the availability and cost of the correct replacement strap before buying a watch with a heavily worn one.', 'Fordern Sie Nahaufnahmen von Keramik- oder Verbundmaterialkanten, sichtbaren Schrauben, Bandanschlüssen und Schließe an. Kratzer, Absplitterungen und Bandalterung sind unterschiedliche Zustandsmängel. Klären Sie die Verfügbarkeit und Kosten des passenden Ersatzbandes, bevor Sie ein stark getragenes Exemplar kaufen.'),
  },
  breitling: {
    sources: ['breitling', 'breitlingCollection'],
    history: b('Breitling developed the Navitimer in 1952 following a request from the Aircraft Owners and Pilots Association. Its circular slide rule explains the information-rich dial. The present family also includes watches without a chronograph, so a familiar bezel does not identify the movement or functions by itself.', 'Breitling entwickelte die Navitimer 1952 auf Anfrage der Aircraft Owners and Pilots Association. Der kreisförmige Rechenschieber erklärt das informationsreiche Zifferblatt. Heute enthält die Familie auch Uhren ohne Chronographen; die bekannte Lünette allein bestimmt daher weder Werk noch Funktionen.'),
    choose: b('Choose Navitimer if its aviation instrument layout appeals, Chronomat if the bracelet and sportier case are central to your preference, and Superocean when comparing dive-oriented references. Check legibility in an ordinary wrist photograph. A beautifully detailed dial enlarged on a screen can feel quite different at normal viewing distance.', 'Wählen Sie Navitimer für die Luftfahrt-Instrumentenoptik, Chronomat für Band und sportlicheres Gehäuse oder Superocean beim Vergleich tauchorientierter Referenzen. Prüfen Sie die Ablesbarkeit auf einem normalen Handgelenkfoto. Ein am Bildschirm vergrößertes Detailzifferblatt wirkt im üblichen Betrachtungsabstand oft anders.'),
    inspect: b('Confirm calibre, case size and service history; Breitling’s broad catalogue includes different movement types. On chronographs, ask for start, stop and reset demonstrations. Do not infer swimming suitability from a robust-looking case or an aviation reputation: use the exact reference’s instructions and a recent water-resistance assessment.', 'Bestätigen Sie Kaliber, Gehäusegröße und Wartungshistorie; Breitlings breites Programm umfasst verschiedene Werkarten. Lassen Sie bei Chronographen Start, Stopp und Rückstellung vorführen. Ein robustes Gehäuse oder Luftfahrtbezug beweist keine Schwimmtauglichkeit: Maßgeblich sind Referenzanleitung und aktuelle Dichtigkeitsprüfung.'),
  },
  audemarsPiguet: {
    sources: ['ap', 'apNumbers'],
    history: b('The Royal Oak debuted in 1972 with a design by Gérald Genta. The Royal Oak Offshore followed in 1993 with Emmanuel Gueit’s more substantial interpretation. Those are related but distinct design histories; a modern Offshore should not be described as simply an enlarged original Royal Oak.', 'Die Royal Oak erschien 1972 nach einem Entwurf von Gérald Genta. 1993 folgte die Royal Oak Offshore mit Emmanuel Gueits massiverer Interpretation. Die Designgeschichten sind verwandt, aber verschieden; eine moderne Offshore ist nicht einfach eine vergrößerte ursprüngliche Royal Oak.'),
    choose: b('Royal Oak rewards attention to bracelet taper and wrist fit; Offshore generally calls for a more deliberate thickness and comfort check. Code 11.59 offers another case architecture to consider if you prefer a strap-based watch. Compare time-only, calendar and chronograph references separately, since their ownership requirements differ.', 'Bei Royal Oak verdienen Bandverjüngung und Sitz besondere Aufmerksamkeit; bei Offshore sollten Höhe und Komfort genauer geprüft werden. Code 11.59 bietet eine andere Gehäusearchitektur für Liebhaber von Uhren am separaten Armband. Vergleichen Sie Zeit-, Kalender- und Chronographenreferenzen getrennt, da ihre Anforderungen verschieden sind.'),
    inspect: b('Case and bracelet finishing deserve close inspection: softened edges can change the appearance of an integrated-bracelet design. Request a full bracelet-length measurement and service documentation. Case, movement and series numbers serve different purposes; a number on the back is not automatically evidence of a limited edition.', 'Gehäuse- und Bandfinish sollten genau geprüft werden: Verrundete Kanten verändern die Wirkung eines integrierten Banddesigns. Verlangen Sie die vollständige Bandlänge und Servicebelege. Gehäuse-, Werk- und Seriennummern haben unterschiedliche Aufgaben; eine Nummer auf dem Boden belegt nicht automatisch eine limitierte Edition.'),
  },
  grandSeiko: {
    sources: ['gs', 'snowflake', 'shunbun'],
    history: b('Grand Seiko introduced its 9R Spring Drive movement in 2004. Its combination of mainspring power and electronic regulation makes it different from both a conventional mechanical escapement and a battery-powered quartz watch. That difference matters more to ownership than the broad label “automatic”.', 'Grand Seiko führte das 9R-Spring-Drive-Werk 2004 ein. Die Verbindung aus Federkraft und elektronischer Regelung unterscheidet es sowohl von einer klassischen mechanischen Hemmung als auch von einer batteriebetriebenen Quarzuhr. Für den Besitz ist dieser Unterschied aussagekräftiger als das allgemeine Wort „Automatik“.'),
    choose: b('Choose the movement experience before the dial nickname: consider winding habits, precision expectations and whether you enjoy a gliding seconds hand. Snowflake and Shunbun then offer distinct case shapes and dial treatments. Compare actual reference dimensions rather than assuming every light-coloured Grand Seiko wears the same.', 'Wählen Sie zuerst das Werkkonzept, dann den Zifferblatt-Spitznamen: Aufzugsgewohnheiten, Genauigkeitswünsche und ein gleitender Sekundenzeiger spielen dabei eine Rolle. Snowflake und Shunbun bieten danach unterschiedliche Gehäuse und Zifferblätter. Vergleichen Sie konkrete Referenzmaße statt alle hellen Grand-Seiko-Modelle gleichzusetzen.'),
    inspect: b('Ask for photographs in diffuse daylight as well as direct light; textured dials can change dramatically with lighting. Examine polished surfaces for dents and uneven refinishing, and confirm spare bracelet links. Keep a nickname, a reference number and a regional model code separate when matching documents to a listing.', 'Bitten Sie um Fotos bei diffusem Tageslicht und direkter Beleuchtung: Strukturzifferblätter können deutlich unterschiedlich wirken. Prüfen Sie polierte Flächen auf Dellen und ungleichmäßige Aufarbeitung sowie zusätzliche Bandglieder. Unterscheiden Sie Spitzname, Referenz und regionalen Modellcode beim Abgleich mit Unterlagen.'),
  },
  iwc: {
    sources: ['iwc', 'iwcGenta', 'iwcAutomatic'],
    history: b('IWC was founded in Schaffhausen in 1868 by Florentine Ariosto Jones. Pilot’s watches, Portugieser and Ingenieur developed different visual identities within the same manufacture. The Ingenieur began in 1955; Genta’s integrated-bracelet Ingenieur SL followed in 1976, not at the family’s beginning.', 'IWC wurde 1868 von Florentine Ariosto Jones in Schaffhausen gegründet. Fliegeruhren, Portugieser und Ingenieur entwickelten innerhalb derselben Manufaktur eigene Gestaltungen. Die Ingenieur entstand 1955; Gentas Ingenieur SL mit integriertem Band folgte 1976, nicht bereits zum Start der Familie.'),
    choose: b('Pilot’s Watches favour an instrument-like display, Portugieser offers a different dress-and-chronograph vocabulary, and Ingenieur places the bracelet-and-case relationship at the centre of many references. Consider case length and thickness alongside diameter. Two watches sharing a nominal size may fit very differently under a sleeve.', 'Pilot’s Watches bieten eine instrumentenartige Anzeige, Portugieser eine andere elegante Chronographensprache, und bei vielen Ingenieur-Referenzen steht das Zusammenspiel von Band und Gehäuse im Mittelpunkt. Beachten Sie Länge und Höhe zusätzlich zum Durchmesser. Gleiche Nennmaße bedeuten nicht denselben Sitz unter einer Manschette.'),
    inspect: b('Use the IW reference to establish the exact calibre and functions. Not every automatic IWC uses the same winding system. Ask about date operation, power-reserve behaviour where indicated and a documented service assessment; a movement running when photographed does not establish its full condition.', 'Ermitteln Sie über die IW-Referenz das genaue Kaliber und die Funktionen. Nicht jede automatische IWC verwendet dasselbe Aufzugssystem. Fragen Sie nach Datumsschaltung, gegebenenfalls Gangreserveanzeige und dokumentierter Prüfung. Ein beim Fotografieren laufendes Werk belegt nicht seinen vollständigen Zustand.'),
  },
  jaegerLeCoultre: {
    sources: ['jlc', 'jlcTesting'],
    history: b('The Reverso originated in 1931; the Duoface concept arrived in 1994, using two faces for different time displays. This is not the same as every reversible case containing two dials. Jaeger-LeCoultre’s round Master Control watches follow a separate design and testing story.', 'Die Reverso entstand 1931; 1994 folgte das Duoface-Konzept mit zwei Seiten für unterschiedliche Zeitanzeigen. Das bedeutet nicht, dass jedes Wendegehäuse zwei Zifferblätter besitzt. Die runden Master-Control-Uhren folgen einer eigenen Gestaltungs- und Prüfgeschichte.'),
    choose: b('For a Reverso, compare case length, thickness and the reversing mechanism, not just width. A simple single-face watch, Duoface travel watch and calendar model solve different needs. For Master models, decide which complication you will use before accepting the extra dial information and servicing complexity.', 'Vergleichen Sie bei Reverso Länge, Höhe und Wendemechanismus, nicht nur Breite. Eine einfache einseitige Uhr, eine Duoface-Reiseuhr und ein Kalendermodell erfüllen unterschiedliche Wünsche. Entscheiden Sie bei Master-Modellen zuerst über die benötigte Komplikation, bevor Sie zusätzliche Anzeigen und Wartungskomplexität wählen.'),
    inspect: b('Check the Reverso carrier and locking action, engraving or refinishing on the reverse, and the correct clasp. For complicated models, ask for each function to be demonstrated. Distinguish vintage examples from modern reissues and collection names; an old-looking dial is not proof of an early production date.', 'Prüfen Sie Reverso-Träger, Verriegelung, Gravuren oder Aufarbeitung der Rückseite und die passende Schließe. Lassen Sie bei komplizierten Modellen jede Funktion vorführen. Unterscheiden Sie historische Exemplare, moderne Neuauflagen und Kollektionsnamen; ein historisch wirkendes Zifferblatt beweist kein frühes Produktionsdatum.'),
  },
  tagHeuer: {
    sources: ['tag', 'tagConnected', 'tagOs'],
    history: b('The Carrera was introduced in 1963 and Formula 1 in 1986. These names span many generations rather than a single movement specification. Connected is a separate digital proposition: its software, battery and phone compatibility require a different buying checklist from a mechanical Carrera.', 'Die Carrera erschien 1963, die Formula 1 1986. Beide Namen umfassen viele Generationen statt einer einzigen Werkspezifikation. Connected ist ein eigenständiges digitales Konzept: Software, Akku und Telefonkompatibilität benötigen eine andere Kaufprüfung als eine mechanische Carrera.'),
    choose: b('Compare Carrera for chronograph-led designs, Monaco for a square case, Aquaracer for dive-oriented references and Formula 1 for varied sporting options. Do not choose a movement by family name alone. Quartz, mechanical and Connected watches answer different expectations about convenience, service and long-term use.', 'Vergleichen Sie Carrera für chronographengeprägte Designs, Monaco für quadratische Gehäuse, Aquaracer für tauchorientierte Referenzen und Formula 1 für unterschiedliche sportliche Optionen. Leiten Sie das Werk nicht allein vom Familiennamen ab. Quarz, Mechanik und Connected erfüllen andere Erwartungen an Komfort, Wartung und langfristige Nutzung.'),
    inspect: b('On a chronograph, inspect pusher operation and reset alignment; on a Connected, test charging, pairing and battery behaviour. Check the exact reference before ordering a replacement strap or clasp. A low purchase price can be outweighed by missing proprietary accessories or an unresolved fault.', 'Prüfen Sie bei Chronographen Drücker und Nullstellung, bei Connected Ladefunktion, Kopplung und Akkuverhalten. Klären Sie vor Ersatzband- oder Schließenbestellungen die exakte Referenz. Fehlendes Spezialzubehör oder ein ungelöster Defekt kann einen günstigen Kaufpreis schnell relativieren.'),
  },
  tudor: {
    sources: ['tudor', 'blackBay', 'pelagos'],
    history: b('The Tudor trademark was registered for Hans Wilsdorf in 1926; Montres Tudor S.A. was established in 1946. These are separate milestones, not contradictory founding dates. Modern Black Bay and Pelagos families should be judged on their own references rather than as substitutes with one universal specification.', 'Die Marke Tudor wurde 1926 für Hans Wilsdorf registriert; Montres Tudor S.A. entstand 1946. Das sind unterschiedliche Meilensteine, keine widersprüchlichen Gründungsdaten. Moderne Black-Bay- und Pelagos-Familien sollten nach ihrer jeweiligen Referenz beurteilt werden, nicht als Ersatzprodukte mit einer einheitlichen Spezifikation.'),
    choose: b('Black Bay offers heritage-led designs across several functions; Pelagos provides a more explicitly technical diving focus, with significant differences between versions. Royal, 1926 and Ranger widen the choice beyond a rotating dive bezel. Decide whether you want a bracelet, fabric strap or rubber before comparing case dimensions.', 'Black Bay bietet historisch geprägte Designs mit mehreren Funktionen; Pelagos ist stärker auf technisches Tauchen ausgerichtet, mit deutlichen Unterschieden zwischen Versionen. Royal, 1926 und Ranger erweitern die Auswahl jenseits einer drehbaren Tauchlünette. Entscheiden Sie über Metall-, Textil- oder Kautschukband vor dem Größenvergleich.'),
    inspect: b('Identify the reference and movement generation, then check bezel action, clasp adjustment and included straps. Fixed-bar FXD models need suitable pass-through straps rather than an assumption of standard bracelet compatibility. Certification, size and depth rating must all be confirmed for the actual watch.', 'Identifizieren Sie Referenz und Werkgeneration, dann prüfen Sie Lünette, Schließenverstellung und mitgelieferte Bänder. FXD-Modelle mit festen Stegen benötigen passende Durchzugsbänder; eine normale Metallband-Kompatibilität darf nicht vorausgesetzt werden. Zertifizierung, Größe und Druckfestigkeit sind am konkreten Modell zu prüfen.'),
  },
  panerai: {
    sources: ['panerai'],
    history: b('Panerai’s history links naval instruments with the Radiomir and Luminor designs; the crown-protection bridge was patented in 1956. Civilian collections arrived in 1993. Historical design cues remain visible, but today’s case sizes, movements and water-resistance specifications cannot be inferred from a military origin.', 'Panerais Geschichte verbindet Marineinstrumente mit Radiomir- und Luminor-Entwürfen; der Kronenschutzbügel wurde 1956 patentiert. Zivile Kollektionen kamen 1993 hinzu. Historische Gestaltungsmerkmale bleiben sichtbar, doch heutige Größen, Werke und Wasserdichtigkeitswerte folgen nicht automatisch aus dem militärischen Ursprung.'),
    choose: b('Luminor’s crown bridge, Radiomir’s different crown-and-case outline and Submersible’s rotating timing bezel give useful starting points. Luminor Due is not simply another diving specification. Try the lug span and strap curvature: a nominal diameter does not capture how a cushion-shaped watch sits on a wrist.', 'Luminors Kronenschutzbügel, Radiomirs andere Kronen- und Gehäusekontur sowie Submersibles drehbare Zeitlünette sind gute Ausgangspunkte. Luminor Due ist nicht einfach eine weitere Tauchspezifikation. Prüfen Sie Hörnerabstand und Bandkrümmung: Der Durchmesser erklärt den Sitz eines kissenförmigen Gehäuses nicht vollständig.'),
    inspect: b('Use the PAM reference to verify size, movement and functions. Inspect strap-change screw heads, crown protection where fitted, and the included buckle. “8 Days”, “Destro” and “Marina” describe different features; none of these names alone supplies the complete reference or confirms its condition.', 'Verifizieren Sie Größe, Werk und Funktionen anhand der PAM-Referenz. Prüfen Sie Bandwechselschrauben, gegebenenfalls Kronenschutz und mitgelieferte Schließe. „8 Days“, „Destro“ und „Marina“ bezeichnen unterschiedliche Merkmale; keiner dieser Namen liefert allein die vollständige Referenz oder bestätigt den Zustand.'),
  },
  bvlgari: {
    sources: ['bvlgari', 'octo', 'octoSteel'],
    history: b('Bvlgari’s Serpenti watch story includes Tubogas designs dating to 1948. The Octo family takes a very different geometric direction. These two identities show why a jewellery watch and an ultra-thin mechanical watch should not be evaluated with the same priorities.', 'Bvlgaris Serpenti-Uhrengeschichte umfasst Tubogas-Entwürfe seit 1948. Die Octo-Familie verfolgt eine deutlich andere geometrische Richtung. Beide Identitäten zeigen, warum eine Schmuckuhr und eine ultraflache mechanische Uhr nicht nach denselben Prioritäten bewertet werden sollten.'),
    choose: b('For Serpenti, begin with the bracelet construction, number of wraps and wrist fit; for Octo Finissimo, begin with the specific calibre, metal and thickness. Octo Roma and Lvcea offer other shapes to compare. Do not assume all Serpenti watches are quartz or all Octo Finissimo references share identical dimensions.', 'Beginnen Sie bei Serpenti mit Bandaufbau, Windungen und Handgelenkpassform; bei Octo Finissimo mit Kaliber, Metall und Höhe. Octo Roma und Lvcea bieten weitere Formen. Nicht jede Serpenti ist eine Quarzuhr, und nicht jede Octo-Finissimo-Referenz hat identische Maße.'),
    inspect: b('On a jewellery-led watch, examine bracelet tension, clasp security and any stone-setting work. On an ultra-thin watch, ask about impact history and servicing rather than assuming a slim case is maintenance-free. Material, dial and bracelet must match the reference when comparing seemingly similar offers.', 'Prüfen Sie bei schmuckorientierten Uhren Bandspannung, Schließsicherheit und gegebenenfalls Steinfassungen. Fragen Sie bei ultraflachen Uhren nach Stößen und Wartung statt ein schlankes Gehäuse mit Wartungsfreiheit gleichzusetzen. Material, Zifferblatt und Band müssen beim Angebotsvergleich zur Referenz passen.'),
  },
  girardPerregaux: {
    sources: ['gp', 'laureato'],
    history: b('Girard-Perregaux traces its manufacture heritage to 1791 and associates its Three Bridges architecture with nineteenth-century watchmaking. Laureato arrived in 1975. A modern Bridges watch and a Laureato therefore express different parts of the brand’s history rather than one being a variation of the other.', 'Girard-Perregaux führt seine Manufakturgeschichte auf 1791 zurück und verbindet die Drei-Brücken-Architektur mit der Uhrmacherei des 19. Jahrhunderts. Die Laureato kam 1975 hinzu. Moderne Bridges-Uhren und Laureato verkörpern damit verschiedene Teile der Markengeschichte, keine bloßen Varianten voneinander.'),
    choose: b('Laureato is the natural place to compare integrated-bracelet designs; 1966 offers rounder dress-watch choices, while Vintage 1945 uses a shaped case. Bridges focuses attention on movement architecture. “Vintage 1945” is a collection name, not evidence that a particular watch was manufactured in 1945.', 'Laureato ist der Ausgangspunkt für integrierte Metallband-Designs; 1966 bietet runde elegante Optionen, Vintage 1945 ein Formgehäuse. Bridges rückt Werkarchitektur in den Mittelpunkt. „Vintage 1945“ ist ein Kollektionsname, kein Beleg dafür, dass eine konkrete Uhr 1945 hergestellt wurde.'),
    inspect: b('Confirm the complete reference, bracelet length and movement condition before focusing on rarity. For unusual complications, obtain a specialist service assessment and clarify parts availability in writing. A scarce model can be fascinating to own while also taking longer to service or resell.', 'Bestätigen Sie vollständige Referenz, Bandlänge und Werkzustand, bevor Seltenheit im Vordergrund steht. Für ungewöhnliche Komplikationen sollten Sie eine fachkundige Serviceeinschätzung und schriftliche Angaben zur Teileverfügbarkeit einholen. Ein seltenes Modell kann faszinierend sein und zugleich längere Wartungs- oder Verkaufszeiten mitbringen.'),
  },
};
