import { bilingual as b } from './sources.js';

// History and selection are different editorial jobs. Keep these passages
// brand-specific instead of swapping names into a universal buying template.
export const BRAND_ESSAYS = {
  rolex: {
    heading: b('From a wristwatch idea to recognisable families', 'Von der Armbanduhr-Idee zu erkennbaren Modellfamilien'),
    sources: ['rolexEarly', 'rolexOyster'],
    story: [
      b('Rolex’s early story begins with Hans Wilsdorf’s watch-distribution business in London in 1905, before the move to Geneva in 1919. The Oyster case of 1926 and Perpetual winding mechanism of 1931 addressed different obstacles to regular wristwatch use: protecting the movement and replenishing its energy. This sequence helps explain why the same words appear together on later dials. They refer to strands of technical development, not simply an ornamental model name.', 'Rolex’ frühe Geschichte beginnt mit Hans Wilsdorfs Uhrenvertrieb 1905 in London, vor dem Umzug nach Genf 1919. Oyster-Gehäuse von 1926 und Perpetual-Aufzug von 1931 begegneten unterschiedlichen Herausforderungen der Armbanduhr: Schutz des Werks und Energiezufuhr beim Tragen. Das erklärt, warum beide Wörter später gemeinsam auf Zifferblättern stehen. Sie beschreiben technische Entwicklungslinien, nicht bloß einen dekorativen Modellnamen.'),
      b('The later families added identifiable functions and visual cues to that foundation. The Datejust made the date part of a versatile everyday design; the Submariner and GMT-Master supplied very different bezel-based interfaces. This is a useful way to read the catalogue today: look at what the display was designed to tell its wearer. Then distinguish that historical purpose from the specifications and condition of the particular reference. A name can remain familiar while the proportions, materials and user experience change substantially.', 'Spätere Familien ergänzten erkennbare Funktionen und Gestaltungsmerkmale. Die Datejust integrierte das Datum in ein vielseitiges Alltagsdesign; Submariner und GMT-Master brachten unterschiedliche lünettenbezogene Anzeigen. So lässt sich auch der heutige Katalog lesen: Welche Information sollte die Uhr vermitteln? Trennen Sie diesen historischen Zweck anschließend von Spezifikation und Zustand der konkreten Referenz. Ein vertrauter Name kann bleiben, während Proportionen, Materialien und Bediengefühl deutlich wechseln.'),
    ],
    choice: b('For a first everyday Rolex, put an Oyster Perpetual beside a Datejust and decide whether you genuinely want a date display. Next compare the bezel and bracelet combinations you prefer rather than simply choosing the largest case. If travel-time reading is important, compare a GMT-Master II on that function; if timing intervals is the attraction, compare the Daytona’s chronograph with the simpler interaction of a timing bezel. This produces a shortlist based on how you will wear the watch rather than a ranking of famous names.', 'Stellen Sie für die erste Alltags-Rolex Oyster Perpetual und Datejust gegenüber und entscheiden Sie, ob Sie ein Datum möchten. Vergleichen Sie danach bevorzugte Lünetten- und Bandkombinationen statt bloß die größte Uhr zu wählen. Für Reisezeit ist GMT-Master II nach dieser Funktion zu beurteilen; für Zeitintervalle vergleichen Sie Daytonas Chronograph mit der einfacheren Zeitlünette. Daraus entsteht eine nutzungsbezogene Auswahl statt einer Rangliste berühmter Namen.'),
  },
  patekPhilippe: {
    heading: b('Two sports-watch designs within a wider tradition', 'Zwei sportliche Entwürfe in einer breiteren Tradition'),
    sources: ['patekHistory', 'patekAquanaut', 'patekCollection'],
    story: [
      b('The 1976 Nautilus is a useful turning point because it places a recognisable sports-oriented case and bracelet within a house also associated with dress watches and complications. The Aquanaut’s 1997 introduction took another direction: its rounded octagonal case and pattern linking dial to strap created a more strap-led visual identity. They share a place in the same collection without being interchangeable designs, and their popularity should not erase the distinct appeal of Calatrava, Golden Ellipse or shaped watches.', 'Die Nautilus von 1976 ist ein wichtiger Orientierungspunkt: ein erkennbar sportorientiertes Gehäuse-Band-Konzept innerhalb eines Hauses, das ebenso für elegante Uhren und Komplikationen steht. Die Aquanaut von 1997 entwickelte mit abgerundet achteckigem Gehäuse und durchgehendem Muster von Zifferblatt zu Band eine andere Identität. Beide sind keine austauschbaren Entwürfe; ihre Bekanntheit sollte Calatrava, Golden Ellipse und Formuhren nicht aus dem Blick drängen.'),
      b('Patek Philippe’s catalogue also shows how a familiar outline can accommodate very different mechanisms. A simple display, travel-time indication, calendar or chronograph changes not only the dial but the owner’s interaction with the watch. Reading that evolution through references is more useful than treating all sports models as one category and all dress models as another. The historical family provides context; the actual calibre, setting method and dimensions establish what the watch is like to own.', 'Patek Philippes Katalog zeigt außerdem, wie unterschiedliche Mechanismen in einer vertrauten Kontur Platz finden. Reine Zeitanzeige, Reisezeit, Kalender oder Chronograph verändern nicht nur das Zifferblatt, sondern den Umgang mit der Uhr. Diese Entwicklung anhand von Referenzen zu verfolgen ist sinnvoller als die pauschale Trennung in Sport- und Dresswatches. Die Familie liefert Kontext; Kaliber, Einstellverfahren und Maße bestimmen den Besitzalltag.'),
    ],
    choice: b('Start with whether you want the watch to be understated, bracelet-led, strap-led or mechanically elaborate. A Calatrava can answer the first preference without needing to compete with a Nautilus on popularity. For Aquanaut, check the fitted strap before comparing dial colours: a cut strap may not suit your wrist. With a calendar complication, ask yourself whether setting it after periods off the wrist will be enjoyable. Buy the configuration whose proportions and routine you appreciate, then assess the individual example’s documentation and condition.', 'Beginnen Sie mit der Frage: zurückhaltend, bandintegriert, am separaten Armband oder mechanisch aufwendig? Eine Calatrava erfüllt die erste Vorliebe ohne Popularitätsvergleich zur Nautilus. Prüfen Sie bei Aquanaut vor Zifferblattfarben das montierte Band: Ein zugeschnittenes Exemplar passt möglicherweise nicht. Bei Kalendern zählt, ob das Einstellen nach Tragepausen Freude macht. Wählen Sie gewünschte Proportionen und Bedienung, danach Zustand und Dokumentation.'),
  },
  omega: {
    heading: b('Design families and technical labels tell different stories', 'Modellfamilien und Technikbegriffe erzählen verschiedene Geschichten'),
    sources: ['omegaTechnology', 'omegaCertification', 'metas'],
    story: [
      b('Omega’s catalogue is easier to understand when the family name and the technical inscription are read separately. Speedmaster identifies a broad chronograph-led tradition; Seamaster contains several very different water-associated and everyday designs. Co-Axial describes a feature of movement architecture, while Master Chronometer concerns testing. The same technical language can therefore appear in watches with very different appearances and purposes. Conversely, two watches with the same family name can belong to different technical generations.', 'Omegas Katalog wird verständlicher, wenn Familienname und technische Aufschrift getrennt gelesen werden. Speedmaster steht für eine breite chronographengeprägte Tradition; Seamaster umfasst unterschiedliche wasserbezogene und alltägliche Entwürfe. Co-Axial bezeichnet Werkarchitektur, Master Chronometer eine Prüfung. Dieselben Technikbegriffe können daher bei optisch und funktional verschiedenen Uhren stehen. Umgekehrt gehören gleichnamige Familienmitglieder möglicherweise unterschiedlichen Technikgenerationen an.'),
      b('The introduction of Master Chronometer certification in 2015 is one concrete marker in that modern development. It provides a way to discuss complete-watch testing without assuming that older examples were assessed under the same framework. For buyers, the historical question becomes practical: which generation supplies the combination of case, bracelet, crystal and movement you want? The most recently introduced technology is one consideration, but it does not automatically outweigh the proportions or character of an earlier reference.', 'Die Einführung der Master-Chronometer-Zertifizierung 2015 ist ein konkreter Marker dieser Entwicklung. Sie erlaubt Aussagen über Prüfungen vollständiger Uhren, ohne ältere Exemplare demselben Rahmen zuzuordnen. Für Käufer wird Geschichte damit praktisch: Welche Generation verbindet gewünschtes Gehäuse, Band, Glas und Werk? Neueste Technik ist ein Gesichtspunkt, überwiegt aber nicht automatisch Proportionen oder Charakter einer früheren Referenz.'),
    ],
    choice: b('If you want a chronograph, choose the Speedmaster reference first and then compare its crystal, winding routine and bracelet. If you want a watch for varied everyday use, compare Aqua Terra with the more visibly dive-oriented Diver 300M or Planet Ocean instead of treating all three as the same Seamaster. For a dressier preference, add Constellation or De Ville to the shortlist. The point is to choose the display and wearing character before allowing a well-known family name to settle the decision.', 'Für einen Chronographen wählen Sie zuerst die Speedmaster-Referenz und vergleichen dann Glas, Aufzugsroutine und Band. Für vielseitigen Alltag vergleichen Sie Aqua Terra mit den sichtbar tauchorientierten Diver 300M oder Planet Ocean, statt alle als gleiche Seamaster zu behandeln. Für elegantere Vorlieben ergänzen Sie Constellation oder De Ville. Anzeige und Tragecharakter sollten vor dem bekannten Familiennamen entscheiden.'),
  },
  cartier: {
    heading: b('A history read through shape and proportion', 'Eine Geschichte von Form und Proportion'),
    sources: ['cartier'],
    story: [
      b('The Santos and Tank establish two different ways of making a watch recognisable without relying on a round case. Santos places emphasis on a square architectural outline; Tank uses the relationship between a rectangular dial and its elongated sides. Looking at these forms explains why the usual comparison by diameter can be unhelpful. Width, length, thickness and how the strap or bracelet leaves the case all contribute to the impression. A smaller watch can retain a strong identity without adding dial detail.', 'Santos und Tank zeigen zwei Wege zu einer erkennbaren Uhr ohne rundes Gehäuse. Santos betont die quadratische Architektur, Tank das Verhältnis von rechteckigem Zifferblatt zu länglichen Seiten. Daran wird deutlich, warum Durchmesservergleiche wenig helfen: Breite, Länge, Höhe und Bandanschluss bestimmen die Wirkung. Auch eine kleinere Uhr kann eine starke Identität besitzen, ohne weitere Zifferblattdetails zu benötigen.'),
      b('This emphasis on design makes the relationship between watch and jewellery important rather than secondary. A bracelet-led Panthère asks a different wearing question from a Tank on a leather strap, while a Ballon Bleu introduces another case outline. The useful historical lesson is continuity of proportion, not a requirement to choose a mechanical movement or a large size. Assess the exact version for what it is meant to look and feel like; then ask whether its condition preserves that effect.', 'Diese Gestaltungsorientierung macht die Beziehung von Uhr und Schmuck wesentlich. Eine bandgeprägte Panthère stellt eine andere Tragefrage als eine Tank am Lederband; Ballon Bleu ergänzt eine weitere Kontur. Die historische Lehre liegt in Proportionen, nicht in der Pflicht zu Mechanik oder großen Maßen. Beurteilen Sie die konkrete Version nach ihrer beabsichtigten Wirkung und anschließend danach, ob ihr Zustand diese bewahrt.'),
    ],
    choice: b('Compare Cartier shapes on the wrist before comparing movements. A Tank that looks small beside a round watch in a photograph may be exactly right in its proportions. On a bracelet model, assess drape and clasp placement; on a strap model, check the buckle and the length of both strap sections. Choose quartz or mechanical according to your desired routine. Neither a larger case nor additional mechanical complexity automatically improves a design whose appeal lies in restraint.', 'Vergleichen Sie Cartier-Formen am Handgelenk vor den Werken. Eine Tank, die neben einer runden Uhr klein wirkt, kann gerade so richtig proportioniert sein. Bei Metallband zählen Fall und Schließenlage, bei separatem Band Schließe und Abschnittslängen. Wählen Sie Quarz oder Mechanik nach gewünschter Routine. Größeres Gehäuse und zusätzliche Komplexität verbessern nicht automatisch einen zurückhaltenden Entwurf.'),
  },
  hublot: {
    heading: b('Material contrast as the central idea', 'Materialkontrast als zentrale Idee'),
    sources: ['hublot'],
    story: [
      b('Hublot’s pairing of gold and rubber in 1980 explains the brand’s emphasis on contrast: precious metal did not have to be paired only with a traditional leather strap or matching bracelet. Big Bang, introduced in 2005, developed a more layered and visibly constructed expression of that approach. The important historical connection is the treatment of materials and their meeting points, not the assumption that every Hublot contains the same movement or serves the same type of wearer.', 'Hublots Verbindung von Gold und Kautschuk 1980 erklärt den betonten Kontrast: Edelmetall musste nicht ausschließlich mit traditionellem Leder- oder Metallband kombiniert werden. Big Bang entwickelte diesen Ansatz ab 2005 in stärker geschichtetem, sichtbar konstruiertem Design weiter. Die historische Verbindung liegt in Materialien und Übergängen, nicht in der Annahme identischer Werke oder Nutzer bei allen Hublot-Uhren.'),
      b('That distinction is useful when looking at a pre-owned Big Bang beside a later Unico version. A shared design language can conceal changes to case construction, controls and movement. Likewise, a darker case is not simply another colour of a metal example: establish whether it is ceramic, coated metal or another material. The story becomes informative when it helps you ask what the actual watch is made of, how it wears and how damage or ageing would be assessed.', 'Das hilft beim Vergleich einer gebrauchten Big Bang mit einer späteren Unico-Version. Gemeinsame Gestaltung kann Änderungen an Konstruktion, Bedienung und Werk verdecken. Ein dunkles Gehäuse ist zudem nicht bloß eine andere Metallfarbe: Klären Sie Keramik, beschichtetes Metall oder anderes Material. Geschichte wird nützlich, wenn sie Fragen nach Aufbau, Tragegefühl sowie Bewertung von Schäden und Alterung schärft.'),
    ],
    choice: b('Try Classic Fusion and Big Bang as different design propositions rather than adjacent steps in a hierarchy. If you enjoy an open, layered dial, check whether the actual hands remain clear against it. If you prefer a quieter display, do not assume that a more complicated-looking option is the better purchase. Establish material and strap specification early, because they affect weight, feel and replacement choices. On any reference, the worn condition of edges and attachment points deserves more attention than a promotional colour name.', 'Probieren Sie Classic Fusion und Big Bang als verschiedene Designideen statt als Rangstufen. Bei offenem, geschichtetem Zifferblatt sollten die Zeiger trotzdem klar bleiben. Eine ruhigere Anzeige kann die bessere persönliche Wahl sein. Klären Sie Material und Band früh, denn davon hängen Gewicht, Gefühl und Ersatzmöglichkeiten ab. Kanten und Befestigungen verdienen mehr Aufmerksamkeit als ein werblicher Farbname.'),
  },
  breitling: {
    heading: b('From calculation instrument to a wider family', 'Vom Recheninstrument zur breiteren Familie'),
    sources: ['breitling', 'breitlingCollection'],
    story: [
      b('The Navitimer’s circular slide rule explains a great deal about its visual identity. The scales were there to support calculations, not merely to make the dial look technical. That purpose helps a viewer understand why the outer display is unusually dense. Today, the familiar outline can appeal even to someone who will never use a slide rule. It remains worth learning which parts are scales, which are normal time indications and which belong to a chronograph on the reference being considered.', 'Navitimers kreisförmiger Rechenschieber erklärt viel von ihrer Identität. Die Skalen dienten Berechnungen und nicht bloß technischer Optik. Daraus entsteht die hohe Informationsdichte am Rand. Heute kann dieser Entwurf auch ohne Rechenschiebernutzung gefallen. Trotzdem lohnt die Unterscheidung zwischen Skalen, normalen Zeitanzeigen und gegebenenfalls Chronographenanzeigen der konkreten Referenz.'),
      b('The modern Navitimer family extends beyond a single chronograph specification. That evolution is a reminder to separate a successful design name from the contents of the case. Chronomat and Superocean add other visual and functional directions, so Breitling cannot be reduced to an aviation dial alone. When comparing eras, use the reference to identify size, calibre and controls. Historical associations add context but do not establish a used watch’s performance, originality or suitability for water.', 'Die moderne Navitimer-Familie reicht über eine einzelne Chronographenspezifikation hinaus. Das zeigt, warum ein erfolgreicher Designname vom Gehäuseinhalt zu trennen ist. Chronomat und Superocean ergänzen andere Richtungen; Breitling ist nicht auf Luftfahrtzifferblätter begrenzt. Beim Epochenvergleich identifiziert die Referenz Größe, Kaliber und Bedienung. Historische Bezüge bestätigen weder Leistung noch Originalität oder heutige Wassereignung.'),
    ],
    choice: b('If the Navitimer is your starting point, view it at normal wrist distance before choosing a busy dial configuration. If bracelet feel and a sportier silhouette matter more, compare Chronomat. If your priority is a dive-oriented display, start with a specific Superocean rather than assuming that every robust Breitling is equally suited to water. Across the shortlist, record movement type and thickness. A simpler display that you read comfortably every day can be a more satisfying choice than an impressive instrument you rarely use.', 'Betrachten Sie eine Navitimer vor der Wahl eines detailreichen Zifferblatts aus normalem Abstand. Für Bandgefühl und sportlichere Silhouette vergleichen Sie Chronomat; für tauchorientierte Anzeige eine konkrete Superocean. Nicht jede robuste Breitling ist gleichermaßen wassergeeignet. Notieren Sie in der Auswahl Werkart und Höhe. Eine täglich bequem lesbare Anzeige kann mehr Freude machen als ein eindrucksvolles, selten genutztes Instrument.'),
  },
  audemarsPiguet: {
    heading: b('Royal Oak and Offshore are related, not identical', 'Royal Oak und Offshore sind verwandt, nicht identisch'),
    sources: ['ap', 'apNumbers'],
    story: [
      b('The Royal Oak’s 1972 introduction and the Offshore’s 1993 arrival describe two distinct design decisions. Genta’s Royal Oak made the relationship between shaped bezel, case and bracelet central to the watch. Gueit’s Offshore explored a more substantial interpretation rather than simply preserving the earlier dimensions. Seeing them side by side makes the difference tangible: the question is not only which name is more famous, but which proportions and physical presence you prefer.', 'Royal Oak 1972 und Offshore 1993 stehen für unterschiedliche Designentscheidungen. Gentas Royal Oak rückte das Verhältnis geformter Lünette, Gehäuse und Band in den Mittelpunkt. Gueits Offshore entwickelte eine massivere Interpretation statt nur frühere Maße fortzusetzen. Nebeneinander wird der Unterschied greifbar: Entscheidend sind bevorzugte Proportionen und Präsenz, nicht nur der bekannteste Name.'),
      b('This history also changes how condition should be read. The meeting of brushed and polished surfaces is part of an architectural composition; excessive refinishing can change that composition even if the watch looks shiny and clean. Numbers on the watch need equal care. AP distinguishes case, movement and series numbering, so a number alone is not a production-limit certificate. Use documented reference information to support a historical claim instead of allowing a compelling design story to stand in for provenance.', 'Diese Geschichte beeinflusst die Zustandsbewertung. Gebürstete und polierte Flächen bilden eine Architektur; starke Aufarbeitung kann sie trotz sauberer, glänzender Optik verändern. Auch Nummern verlangen Sorgfalt. AP unterscheidet Gehäuse-, Werk- und Seriennummerierung; eine Zahl allein bestätigt keine Limitierung. Historische Aussagen sollten durch Referenzinformationen belegt sein, statt Designgeschichte mit Herkunftsnachweis gleichzusetzen.'),
    ],
    choice: b('Compare Royal Oak and Offshore by the entire watch, including first bracelet links or strap attachment, thickness and clasp. A favourite dial can become a poor choice if the case does not settle on your wrist. Add Code 11.59 if you prefer a different case architecture on a separate strap. Then choose the function: time display, calendar or chronograph. These are not merely dial variants; they alter the controls, servicing questions and day-to-day experience that should be reflected in your purchase decision.', 'Vergleichen Sie Royal Oak und Offshore vollständig: erste Glieder oder Bandanschluss, Höhe und Schließe. Ein Lieblingszifferblatt hilft wenig, wenn das Gehäuse nicht sitzt. Ergänzen Sie Code 11.59 für andere Architektur am separaten Band. Wählen Sie danach Zeit, Kalender oder Chronograph. Das sind nicht bloß Zifferblattvarianten, sondern unterschiedliche Bedienungs- und Wartungsfragen.'),
  },
  grandSeiko: {
    heading: b('Movement character and dial character', 'Werkcharakter und Zifferblattcharakter'),
    sources: ['gs', 'snowflake', 'shunbun'],
    story: [
      b('Spring Drive’s introduction to Grand Seiko in 2004 provides a clear technical chapter in the brand’s story. The combination of mainspring power and electronic regulation is deliberately different from both an ordinary quartz drive and a conventional mechanical escapement. That difference can be seen directly in the seconds hand. It is a useful example of why a watch’s movement should be described by how it works, not forced into a simplified ranking where one broad category is always superior.', 'Spring Drives Einführung bei Grand Seiko 2004 bildet ein klares technisches Kapitel. Federkraft und elektronische Regelung unterscheiden sich bewusst von gewöhnlichem Quarzantrieb und konventioneller mechanischer Hemmung. Sichtbar wird das am Sekundenzeiger. Das zeigt, warum Werke nach ihrer Arbeitsweise statt nach vereinfachten Ranglisten beschrieben werden sollten, in denen eine Kategorie immer überlegen gilt.'),
      b('The Snowflake SBGA211 and Shunbun SBGA413 demonstrate another strand: dial texture and case shape can give two watches with the same 9R65 calibre a different character. Their nicknames are helpful shorthand, but they are not reference numbers. The Snowflake’s white surface and Shunbun’s pink-toned treatment should be viewed under ordinary lighting, not only dramatic close-up photography. Understanding the distinction between mechanism, case and dial lets a buyer appreciate each part without expecting one popular nickname to describe them all.', 'Snowflake SBGA211 und Shunbun SBGA413 zeigen eine weitere Seite: Struktur und Gehäuse geben demselben 9R65-Kaliber unterschiedlichen Charakter. Die Spitznamen helfen, ersetzen aber keine Referenznummer. Weiße Snowflake und rosafarbene Shunbun sollten bei normaler Beleuchtung statt nur in dramatischen Nahaufnahmen betrachtet werden. Die Trennung von Mechanik, Gehäuse und Zifferblatt verhindert, dass ein populärer Name alle Eigenschaften vertreten muss.'),
    ],
    choice: b('Decide first whether the movement experience or a particular dial is leading your interest. If Spring Drive is central, compare the actual calibre and reserve rather than assuming every gliding-seconds watch shares the Snowflake’s specification. If the dial is central, view it in diffuse light and check that the hands remain easy to read. Between SBGA211 and SBGA413, wrist fit may decide more than the one-millimetre diameter difference. Confirm the full reference and bracelet completeness before comparing offers by nickname.', 'Klären Sie zuerst, ob Werkserlebnis oder Zifferblatt Ihr Interesse bestimmt. Für Spring Drive vergleichen Sie Kaliber und Reserve statt allgemeiner Snowflake-Annahmen. Beim Zifferblatt zählen diffuses Licht und lesbare Zeiger. Zwischen SBGA211 und SBGA413 kann die Passform wichtiger sein als ein Millimeter Durchmesser. Bestätigen Sie Referenz und Bandvollständigkeit vor dem Spitznamenvergleich.'),
  },
  iwc: {
    heading: b('Schaffhausen, industrial ambition and distinct design families', 'Schaffhausen, industrielle Ambition und eigene Modellfamilien'),
    sources: ['iwc', 'iwcGenta'],
    story: [
      b('Florentine Ariosto Jones founded IWC in Schaffhausen with an industrial ambition: combine Swiss watchmaking skills with modern production and the power available from the Rhine. This gives the 1868 foundation a more specific meaning than simply an old date on a dial. The later wristwatch families did not all express that ambition through the same shape. Pilot’s Watches, Portugieser and Ingenieur each give the wearer a different relationship with the display and case.', 'Florentine Ariosto Jones gründete IWC in Schaffhausen mit industriellem Anspruch: Schweizer Uhrmacherkenntnisse sollten mit moderner Fertigung und Rheinkraft verbunden werden. Das gibt 1868 mehr Bedeutung als nur ein altes Zifferblattdatum. Spätere Armbanduhren drückten diese Ambition nicht durch dieselbe Form aus. Fliegeruhren, Portugieser und Ingenieur bieten unterschiedliche Beziehungen zu Anzeige und Gehäuse.'),
      b('The Ingenieur illustrates how one family can contain several historical chapters. Its 1955 beginning predates the integrated-bracelet Ingenieur SL designed by Genta and introduced in 1976. The reference 1832 identifies that later design chapter; it should not be used as a description of every earlier or later Ingenieur. This distinction matters to collectors and everyday buyers alike, because historical continuity does not guarantee continuity of case size, bracelet construction or movement.', 'Die Ingenieur zeigt mehrere Kapitel innerhalb einer Familie. Ihr Beginn 1955 liegt vor Gentas 1976 eingeführter Ingenieur SL mit integriertem Band. Referenz 1832 kennzeichnet dieses spätere Kapitel und beschreibt nicht jede frühere oder spätere Ingenieur. Das ist für Sammler wie Alltagsträger wichtig: Historische Kontinuität garantiert keine gleichen Maße, Bandkonstruktionen oder Werke.'),
    ],
    choice: b('For an instrument-like display, compare a simple Pilot’s Watch against a Pilot’s Chronograph at normal wrist distance. For a more dress-oriented chronograph, add a Portugieser and examine how its case length sits under a sleeve. For an integrated bracelet, assess the Ingenieur’s first links and clasp position rather than only diameter. Record the IW reference for each finalist: it turns an appealing family name into a watch whose movement and dimensions can actually be compared.', 'Für Instrumentenoptik vergleichen Sie einfache Fliegeruhr und Fliegerchronograph aus normalem Abstand. Ergänzen Sie für elegantere Chronographen eine Portugieser und prüfen Sie Gehäuselänge unter dem Ärmel. Bei Ingenieur zählen erste Glieder und Schließenposition statt nur Durchmesser. Die IW-Referenz macht aus einem reizvollen Familiennamen ein konkret vergleichbares Werk und Gehäuse.'),
  },
  jaegerLeCoultre: {
    heading: b('A reversible case with more than one purpose', 'Ein Wendegehäuse mit mehreren Aufgaben'),
    sources: ['jlc', 'jlcTesting'],
    story: [
      b('The Reverso’s 1931 origin and the Duoface concept introduced in 1994 should be read as separate stages. A reversible case is a physical construction; a second dial with another time display is a particular use of that construction. Confusing the two makes it easy to describe a single-face Reverso incorrectly or assume that every two-sided model has the same functions. The pleasure of the design is partly in this interaction between the carrier, the turning case and what each side reveals.', 'Reversos Ursprung 1931 und das Duoface-Konzept von 1994 sind getrennte Stufen. Ein Wendegehäuse ist eine Konstruktion, ein zweites Zifferblatt mit weiterer Zeit eine bestimmte Nutzung davon. Wer das verwechselt, beschreibt einseitige Reverso-Uhren falsch oder unterstellt allen doppelseitigen dieselben Funktionen. Der Designreiz liegt im Zusammenspiel von Träger, drehendem Gehäuse und den sichtbaren Seiten.'),
      b('Master Control offers another way into Jaeger-LeCoultre, with a round-case identity and its own testing story. The manufacturer’s 1,000 Hours Control and the HPG language of the newer Master Control Chronometre generation belong to specific contexts. They should not become a blanket claim on every pre-owned Master watch. The useful approach to the brand’s history is therefore to connect a design or technical development to an identifiable watch, rather than treating every collection as an expression of the same specification.', 'Master Control eröffnet mit rundem Gehäuse und eigener Prüfgeschichte einen anderen Zugang. Die herstellereigene 1.000-Stunden-Prüfung und HPG der neueren Master-Control-Chronometre-Generation gehören in konkrete Zusammenhänge. Sie sind keine pauschalen Aussagen für jede gebrauchte Master. Sinnvoll ist, Gestaltung und technische Entwicklung identifizierbaren Uhren zuzuordnen statt alle Kollektionen als gleiche Spezifikation zu behandeln.'),
    ],
    choice: b('Try a Reverso by length as well as width: a rectangular case occupies the wrist differently from a round Master watch. For Duoface, decide whether you will use both displays and enjoy turning the case. For Master, compare a simple display with a chronograph or calendar before choosing complexity by appearance. Ask for a demonstration of every selected function, including the Reverso’s carrier and locking action where relevant. A watch that suits your routine is more rewarding than a collection name alone.', 'Probieren Sie Reverso nach Länge und Breite; Rechteck- und Rundgehäuse belegen das Handgelenk unterschiedlich. Bei Duoface zählt, ob Sie beide Anzeigen und das Wenden nutzen möchten. Vergleichen Sie bei Master einfache Anzeige mit Chronograph oder Kalender. Lassen Sie alle Funktionen zeigen, gegebenenfalls auch Reverso-Träger und Verriegelung. Die passende Routine zählt mehr als der Kollektionsname allein.'),
  },
  tagHeuer: {
    heading: b('Timing traditions and connected technology', 'Zeitmesstradition und vernetzte Technik'),
    sources: ['tag', 'tagConnected', 'tagOs'],
    story: [
      b('Carrera’s 1963 beginning and Formula 1’s 1986 arrival represent different chapters within TAG Heuer’s timing-led identity. Familiar names have continued while case sizes, movements and wearing preferences have changed. That is why a current Carrera and an older Carrera should not be collapsed into one generic specification. Nor is Formula 1 simply a synonym for one movement type. Use the historical name to find the family, then the reference to establish the watch.', 'Carreras Beginn 1963 und Formula 1 ab 1986 markieren verschiedene Kapitel einer zeitmessungsorientierten Identität. Namen blieben, während Größen, Werke und Tragevorlieben wechselten. Deshalb sind aktuelle und ältere Carrera keine gemeinsame Standardspezifikation. Auch Formula 1 bezeichnet nicht nur eine Werkart. Der historische Name führt zur Familie, die Referenz zur konkreten Uhr.'),
      b('Connected adds a genuinely different ownership model rather than just another dial style. The Calibre E5 uses TAG Heuer OS and the manufacturer’s Connected app, so software compatibility and battery support become part of the buying decision. This is not the same checklist as for a mechanical chronograph. Looking across those collections shows a broad approach to wearing and interacting with time: the right choice depends on which interaction you value, not on forcing electronic and mechanical watches into a single prestige scale.', 'Connected ergänzt ein anderes Besitzmodell statt nur einen Zifferblattstil. Bei Calibre E5 mit TAG Heuer OS und Connected App werden Softwarekompatibilität und Akkusupport Teil des Kaufs. Das ist nicht dieselbe Prüfliste wie beim mechanischen Chronographen. Die Kollektionen zeigen verschiedene Arten, Zeit zu tragen und zu nutzen; entscheidend ist Ihre bevorzugte Interaktion statt einer einzigen Prestigeskala für Elektronik und Mechanik.'),
    ],
    choice: b('Make three shortlists if necessary: mechanical, quartz and Connected. Within mechanical or quartz, compare a simple display with a chronograph before choosing Carrera, Formula 1 or another family. For Connected, verify your phone and current app compatibility first, then size and finish. For any chronograph, ensure you can read the counters without bringing the watch close to your face. This keeps convenience, function and style visible as separate choices rather than allowing a familiar logo to hide the compromises.', 'Erstellen Sie bei Bedarf getrennte Listen für Mechanik, Quarz und Connected. Vergleichen Sie bei den ersten beiden einfache Anzeige und Chronograph vor Carrera, Formula 1 oder anderer Familie. Bei Connected stehen Telefon- und App-Kompatibilität vor Größe und Finish. Chronographenzähler sollten ohne Nahansicht lesbar sein. So bleiben Komfort, Funktion und Stil getrennte Entscheidungen.'),
  },
  tudor: {
    heading: b('A separate identity within a familiar origin story', 'Eine eigene Identität mit bekannten Ursprüngen'),
    sources: ['tudor', 'blackBay', 'pelagos'],
    story: [
      b('The distinction between the Tudor trademark’s 1926 registration and the establishment of Montres Tudor S.A. in 1946 helps make sense of anniversary language. A brand name, a company and a particular collection need not begin on the same date. That is more than a historical footnote: a modern watch’s anniversary theme does not establish that its design or movement has existed unchanged for that entire period.', 'Die Unterscheidung zwischen Tudor-Markenregistrierung 1926 und Montres Tudor S.A. 1946 erklärt Jubiläumsaussagen. Markenname, Gesellschaft und Kollektion müssen nicht gleichzeitig entstehen. Das ist mehr als eine Fußnote: Ein Jubiläumsthema bestätigt nicht, dass Gestaltung oder Werk einer modernen Uhr über den ganzen Zeitraum unverändert existierten.'),
      b('Today, Black Bay’s heritage-led styling and Pelagos’s more technical diving direction give buyers two different starting points. The families themselves continue to branch into variants, including travel-time displays, chronographs and distinct strap arrangements. Tudor is therefore best understood through those actual design choices rather than only its relationship to another watch brand. For a pre-owned purchase, establish the generation and exact reference before using a current family page to interpret the listing.', 'Heute bieten Black Bays historisch geprägter Stil und Pelagos’ technischer Tauchfokus unterschiedliche Ausgangspunkte. Innerhalb der Familien entstehen wiederum Reisezeitanzeigen, Chronographen und eigene Bandsysteme. Tudor lässt sich deshalb besser durch konkrete Entwürfe verstehen als nur über die Beziehung zu einer anderen Marke. Ermitteln Sie beim Gebrauchtkauf Generation und Referenz, bevor aktuelle Familienseiten das Angebot erklären sollen.'),
    ],
    choice: b('Begin with whether you want a simple everyday display, a dive-style bezel, a GMT or a chronograph. Then compare actual Black Bay and Pelagos variants on fit rather than deciding from family reputation. A smaller watch may still be relatively thick; a fixed-bar strap arrangement may limit changes you assumed would be easy. If a rotating bezel is not important, include Royal, Ranger or 1926 where their design suits your preference. Select the configuration you will enjoy wearing, not a proxy for another brand.', 'Beginnen Sie mit Alltag, Tauchzeitlünette, GMT oder Chronograph. Vergleichen Sie danach konkrete Black-Bay- und Pelagos-Varianten nach Sitz statt Familienruf. Eine kleinere Uhr kann weiterhin hoch sein; feste Stege können erwartete Bandwechsel begrenzen. Ohne Lünettenbedarf ergänzen Sie gegebenenfalls Royal, Ranger oder 1926. Wählen Sie eine gern getragene Konfiguration statt einen Ersatz für eine andere Marke.'),
  },
  panerai: {
    heading: b('From specialised instruments to civilian wristwatches', 'Von Spezialinstrumenten zu zivilen Armbanduhren'),
    sources: ['panerai'],
    story: [
      b('Panerai’s naval-instrument background helps explain the prominence of case outline, crown protection and highly visible dial forms in its identity. The crown-protection bridge patented in 1956 is a specific historical development, not a generic feature of all cushion-shaped watches. The arrival of civilian collections in 1993 marks another distinct chapter. A modern watch can quote that visual language without reproducing the construction, movement or intended service of an early instrument.', 'Panerais Hintergrund bei Marineinstrumenten erklärt die Bedeutung von Gehäusekontur, Kronenschutz und gut sichtbaren Zifferblattformen. Der 1956 patentierte Kronenschutzbügel ist eine konkrete Entwicklung, kein allgemeines Merkmal aller Kissengehäuse. Zivile Kollektionen ab 1993 bilden ein weiteres Kapitel. Eine moderne Uhr kann diese Sprache aufgreifen, ohne Aufbau, Werk oder Einsatzzweck früher Instrumente zu wiederholen.'),
      b('Radiomir, Luminor and Submersible are useful names because they direct attention to different case and bezel ideas. They become less useful when treated as complete specifications. A Radiomir’s lug construction can vary, a Luminor name does not settle the winding system, and a Submersible’s actual reference determines its dimensions. History should help you notice those details, not replace the reference-level information needed to choose a comfortable watch and understand its care requirements.', 'Radiomir, Luminor und Submersible lenken den Blick auf unterschiedliche Gehäuse- und Lünettenideen. Als vollständige Datenblätter taugen sie nicht. Radiomir-Anstöße können variieren, Luminor bestimmt nicht das Aufzugssystem, Submersible nicht pauschal die Maße. Geschichte sollte solche Details sichtbar machen, nicht referenzbezogene Informationen zu Komfort und Pflege ersetzen.'),
    ],
    choice: b('Choose the silhouette first: Radiomir’s crown-side outline, Luminor’s protective bridge or Submersible’s timing bezel. Then compare the PAM references on thickness, lug span and strap curve. Do not use one nominal diameter as a complete fit test. If you prefer manual winding, confirm the calibre; if a long reserve attracts you, check the actual specification rather than assuming every similar dial shares it. Correct strap hardware and an appropriate buckle are part of a wearable example, not incidental accessories.', 'Wählen Sie zuerst Radiomir-Kontur, Luminor-Bügel oder Submersible-Zeitlünette. Vergleichen Sie danach PAM-Referenzen nach Höhe, Hörnerabstand und Bandkrümmung statt nur Durchmesser. Handaufzug und lange Reserve müssen am Kaliber bestätigt werden. Passende Befestigung und Schließe gehören zur tragbaren Uhr und sind keine beiläufigen Extras.'),
  },
  bvlgari: {
    heading: b('Serpenti and Octo: two ways to make the case matter', 'Serpenti und Octo: zwei Wege zu prägender Gestaltung'),
    sources: ['bvlgari', 'octo', 'octoSteel'],
    story: [
      b('The Tubogas chapter of Bvlgari’s watch history reaches back to 1948 and makes the bracelet central to the composition. Serpenti is therefore best understood as a relationship between wrist, wrap and watch rather than a dial attached to a standard strap. The architecture invites a different kind of comparison: how the piece settles, how it opens and which parts of the design are visible while worn. Movement choice still matters, but it does not explain the whole object.', 'Das Tubogas-Kapitel reicht bei Bvlgari bis 1948 zurück und stellt das Band ins Zentrum. Serpenti ist deshalb ein Zusammenspiel von Handgelenk, Wicklung und Uhr statt ein Zifferblatt am Standardband. Entscheidend werden Sitz, Öffnung und sichtbare Gestaltung beim Tragen. Die Werkart bleibt wichtig, erklärt aber nicht den gesamten Gegenstand.'),
      b('Octo Finissimo develops a contrasting interest in geometry and thin construction. Even within that family, the specifications of a rose-gold 102912 and steel 103431 differ, illustrating why an ultra-thin headline cannot describe every reference. Together, Serpenti and Octo show the breadth of Bvlgari’s watch design: one leads the eye around the wrist, the other through a strongly articulated case. A good buyer’s comparison respects those separate aims instead of judging both by a single conventional sports-watch checklist.', 'Octo Finissimo verfolgt dagegen Geometrie und flache Konstruktion. Schon Roségold-102912 und Stahl-103431 unterscheiden sich und zeigen, warum eine Ultrathin-Schlagzeile nicht jede Referenz beschreibt. Serpenti führt den Blick um das Handgelenk, Octo durch ein klar gegliedertes Gehäuse. Ein guter Vergleich respektiert diese Ziele statt beide nach einer einzigen Sportuhren-Prüfliste zu bewerten.'),
    ],
    choice: b('For Serpenti, resolve wrist fit and construction before colour or stone setting. Ask what can actually be adjusted on that reference. For Octo Finissimo, compare the exact material, case thickness and bracelet articulation instead of selecting by a thinness record. Octo Roma and Lvcea may suit someone who prefers a different case balance. In every case, confirm whether the watch is quartz or mechanical rather than assuming its appearance settles the movement type.', 'Bei Serpenti stehen Passform und Konstruktion vor Farbe oder Besatz; klären Sie die tatsächliche Anpassbarkeit. Bei Octo Finissimo vergleichen Sie Material, Höhe und Bandbeweglichkeit statt Flachheitsrekorde. Octo Roma und Lvcea bieten andere Gehäusebalance. Bestätigen Sie Quarz oder Mechanik, statt die Werkart vom Aussehen abzuleiten.'),
  },
  girardPerregaux: {
    heading: b('Visible architecture and integrated design', 'Sichtbare Werkarchitektur und integriertes Design'),
    sources: ['gp', 'laureato', 'jackpot'],
    story: [
      b('Girard-Perregaux’s Three Bridges and Laureato point towards different kinds of visual structure. Bridges draws attention to the organisation of the mechanism; Laureato, introduced in 1975, brings case, bezel and bracelet into one integrated composition. A buyer interested in one may not be looking for the other at all. The brand’s history is consequently more useful as a set of design and mechanical ideas than as a single style applied across every watch.', 'Girard-Perregaux’ Drei Brücken und Laureato stehen für verschiedene Strukturen. Bridges lenkt den Blick auf die Organisation des Mechanismus; Laureato verbindet seit 1975 Gehäuse, Lünette und Band zu einem integrierten Entwurf. Wer das eine sucht, interessiert sich möglicherweise nicht für das andere. Die Geschichte ist daher eher ein Bestand gestalterischer und mechanischer Ideen als ein einheitlicher Stil aller Uhren.'),
      b('The Vintage 1945 name creates another distinction worth preserving: it is a design-family name, not automatically a production date. The Jackpot Tourbillon reference 99720, introduced in 2007, makes that especially clear. Its miniature mechanical display is very different from the everyday requirements of a simpler rectangular watch. When browsing older Girard-Perregaux listings, identify the reference and actual mechanism before interpreting a collection name as evidence of age, rarity or intended use.', 'Auch Vintage 1945 verdient genaue Einordnung: Es ist ein Designfamilienname, nicht automatisch ein Produktionsjahr. Die 2007 eingeführte Jackpot Tourbillon Referenz 99720 verdeutlicht das. Ihr mechanisches Miniaturschauspiel unterscheidet sich von den Alltagsanforderungen einer einfachen rechteckigen Uhr. Identifizieren Sie bei älteren Angeboten Referenz und Mechanismus, bevor ein Kollektionsname Alter, Seltenheit oder Nutzung belegen soll.'),
    ],
    choice: b('For a bracelet-led everyday design, start with Laureato and assess how its first links fit your wrist. For a rounder dress watch, compare 1966; for a shaped case, look at Vintage 1945 without mistaking the name for the watch’s age. Bridges belongs on the shortlist when the movement architecture is itself the attraction. With any unusual complication, establish a realistic service route before making rarity the reason to buy. The best-documented example of the configuration you want is a stronger starting point than an unexplained scarce reference.', 'Für integrierten Alltagsstil beginnen Sie mit Laureato und ersten Bandgliedern. Vergleichen Sie 1966 für runde Eleganz oder Vintage 1945 für Formgehäuse, ohne den Namen als Alter zu lesen. Bridges passt, wenn Werkarchitektur selbst der Reiz ist. Bei ungewöhnlichen Komplikationen klären Sie den Serviceweg vor dem Seltenheitsargument. Eine dokumentierte Wunschausführung ist die bessere Grundlage als eine ungeklärte seltene Referenz.'),
  },
};
