import { TOPICS, guideTopic } from './topics.js';
import { BRAND_RESEARCH } from './brands.js';
import { REVIEW_DATE } from './sources.js';

// Czech editorial copy uses the same researched facts, reference identifiers and
// source registry as the English/German articles. Product data is not translated here.
const profile = (history, choose, inspect) => ({ history, choose, inspect });
export const CZECH_BRAND_PROFILES = {
  rolex: profile(
    'Známé kolekce Rolex vznikaly jako odpovědi na rozdílné každodenní i profesionální potřeby. Datejust se představila v roce 1945, Submariner v roce 1953 a GMT-Master v roce 1955. Přetrvávající názvy však neznamenají neměnnou konstrukci: mezi generacemi se výrazně proměnila pouzdra, náramky i strojky.',
    'Začněte funkcí, kterou skutečně využijete. Pro každodenní nošení porovnejte Datejust a Oyster Perpetual, pro otočnou potápěčskou lunetu Submariner, pro cestování GMT-Master II a pro měření uplynulého času Daytona. Chronograf není ukazatel druhého časového pásma. Obvod zápěstí, manžeta a preference datumovky často zúží výběr lépe než popularita modelu.',
    'U použitých hodinek Rolex zkontrolujte souměrnost pouzdra, stav lunety, pohyblivost článků náramku a sponu. Ptejte se na výměny číselníku, ruček i částí náramku. Pozdější originální servisní díl může dobře sloužit při běžném nošení, ale pro sběratele hledajícího dobovou původnost má jiný význam.'),
  patekPhilippe: profile(
    'Nautilus vstoupila do kolekce Patek Philippe v roce 1976, Aquanaut následoval v roce 1997. Sportovně laděné řady doplňují společenské hodinky, tvarovaná pouzdra a kalendářní komplikace. Značku proto nelze ztotožňovat pouze se dvěma nejviditelnějšími kolekcemi.',
    'Calatrava nabízí střídmé společenské proporce, zatímco Nautilus a Aquanaut odlišují charakteristická pouzdra a spojení s náramkem či řemínkem. U řad Complications a Grand Complications nejprve zvolte požadovanou funkci a poté ověřte její nastavování a servis. Ne všechny hodinky Patek Philippe mají automatický nátah; rozhoduje konkrétní reference.',
    'Před porovnáním cen ověřte délku náramku či upraveného řemínku, správnou sponu a přesný seznam dokumentů. Chybějící články integrovaného náramku mohou znamenat významný výdaj. U kalendářních modelů požádejte o předvedení člověka, který zná daný kalibr; nezkoušejte korektory bez návodu.'),
  omega: profile(
    'Technický vývoj značky Omega zahrnuje krokové ústrojí Co-Axial a od roku 2015 certifikaci Master Chronometer. Tyto pojmy označují dvě rozdílné věci: konstrukci strojku a soubor zkoušek. Ani jedno označení nelze automaticky vztáhnout na každou starší Omegu.',
    'Při výběru chronografu rozlišujte Moonwatch od dalších rozměrů a strojků řady Speedmaster. Seamaster Diver 300M, Planet Ocean a Aqua Terra nejsou zaměnitelné možnosti. Aqua Terra působí méně sportovně, zatímco Constellation a De Ville rozšiřují výběr společenských hodinek.',
    'Vyžádejte si úplnou referenci, nikoli pouze označení Seamaster nebo Moonwatch. Ověřte chod lunety, návrat chronografu do nulové polohy, délku náramku a doložené servisní práce. Safírové a akrylátové sklíčko, jiný strojek nebo generace náramku mohou zásadně změnit zkušenost s nošením.'),
  cartier: profile(
    'Historie designu Santos sahá do roku 1904, Tank do roku 1917. Jejich význam spočívá především v tvaru a proporcích. Obdélníkové a čtvercové hodinky proto porovnávejte podle délky, šířky a plochy na zápěstí, nikoli pouze podle průměru používaného u kulatých pouzder.',
    'Tank nabízí obdélníkovou siluetu, Santos výraznější čtvercový tvar, Panthère šperkový charakter náramku a Ballon Bleu kulatější pouzdro. Až po výběru tvaru zvolte velikost a strojek. Malé quartzové hodinky Cartier mohou být záměrnou estetickou volbou, nikoli horší náhradou větších mechanických hodinek.',
    'Prohlédněte leštěné hrany pouzdra, korunku, ohebnost náramku a zavírání spony. U řemínku ověřte přiloženou přezku i vhodnou délku. U quartzové reference se ptejte na výměnu baterie a kontrolu; tvrzení „potřebuje baterii“ není spolehlivá diagnóza.'),
  hublot: profile(
    'Hublot spojuje filozofii kombinování materiálů se svými počátky v roce 1980 a uvedením Big Bang v roce 2005. Pro kupující je důležité rozlišovat společný designový jazyk od různých materiálů a strojků uvnitř stejné kolekce. Samotný název Big Bang není technickou specifikací.',
    'Classic Fusion je střídmější výchozí volbou, Big Bang zdůrazňuje vrstvenou konstrukci a mechanické detaily. Unico, Spirit of Big Bang a Square Bang porovnávejte podle tvaru, výšky a funkcí, nikoli jako barevné varianty. Posuzujte pouzdro společně s řemínkem na zápěstí podobném vašemu.',
    'Požádejte o detailní fotografie hran keramiky a kompozitu, šroubů, uchycení řemínku a spony. Škrábance, odštípnutí a stárnutí řemínku jsou odlišné problémy. Před nákupem hodinek s opotřebeným řemínkem zjistěte cenu a dostupnost správné náhrady.'),
  breitling: profile(
    'Navitimer vznikl v roce 1952 na podnět Aircraft Owners and Pilots Association. Kruhové logaritmické pravítko vysvětluje bohatě členěný číselník. Dnešní rodina obsahuje i hodinky bez chronografu, takže známá luneta sama neurčuje strojek ani funkce.',
    'Navitimer oslovuje přístrojovým leteckým designem, Chronomat sportovnějším pouzdrem a náramkem a Superocean potápěčským zaměřením. Ověřte čitelnost na obyčejné fotografii na zápěstí. Číselník zvětšený přes celou obrazovku může působit jinak než při běžném pohledu.',
    'Zjistěte kalibr, rozměry a servisní historii; nabídka Breitling zahrnuje různé typy strojků. U chronografu si nechte předvést spuštění, zastavení a vynulování. Vhodnost pro plavání neodvozujte od robustního vzhledu, ale od návodu konkrétní reference a aktuální zkoušky těsnosti.'),
  audemarsPiguet: profile(
    'Royal Oak navržený Géraldem Gentou se představil v roce 1972. Výraznější Royal Oak Offshore podle návrhu Emmanuela Gueita následoval v roce 1993. Jde o příbuzné, ale samostatné designové příběhy; Offshore není jen zvětšenou původní Royal Oak.',
    'U Royal Oak věnujte pozornost zúžení náramku a usazení na zápěstí, u Offshore zvlášť výšce a pohodlí. Code 11.59 nabízí odlišnou architekturu pouzdra na řemínku. Jednoduché časové modely, kalendáře a chronografy porovnávejte odděleně, protože kladou jiné nároky na obsluhu a servis.',
    'Změkčené hrany po leštění mohou změnit vzhled celého integrovaného designu. Vyžádejte si přesnou délku náramku a servisní dokumentaci. Čísla pouzdra, strojku a série mají odlišné účely; číslo na dýnku samo nedokládá limitovanou edici.'),
  grandSeiko: profile(
    'Grand Seiko představilo strojek 9R Spring Drive v roce 2004. Spojení energie hnacího pera s elektronickou regulací se liší od běžného mechanického kroku i quartzových hodinek napájených baterií. Pro majitele je tento rozdíl podstatnější než obecné označení automatické hodinky.',
    'Před přezdívkou číselníku zvolte typ strojku: zvažte způsob natahování, požadovanou přesnost a plynulý pohyb sekundové ručky. Snowflake a Shunbun mají odlišná pouzdra i číselníky. Porovnávejte skutečné reference, nikoli předpoklad, že všechny světlé Grand Seiko sedí stejně.',
    'Vyžádejte si snímky v rozptýleném denním i přímém světle; strukturované číselníky se s osvětlením výrazně mění. Zkontrolujte promáčkliny a nerovnoměrné přeleštění lesklých ploch a přiložené články náramku. Přezdívku, referenci a regionální kód nepovažujte za totéž.'),
  iwc: profile(
    'IWC založil Florentine Ariosto Jones v Schaffhausenu v roce 1868. Pilot’s Watches, Portugieser a Ingenieur si vytvořily odlišné vizuální identity. Ingenieur vznikl v roce 1955; Gentův Ingenieur SL s integrovaným náramkem přišel až v roce 1976.',
    'Pilot’s Watches staví na čitelnosti leteckých přístrojů, Portugieser na společenských proporcích a chronografech a Ingenieur na vztahu pouzdra a náramku. Vedle průměru sledujte délku a výšku. Dvoje hodinky se stejným jmenovitým průměrem mohou pod manžetou sedět velmi odlišně.',
    'Přesnou referencí IW ověřte kalibr a funkce. Ne všechny automatické IWC používají stejný systém nátahu. Ptejte se na chod data, rezervu chodu a doložené posouzení servisem. To, že hodinky běžely při fotografování, nepotvrzuje jejich úplný technický stav.'),
  jaegerLeCoultre: profile(
    'Reverso vzniklo v roce 1931. Koncept Duoface přišel v roce 1994 a využívá dvě tváře pro odlišné časové údaje. Ne každé otočné pouzdro má dva číselníky. Kulaté hodinky Master Control představují jinou část designové a zkušební historie značky.',
    'U Reversa porovnávejte délku, výšku a otočný mechanismus, ne pouze šířku. Jednoduchý číselník, cestovní Duoface a kalendář řeší různé potřeby. U modelů Master zvolte využitelnou komplikaci dříve, než přijmete složitější číselník a náročnější servis.',
    'Ověřte vodicí rám a zamykání Reversa, případné rytiny či přeleštění zadní strany a správnou sponu. Nechte si předvést všechny komplikace. Rozlišujte původní historické kusy a novodobé reedice; číselník ve starém stylu nedokazuje raný rok výroby.'),
  tagHeuer: profile(
    'Carrera byla uvedena v roce 1963 a Formula 1 v roce 1986. Oba názvy zahrnují více generací, nikoli jediný typ strojku. Digitální Connected vyžaduje samostatné posouzení softwaru, baterie a kompatibility s telefonem.',
    'Carrera nabízí chronografický design, Monaco čtvercové pouzdro, Aquaracer potápěčsky zaměřené reference a Formula 1 různé sportovní možnosti. Typ strojku neurčujte pouze podle rodiny. Quartz, mechanika a Connected odpovídají odlišným požadavkům na pohodlí a dlouhodobou údržbu.',
    'U chronografu zkontrolujte tlačítka a návrat do nulové polohy; u Connected nabíjení, párování a chování baterie. Před objednáním řemínku či spony ověřte referenci. Nízkou pořizovací cenu mohou převážit chybějící specifické doplňky nebo nevyřešená závada.'),
  tudor: profile(
    'Ochranná známka Tudor byla pro Hanse Wilsdorfa registrována v roce 1926; společnost Montres Tudor S.A. vznikla v roce 1946. Jde o dva různé milníky. Současné Black Bay a Pelagos posuzujte podle konkrétních referencí, nikoli jedné domnělé společné specifikace.',
    'Black Bay nabízí historicky inspirovaný design a více funkcí. Pelagos zdůrazňuje technické potápěčské využití, ale jednotlivé varianty se významně liší. Royal, 1926 a Ranger rozšiřují výběr mimo potápěčské lunety. Před porovnáním rozměrů zvažte náramek, textil nebo pryž.',
    'Určete referenci a generaci strojku, poté zkontrolujte lunetu, nastavení spony a přiložené řemínky. FXD má pevné stěžejky a vyžaduje vhodný průvlečný řemínek. Certifikaci, rozměry i vodotěsnost vždy potvrďte pro skutečně nabízené hodinky.'),
  panerai: profile(
    'Historie Panerai spojuje námořní přístroje s designy Radiomir a Luminor. Ochranný můstek korunky byl patentován v roce 1956; civilní kolekce přišly v roce 1993. Z vojenského původu nelze odvozovat dnešní rozměry, strojek ani vodotěsnost.',
    'Můstek Luminoru, odlišná korunka a obrys Radiomiru a otočná luneta Submersible jsou užitečné výchozí rozdíly. Luminor Due nepředstavuje automaticky další potápěčskou specifikaci. Ověřte rozpětí nožek a zakřivení řemínku; průměr nevystihuje usazení polštářového pouzdra.',
    'Rozměry, strojek a funkce ověřte referencí PAM. Prohlédněte hlavy šroubů řemínku, ochranu korunky a přiloženou přezku. Označení 8 Days, Destro a Marina popisují různé vlastnosti; žádné nenahrazuje úplnou referenci ani údaj o stavu.'),
  bvlgari: profile(
    'Historie hodinek Serpenti zahrnuje design Tubogas od roku 1948. Rodina Octo rozvíjí výrazně geometrický směr. Šperkové hodinky a ultratenký mechanický model proto vyžadují rozdílné priority při výběru.',
    'U Serpenti začněte konstrukcí náramku, počtem ovinutí a velikostí zápěstí. U Octo Finissimo konkrétním kalibrem, materiálem a výškou. Octo Roma a Lvcea nabízejí další tvary. Ne všechny Serpenti jsou quartzové a ne všechny Octo Finissimo mají stejné rozměry.',
    'U šperkového modelu zkontrolujte napětí náramku, bezpečnost spony a zasazení kamenů. U ultratenkého modelu se ptejte na nárazy a servis; tenké pouzdro neznamená bezúdržbovost. Materiál, číselník a náramek musí odpovídat referenci.'),
  girardPerregaux: profile(
    'Girard-Perregaux spojuje své kořeny s rokem 1791 a konstrukci Three Bridges s hodinářstvím devatenáctého století. Laureato se představilo v roce 1975. Moderní Bridges a Laureato tak vyjadřují různé části historie značky.',
    'Laureato je výchozí volbou pro integrovaný náramek, 1966 pro kulaté společenské hodinky a Vintage 1945 pro tvarované pouzdro. Bridges zdůrazňuje architekturu strojku. Vintage 1945 je název kolekce, nikoli důkaz výroby hodinek v roce 1945.',
    'Před úvahou o vzácnosti potvrďte úplnou referenci, délku náramku a stav strojku. U nezvyklých komplikací si vyžádejte odborné posouzení servisu a písemné informace o dílech. Vzácný model může být zajímavý, ale jeho servis i další prodej mohou trvat déle.'),
};

const topic = (title, paragraphs, checks) => ({ title, paragraphs, checks });
export const CZECH_TOPICS = {
  story: topic('Historie a vývoj kolekcí', ['Historické datum pomáhá pochopit původ designu, ale neurčuje stáří konkrétních hodinek. Současná reedice může připomínat starší model a přitom používat jiný strojek, rozměry i materiály. Při čtení historie rozlišujte uvedení kolekce, generaci reference a rok výroby jednotlivého kusu.', 'Vývoj značky není nepřerušený žebříček zlepšení. Změna průměru, náramku či způsobu natahování může být pro jednoho nositele přínosem a pro jiného kompromisem. Dobový kontext proto využijte k porozumění návrhu, nikoli jako automatické potvrzení vyšší hodnoty.'], 'Porovnejte fotografie a dokumentaci správného období. U historických hodinek si odděleně ověřte původnost, provedené opravy a současnou funkčnost.'),
  choice: topic('Jak vybrat správné hodinky', ['Nejdříve si určete způsob nošení, velikost zápěstí a celkový rozpočet. Jiný výběr dává smysl pro každodenní práci, jiný pro sport a jiný pro příležitostné společenské nošení. Funkci, kterou nikdy nepoužijete, neposuzujte jako automatickou výhodu.', 'Zúžte výběr na několik přesných referencí a porovnejte je za stejných podmínek. Vedle průměru sledujte výšku, délku mezi nožkami, hmotnost a délku řemínku. Pokud si hodinky nemůžete vyzkoušet, požádejte o boční fotografii a snímek na zápěstí se známým obvodem.'], 'U každého kandidáta si napište jednu výhodu a jeden kompromis. Potom porovnejte konkrétní nabízené kusy podle doloženého stavu, příslušenství a servisních potřeb.'),
  newPreowned: topic('Nové, nebo použité hodinky?', ['Nové a použité hodinky nejsou pouze dvě cenové kategorie. Záleží na skutečném stavu, předchozím používání, původu, začátku případné záruky a úplnosti příslušenství. Výraz „nenošené“ nemusí znamenat, že hodinky právě opustily výrobu nebo že výrobní záruka začíná znovu.', 'Použitý trh zpřístupňuje i ukončené reference a jiné generace pouzder či náramků. Na druhou stranu může přinést náklady na seřízení délky, servis nebo nahrazení chybějících dílů. Nižší cena není výhodou, pokud pouze přesouvá známý výdaj na nového majitele.'], 'Porovnávejte stejnou referenci, materiál a rozsah dodávky. Písemně si potvrďte stav, platnou záruku a případné známé závady; původní ceník nepovažujte za současnou tržní hodnotu.'),
  maintenance: topic('Péče, servis a dlouhodobé používání', ['Servisní interval není jednotný pro všechny hodinky. Řiďte se pokyny výrobce konkrétního kalibru, způsobem používání a skutečnými projevy závady. Změna chodu, odpor při natahování nebo vlhkost pod sklem jsou důvodem k odborné kontrole, nikoli k čekání na doporučený termín.', 'Vodotěsnost není trvalá vlastnost bez údržby. Těsnění stárne a náraz či otevření pouzdra mohou změnit jeho stav. Před použitím starších hodinek ve vodě požádejte o aktuální kontrolu a dodržujte pravidla pro korunku a tlačítka. Vnější označení hloubky nenahrazuje tuto kontrolu.'], 'Před zadáním servisu se dohodněte na rozsahu prací, cenovém odhadu a zachování původních dílů. U sběratelských kusů nedávejte automatický souhlas k leštění nebo výměně číselníku.'),
  price: topic('Co ovlivňuje cenu hodinek', ['Cena závisí na referenci, kovu, číselníku, stáří, původnosti, stavu a rozsahu dodávky. Ceníková částka výrobce, požadavek prodejce a doložená prodejní cena nejsou stejné údaje. Nabídka, která dlouho zůstává neprodaná, sama neprokazuje tržní hodnotu.', 'Srovnávejte pouze smysluplně podobné kusy. Ocel a drahý kov, původní číselník a pozdější servisní varianta nebo úplný a neúplný náramek mohou vysvětlovat velký rozdíl. Do rozpočtu zahrňte známé servisní práce, dopravu a případné povinné poplatky.'], 'Zeptejte se, jaké doložené vlastnosti podporují právě tuto cenu. Nepředpokládejte garantovaný růst hodnoty ani rychlý další prodej.'),
  vintage: topic('Starší modely a původnost', ['U historických hodinek oddělujte pravost, původnost a funkční stav. Pravý servisní číselník může být novější než pouzdro. Oprava může pomoci běžnému nošení, ale změnit to, co hledá sběratel dobových součástí.', 'Stav posuzujte podrobně: hrany pouzdra, korozi, stav strojku, ručky, svítící hmotu a soulad identifikačních údajů. Patina není automatickým důkazem pravosti a dokonale čistý vzhled nemusí znamenat výborně zachovaný originál.'], 'Vyžádejte si fotografie a odborné posouzení konkrétní reference. Servisní možnosti a dostupnost náhradních dílů ověřte ještě před cenovou dohodou.'),
  papers: topic('Krabička, doklady a jejich význam', ['Krabička, záruční karta, návod, servisní faktura a původní účtenka mají různé účely. Výraz „box and papers“ proto nestačí; požadujte přesný seznam a fotografie dodaných předmětů. Ověřte soulad reference a dostupných identifikačních údajů.', 'Doklady mohou doložit historii a usnadnit porovnání nabídek, samy ale neprokazují pravost hodinek. Krabičku lze doplnit později a karta neříká vše o současném stavu. Chybějící příslušenství také není samo o sobě důkazem padělku.'], 'Oddělte ocenění hodinek od ocenění příslušenství. Servisní doklad propojte s konkrétním kusem a ověřte rozsah i datum provedených prací.'),
  archives: topic('Výpis z archivu Patek Philippe', ['Výpis z archivu zachycuje historické údaje z výrobních záznamů. Není totožný s původním certifikátem původu ani se současnou technickou prohlídkou. Nelze z něj bez dalšího vyvozovat, že všechny dnes přítomné součásti odpovídají původnímu provedení.', 'Porovnávejte informace v dokumentu s pouzdrem, strojkem, číselníkem a referencí konkrétních hodinek. Historický údaj o výrobě a pozdější prodej mohou mít různá data; tento rozdíl nemusí sám znamenat nesrovnalost.'], 'Před objednáním výpisu ověřte aktuální podmínky výrobce. Při nákupu kombinujte archivní informace s odbornou kontrolou skutečných hodinek.'),
  rolexMechanics: topic('Konstrukce a hodinářství Rolex', ['Pouzdro, strojek, korunka a náramek tvoří funkční celek. Označení Oyster nebo Perpetual pomáhá orientaci v konstrukční historii, ale neříká všechno o vodotěsnosti, rezervě chodu či materiálu konkrétní reference.', 'Rozdíly mezi generacemi mohou měnit způsob nošení i servisní požadavky. Při porovnání si zaznamenejte kalibr, rozměry, typ sklíčka a provedení spony. Výrobní přesnost nových hodinek neznamená automaticky totožný chod každého použitého kusu.'], 'Technické údaje ověřte pro správnou referenci. U použitého kusu požadujte doklad o aktuálním chodu a těsnosti, pokud na těchto vlastnostech závisí váš nákup.'),
  patekMechanics: topic('Hodinářství a komplikace Patek Philippe', ['Hodinářská komplikace přidává funkci nad základní zobrazení času. Kalendář, chronograf, druhé časové pásmo a odbíjení vyžadují různé mechanismy i způsoby obsluhy. Vyšší počet funkcí sám neurčuje, které hodinky jsou pro vás vhodnější.', 'Tenkost, dokončení strojku a konstrukce pouzdra mají praktické důsledky. U složitého kalendáře potřebujete správný postup nastavování; u jemného pouzdra obezřetnost při nošení. Vizuální obdiv ke strojku nenahrazuje kontrolu jeho funkce.'], 'Vyžádejte si návod správného kalibru a odbornou demonstraci každé funkce. Před nákupem zjistěte předpokládaný servisní postup a nechte posoudit nejasné projevy.'),
  coaxial: topic('Jak rozumět strojku Omega Co-Axial', ['Co-Axial označuje konstrukci krokového ústrojí, nikoli obecně všechny automatické hodinky Omega. Jeho princip se liší od tradičního švýcarského kotvového kroku. Není to však příslib, že se strojek nikdy nebude muset mazat, kontrolovat nebo servisovat.', 'Název Co-Axial a certifikace Master Chronometer nejsou zaměnitelné. Jeden popisuje technickou část strojku, druhý zkoušky podle stanoveného rámce. U staršího modelu ověřte přesný kalibr a příslušnou generaci.'], 'Při srovnání nabídek se ptejte na servisní dokumentaci a aktuální stav. Specifikaci jiné reference nepřenášejte na své hodinky pouze kvůli nápisu na číselníku.'),
  metas: topic('Co znamená Master Chronometer', ['Master Chronometer je certifikační rámec spojený se zkouškami celých hodinek podle požadavků METAS. Zahrnuje více než jeden údaj o denní odchylce. Je nutné rozlišovat zkoušku strojku a zkoušku hotových hodinek.', 'Certifikace je důležitá technická informace, ale nenahrazuje posouzení použitých hodinek po letech nošení. Náraz, voda nebo zanedbaný servis mohou ovlivnit jejich současný stav. Označení nelze automaticky přisoudit celé kolekci bez ověření reference.'], 'Ověřte certifikaci podle konkrétního modelu a dostupných záznamů výrobce. U nabízeného kusu odděleně požadujte doložení současné funkčnosti a případné kontroly těsnosti.'),
  speedSeamaster: topic('Omega Speedmaster, nebo Seamaster?', ['Speedmaster a Seamaster nejsou dvě jediné specifikace. U Speedmasteru vyberte konkrétní chronograf a strojek; u Seamasteru rozlišujte Diver 300M, Planet Ocean a Aqua Terra. Každá rodina zahrnuje různá pouzdra, rozměry a generace.', 'U chronografu rozhoduje způsob natahování, ovládání tlačítek a čitelnost. U potápěčsky zaměřeného modelu luneta, výška pouzdra a skutečně zamýšlené použití ve vodě. Nepředpokládejte, že každá Speedmaster je ručně natahovaná Moonwatch nebo každý Seamaster stejná potápěčská konstrukce.'], 'Vyberte dvě přesné reference a porovnejte jejich usazení na zápěstí, funkce a dokumentovaný stav. Volbu podřiďte svému používání, nikoli pouze příběhu kolekce.'),
  exceptional: topic('Výjimečné hodinky Audemars Piguet a jejich ceny', ['Mimořádná cena může souviset s komplikací, materiálem, původem, zachovalostí nebo konkrétní aukční situací. Jediný rekord nepředstavuje běžnou hodnotu celé kolekce. Rozlišujte cenu včetně aukčních poplatků a částku bez nich.', 'Vzácnost a snadný další prodej nejsou totéž. Úzký okruh zájemců může znamenat delší hledání kupce. U vysoce komplikovaných hodinek má význam nejen vzácnost, ale i prokazatelná funkčnost a dostupnost odborného servisu.'], 'Před nákupem požadujte ověření původu, specialistou předvedené mechanismy a písemnou servisní představu. Výjimečnost nepovažujte za záruku budoucího výnosu.'),
  springDrive: topic('Grand Seiko Spring Drive: energie a regulace', ['Spring Drive využívá energii hnacího pera a elektronickou regulaci chodu. Nejde o běžný bateriový quartz ani o tradiční mechanický krok. Plynulý pohyb sekundové ručky je viditelným projevem této konstrukce, nikoli jedinou vlastností strojku.', 'Konkrétní kalibry se liší nátahovým systémem, rezervou chodu i uváděnou přesností. Automatický nátah neznamená, že hodinky poběží bez dostatečného pohybu navždy. Způsob doplnění energie si ověřte v návodu dané reference.'], 'Při nákupu porovnávejte úplné reference a servisní historii. Nenechte přezdívku číselníku zastínit typ strojku a skutečné rozměry hodinek.'),
  snowflakeShunbun: topic('Grand Seiko Snowflake a Shunbun', ['Reference SBGA211 Snowflake a SBGA413 Shunbun používají Spring Drive 9R65, ale mají odlišné proporce. Snowflake má podle výrobce průměr 41 mm, délku mezi nožkami 49 mm a výšku 12,5 mm. Shunbun má průměr 40 mm, délku 47 mm a výšku 12,8 mm.', 'Menší průměr tedy neznamená nižší pouzdro. Obě uvedené reference mají titanové pouzdro a náramek. Bílá struktura Snowflake a růžově tónovaný Shunbun se mění se světlem; výrazná studiová fotografie nemusí odpovídat běžnému pohledu.'], 'Porovnejte obě reference v denním světle a na zápěstí. Tyto rozměry nepřenášejte automaticky na každý model s podobnou přezdívkou.'),
  iwcAutomatic: topic('Automatické hodinky IWC', ['Automatické natahování využívá pohyb zápěstí k doplňování energie hnacího pera. Neříká však samo o sobě, jaký kalibr, konstrukce nátahu nebo rezerva chodu jsou uvnitř. Dvoje automatické IWC mohou mít výrazně odlišnou obsluhu i rozměry.', 'Při občasném nošení počítejte s potřebou nastavení času a případně data. U složitého kalendáře používejte správný postup a vyhněte se nastavování v zakázaném časovém úseku uvedeném v návodu. Nátah nenahrazuje servis.'], 'Ověřte referenci IW a kalibr, sledujte chod po běžném nošení a požádejte o doložené servisní práce. Pouhá fotografie běžící sekundové ručky není úplnou technickou kontrolou.'),
  pilot: topic('Výběr IWC Pilot’s Watch', ['Pilotní hodinky staví na čitelnosti, ale rodina IWC Pilot’s Watches obsahuje různé velikosti i komplikace. Jednoduchý časový model, chronograf a Big Pilot mohou na zápěstí působit zcela odlišně. Velká korunka je součástí konstrukce, kterou je dobré vyzkoušet při ohnutí ruky.', 'Vedle průměru sledujte délku pouzdra, výšku a čitelnost při běžné vzdálenosti. Chronograf přidává měření času, ale i údaje na číselníku. Keramika, ocel a titan vyžadují odlišné posouzení povrchu a poškození.'], 'Porovnejte konkrétní kalibr, funkce a uchycení řemínku. Robustní vzhled nepovažujte za univerzální potvrzení vodotěsnosti nebo odolnosti každé reference.'),
  ingenieur: topic('IWC Ingenieur a integrovaný design', ['Ingenieur vznikl v roce 1955, zatímco Gérald Genta navrhl integrovaný Ingenieur SL uvedený v roce 1976. Tyto milníky nepopisují tutéž generaci. Dnešní provedení porovnávejte podle konkrétní reference, nikoli pouze podobné lunety.', 'Pouzdro a náramek tvoří souvislý celek. Záleží na prvních článcích, ohybu kolem zápěstí, hmotnosti a možnosti seřízení délky. Udávaný průměr sám nestačí k odhadu pohodlí.'], 'Zkontrolujte povrchové úpravy, hrany lunety, sponu a přiložené články. Vlastnosti strojku nebo ochrany před magnetismem nepřenášejte mezi generacemi bez dokumentace.'),
  duoface: topic('Jaeger-LeCoultre Reverso Duoface', ['Duoface využívá dvě tváře k zobrazení rozdílných časových údajů. Není totožný s každým Reversem, jehož pouzdro se dá otočit. Při výběru ověřte přesnou funkci obou stran a způsob nastavení podle konkrétního kalibru.', 'Pro pohodlí je důležitá délka pouzdra i jeho výška. Otočný mechanismus by měl pracovat plynule a bezpečně zapadnout. Druhou stranu prohlédněte stejně pečlivě jako hlavní číselník, včetně rytin, leštění a známek poškození.'], 'Nechte si předvést překlápění a nastavování obou časů. Ptejte se na servis mechanismu, správný řemínek a sponu; nezkoušejte zatuhlé díly násilím.'),
  masterChronograph: topic('Chronografy Jaeger-LeCoultre Master', ['Chronograf měří uplynulý čas nezávisle na běžné časové indikaci. Modely Master mohou přidávat další kalendářní funkce, takže samotný rodinný název neurčuje kompletní výbavu. Ověřte kalibr a přesný seznam komplikací.', 'Prohlédněte čitelnost při běžném nošení, polohu tlačítek a výšku pouzdra. Složitější číselník má smysl, pokud funkcím rozumíte a skutečně je využijete. Výrobní zkoušky nejsou náhradou za současné posouzení použitého kusu.'], 'Vyžádejte si ukázku spuštění, zastavení a návratu chronografu do nuly i správného chodu kalendáře. Ovládejte pouze podle návodu příslušné reference.'),
  carreraFormula: topic('TAG Heuer Carrera a Formula 1', ['Carrera vznikla v roce 1963 a Formula 1 v roce 1986. Oba názvy dnes zahrnují mnoho generací. Rozdělení na mechanickou Carreru a quartzovou Formula 1 je příliš jednoduché; rozhoduje úplná reference.', 'Vyberte dvě hodinky odpovídající rozpočtu a porovnejte jejich rozměry, strojek, displej a funkce. Quartzové pohodlí a zájem o mechaniku jsou různé preference, nikoli automatický žebříček kvality.'], 'Srovnávejte podobný stav a příslušenství. Ověřte servis či baterii podle typu strojku, chod chronografu a délku náramku.'),
  connected: topic('TAG Heuer Connected Calibre E5', ['Connected Calibre E5 byl uveden v roce 2025 ve velikostech 40 a 45 mm. Používá TAG Heuer OS a aplikaci TAG Heuer Connected. Předpoklady o systému dřívější generace proto nelze automaticky použít pro E5.', 'Před nákupem ověřte kompatibilitu se svým telefonem a aktuální požadavky aplikace. Vyzkoušejte párování, oznámení, nabíjení a potřebné funkce. Výdrž baterie se mění podle nastavení a používání; reklamní údaj neprokazuje stav konkrétního použitého akumulátoru.'], 'Potvrďte správnou nabíječku a odstranění účtu předchozího majitele podporovaným resetem. Ověřte možnosti servisu baterie a softwarové podpory; nepředpokládejte neomezené aktualizace.'),
  blackBay: topic('Tudor Black Bay: výběr reference', ['Black Bay je široká rodina, nikoli jediná potápěčská specifikace. Chronograf, GMT a jednoduché hodinky s otočnou lunetou řeší různé potřeby. Barva číselníku sama nestačí k porovnání strojku a rozměrů.', 'Porovnejte výšku pouzdra, náramek, řemínek a nastavení spony stejně pečlivě jako průměr. Menší údaj v tabulce nemusí znamenat plošší usazení na zápěstí. Certifikaci i vodotěsnost ověřujte pro konkrétní referenci.'], 'Zkontrolujte lunetu, korunku, přiložené články a servisní historii. Ptejte se na předchozí leštění a případnou aktuální kontrolu těsnosti.'),
  blackBayPelagos: topic('Tudor Black Bay, nebo Pelagos?', ['Black Bay obvykle oslovuje historicky inspirovaným vzhledem, Pelagos silnějším technickým potápěčským zaměřením. Je to výchozí orientace, nikoli náhrada za srovnání konkrétních referencí.', 'Pelagos, Pelagos 39, LHD, FXD a Ultra nemají jediný společný rozměr nebo údaj o hloubce. Lišit se může i uchycení řemínku a funkce lunety. Také Black Bay zahrnuje více než jednoduché potápěčské hodinky.'], 'Pro použití ve vodě ověřte návod a současnou těsnost, pro běžný den čitelnost a pohodlí. Pevné stěžejky FXD neumožňují automaticky nasadit běžný kovový náramek.'),
  luminorRadiomir: topic('Panerai Luminor a Radiomir', ['Luminor je spojen s ochranným můstkem korunky, Radiomir s jiným obrysem korunky a pouzdra. Historická a pozdější provedení Radiomiru se liší také nožkami. Nejde o totožné hodinky pod dvěma názvy.', 'Porovnávejte přesné reference PAM podle šířky, výšky, délky a strojku. Můstek Luminoru vytváří výrazný boční profil; Radiomir může na straně korunky méně vyčnívat. Rodinný název neurčuje ruční nebo automatický nátah.'], 'Vyzkoušejte podobné pouzdro a usazení řemínku. U použitého kusu prověřte korunku, můstek a upevnění pásku bez násilí.'),
  luminorSubmersible: topic('Panerai Luminor a Submersible', ['Praktickým rozdílem je otočná měřicí luneta Submersible oproti střídmější lunetě mnoha modelů Luminor. Dodatečné ovládání mění vzhled i způsob používání. Společný tvar ochrany korunky neznamená shodnou vodotěsnost.', 'Porovnejte materiál, výšku, hmotnost a rozsah řemínku. Pokud chcete měřit čas lunetou, ověřte její čitelnost a chod. Rozlišení podle rodiny vám pomůže zúžit nabídku, ale konečné rozhodnutí musí vycházet z reference.'], 'Před použitím ve vodě prostudujte konkrétní návod a požádejte o aktuální zkoušku těsnosti. Běžná fotografie nevyloučí opotřebená těsnění ani poškození lunety.'),
  serpenti: topic('Bvlgari Serpenti: nejprve správná velikost', ['Serpenti je designová rodina, nikoli jediná konstrukce náramku či strojku. Historie Tubogas sahá do roku 1948, současné reference však používají různé materiály a mechanismy. Ne všechny se ovíjejí a nastavují stejným způsobem.', 'Kromě číselníku posuzujte pohodlí a bezpečné usazení. Zjistěte určený obvod zápěstí, počet ovinutí, funkci spony a případné dodatečné úpravy nebo osazení kamenů. Ne každá Serpenti je quartzová.'], 'Požádejte o detaily pružných částí a míst dotyku s rukou. Předem ověřte možné úpravy velikosti a potřebného specialistu; nevhodná velikost nemusí být řešitelná jednoduchou výměnou řemínku.'),
  octo: topic('Bvlgari Octo Finissimo', ['Octo Finissimo kombinuje geometrické pouzdro s důrazem na malou výšku. Reference 102912 z růžového zlata používá automatický kalibr BVL 138 a výrobce uvádí výšku 5,15 mm. Ocelová 103431 má uvedeno 6,4 mm: název rodiny tedy nezaručuje stejné rozměry.', 'Srovnávejte úplnou referenci podle materiálu, povrchu, výšky a vodotěsnosti. Široký obrys může pokrýt velkou část zápěstí i u velmi tenkých hodinek. Údaj raného společenského modelu nelze přenášet na všechny pozdější ocelové varianty.'], 'Prohlédněte hrany, články náramku a sponu. Tenkost není důkazem odolnosti proti nárazu; zajímejte se o servis a dřívější poškození.'),
  laureato: topic('Girard-Perregaux Laureato', ['Laureato vzniklo v roce 1975. Jeho charakter netvoří jen číselník: pouzdro, luneta a náramek představují souvislý design. Současné reference se liší velikostí, materiálem i strojkem.', 'Zkontrolujte výšku, zúžení náramku a pohyblivost kolem zápěstí. Integrovaný náramek nemusí umožnit použití běžného náhradního řemínku. Povrchové úpravy patří k designu a zaslouží si detailní fotografie stavu.'], 'Vyžádejte si další články, informace o sponě a servisní historii. Starší kusy odlišujte od reedicí a nepřenášejte na ně současné technické údaje.'),
  jackpot: topic('Girard-Perregaux Jackpot Tourbillon', ['Vintage 1945 Jackpot Tourbillon spojuje tourbillon, miniaturní válcovou herní indikaci a zvukový mechanismus. Christie’s dokumentuje referenci 99720 a uvedení modelu v roce 2007. Vintage 1945 je zde název designové rodiny, nikoli rok výroby prodávaných hodinek.', 'Aukční katalog dokládá konkrétní položku, ne současnou cenu všech Jackpotů. Význam má materiál, stav, příslušenství, termín prodeje a poplatky. Mechanismus je hodinářské představení; neznamená peněžní výhru ani příslib investičního výnosu.'], 'Vyžadujte odbornou demonstraci a servisní posouzení všech mechanismů. Před cenovou dohodou vyjasněte přepravu, pojištění a dostupnost součástí.'),
};

export function getCzechResearchArticle(route) {
  const key = route.pageData.isGuide ? guideTopic(route.slug) : 'choice';
  const content = CZECH_TOPICS[key];
  const brand = CZECH_BRAND_PROFILES[route.pageKey];
  if (!content || !brand) return null;
  const title = !route.pageData.isGuide ? route.pageData.h1_cs
    : key === 'story' ? `${route.brandName}: historie a vývoj hodinek`
    : key === 'choice' ? `Jak vybrat hodinky ${route.brandName}`
      : ['newPreowned', 'maintenance', 'price', 'vintage', 'papers'].includes(key) ? `${route.brandName}: ${content.title.toLocaleLowerCase('cs-CZ')}` : content.title;
  const sources = [...new Set([...(TOPICS[key]?.sources || []), ...BRAND_RESEARCH[route.pageKey].sources])];
  const sections = [
    { id: 'understand', title: content.title, paragraphs: content.paragraphs, sources: TOPICS[key]?.sources || [] },
    { id: 'brand-context', title: `Souvislosti značky ${route.brandName}`, paragraphs: [brand.history, brand.choose], sources: BRAND_RESEARCH[route.pageKey].sources },
    { id: 'individual-watch', title: 'Co ověřit u konkrétních hodinek', paragraphs: [brand.inspect, content.checks], sources: [] },
  ];
  const words = sections.flatMap((section) => section.paragraphs).join(' ').split(/\s+/).length;
  return { title, excerpt: `${content.paragraphs[0]} ${content.checks}`, sections, sources, dateModified: REVIEW_DATE, readMinutes: Math.max(2, Math.ceil(words / 200)), topic: key };
}
