import { bilingual as b } from './sources.js';

// These are original explanations and worked buying decisions, not manufacturer
// claims about a particular item in our inventory. Reference facts are sourced.
const section = (id, title, paragraphs, sources = []) => ({ id, title, paragraphs, sources });
export const TOPIC_DEPTH = {
  newPreowned: [
    section('compare-generations', b('A comparison that changes the decision', 'Ein Vergleich, der die Entscheidung verändert'), [
      b('Imagine two watches from the same collection: an earlier example with a recent, itemised service invoice, and a newer unworn example with no documented inspection. The newer watch may offer the preferred clasp or case shape, but the older one may give you a clearer view of immediate maintenance needs. Make two separate comparisons: which generation you want to wear, and which individual example is better documented. Mixing those questions can lead you to pay for a newer date while overlooking the condition that matters today.', 'Stellen Sie sich zwei Uhren derselben Kollektion vor: ein früheres Exemplar mit aktueller, detaillierter Servicerechnung und ein neueres, ungetragenes ohne dokumentierte Prüfung. Die neuere Uhr bietet vielleicht die gewünschte Schließe oder Gehäuseform; bei der älteren lässt sich der unmittelbare Wartungsbedarf möglicherweise besser einschätzen. Vergleichen Sie deshalb getrennt die gewünschte Generation und die Qualität des konkreten Exemplars. Andernfalls bezahlen Sie für ein jüngeres Datum und übersehen den heutigen Zustand.'),
      b('For a watch you intend to wear regularly, honest light wear can be easier to accept than a pristine finish that makes you reluctant to use it. For a gift, presentation, suitable bracelet length and dependable timing of delivery may carry more weight. Neither preference requires a universal rule that new or pre-owned is always better.', 'Bei einer regelmäßig getragenen Uhr können ehrliche leichte Gebrauchsspuren angenehmer sein als ein makelloses Finish, das vom Tragen abhält. Bei einem Geschenk zählen womöglich Präsentation, passende Bandlänge und ein verlässlicher Liefertermin stärker. Dafür braucht es keine pauschale Regel, dass neu oder gebraucht grundsätzlich besser wäre.'),
    ]),
  ],
  papers: [
    section('read-the-file', b('Read the documents as a timeline', 'Unterlagen als Zeitablauf lesen'), [
      b('Lay out the original sale document, later purchase invoices and service records in date order. For each one, ask what it actually establishes: the original delivery, a change of owner, work performed, or a warranty starting after that work. A service invoice that lists a replacement dial explains a change; a warranty card on its own does not explain the watch’s subsequent life. Missing years are not proof of a problem, but they remain gaps rather than a documented continuous history.', 'Ordnen Sie Erstverkaufsunterlagen, spätere Kaufrechnungen und Servicebelege zeitlich. Fragen Sie jeweils, was belegt wird: Auslieferung, Eigentümerwechsel, ausgeführte Arbeiten oder eine daran anknüpfende Garantie. Eine Servicerechnung mit Zifferblattersatz erklärt eine Veränderung; eine Garantiekarte allein erklärt das spätere Leben der Uhr nicht. Fehlende Jahre beweisen keinen Mangel, bleiben aber Lücken und sind keine lückenlose Historie.'),
      b('If one offer includes a box and another includes a recent detailed movement service, do not treat both additions as equivalent “extras”. The box helps complete the presentation; the invoice can clarify work and replacement parts. Decide whether you are buying a period-correct collecting set or a well-documented watch to wear. Keep copies of the listing and the agreed contents with your invoice so that the next owner can understand the same distinctions.', 'Enthält ein Angebot eine Box und ein anderes einen aktuellen detaillierten Werkservice, sind das keine gleichwertigen „Extras“. Die Box vervollständigt die Präsentation, die Rechnung kann Arbeiten und Ersatzteile erklären. Entscheiden Sie zwischen zeitgenössisch vollständigem Sammlerset und gut dokumentierter Trageuhr. Bewahren Sie Angebot und vereinbarten Lieferumfang zusammen mit Ihrer Rechnung auf, damit auch ein späterer Besitzer diese Unterschiede nachvollziehen kann.'),
    ]),
  ],
  archives: [
    section('archive-versus-inspection', b('Three questions an archive cannot answer alone', 'Drei Fragen, die ein Archiv allein nicht beantwortet'), [
      b('First, is the watch offered today the same configuration described in the record? Compare the reference, material and dial description with the actual object. Second, what happened after the original sale? A later dial, replacement crown or bracelet may require separate service evidence. Third, how is the movement performing now? An archive entry records history, not the present condition of lubrication, bearings or calendar mechanisms. These questions need different evidence, even when the extract itself is genuine.', 'Erstens: Entspricht die heute angebotene Uhr der dokumentierten Konfiguration? Vergleichen Sie Referenz, Material und Zifferblattbeschreibung mit dem Gegenstand. Zweitens: Was geschah nach dem Erstverkauf? Ein späteres Zifferblatt, eine andere Krone oder ein Bandwechsel benötigen gegebenenfalls eigene Servicebelege. Drittens: Wie arbeitet das Werk heute? Ein Archiveintrag dokumentiert Geschichte, nicht den aktuellen Zustand von Schmierung, Lagern oder Kalendermechanik. Auch ein echter Auszug beantwortet diese Fragen nicht allein.'),
      b('Consider a watch whose extract describes a light dial while the listing shows a dark one. That difference does not establish a diagnosis from photographs: it could involve a documented change, an incorrect listing or an issue needing specialist investigation. Ask for an explanation before treating the document as reassurance. If the seller cannot reconcile the difference, pause the purchase rather than using the extract’s presence to dismiss it.', 'Angenommen, der Auszug beschreibt ein helles Zifferblatt, während das Angebot ein dunkles zeigt. Fotos allein erlauben keine Diagnose: Möglich sind ein belegter Austausch, ein falsches Angebot oder ein fachlich zu klärender Sachverhalt. Lassen Sie sich die Abweichung erklären, bevor Sie den Auszug als Absicherung betrachten. Kann der Verkäufer sie nicht nachvollziehbar auflösen, sollten Sie den Kauf zurückstellen.'),
    ]),
  ],
  price: [
    section('normalise-offers', b('Turn asking prices into a useful shortlist', 'Aus Angebotspreisen eine brauchbare Auswahl machen'), [
      b('Build a small comparison sheet with one row per actual watch. Record the full reference, dial, metal, bracelet length, accessories, service evidence, visible wear and delivered price. Do not average a steel time-only model with a precious-metal chronograph simply because the collection name matches. Remove offers with unclear specifications from the comparison until the missing details are supplied. A remarkably low price is a reason to investigate the difference, not evidence that every higher-priced example is poor value.', 'Erstellen Sie eine kleine Vergleichsliste mit einer Zeile je konkreter Uhr. Notieren Sie Referenz, Zifferblatt, Metall, Bandlänge, Zubehör, Servicebelege, sichtbare Spuren und Gesamtpreis mit Lieferung. Eine Dreizeiger-Stahluhr und ein Edelmetallchronograph ergeben keinen sinnvollen Durchschnitt, nur weil der Kollektionsname gleich ist. Unklare Angebote bleiben bis zur Klärung außerhalb des Vergleichs. Ein auffällig niedriger Preis ist ein Anlass zur Prüfung, kein Beweis gegen teurere Exemplare.'),
      b('Then separate purchase cost from ownership cost. Missing links, an incorrect buckle, immediate service or specialist transport can change which offer is attractive. Use written quotations where possible; an arbitrary service allowance can hide rather than resolve uncertainty. If two examples remain close, prioritise the configuration you want and the evidence you can verify. A watch is not necessarily cheap because its asking price is below a different seller’s uncompleted listing.', 'Trennen Sie danach Kauf- und Folgekosten. Fehlende Glieder, eine falsche Schließe, sofortiger Service oder Spezialtransport verändern den Vergleich. Nutzen Sie möglichst schriftliche Kostenvoranschläge; ein willkürlicher Servicepuffer kann Unsicherheit verdecken. Liegen zwei Angebote weiterhin nahe beieinander, priorisieren Sie gewünschte Ausführung und überprüfbare Belege. Eine Uhr ist nicht zwangsläufig günstig, weil ihr Preis unter einem noch unverkauften Vergleichsangebot liegt.'),
    ]),
  ],
  exceptional: [
    section('complexity-versus-collectability', b('Technical complexity and collectability are different', 'Technische Komplexität und Sammelwert unterscheiden'), [
      b('A complicated movement and a highly sought-after design can command attention for different reasons. A calendar organises information about the date; a chronograph adds interval timing; a striking mechanism makes time audible. Their appeal lies partly in what the mechanism does and how it is executed. A time-only Royal Oak may instead attract a buyer through proportions, bracelet construction or a particular historical configuration. Counting complications does not produce a reliable ranking of prices or desirability.', 'Ein kompliziertes Werk und ein stark gesuchtes Design können aus verschiedenen Gründen begehrt sein. Ein Kalender ordnet Datumsinformationen, ein Chronograph misst Zeitabschnitte, ein Schlagwerk macht die Zeit hörbar. Ihr Reiz liegt unter anderem in Funktion und Ausführung. Eine Royal Oak ohne Zusatzfunktion kann dagegen durch Proportionen, Bandkonstruktion oder historische Ausführung interessieren. Das Zählen von Komplikationen ergibt keine verlässliche Preis- oder Begehrlichkeitsrangfolge.'),
      b('For an exceptional piece, the sale file should become more detailed, not less. Ask what supports a production-number claim, who assessed the mechanism and which functions were demonstrated. Distinguish the hammer price of an auction from the buyer’s total including premium and applicable charges. A charity sale, celebrity association or unique commission may explain one transaction without providing a repeatable benchmark for the watch you are considering.', 'Bei einem außergewöhnlichen Stück sollte die Dokumentation ausführlicher werden, nicht knapper. Fragen Sie nach Belegen für Stückzahlangaben, Prüfer und vorgeführten Funktionen. Trennen Sie Auktionszuschlag und tatsächlichen Käufergesamtpreis einschließlich Aufgeld und weiterer Kosten. Wohltätigkeitsverkauf, prominente Herkunft oder Einzelauftrag können eine Transaktion erklären, ohne einen übertragbaren Maßstab für Ihre Wunschuhr zu liefern.'),
    ]),
  ],
  vintage: [
    section('conservation-decisions', b('Decide what you want to preserve', 'Entscheiden, was erhalten bleiben soll'), [
      b('Vintage buying involves two separate judgements: whether you like the watch now, and whether its components and finish are appropriate for the version being described. A refinished dial can look attractive yet matter differently to a collector than to a daily wearer. A replacement crystal may improve usability without making the dial original. Ask the seller to describe each known intervention rather than using “restored” or “original” as a single label for the whole object.', 'Beim Vintage-Kauf sind zwei Urteile zu trennen: Gefällt Ihnen die Uhr heute, und passen Teile sowie Finish zur beschriebenen Ausführung? Ein restauriertes Zifferblatt kann attraktiv aussehen und für Sammler anders zählen als für Alltagsträger. Ein Ersatzglas kann die Nutzbarkeit verbessern, macht aber das Zifferblatt nicht original. Lassen Sie bekannte Eingriffe einzeln beschreiben, statt die gesamte Uhr pauschal als „restauriert“ oder „original“ einzustufen.'),
      b('Before commissioning work, agree on priorities with the watchmaker. Mechanical reliability, keeping an existing dial, retaining case geometry and achieving a cosmetically fresh appearance are not always the same project. Request approval before visible parts are replaced or surfaces refinished. Keep the proposal, final invoice and photographs together. That record is useful even if you never sell: it explains what was changed and gives the next service provider a clearer starting point.', 'Vereinbaren Sie vor Arbeiten die Prioritäten mit dem Uhrmacher. Technische Zuverlässigkeit, Zifferblatterhalt, Gehäusekonturen und eine neuwertige Optik sind nicht immer dasselbe Vorhaben. Verlangen Sie Rücksprache vor sichtbarem Teiletausch oder Aufarbeitung. Bewahren Sie Vorschlag, Abschlussrechnung und Fotos gemeinsam auf. Das hilft auch ohne Verkaufsabsicht, denn es erklärt Veränderungen und erleichtert dem nächsten Servicebetrieb die Einschätzung.'),
    ]),
  ],
  maintenance: [
    section('service-scope', b('Inspection, regulation and overhaul are not the same job', 'Prüfung, Regulierung und Revision sind verschiedene Arbeiten'), [
      b('An inspection establishes findings; regulation aims to adjust the rate of a movement whose condition permits it; an overhaul involves a broader intervention. A pressure test answers a sealing question, not whether the movement has been serviced. Ask the provider to specify the scope rather than comparing quotations by the word “service” alone. Cosmetic polishing should also be a separate decision, especially where sharp case transitions or period surfaces are important to you.', 'Eine Prüfung ermittelt Befunde, eine Regulierung korrigiert den Gang eines dafür geeigneten Werks, eine Revision greift umfassender ein. Eine Druckprüfung beantwortet die Dichtigkeitsfrage, nicht die Frage nach einer Werkrevision. Lassen Sie den Umfang präzisieren, statt Angebote allein nach dem Wort „Service“ zu vergleichen. Auch Polieren ist eine eigene Entscheidung, besonders wenn klare Gehäuseübergänge oder historische Oberflächen wichtig sind.'),
      b('Give the watchmaker a useful symptom history: when a change started, whether the watch stops after a predictable period and whether there was an impact or water exposure. Do not repeatedly wind or operate a watch that feels abnormal to prove a fault. After work, retain the test results and instructions as well as the invoice. These help you distinguish a new problem from an old one and make the next maintenance decision less dependent on memory.', 'Beschreiben Sie dem Uhrmacher den Verlauf: Seit wann besteht die Veränderung, bleibt die Uhr nach bestimmter Laufzeit stehen, gab es einen Stoß oder Wasserkontakt? Eine auffällige Uhr sollte nicht wiederholt aufgezogen oder bedient werden, nur um den Fehler zu beweisen. Bewahren Sie nach der Arbeit neben der Rechnung Prüfwerte und Hinweise auf. So lassen sich neue von früheren Problemen unterscheiden und spätere Entscheidungen besser begründen.'),
    ]),
  ],
  rolexMechanics: [
    section('movement-and-case', b('Follow the energy before comparing the labels', 'Vor dem Siegelvergleich den Energiefluss verstehen'), [
      b('In a mechanical watch, winding stores energy in the mainspring. A train of wheels carries that energy to the hands, while the escapement and oscillator control its release. Automatic winding describes how energy is replenished; chronometer testing describes measured performance. Water resistance concerns the case and seals. These are related parts of a complete watch, but none is a substitute for the others. An automatically wound watch can still need winding after storage, and good timekeeping does not prove that a case is watertight.', 'Bei einer mechanischen Uhr speichert der Aufzug Energie in der Zugfeder. Das Räderwerk überträgt sie auf die Zeiger, Hemmung und Schwinger steuern die Abgabe. Automatik beschreibt die Energiezufuhr, Chronometerprüfung die gemessene Leistung, Wasserdichtigkeit dagegen Gehäuse und Dichtungen. Diese Eigenschaften gehören zur Uhr, ersetzen einander aber nicht. Nach Lagerung kann auch eine Automatikuhr Aufzug benötigen, und guter Gang beweist kein dichtes Gehäuse.'),
      b('For a pre-owned example, ask for observations under stated conditions rather than an unsupported “keeps perfect time”. A useful report identifies the watch, test date and what was measured. A short timegrapher snapshot, the owner’s wrist observation and a complete manufacturer test are different kinds of evidence. Discuss an unexplained change in behaviour with a qualified watchmaker before assuming that a familiar movement name makes further checks unnecessary.', 'Fragen Sie beim Gebrauchtkauf nach Beobachtungen unter benannten Bedingungen statt nach pauschal „perfektem Gang“. Ein brauchbarer Bericht nennt Uhr, Prüfdatum und Messung. Eine kurze Zeitwaagenaufnahme, die Tragebeobachtung des Besitzers und eine umfassende Herstellerprüfung sind unterschiedliche Belege. Klären Sie unerklärliche Veränderungen fachkundig, statt weitere Prüfungen wegen eines bekannten Kalibernamens für unnötig zu halten.'),
    ]),
  ],
  patekMechanics: [
    section('calendar-differences', b('Date, annual calendar and perpetual calendar', 'Datum, Jahreskalender und ewiger Kalender'), [
      b('A basic date display normally counts through 31 dates, so shorter months require correction. Patek Philippe’s Annual Calendar, introduced in 1996, distinguishes 30- and 31-day months but still needs its scheduled correction at the end of February. A perpetual calendar also accounts for February and the leap-year cycle within the limits of its mechanism. These distinctions describe calendar logic, not how difficult a specific watch is to set. A stopped calendar still needs to be brought back to the correct indications using its own instructions.', 'Eine einfache Datumsanzeige zählt normalerweise bis 31 und benötigt bei kürzeren Monaten Korrektur. Patek Philippes 1996 eingeführter Jahreskalender unterscheidet 30 und 31 Tage, muss aber am Februarende korrigiert werden. Ein ewiger Kalender berücksichtigt innerhalb seiner konstruktiven Grenzen auch Februar und Schaltjahre. Das beschreibt Kalenderlogik, nicht die Bedienungsschwierigkeit einer bestimmten Uhr. Ein stehengebliebener Kalender muss nach seiner eigenen Anleitung wieder richtig eingestellt werden.'),
      b('For example, if you rotate several watches and often let them stop, compare the practical reset procedure before paying for a more elaborate calendar. If you wear the same watch continuously, the reduction in routine month-end correction may be more relevant. Choose with an understanding of that routine rather than assuming that “perpetual” means the owner will never need to make an adjustment.', 'Wechseln Sie häufig zwischen Uhren, die dabei stehen bleiben, vergleichen Sie zuerst das praktische Neueinstellen. Tragen Sie dieselbe Uhr kontinuierlich, ist weniger Korrektur am Monatsende möglicherweise wichtiger. „Ewig“ bedeutet nicht, dass ein Besitzer niemals mehr etwas einstellen muss; entscheiden Sie anhand Ihrer tatsächlichen Routine.'),
    ], ['patekCalendars']),
    section('living-with-complications', b('Choose the complication you want to live with', 'Die Komplikation wählen, mit der Sie leben möchten'), [
      b('A simple time display, an annual calendar and a perpetual calendar create different relationships with the owner. More calendar information means more to understand when setting a stopped watch. Before choosing, consider whether the watch will be worn daily or rotated with several others, whether you enjoy resetting a calendar and whether you can access the correct instructions. A more elaborate movement is not automatically a better first Patek Philippe if its routine makes you less likely to wear it.', 'Eine reine Zeitanzeige, ein Jahreskalender und ein ewiger Kalender stellen unterschiedliche Anforderungen. Mehr Kalenderinformationen bedeuten auch mehr Wissen beim Einstellen einer stehengebliebenen Uhr. Überlegen Sie, ob Sie täglich oder im Wechsel tragen, Kalenderkorrekturen gern vornehmen und die richtige Anleitung verfügbar ist. Ein aufwendigeres Werk ist nicht automatisch die bessere erste Patek Philippe, wenn seine Bedienung vom Tragen abhält.'),
      b('Condition assessment should match the complication. A photograph can show a displayed date but not prove that every calendar transition works. A running balance visible through a caseback does not test the winding system or all correctors. Request a calibre-specific demonstration and an assessment of required work. Keep movement finishing, functional health and the originality of external parts as separate questions: each contributes something different to a well-informed purchase.', 'Die Zustandsprüfung muss zur Komplikation passen. Ein Foto zeigt ein Datum, beweist aber nicht sämtliche Kalenderwechsel. Eine sichtbare laufende Unruh prüft weder Aufzug noch alle Korrektoren. Verlangen Sie eine kaliberspezifische Vorführung und Einschätzung erforderlicher Arbeiten. Trennen Sie Werkfinish, Funktionszustand und Originalität äußerer Teile; jede Frage trägt etwas Eigenes zu einer fundierten Entscheidung bei.'),
    ]),
  ],
  metas: [
    section('testing-sequence', b('Movement certification and complete-watch testing', 'Werkzertifizierung und Prüfung der vollständigen Uhr'), [
      b('The distinction matters because a movement does not operate in isolation once it is inside a case. The METAS framework includes checks concerning precision, magnetic fields, water resistance and power reserve for the assembled watch. It is not merely a different word for a conventional chronometer certificate. When comparing two listings, identify which claim each actually makes and whether the reference is covered; an older watch should not acquire a later standard just because its current collection uses that terminology.', 'Ein Werk arbeitet nach dem Einschalen nicht mehr isoliert. Der METAS-Rahmen umfasst Prüfungen zu Präzision, Magnetfeldern, Wasserdichtigkeit und Gangreserve an der vollständigen Uhr. Er ist deshalb nicht bloß ein anderes Wort für ein herkömmliches Chronometerzertifikat. Prüfen Sie bei zwei Angeboten, welche Aussage jeweils gemacht wird und ob die Referenz darunter fällt. Eine ältere Uhr übernimmt einen späteren Standard nicht durch den aktuellen Namen ihrer Kollektion.'),
      b('For the owner, certification is a useful baseline, not a permanent condition report. Years of use, accidental damage and subsequent repairs still need their own assessment. If a seller supplies test information, match it to the watch rather than accepting a general promotional certificate. Decide whether the tested capabilities solve a real need in your life, then assess fit, readability and service history alongside them. A technically impressive specification cannot make an uncomfortable watch enjoyable.', 'Für Besitzer ist die Zertifizierung eine nützliche Ausgangsbasis, kein dauerhafter Zustandsbericht. Nutzung, Schäden und spätere Reparaturen müssen gesondert beurteilt werden. Ordnen Sie vorgelegte Prüfinformationen der Uhr zu, statt ein allgemeines Werbezertifikat zu akzeptieren. Überlegen Sie, ob die Fähigkeiten für Sie relevant sind, und bewerten Sie daneben Sitz, Ablesbarkeit und Service. Eine eindrucksvolle Spezifikation macht eine unbequeme Uhr nicht angenehm.'),
    ], ['metas', 'metasStandard']),
  ],
  coaxial: [
    section('what-the-escapement-does', b('What changes—and what does not', 'Was sich ändert – und was nicht'), [
      b('The word escapement describes the point where stored energy is released in controlled steps and the oscillator receives the impulse that keeps it moving. It is one part of the movement, not the whole movement. This is why two Co-Axial watches can differ in size, reserve, date adjustment and chronograph operation. Buyers gain more from identifying the calibre than from treating the dial wording as a complete specification or as a promise that every generation behaves identically.', 'Die Hemmung ist die Stelle, an der gespeicherte Energie kontrolliert freigegeben wird und der Schwinger seinen Antriebsimpuls erhält. Sie ist ein Bestandteil, nicht das gesamte Uhrwerk. Deshalb können zwei Co-Axial-Uhren bei Größe, Reserve, Datumskorrektur und Chronographenbedienung verschieden sein. Käufer profitieren stärker von der Kaliberidentifikation als davon, die Zifferblattaufschrift als vollständiges Datenblatt oder Gleichheitsversprechen aller Generationen zu verstehen.'),
      b('A useful comparison starts with how you use the watch. If it rotates with other watches, check reserve and setting convenience. If you want a chronograph, confirm the actual pusher sequence. If magnetic resistance matters, consult the reference-specific certification and instructions. A service invoice should identify the movement work carried out; merely repeating “Co-Axial serviced” is less informative than listing the work and subsequent tests. The technology and the condition of the individual example deserve equal attention.', 'Beginnen Sie den Vergleich mit Ihrer Nutzung. Beim Wechsel mit anderen Uhren zählen Reserve und einfaches Einstellen. Für einen Chronographen ist die konkrete Bedienfolge wichtig. Bei Magnetfeldschutz helfen referenzbezogene Zertifizierung und Anleitung. Eine Servicerechnung sollte die ausgeführten Werkarbeiten nennen; „Co-Axial gewartet“ sagt weniger aus als Umfang und anschließende Prüfungen. Technologie und Zustand des einzelnen Exemplars verdienen gleichermaßen Aufmerksamkeit.'),
    ]),
  ],
  speedSeamaster: [
    section('two-wearing-scenarios', b('Two everyday scenarios', 'Zwei Alltagssituationen'), [
      b('If you enjoy timing a journey or an activity and want the interaction of starting, stopping and reading a chronograph, begin with a Speedmaster reference whose display you can read easily. Then decide whether manual winding is part of the pleasure or an unwanted routine. The classic Moonwatch idea should not stop you comparing other Speedmasters if a different size or winding arrangement suits you better. Check which hand displays ordinary seconds and which one records the timed interval.', 'Wenn Sie Fahrten oder Aktivitäten stoppen und Starten, Anhalten und Ablesen eines Chronographen mögen, beginnen Sie mit einer gut lesbaren Speedmaster-Referenz. Entscheiden Sie danach, ob Handaufzug Freude oder unerwünschte Routine ist. Die klassische Moonwatch-Idee sollte andere Speedmaster-Varianten nicht ausschließen, wenn Größe oder Aufzug besser passen. Klären Sie, welcher Zeiger die normale Sekunde und welcher die gestoppte Zeit anzeigt.'),
      b('If your priority is a watch that moves easily between work, travel and time near water, start by separating the Seamaster families. A prominent rotating bezel and a thicker case create a different presence from an Aqua Terra’s less overtly diving-oriented design. Try a sleeve over the watch and consider how the bracelet adjusts when your wrist changes through the day. The right answer may be a quieter Seamaster rather than the most technically imposing diver—or a Speedmaster when water use is not your priority.', 'Soll die Uhr Büro, Reise und Zeit am Wasser begleiten, unterscheiden Sie zuerst die Seamaster-Familien. Eine markante Drehlünette und ein höheres Gehäuse wirken anders als die weniger tauchbetonte Aqua Terra. Prüfen Sie den Sitz unter einem Ärmel und die Bandanpassung im Tagesverlauf. Die passende Wahl kann eine ruhigere Seamaster statt des technisch eindrucksvollsten Tauchermodells sein – oder eine Speedmaster, wenn Wassernutzung keine Priorität hat.'),
    ]),
  ],
  springDrive: [
    section('regulation-explained', b('Why the seconds hand glides', 'Warum der Sekundenzeiger gleitet'), [
      b('In Spring Drive, the mainspring drives a glide wheel that generates the small amount of electricity needed by the regulating circuit. A quartz reference and electronic control govern an electromagnetic brake. Instead of the stop-and-release action of a conventional escapement, the system controls the speed of a continuously rotating train. That explains why the visual result is a glide rather than an ordinary mechanical sweep. It also explains why calling the watch either “just quartz” or wholly conventional mechanical misses something important.', 'Bei Spring Drive treibt die Zugfeder ein Gleitrad an, das den geringen Strom für die Regelung erzeugt. Quarzreferenz und Elektronik steuern eine elektromagnetische Bremse. Statt des wechselnden Anhaltens und Freigebens einer herkömmlichen Hemmung wird die Geschwindigkeit einer kontinuierlichen Drehbewegung geregelt. Daraus entsteht das Gleiten des Zeigers. „Nur Quarz“ und „rein konventionell mechanisch“ lassen deshalb jeweils einen wichtigen Teil des Konzepts aus.'),
      b('The practical choice is about what you value. Someone who enjoys a traditional escapement may prefer a different movement despite Spring Drive’s appeal; someone who appreciates controlled timekeeping and the gliding display may welcome the combination. Compare the actual calibre’s reserve and winding method. The 9R65 in the SBGA211 and SBGA413 is a useful starting example, not a specification for every later Spring Drive. When buying used, ask how the reserve was checked and keep the relevant operating instructions.', 'Die praktische Wahl hängt von Ihren Vorlieben ab. Wer eine traditionelle Hemmung schätzt, bevorzugt womöglich bewusst ein anderes Werk; wer geregelten Gang und gleitende Anzeige mag, findet gerade die Verbindung reizvoll. Vergleichen Sie Reserve und Aufzug des Kalibers. Das 9R65 in SBGA211 und SBGA413 ist ein hilfreiches Beispiel, kein Datenblatt jeder späteren Spring Drive. Fragen Sie beim Gebrauchtkauf nach der Reserveprüfung und bewahren Sie die passende Anleitung auf.'),
    ], ['gs', 'snowflake', 'shunbun']),
  ],
  snowflakeShunbun: [
    section('fit-beyond-diameter', b('The fit difference is larger than the headline suggests', 'Die Passform sagt mehr als der Durchmesser'), [
      b('The SBGA211 measures 49 mm from lug to lug, against 47 mm for the SBGA413; the stated heights are 12.5 mm and 12.8 mm respectively. The smaller-diameter Shunbun is therefore not the thinner of this pair. Consider those dimensions together with where your wrist begins to curve downwards. A watch whose lugs project past the usable top surface of your wrist can feel less settled even if its diameter sounds modest.', 'Die SBGA211 misst 49 mm über die Hörner, die SBGA413 47 mm; die angegebenen Höhen betragen 12,5 beziehungsweise 12,8 mm. Die kleinere Shunbun ist in diesem Paar also nicht die flachere Uhr. Betrachten Sie diese Maße zusammen mit der Wölbung Ihres Handgelenks. Reichen die Hörner über dessen obere Auflagefläche hinaus, kann die Uhr trotz moderatem Durchmesser weniger ruhig sitzen.'),
      b('The dial comparison also deserves more than a colour preference. Ask for the same watch photographed in neutral light, at an angle and at normal wrist distance. This shows how the texture interacts with the hands and markers rather than only how dramatic it looks in a close-up. For a first purchase, try to resolve case fit before selecting by a favourite dial photograph. For an additional watch, consider whether the white Snowflake or pink-toned Shunbun adds the contrast you actually want in your collection.', 'Auch das Zifferblatt verdient mehr als eine Farbentscheidung. Bitten Sie um Fotos derselben Uhr bei neutralem Licht, schräg und aus normalem Handgelenkabstand. So zeigt sich das Zusammenspiel von Struktur, Zeigern und Indizes statt nur eine dramatische Nahaufnahme. Klären Sie bei der ersten Uhr die Gehäusepassform vor der Wahl nach Lieblingsfoto. Bei einer Ergänzung zählt, ob die weiße Snowflake oder rosafarbene Shunbun den gewünschten Kontrast schafft.'),
    ], ['snowflake', 'shunbun']),
  ],
  iwcAutomatic: [
    section('winding-and-reserve', b('Reserve is not the same as winding efficiency', 'Gangreserve ist nicht Aufzugseffizienz'), [
      b('Power reserve describes how long a suitably wound watch is intended to run without more energy being added. Automatic winding efficiency concerns how wearing activity replenishes that energy. A long-reserve watch can still stop if it begins nearly empty and is worn only briefly. Before concluding that it has a fault, use the correct manual to establish the intended starting procedure; before concluding that it is healthy, obtain a proper assessment if the behaviour remains unexplained.', 'Gangreserve bezeichnet die vorgesehene Laufzeit einer ausreichend aufgezogenen Uhr ohne weitere Energiezufuhr. Aufzugseffizienz betrifft dagegen, wie gut Tragebewegung Energie nachliefert. Auch eine Uhr mit langer Reserve kann stehen bleiben, wenn sie fast leer startet und nur kurz getragen wird. Klären Sie zuerst anhand der Anleitung den vorgesehenen Start. Bleibt das Verhalten unerklärt, ersetzt diese Überlegung keine fachkundige Zustandsprüfung.'),
      b('IWC’s Pellaton system is a specific solution within the larger subject of automatic winding. It uses the rotor’s movement in both directions to contribute to winding. That history is interesting, but it does not make the word automatic sufficient identification for a listing. Record the IW reference and movement number, then compare reserve, calendar operation and maintenance evidence. For someone who alternates watches weekly, convenient restarting may be more useful than owning the movement with the longest headline reserve.', 'IWCs Pellaton-System ist eine besondere Lösung innerhalb automatischer Aufzüge. Es nutzt Rotorbewegungen in beiden Richtungen für den Aufzug. Diese Geschichte ist interessant, doch „Automatik“ identifiziert ein Angebot nicht ausreichend. Halten Sie IW-Referenz und Kaliber fest und vergleichen Sie Reserve, Kalenderbedienung und Wartungsbelege. Wer wöchentlich Uhren wechselt, profitiert möglicherweise stärker vom einfachen Neustart als von der längsten beworbenen Reserve.'),
    ], ['iwcAutomatic']),
  ],
  pilot: [
    section('instrument-at-wrist-distance', b('Read the dial at wrist distance', 'Das Zifferblatt aus normalem Abstand lesen'), [
      b('A pilot-style watch is easiest to compare when you look at it as an instrument, not an enlarged catalogue image. Can you distinguish the hour and minute hands immediately? Do the chronograph counters distract from the time you read most often? Does the crown press into your wrist when you bend it? Try these questions with the watch sitting naturally rather than held upright for a photograph. Greater diameter can improve the display while increasing leverage and crown contact.', 'Eine Fliegeruhr lässt sich besser als Instrument beurteilen denn als vergrößertes Katalogbild. Unterscheiden Sie Stunden- und Minutenzeiger sofort? Lenken Hilfszifferblätter von der meistgelesenen Uhrzeit ab? Drückt die Krone beim Abwinkeln? Prüfen Sie das in natürlicher Trageposition statt mit aufgerichteter Uhr fürs Foto. Mehr Durchmesser kann die Anzeige verbessern und gleichzeitig Hebelwirkung oder Kronenkontakt verstärken.'),
      b('The Pilot’s Watch story provides context, but present-day wearing needs should settle the purchase. A simple display can be a strong choice for someone who already uses a phone for travel calculations. A chronograph makes sense when you enjoy the function and accept the extra controls. Pay equal attention to strap length and buckle placement: a comfortable case can become awkward when a stiff or incorrectly sized strap prevents it from sitting centrally.', 'Die Fliegeruhrengeschichte liefert Kontext; entscheiden sollten heutige Tragebedürfnisse. Eine einfache Anzeige passt gut, wenn Reiseberechnungen ohnehin über das Telefon laufen. Ein Chronograph ist sinnvoll, wenn Sie die Funktion und zusätzliche Bedienung mögen. Achten Sie ebenso auf Bandlänge und Schließenposition: Selbst ein passendes Gehäuse sitzt schlecht, wenn ein steifes oder falsch dimensioniertes Band es aus der Mitte zieht.'),
    ]),
  ],
  ingenieur: [
    section('modern-reference-example', b('A modern reference: IW328902', 'Ein modernes Beispiel: IW328902'), [
      b('IWC lists the Ingenieur Automatic 40 IW328902 with a 40 mm steel case, 10.7 mm height and automatic calibre 32111 with a stated 120-hour reserve. Those figures make a useful reference point for comparing a listing; they are not specifications for every Ingenieur. In particular, a seller using “Ingenieur 40 mm” has not yet established which generation you are looking at. Match the complete IW number before borrowing dimensions or movement claims.', 'IWC führt die Ingenieur Automatic 40 IW328902 mit 40-mm-Stahlgehäuse, 10,7 mm Höhe und automatischem Kaliber 32111 mit angegebenen 120 Stunden Reserve. Diese Daten helfen beim Angebotsvergleich, gelten aber nicht für jede Ingenieur. „Ingenieur 40 mm“ identifiziert noch keine Generation. Gleichen Sie die vollständige IW-Nummer ab, bevor Maße oder Werkangaben übernommen werden.'),
      b('A long reserve can be convenient when you leave a sufficiently wound watch off the wrist for several days. It does not tell you whether the bracelet fits, whether the case has been heavily refinished or whether a used movement reaches the stated reserve today. Compare the specification first, then the individual watch’s evidence. Both are necessary for a sound purchase.', 'Eine lange Reserve ist praktisch, wenn eine ausreichend aufgezogene Uhr mehrere Tage abgelegt wird. Sie verrät weder Bandsitz noch starke Aufarbeitung oder die heutige Laufzeit eines gebrauchten Werks. Vergleichen Sie zuerst die Spezifikation und anschließend die Belege des Exemplars. Beides ist für den Kauf notwendig.'),
    ], ['iwc328902']),
    section('bracelet-as-architecture', b('The bracelet is part of the case design', 'Das Band ist Teil der Gehäusegestaltung'), [
      b('With an integrated-bracelet watch, the first links contribute to the shape resting on your wrist. Two examples of similar diameter can feel different if those links fall differently. Ask for a side photograph showing the bracelet’s first bend, not only the dial. Then check whether the bracelet can be sized to your wrist without putting the clasp off-centre. Replacing a conventional leather strap is not the same problem as sourcing the correct links or components for an older Ingenieur.', 'Bei einer Uhr mit integriertem Band bestimmen die ersten Glieder die Auflageform mit. Ähnliche Durchmesser können sich verschieden tragen, wenn diese Glieder anders abfallen. Fordern Sie ein Seitenfoto mit dem ersten Bandknick an, nicht nur das Zifferblatt. Prüfen Sie anschließend, ob die passende Länge ohne versetzte Schließe erreichbar ist. Ein normales Lederband zu wechseln ist etwas anderes, als korrekte Glieder einer älteren Ingenieur zu beschaffen.'),
      b('The historical reference 1832 is useful because it identifies Genta’s Ingenieur SL chapter, not because every watch carrying the Ingenieur name shares its case or movement. For a later reinterpretation, compare which visual elements you like and what changed in proportions. For an earlier example, prioritise condition and configuration evidence. An attractive association with a designer cannot resolve an over-refinished case, incomplete bracelet or ambiguous description.', 'Die historische Referenz 1832 identifiziert Gentas Ingenieur-SL-Kapitel, bedeutet aber keine identischen Gehäuse oder Werke aller Ingenieur-Uhren. Vergleichen Sie bei späteren Neuinterpretationen die gewünschten Gestaltungselemente und veränderten Proportionen. Bei früheren Exemplaren zählen Zustand und Konfigurationsbelege. Ein reizvoller Designerbezug klärt weder ein stark aufgearbeitetes Gehäuse noch ein unvollständiges Band oder eine ungenaue Beschreibung.'),
    ], ['iwcGenta']),
  ],
  duoface: [
    section('two-time-zones-in-use', b('Think through one actual journey', 'Eine konkrete Reise durchspielen'), [
      b('Imagine leaving home, changing time zone and attending an evening event. Which display would you keep as home time, and which would you want to read during the day? Would you enjoy reversing the case to change the visual character, or prefer both times on one visible dial? Those questions distinguish the Duoface experience from a conventional GMT watch more clearly than a list of complications. The appeal is the interaction of two faces, not merely an additional hour indication.', 'Stellen Sie sich Abreise, Zeitzonenwechsel und eine Abendveranstaltung vor. Welche Seite soll die Heimatzeit behalten, welche lesen Sie tagsüber? Möchten Sie durch Wenden auch den Stil wechseln, oder beide Zeiten gleichzeitig auf einem Zifferblatt sehen? Das unterscheidet das Duoface-Erlebnis klarer von einer üblichen GMT-Uhr als eine Komplikationsliste. Der Reiz liegt im Zusammenspiel zweier Seiten, nicht nur in einer zusätzlichen Stundenanzeige.'),
      b('Reference Q3918420, for example, is a Reverso Tribute Duoface Calendar; its calendar is part of that particular configuration, not a feature to assume on every Duoface. When comparing listings, make a separate line for each face’s displays and the method used to set them. Ask to see the reversing action with the strap fitted, and check whether the watch still sits comfortably when the other side faces upwards. Both faces should work as watches you want to wear.', 'Referenz Q3918420 ist beispielsweise eine Reverso Tribute Duoface Calendar. Ihr Kalender gehört zu dieser Ausführung und darf nicht jeder Duoface zugeschrieben werden. Notieren Sie beim Angebotsvergleich Anzeigen und Einstellverfahren beider Seiten getrennt. Lassen Sie das Wenden mit montiertem Band zeigen und prüfen Sie den Komfort auch mit der anderen Seite oben. Beide Seiten sollten Uhren ergeben, die Sie tatsächlich tragen möchten.'),
    ], ['jlc']),
  ],
  masterChronograph: [
    section('chronograph-reference-example', b('An example with more than a stopwatch: Q4138480', 'Mehr als eine Stoppfunktion: Q4138480'), [
      b('The Master Control Chronograph Calendar Q4138480 illustrates why the full reference matters. Jaeger-LeCoultre describes this model with automatic calibre 759, a chronograph, triple calendar and moon-phase display, with a stated 65-hour reserve. It is therefore a different ownership proposition from a simpler watch described loosely as “Master Chronograph”. The additional displays need to be included in the demonstration and service assessment, not treated as decorative details.', 'Die Master Control Chronograph Calendar Q4138480 zeigt den Nutzen der vollständigen Referenz. Jaeger-LeCoultre nennt Kaliber 759 mit Automatik, Chronograph, Vollkalender und Mondphase sowie 65 Stunden Reserve. Das ergibt andere Anforderungen als eine einfachere, pauschal „Master Chronograph“ genannte Uhr. Zusatzanzeigen gehören in Vorführung und Serviceprüfung statt als Dekoration behandelt zu werden.'),
      b('Use that example as a method, not a requirement to choose this particular watch: list every displayed function, find the matching instructions and compare how frequently you would use it. Do not describe a triple calendar as perpetual just because day, date and month are all visible. The information on the dial and the logic that advances it are separate specifications.', 'Nutzen Sie das Beispiel als Methode, nicht als Kaufvorgabe: Funktionen auflisten, Anleitung zuordnen und tatsächliche Nutzung vergleichen. Ein Vollkalender ist nicht allein deshalb ewig, weil Wochentag, Datum und Monat sichtbar sind. Sichtbare Informationen und die Logik ihrer Fortschaltung sind getrennte Spezifikationen.'),
    ], ['jlcChronograph']),
    section('read-the-counters', b('Understand what each display is doing', 'Die Aufgabe jeder Anzeige verstehen'), [
      b('Before comparing dial colours, identify normal seconds, chronograph seconds and the elapsed-minute or hour counters on the actual reference. A stopped central chronograph hand is not necessarily a stopped watch. Conversely, hands positioned neatly in a photograph do not prove that reset alignment is correct after use. Ask for a short start–stop–reset demonstration and an explanation of any additional calendar displays. This makes it easier to spot a listing that uses a broad collection label instead of describing the watch accurately.', 'Identifizieren Sie vor dem Farbvergleich normale Sekunde, Chronographensekunde sowie Minuten- oder Stundenzähler der Referenz. Ein stehender zentraler Stoppzeiger bedeutet nicht automatisch eine stehende Uhr. Umgekehrt beweisen ordentlich positionierte Fotozeiger keine korrekte Rückstellung nach Nutzung. Bitten Sie um eine kurze Start-Stopp-Nullstellungs-Vorführung und Erläuterung weiterer Kalenderanzeigen. So fallen ungenaue Kollektionsbezeichnungen leichter auf.'),
      b('For regular office wear, compare dial space and pusher projection with a simpler Master model before deciding that more information is preferable. For a collector who enjoys using a chronograph, tactile operation and legibility may justify the extra complexity. In both cases, ask whether the last service covered the chronograph as well as timekeeping. The relevant question is not only whether the watch runs, but whether every mechanism you are paying for works as intended.', 'Fürs Büro vergleichen Sie Zifferblattfläche und Drückerüberstand mit einem einfacheren Master-Modell, bevor mehr Information als besser gilt. Wer Chronographen gern benutzt, schätzt vielleicht gerade Bediengefühl und Messanzeige. Fragen Sie in beiden Fällen, ob der letzte Service auch den Chronographen statt nur den Gang umfasste. Entscheidend ist nicht allein, ob die Uhr läuft, sondern ob alle bezahlten Mechanismen bestimmungsgemäß arbeiten.'),
    ]),
  ],
  carreraFormula: [
    section('choose-a-movement-routine', b('Start with the routine, then choose the design', 'Zuerst die Nutzung, dann das Design wählen'), [
      b('For occasional wear, a quartz reference can offer an uncomplicated pick-up-and-wear routine, subject to battery condition and correct setting. A mechanical reference can appeal if winding, observing the movement and regular wear are part of what you enjoy. Do not let a general ranking of collection names override that preference. A chronograph adds another decision: whether you want to use the stopwatch or mostly like its dial arrangement. Compare those decisions before judging a Carrera against a Formula 1.', 'Bei gelegentlichem Tragen kann eine Quarzreferenz unkompliziert sein, vorausgesetzt Batterie und Einstellung stimmen. Mechanik passt, wenn Aufziehen, Werkbeobachtung und regelmäßiges Tragen zum Vergnügen gehören. Eine pauschale Rangfolge der Kollektionen sollte diese Vorliebe nicht verdrängen. Beim Chronographen kommt hinzu, ob Sie die Stoppfunktion nutzen oder vor allem die Zifferblattgestaltung mögen. Klären Sie das vor dem Vergleich Carrera gegen Formula 1.'),
      b('When you have selected two references, compare the quality of the actual offers: a complete bracelet, the correct clasp and evidence of functioning pushers matter more than a flattering photograph. For quartz, a dead battery explanation should be verified before purchase rather than priced as a guaranteed simple repair. For mechanical, request the service history rather than assuming that motion in a video establishes healthy reserve. Choose between specific watches, not between a convenient stereotype of two large families.', 'Vergleichen Sie bei zwei ausgewählten Referenzen die konkreten Angebote: vollständiges Band, richtige Schließe und funktionierende Drücker zählen mehr als ein schmeichelhaftes Foto. Bei Quarz sollte die Erklärung „leere Batterie“ vor dem Kauf geprüft werden, nicht als sicher einfache Reparatur gelten. Bei Mechanik ist die Servicehistorie wichtiger als bloße Bewegung im Video. Entscheiden Sie zwischen Uhren statt zwischen vereinfachten Bildern zweier großer Modellfamilien.'),
    ]),
  ],
  connected: [
    section('test-the-digital-watch', b('A useful pre-purchase test', 'Eine sinnvolle Prüfung vor dem Kauf'), [
      b('Ask the seller to demonstrate a full charge, successful pairing and the functions you expect to use on a compatible phone. Observe whether touch input, buttons and the screen respond consistently. A photograph of the time display proves very little about a connected watch’s battery or software state. Make sure the charger belongs to that generation rather than accepting a visually similar accessory. Confirm the supported reset and transfer process before handing over personal account details or treating a demonstration device as ready to use.', 'Lassen Sie vollständiges Laden, erfolgreiche Kopplung und gewünschte Funktionen mit einem kompatiblen Telefon zeigen. Prüfen Sie, ob Touchscreen, Tasten und Anzeige zuverlässig reagieren. Ein Foto der Uhrzeit sagt wenig über Akku oder Softwarezustand aus. Das Ladegerät muss zur Generation gehören, nicht nur ähnlich aussehen. Klären Sie Rücksetzen und Übergabe, bevor persönliche Kontodaten eingegeben werden oder ein Vorführgerät als sofort nutzbar gilt.'),
      b('Separate the value of the physical watch from your expectations of ongoing digital services. A preferred case size, strap and finish can remain attractive while apps, phone compatibility or software support change. Read the current manufacturer requirements and ask about available battery service. Buying used makes most sense when the present functions already meet your needs; it should not depend on an assumed future update, unlimited battery life or features belonging to a different Connected generation.', 'Trennen Sie den Wert der Uhr von Erwartungen an fortlaufende digitale Dienste. Größe, Band und Finish können attraktiv bleiben, während Apps, Telefonkompatibilität oder Softwareunterstützung wechseln. Lesen Sie aktuelle Herstelleranforderungen und fragen Sie nach Akkuservice. Ein Gebrauchtkauf sollte mit den heute nutzbaren Funktionen überzeugen, nicht von angenommenen künftigen Updates, unbegrenzter Akkulebensdauer oder Funktionen einer anderen Connected-Generation abhängen.'),
    ]),
  ],
  blackBay: [
    section('narrow-the-family', b('Choose the display before the colour', 'Vor der Farbe die Anzeige wählen'), [
      b('Make the first split by function: a relatively simple time display, a second-time-zone watch or a chronograph. Only then compare colour, bezel treatment and strap. A Black Bay GMT and a Black Bay Chrono may both be attractive, but they ask different things of the wearer and do different jobs. If you want the least visual interruption when reading the time, begin with a simpler dial. If you actively use an additional function, check that its display is readable at ordinary wrist distance.', 'Teilen Sie zuerst nach Funktion auf: eher einfache Zeitanzeige, zweite Zeitzone oder Chronograph. Danach folgen Farbe, Lünette und Band. Black Bay GMT und Black Bay Chrono können beide gefallen, erfüllen aber unterschiedliche Aufgaben. Für möglichst ungestörtes Zeitablesen beginnen Sie mit einem ruhigeren Zifferblatt. Nutzen Sie Zusatzfunktionen, prüfen Sie deren Lesbarkeit aus normalem Handgelenkabstand.'),
      b('Next compare generations within the shortlisted version. Do not merge seller descriptions just because the watches look similar: movement, clasp and case proportions need to be established separately. Ask for the full reference and photographs of the actual bracelet adjustment. If a watch comes with several straps, check which are included and whether the fitting components are present. A preferred colour is a poor trade for a watch that cannot be sized comfortably or whose condition remains unclear.', 'Vergleichen Sie anschließend Generationen der engeren Auswahl. Ähnliche Fotos rechtfertigen keine zusammengeführten Beschreibungen: Werk, Schließe und Proportionen sind separat zu ermitteln. Fordern Sie Referenz und Fotos der tatsächlichen Bandverstellung an. Bei mehreren Bändern sollten Lieferumfang und Befestigungsteile klar sein. Eine Lieblingsfarbe gleicht weder schlechte Anpassbarkeit noch ungeklärten Zustand aus.'),
    ]),
  ],
  blackBayPelagos: [
    section('comfort-and-attachment', b('What changes after the first five minutes?', 'Was zählt nach den ersten fünf Minuten?'), [
      b('The initial attraction may be a bezel colour or the look of a technical diver, but daily comfort comes from the whole assembly. Compare case material, total weight, where the clasp sits and how the bracelet moves at the first links. If you plan to alternate between bracelet and fabric strap, establish compatibility before choosing an FXD with fixed bars. A strap system designed for a specific purpose should be a conscious preference, not a surprise after the watch arrives.', 'Zunächst locken vielleicht Lünettenfarbe oder technische Taucheroptik. Im Alltag entscheidet jedoch das gesamte Zusammenspiel: Material, Gewicht, Schließenlage und Beweglichkeit der ersten Glieder. Soll zwischen Metall- und Textilband gewechselt werden, klären Sie die Kompatibilität vor der Wahl einer FXD mit festen Stegen. Ein zweckgebundenes Bandsystem sollte bewusst gewählt werden und nicht erst nach Lieferung überraschen.'),
      b('For an owner who rarely swims, a Black Bay’s chosen proportions or historical styling can matter more than a higher stated depth rating elsewhere. For an owner who intends water use, the exact Pelagos or Black Bay specification and current sealing assessment become central. Neither choice should rest on a claim that one family is automatically the professional or better watch. Choose the reference whose design, adjustment and supported use fit what you will actually do.', 'Wer selten schwimmt, gewichtet möglicherweise Black-Bay-Proportionen oder historischen Stil stärker als eine höhere Tiefenangabe anderswo. Bei geplanter Wassernutzung stehen konkrete Pelagos- oder Black-Bay-Spezifikation und heutige Dichtheit im Mittelpunkt. Keine Familie ist pauschal die professionellere oder bessere Uhr. Wählen Sie die Referenz, deren Gestaltung, Anpassung und vorgesehene Nutzung zu Ihrem Alltag passen.'),
    ]),
  ],
  luminorRadiomir: [
    section('shape-on-the-wrist', b('Why cushion cases need a different size comparison', 'Warum Kissengehäuse anders verglichen werden sollten'), [
      b('A cushion-shaped case fills the corners of its outline differently from a round case, and the strap can make the watch appear longer than the case measurement suggests. Compare a straight-on wrist photograph with a side view showing where the strap turns down. On a Luminor, include the crown-protection bridge in the comfort assessment. On a Radiomir, pay attention to the specific lug design rather than assuming that every version has the same wire-lug appearance.', 'Ein Kissengehäuse füllt seine Kontur anders als ein rundes; das Band kann zusätzlich Länge erzeugen. Vergleichen Sie eine Frontalaufnahme am Handgelenk mit einer Seitenansicht des Bandabfalls. Bei Luminor gehört der Kronenschutzbügel zur Komfortprüfung. Bei Radiomir zählt die konkrete Hörnerkonstruktion, statt jeder Variante dieselben Drahtanstöße zuzuschreiben.'),
      b('If you prefer a quieter outline under a jacket, the Radiomir shape may be the better starting point. If the bridge is precisely what attracts you to Panerai, try the Luminor with the type of strap you will actually wear. A stiff new strap and a softened used strap can position the same case differently. Before buying, check which buckle, strap length and fastening hardware are supplied; those details can change whether the watch is immediately wearable.', 'Für eine ruhigere Kontur unter einer Jacke kann Radiomir der passende Ausgangspunkt sein. Ist gerade der Bügel Ihr Panerai-Motiv, probieren Sie Luminor mit der vorgesehenen Bandart. Ein steifes neues und ein eingetragenes Band können dasselbe Gehäuse unterschiedlich positionieren. Klären Sie vor dem Kauf Schließe, Länge und Befestigungsteile; davon hängt die sofortige Tragbarkeit ab.'),
    ]),
  ],
  luminorSubmersible: [
    section('timing-versus-silhouette', b('Choose between a timing tool and a quieter silhouette', 'Zeitmessfunktion oder ruhigere Silhouette wählen'), [
      b('A rotating timing bezel adds a visible scale and a physical control that you interact with separately from the crown. That may be useful for tracking ordinary intervals even when diving is not planned. It also changes the outline and the amount of information surrounding the dial. Compare whether you enjoy that additional interface or prefer the visual simplicity of a Luminor without it. An unused feature can still be a design preference, but it should not be confused with a practical requirement.', 'Eine drehbare Zeitlünette ergänzt Skala und Bedienelement neben der Krone. Sie kann auch ohne Tauchen für alltägliche Zeitabschnitte nützlich sein, verändert aber Kontur und Informationsmenge um das Zifferblatt. Vergleichen Sie, ob Ihnen diese Bedienung gefällt oder eine Luminor ohne sie ruhiger wirkt. Eine ungenutzte Funktion darf gefallen, ist aber keine praktische Notwendigkeit.'),
      b('For a used Submersible, request a demonstration of bezel movement and a clear view of its edge and insert where applicable. For either family, examine how the crown-protection mechanism operates and ask about previous repairs. Avoid forcing unfamiliar controls, including during an inspection. If the listing’s selling point is underwater capability, require reference-level instructions and evidence relevant to present condition. The crown bridge alone cannot answer that question.', 'Lassen Sie bei einer gebrauchten Submersible die Lünette vorführen und Kante sowie gegebenenfalls Einlage deutlich zeigen. Bei beiden Familien sollten Kronenschutz und frühere Reparaturen geklärt sein. Erzwingen Sie keine unbekannte Bedienung, auch nicht während einer Prüfung. Wird mit Unterwassertauglichkeit geworben, benötigen Sie referenzbezogene Anleitung und aktuelle Zustandsbelege. Der Kronenschutzbügel allein beantwortet das nicht.'),
    ]),
  ],
  serpenti: [
    section('jewellery-and-timekeeping', b('Assess the bracelet and the watch separately', 'Band und Uhr getrennt beurteilen'), [
      b('With Serpenti, the bracelet is not just a way of attaching a conventional watch to the wrist; it is central to the design. View the piece from the side and underneath as well as face-on. Ask how it opens, how it settles on the intended wrist and what size adjustment is possible for that exact construction. A photograph that shows a dramatic coil does not tell you whether the ends sit securely or whether the piece has been altered.', 'Bei Serpenti befestigt das Band nicht bloß eine gewöhnliche Uhr; es prägt den Entwurf. Betrachten Sie Seite und Unterseite ebenso wie die Front. Fragen Sie nach Öffnung, Sitz am vorgesehenen Handgelenk und Anpassungsmöglichkeiten der konkreten Konstruktion. Ein eindrucksvolles Wicklungsfoto zeigt weder sicheren Sitz der Enden noch mögliche Änderungen.'),
      b('Then evaluate timekeeping on its own terms. Confirm whether the reference is quartz or mechanical and request appropriate function and service evidence. Where stones are fitted, establish whether the setting belongs to the original configuration or a later alteration; photographs alone should not be treated as a gemmological report. For a gift, discreetly establish wrist size before choosing. A slightly different reference that fits correctly is more useful than a visually preferred piece that requires uncertain or irreversible modification.', 'Bewerten Sie anschließend die Zeitmessung separat. Klären Sie Quarz oder Mechanik und passende Funktions- sowie Servicebelege. Bei Steinbesatz muss feststehen, ob er zur ursprünglichen Konfiguration oder einer späteren Änderung gehört; Fotos sind kein gemmologisches Gutachten. Für ein Geschenk sollte der Handgelenkumfang vorab bekannt sein. Eine passende andere Referenz ist sinnvoller als ein Favorit mit unklaren oder irreversiblen Anpassungen.'),
    ]),
  ],
  octo: [
    section('thinness-in-everyday-use', b('Thinness solves one problem, not every problem', 'Flachheit löst eine Frage, nicht jede'), [
      b('A low case can be welcome under a close cuff, but the Octo’s angular outline still has a substantial visual footprint. Assess it with your normal sleeve and from a natural viewing distance. Then look at how the bracelet turns down around the wrist and where the clasp rests. A comparison based only on millimetres of thickness misses why one thin watch can feel balanced while another sits too broadly for its wearer.', 'Ein niedriges Gehäuse passt leichter unter enge Manschetten; Octos kantige Kontur bleibt dennoch optisch präsent. Beurteilen Sie sie mit Ihrer normalen Kleidung und aus natürlichem Abstand. Prüfen Sie Bandabfall und Schließenlage. Ein Vergleich allein nach Millimetern Gehäusehöhe erklärt nicht, warum eine flache Uhr ausgewogen wirkt und eine andere zu breit aufliegt.'),
      b('When comparing finishes, ask for close-ups that show edges and changes between surfaces rather than only a uniformly lit dial. Dents and uneven refinishing can alter the architecture that makes the design attractive. Do not borrow water-resistance or crown instructions from another Octo Finissimo because its case looks similar. A reference-level comparison lets you choose deliberately between the materials and constructions instead of buying the broad idea of an ultra-thin watch.', 'Fordern Sie beim Finishvergleich Nahaufnahmen von Kanten und Flächenübergängen statt nur gleichmäßig beleuchteter Zifferblätter an. Dellen und ungleichmäßige Aufarbeitung verändern die reizvolle Architektur. Übernehmen Sie Wasserdichtigkeit und Kronenanleitung nicht von einer ähnlich aussehenden Octo Finissimo. Der Referenzvergleich ermöglicht eine bewusste Wahl zwischen Materialien und Konstruktionen statt nur dem allgemeinen Konzept ultraflacher Uhrmacherei.'),
    ]),
  ],
  laureato: [
    section('integrated-fit', b('Judge the transition from bezel to bracelet', 'Den Übergang von Lünette zu Band beurteilen'), [
      b('The Laureato’s geometric bezel and integrated bracelet need to be seen together. A close crop of the dial can make it difficult to judge the case’s proportions or the way the first links follow the wrist. Ask for a wider photograph and a side view, then compare the actual bracelet length with your requirements. For an older example, confirm that the fitted bracelet and clasp are correct for the reference rather than assuming any similar-looking Laureato parts are interchangeable.', 'Laureatos geometrische Lünette und integriertes Band wirken zusammen. Ein enger Zifferblattausschnitt erschwert die Beurteilung von Proportionen und ersten Gliedern. Bitten Sie um ein weiteres Bild und eine Seitenansicht und gleichen Sie die Bandlänge mit Ihrem Bedarf ab. Bei älteren Exemplaren müssen Band und Schließe zur Referenz passen; ähnlich aussehende Laureato-Teile sind nicht automatisch austauschbar.'),
      b('A useful buying decision begins with whether you like this design independently. Comparing it only against a Royal Oak or Nautilus can obscure the details you will actually live with: dial treatment, case profile, bracelet articulation and service needs. Once the preferred reference is clear, compare condition and completeness. Refinishing should be disclosed because the distinction between crisp and softened transitions can matter more here than a small superficial scratch.', 'Eine gute Kaufentscheidung beginnt damit, ob Ihnen dieses Design eigenständig gefällt. Der ausschließliche Vergleich mit Royal Oak oder Nautilus verdeckt leicht die täglichen Details: Zifferblatt, Gehäuseprofil, Bandbeweglichkeit und Wartung. Vergleichen Sie nach der Referenzwahl Zustand und Vollständigkeit. Aufarbeitung sollte offengelegt sein, denn klare oder verrundete Übergänge können wichtiger sein als ein kleiner oberflächlicher Kratzer.'),
    ]),
  ],
  jackpot: [
    section('document-the-performance', b('Document the whole mechanical performance', 'Das gesamte mechanische Schauspiel dokumentieren'), [
      b('The Jackpot deserves a more specific demonstration than a video showing the time display. The miniature reels, sound and tourbillon are different elements of what makes the watch interesting. A prospective buyer should ask a qualified person to demonstrate the intended sequence and identify any restrictions on operation. Do not experiment with a rare mechanism simply to see what happens. A written assessment should explain which functions were tested and which could not be verified.', 'Die Jackpot verdient mehr als ein Video der Zeitanzeige. Miniaturwalzen, Klang und Tourbillon sind unterschiedliche Bestandteile ihres Reizes. Lassen Sie den vorgesehenen Ablauf und Bedienungsgrenzen fachkundig zeigen. Experimentieren Sie nicht mit einem seltenen Mechanismus. Eine schriftliche Einschätzung sollte erklären, welche Funktionen geprüft wurden und welche nicht bestätigt werden konnten.'),
      b('The same specificity belongs in the ownership plan. Ask who can maintain the complete watch, whether specialist transport is needed and how an estimate is obtained before work begins. An auction description can establish the configuration of its lot, but it is not a service quotation for another example. For a collector, the pleasure may be mechanical theatre rather than daily utility. That makes functional evidence and a realistic support route more important, not less.', 'Dieselbe Genauigkeit gehört zum Besitzplan. Klären Sie, wer die gesamte Uhr betreuen kann, ob Spezialtransport nötig ist und wie vor Arbeiten ein Kostenvoranschlag entsteht. Eine Auktionsbeschreibung belegt die Konfiguration ihres Loses, ist aber kein Serviceangebot für ein anderes Exemplar. Der Reiz kann für Sammler eher im mechanischen Schauspiel als im Alltagsnutzen liegen. Funktionsbelege und ein realistischer Serviceweg werden dadurch wichtiger, nicht weniger wichtig.'),
    ]),
  ],
};
