// Primary sources checked for the September 2026 editorial review.
// Keep facts reference-specific; a current catalogue is not a vintage specification.
export const REVIEW_DATE = '2026-09-12';
const source = (publisher, title, url) => ({ publisher, title, url, accessed: REVIEW_DATE });
export const SOURCES = {
  rolexHistory: source('Rolex', 'History of Rolex', 'https://newsroom.rolex.com/about-rolex/history-of-rolex'),
  rolexCare: source('Rolex', 'Watch care and service: frequently asked questions', 'https://www.rolex.com/en-us/watch-care-and-service/faq'),
  rolexWarranty: source('Rolex', 'The Rolex guarantee', 'https://www.rolex.com/buying-a-rolex/the-rolex-guarantee'),
  rolexService: source('Rolex', 'The Rolex service card', 'https://www.rolex.com/en-us/watch-care-and-service/rolex-service-card'),
  rolexPrecision: source('Rolex', 'Oyster Perpetual: Superlative Chronometer', 'https://newsroom.rolex.com/watches/new-watches-2025/oyster-perpetual'),
  patekCollection: source('Patek Philippe', 'Watch collection', 'https://www.patek.com/en/collection'),
  patekAquanaut: source('Patek Philippe', 'Aquanaut collection and origins', 'https://www.patek.com/en/collection/aquanaut'),
  patekHistory: source('Patek Philippe', 'Nautilus 40th anniversary, 2016', 'https://static.patek.com/pdf/pressreleases/en/2016_PatekPhilippe_Nautilus_40th_Anniversary.pdf'),
  patekArchive: source('Patek Philippe', 'Extract from the Archives: questions and conditions', 'https://www.patek.com/en/service/frequently-asked-questions/extract-from-the-archives'),
  patekService: source('Patek Philippe', 'Our commitment to service', 'https://www.patek.com/en/service/our-commitment-to-service/our-commitment-to-service'),
  metas: source('METAS', 'Certification of watches', 'https://www.metas.ch/metas/en/home/dl/konformitaetsbewertungsstelle-metas-cert/zertifizierung_uhren.html'),
  metasStandard: source('METAS', 'N001: requirements for mechanical watches', 'https://www.metas.ch/dam/metas/en/data/dokumentation/rechtliches/zertifizierung-uhren/metas_n001_v_1_2-e.pdf.download.pdf/metas_n001_v_1_2-e.pdf'),
  omegaCertification: source('Omega', 'Ten years of Master Chronometer certification', 'https://press.omegawatches.com/omega-celebrates-10-years-of-master-chronometer-certification/'),
  omegaTechnology: source('Omega', 'Constellation Observatory and the evolution of precision testing', 'https://press.omegawatches.com/the-constellation-observatory-the-first-two-hand-watch-to-achieve-master-chronometer-certification-fully-tested-at-the-laboratoire-de-precision/'),
  cartier: source('Cartier', 'Watchmaking design: Santos and Tank', 'https://www.cartier.com/en-us/our-style.html'),
  hublot: source('Hublot', 'Big Bang Original Unico: twenty years in the making', 'https://www.hublot.com/en-gb/news/big-bang-original-unico-twenty-years-making'),
  breitling: source('Breitling', 'Navitimer history', 'https://www.breitling.com/ca-en/about/icons/navitimer/'),
  breitlingCollection: source('Breitling', 'Navitimer collection', 'https://www.breitling.com/us-en/collections/navitimer/'),
  ap: source('Audemars Piguet', 'AP Chronicles: the AP story', 'https://apchronicles.audemarspiguet.com/en/article/lepopee-ap'),
  apNumbers: source('Audemars Piguet', 'Royal Oak numbering', 'https://apchronicles.audemarspiguet.com/en/article/royal-oak-numbering'),
  gs: source('Grand Seiko', 'Spring Drive movement', 'https://www.grand-seiko.com/uk-en/collections/movement/springdrive'),
  snowflake: source('Grand Seiko', 'SBGA211 Snowflake specifications', 'https://www.grand-seiko.com/us-en/collections/SBGA211G'),
  shunbun: source('Grand Seiko', 'SBGA413 Shunbun specifications', 'https://www.grand-seiko.com/us-en/collections/SBGA413G'),
  iwc: source('IWC Schaffhausen', 'Historical timeline', 'https://press.iwc.com/timeline/'),
  iwcGenta: source('IWC Schaffhausen', 'Gérald Genta and the Ingenieur', 'https://www.iwc.com/fi/en/specials/gerald-genta.html'),
  iwcAutomatic: source('IWC Schaffhausen', 'Time machines: Pellaton winding', 'https://press.iwc.com/time-machines-en/'),
  jlc: source('Jaeger-LeCoultre', 'Reverso Tribute Duoface Calendar Q3918420', 'https://www.jaeger-lecoultre.com/us-en/watches/reverso/reverso-tribute/reverso-tribute-duoface-calendar-stainless-steel-q3918420'),
  jlcTesting: source('Jaeger-LeCoultre', 'Master Control Chronometre Date Q415216J and HPG testing', 'https://www.jaeger-lecoultre.com/us-en/watches/master-control/master-control-chronometre-date-q415216j'),
  tag: source('TAG Heuer', 'A history written in seconds', 'https://magazine.tagheuer.com/en/2025/08/05/a-history-written-in-seconds/'),
  tagConnected: source('TAG Heuer', 'Connected Calibre E5 generations', 'https://faq.tagheuer.com/articles/en_US/FAQ/000001311'),
  tagOs: source('TAG Heuer', 'Connected Calibre E5 operating system and app', 'https://faq.tagheuer.com/articles/FAQ/000001263'),
  tudor: source('Tudor', 'Origins: 1926 to 1949', 'https://www.tudorwatch.com/en/inside-tudor/history/tudor-history-origins-1926-to-1949'),
  blackBay: source('Tudor', 'Black Bay watch family', 'https://www.tudorwatch.com/en/watch-family/black-bay'),
  pelagos: source('Tudor', 'Pelagos collection', 'https://www.tudorwatch.com/en/collections/pelagos'),
  panerai: source('Panerai', 'History of the manufacture', 'https://www.panerai.com/en/world-of-panerai/history.html'),
  bvlgari: source('Bvlgari', 'Titolo: Serpenti and Tubogas history', 'https://media.bulgari.com/image/upload/v1747837328/pdf/TITOLO/TITOLO_002_rm6whn.pdf'),
  octo: source('Bvlgari', 'Octo Finissimo Automatic 102912', 'https://www.bulgari.com/en-us/product/102912'),
  octoSteel: source('Bvlgari', 'Octo Finissimo 103431', 'https://www.bulgari.com/en-int/watches/mens-2/octo-finissimo-watch-silver-103431'),
  gp: source('Girard-Perregaux', 'Manufacture know-how', 'https://www.girard-perregaux.com/en-us/our-maison/our-know-how'),
  laureato: source('Girard-Perregaux', 'Laureato 81010-11-431-11A', 'https://www.girard-perregaux.com/en-us/watches/laureato/81010-11-431-11a'),
  jackpot: source('Christie’s', 'Girard-Perregaux Vintage 1945 Jackpot Tourbillon, reference 99720', 'https://www.christies.com/lot/lot-6002815'),
  market: source('Deloitte', 'Swiss Watch Industry Insights 2024: pre-owned market', 'https://www.deloitte.com/ch/en/Industries/consumer/perspectives/swiss-watch-industry-preowned-market.html'),
};

export const bilingual = (en, de) => ({ en, de });
