import { bilingual as b } from './sources.js';

// Each topic answers a distinct search intent. Reusable process advice is kept
// separate from these researched explanations so it cannot replace the answer.
const topic = (heading, answer, detail, action, sources = []) => ({ heading, answer, detail, action, sources });
export const TOPICS = {
  choice: topic(
    b('Choose for your wrist and routine', 'Nach Handgelenk und Alltag auswählen'),
    b('The right watch is the one whose size, functions and ownership demands suit you—not necessarily the model attracting the most attention. Start with three decisions: when you will wear it, which display you need and how much maintenance you are comfortable arranging.', 'Die richtige Uhr passt in Größe, Funktion und Pflegeaufwand zu Ihnen – sie muss nicht das Modell mit der größten Aufmerksamkeit sein. Klären Sie zuerst drei Fragen: Wann tragen Sie die Uhr, welche Anzeige benötigen Sie und welchen Wartungsaufwand möchten Sie übernehmen?'),
    b('Build a shortlist of three exact references, not three broad brand names. Compare diameter, thickness, length across the lugs, bracelet adjustment and readability. A date, second time zone or stopwatch should earn its place on the dial through actual use. More complications do not automatically make a better everyday watch.', 'Erstellen Sie eine Auswahl aus drei konkreten Referenzen statt drei allgemeinen Markennamen. Vergleichen Sie Durchmesser, Höhe, Hörnerabstand, Bandverstellung und Ablesbarkeit. Datum, zweite Zeitzone und Stoppfunktion sollten im Alltag wirklich nützlich sein. Mehr Komplikationen ergeben nicht automatisch eine bessere Alltagsuhr.'),
    b('Before choosing, write down your total budget including inspection, any immediate service and missing accessories. Request a wrist photograph and a complete condition description for the finalist. If the available listing does not answer an important question, clarify it rather than filling the gap with the specifications of a similar-looking model.', 'Notieren Sie vor der Entscheidung Ihr Gesamtbudget einschließlich Prüfung, zeitnaher Wartung und fehlendem Zubehör. Fordern Sie für den Favoriten ein Handgelenkfoto und eine vollständige Zustandsbeschreibung an. Offene Fragen sollten geklärt werden, statt sie mit Daten eines ähnlich aussehenden Modells zu beantworten.')),
  story: topic(
    b('Read the history through the watch', 'Die Geschichte an der Uhr verstehen'),
    b('A brand history is most useful when it helps explain the watch in front of you. Separate a collection’s first appearance from the production date of a particular reference. A familiar name can continue through major changes in construction, movement and proportions.', 'Eine Markengeschichte ist besonders nützlich, wenn sie die vorliegende Uhr erklärt. Unterscheiden Sie die Einführung einer Kollektion vom Produktionsdatum einer konkreten Referenz. Ein bekannter Name kann trotz grundlegender Änderungen an Konstruktion, Werk und Proportionen fortbestehen.'),
    b('A modern heritage model may quote an older dial or case without reproducing its original mechanism or dimensions. That can be an advantage for everyday ownership. Conversely, a vintage watch may preserve period character while demanding more careful handling and specialist servicing. Neither is automatically the more authentic expression of your personal taste.', 'Ein modernes Heritage-Modell kann ein historisches Zifferblatt oder Gehäuse aufgreifen, ohne das ursprüngliche Werk oder die Maße zu übernehmen. Im Alltag kann das vorteilhaft sein. Eine Vintage-Uhr bewahrt dagegen ihren Zeitcharakter, benötigt aber möglicherweise vorsichtigere Nutzung und spezialisierte Wartung. Keine Variante trifft automatisch besser Ihren persönlichen Geschmack.'),
    b('Use the manufacturer’s chronology to establish context, then verify the actual reference, case and movement. Ask whether dial, hands and bracelet are period-correct, later manufacturer replacements or aftermarket parts. Provenance should describe the individual watch; an evocative story about the brand cannot substitute for it.', 'Nutzen Sie die Herstellerchronologie als Kontext und prüfen Sie anschließend Referenz, Gehäuse und Werk. Fragen Sie, ob Zifferblatt, Zeiger und Band zeitgenössisch, spätere Herstellerersatzteile oder Fremdteile sind. Herkunftsnachweise müssen die einzelne Uhr betreffen; eine eindrucksvolle Markengeschichte ersetzt sie nicht.')),
  newPreowned: topic(
    b('New or pre-owned: compare evidence, not labels', 'Neu oder gebraucht: Belege statt Etiketten vergleichen'),
    b('New and pre-owned watches offer different trade-offs, but the label alone does not settle condition or warranty. A pre-owned example can provide access to an earlier design; an unworn watch can still have an older sale date and a manufacturer warranty that has already started.', 'Neue und gebrauchte Uhren bieten unterschiedliche Vorteile, doch die Bezeichnung allein klärt weder Zustand noch Garantie. Ein gebrauchtes Exemplar eröffnet Zugang zu früheren Designs; eine ungetragene Uhr kann bereits vor Jahren verkauft worden sein und eine laufende Herstellergarantie besitzen.'),
    b('Compare the exact generation, not merely the collection name. An older movement, clasp or case profile may be precisely what attracts you, or it may create a compromise you do not want. “Unworn”, “new old stock”, “refurbished” and “recently serviced” describe different histories and need separate evidence.', 'Vergleichen Sie die genaue Generation, nicht bloß den Kollektionsnamen. Ein älteres Werk, eine frühere Schließe oder Gehäuseform kann gewünscht sein oder einen unerwünschten Kompromiss bedeuten. „Ungetragen“, „Lagerware“, „aufgearbeitet“ und „frisch gewartet“ beschreiben unterschiedliche Historien und benötigen eigene Belege.'),
    b('Ask for the original sale date, current warranty provider and coverage, service invoices and an itemised accessory list. Then compare the total delivered cost plus foreseeable maintenance. Do not assume a marketplace listing carries an official manufacturer programme or a fresh manufacturer warranty unless that is explicitly documented.', 'Fragen Sie nach Erstverkaufsdatum, aktuellem Garantiegeber und Umfang, Servicerechnungen und einer einzelnen Zubehörliste. Vergleichen Sie anschließend Gesamtkosten inklusive Lieferung und absehbarer Wartung. Ein Marktplatzangebot gehört nicht automatisch zu einem offiziellen Herstellerprogramm und besitzt nicht zwangsläufig eine neue Herstellergarantie.')),
  papers: topic(
    b('Original papers, service documents and the watch itself', 'Originalpapiere, Servicebelege und die Uhr selbst'),
    b('For a Rolex, distinguish the original warranty document from a later service card. Rolex’s five-year new-watch guarantee has specific sale and documentation conditions; an official full service has its own service guarantee. These are separate records, not interchangeable proof of the original delivery set.', 'Unterscheiden Sie bei Rolex die ursprüngliche Garantieunterlage von einer späteren Servicekarte. Die fünfjährige Neuuhrengarantie ist an konkrete Verkaufs- und Dokumentationsbedingungen gebunden; ein offizieller Komplettservice hat eine eigene Servicegarantie. Das sind unterschiedliche Nachweise, keine austauschbaren Belege des ursprünglichen Lieferumfangs.'),
    b('“Full set” needs an inventory: box, warranty card or certificate, booklets, spare links and any other claimed items. Check which numbers are recorded and whether they correspond to the watch. A genuine box can be purchased separately, and papers can be mismatched; neither establishes authenticity on its own.', '„Full Set“ benötigt eine Aufstellung: Box, Garantiekarte oder Zertifikat, Hefte, zusätzliche Glieder und weiteres genanntes Zubehör. Prüfen Sie vorhandene Nummern und ihre Zuordnung zur Uhr. Eine echte Box kann nachgekauft und ein Papier falsch zugeordnet sein; beides beweist allein keine Echtheit.'),
    b('Ask the seller to distinguish original items from later additions in writing. If the watch is older and has no papers, focus on a competent physical assessment and a traceable invoice. Do not apply an assumed fixed percentage discount: compare the same reference and condition with and without equivalent documentation.', 'Lassen Sie Originalteile und spätere Ergänzungen schriftlich unterscheiden. Bei älteren Uhren ohne Papiere stehen eine fachkundige Untersuchung und eine nachvollziehbare Rechnung im Vordergrund. Verwenden Sie keinen pauschalen prozentualen Abschlag, sondern vergleichen Sie dieselbe Referenz und denselben Zustand mit gleichwertigen Unterlagen.'),
    ['rolexWarranty', 'rolexService']),
  archives: topic(
    b('What a Patek Philippe archive extract can tell you', 'Was ein Patek-Philippe-Archivauszug aussagt'),
    b('An Extract from the Archives reports information held in Patek Philippe’s historical records. It is different from the original Certificate of Origin supplied with a new watch. Patek states that the original certificate cannot be replaced; an extract is not a replacement original guarantee document.', 'Ein Archivauszug gibt Informationen aus Patek Philippes historischen Aufzeichnungen wieder. Er unterscheidet sich vom ursprünglichen Certificate of Origin einer neuen Uhr. Laut Patek kann dieses Originalzertifikat nicht ersetzt werden; ein Archivauszug ist keine neu ausgestellte ursprüngliche Garantieurkunde.'),
    b('At the September 2026 review, the manufacturer required the first sale to have taken place more than ten years earlier and limited repeat extracts for the same watch. Photographs and identifying information form part of the application. Check the current official conditions and fee before ordering; eligibility is not a promise about present condition or originality.', 'Zum Recherchestand September 2026 verlangte der Hersteller einen Erstverkauf vor mehr als zehn Jahren und begrenzte wiederholte Auszüge für dieselbe Uhr. Fotos und Identifikationsangaben gehören zum Antrag. Prüfen Sie die aktuellen offiziellen Bedingungen und Gebühren; die Berechtigung sagt nichts Verbindliches über heutigen Zustand oder Originalität aus.'),
    b('Read an extract alongside the watch and any service records. If the present dial or material differs from the recorded description, request an explanation and specialist assessment. Do not buy solely because an archive document is offered: it cannot replace inspection of the physical object now being sold.', 'Lesen Sie den Auszug zusammen mit der Uhr und vorhandenen Servicebelegen. Weichen heutiges Zifferblatt oder Material von der Aufzeichnung ab, verlangen Sie eine Erklärung und fachkundige Prüfung. Kaufen Sie nicht allein wegen eines angebotenen Archivauszugs: Er ersetzt keine Untersuchung des heute verkauften Gegenstands.'),
    ['patekArchive']),
  price: topic(
    b('Build a reference-level price comparison', 'Preise auf Referenzebene vergleichen'),
    b('There is no single useful price for an entire watch brand. Separate the manufacturer’s current retail price, a dealer’s asking price, a completed transaction and the amount a dealer would pay to buy the watch from you. These figures answer different questions and should not be presented as one market value.', 'Für eine ganze Uhrenmarke gibt es keinen einzelnen aussagekräftigen Preis. Trennen Sie aktuelle Herstellerpreise, Händler-Angebotspreise, tatsächlich abgeschlossene Verkäufe und Händler-Ankaufspreise. Diese Werte beantworten unterschiedliche Fragen und sind kein einheitlicher Marktwert.'),
    b('Choose the exact reference, material, dial and bracelet, then compare examples with similar condition and accessories. Record currency, date, taxes, fees and service history. An exceptional auction result can include provenance or rarity that an ordinary example does not share; it is not a price guide for every watch with the same logo.', 'Wählen Sie genaue Referenz, Material, Zifferblatt und Band und vergleichen Sie ähnliche Zustände und Zubehörumfänge. Notieren Sie Währung, Datum, Steuern, Gebühren und Wartungshistorie. Ein außergewöhnliches Auktionsergebnis kann durch Herkunft oder Seltenheit entstehen, die ein normales Exemplar nicht besitzt.'),
    b('This guide deliberately does not invent a live price range. Use dated, comparable offers and documented sold results where available, then obtain a service estimate for uncertain condition. Keep an ownership reserve rather than spending the entire budget on the advertised price. Scarcity and past appreciation do not guarantee a profitable resale.', 'Dieser Guide erfindet bewusst keine aktuelle Preisspanne. Nutzen Sie datierte vergleichbare Angebote und, soweit verfügbar, belegte Verkaufsergebnisse; bei unklarem Zustand zusätzlich einen Kostenvoranschlag. Planen Sie eine Reserve statt das ganze Budget für den Angebotspreis auszugeben. Seltenheit und frühere Wertsteigerung garantieren keinen profitablen Wiederverkauf.')),
  exceptional: topic(
    b('Why exceptional watches command exceptional prices', 'Warum außergewöhnliche Uhren außergewöhnliche Preise erzielen'),
    b('A search for the “most expensive Audemars Piguet” can mix retail prices, unique commissions, charity auctions and ordinary secondary-market sales. Without specifying the category, currency and date, a claimed record is misleading. A rare complication or documented provenance can matter more than the brand name alone.', 'Die Suche nach der „teuersten Audemars Piguet“ kann Listenpreise, Einzelanfertigungen, Wohltätigkeitsauktionen und normale Zweitmarktverkäufe vermischen. Ohne Kategorie, Währung und Datum ist ein behaupteter Rekord irreführend. Eine seltene Komplikation oder belegte Herkunft kann wichtiger sein als der Markenname allein.'),
    b('Evaluate what makes the individual watch unusual: movement complexity, execution, production context, material and documented history. A numbered case is not sufficient evidence of a limited series. Ask for the manufacturer reference and supporting records before accepting a rarity claim or a premium based on it.', 'Bewerten Sie, was die einzelne Uhr besonders macht: Werkkomplexität, Ausführung, Produktionskontext, Material und dokumentierte Geschichte. Eine Gehäusenummer belegt keine limitierte Serie. Verlangen Sie Herstellerreferenz und Unterlagen, bevor Sie Seltenheitsbehauptungen oder entsprechende Aufpreise akzeptieren.'),
    b('For a high-value purchase, separate admiration from valuation. Obtain independent condition advice and a realistic servicing and resale plan. This page does not claim an all-time auction record or suggest that an expensive AP will appreciate; both would require evidence specific to the transaction and time period.', 'Trennen Sie bei hochpreisigen Käufen Begeisterung von Bewertung. Holen Sie eine unabhängige Zustandseinschätzung und einen realistischen Wartungs- und Wiederverkaufsplan ein. Diese Seite behauptet weder einen ewigen Auktionsrekord noch eine künftige Wertsteigerung teurer AP-Uhren; beides benötigt konkrete Belege.'),
    ['apNumbers']),
  vintage: topic(
    b('Identify the watch before assigning an age', 'Die Uhr identifizieren, bevor ihr Alter feststeht'),
    b('An old model name, a vintage-inspired dial and an old watch are three different things. Start with the case reference, movement, available serial information and the manufacturer’s archive or historical catalogue. A style resemblance alone cannot date a watch or establish that all its components left the factory together.', 'Ein alter Modellname, ein historisch gestaltetes Zifferblatt und eine alte Uhr sind drei verschiedene Dinge. Beginnen Sie mit Gehäusereferenz, Werk, Serienangaben und Herstellerarchiv oder historischem Katalog. Stilähnlichkeit allein datiert keine Uhr und beweist keine gemeinsame Werksauslieferung aller Teile.'),
    b('Separate authenticity, period correctness and condition. A genuine later service dial can be mechanically suitable but different from the original configuration. Refinishing may improve appearance while reducing sharpness or historical character. Ask for disclosures rather than assuming that a very clean vintage watch is untouched.', 'Trennen Sie Echtheit, zeitliche Stimmigkeit und Zustand. Ein echtes späteres Servicezifferblatt kann technisch passen, aber von der ursprünglichen Konfiguration abweichen. Aufarbeitung kann die Optik verbessern und zugleich Konturen oder historischen Charakter verändern. Verlangen Sie Angaben statt eine makellose Vintage-Uhr automatisch für unberührt zu halten.'),
    b('Before paying, obtain a specialist view of the movement and an estimate for necessary work. Confirm whether replacement parts are available and whether conservation or cosmetic restoration is your priority. Do not open a vintage case or disturb old luminous material yourself. A running seconds hand is not a complete health check.', 'Holen Sie vor dem Kauf eine fachkundige Werkeinschätzung und einen Kostenvoranschlag ein. Klären Sie Teileverfügbarkeit und ob Erhalt oder optische Restaurierung Vorrang hat. Öffnen Sie alte Gehäuse nicht selbst und bearbeiten Sie keine historische Leuchtmasse. Ein laufender Sekundenzeiger ist keine vollständige Zustandsprüfung.')),
  maintenance: topic(
    b('Maintain the watch you own, not an imagined average', 'Die konkrete Uhr warten, nicht einen Durchschnitt'),
    b('Maintenance depends on the reference, age, use and service history. Follow the manual for the exact calibre, especially for winding and calendar correction. A universal internet service interval cannot diagnose a particular watch, and a claimed factory depth rating does not establish that an older example is safe to immerse today.', 'Wartung hängt von Referenz, Alter, Nutzung und Servicehistorie ab. Beachten Sie die Anleitung des genauen Kalibers, besonders beim Aufziehen und bei Kalenderkorrekturen. Ein pauschales Internetintervall diagnostiziert keine einzelne Uhr; die ursprüngliche Druckangabe bestätigt nicht die heutige Dichtheit eines älteren Exemplars.'),
    b('A change in rate, reduced running time, unreliable date change or moisture deserves assessment. If condensation appears, stop exposing the watch to water and arrange prompt professional attention; do not apply heat or open the case. Until its sealing condition is known, keep cleaning conservative with a soft dry cloth.', 'Gangänderungen, kürzere Laufzeit, unzuverlässige Datumsschaltung oder Feuchtigkeit sollten geprüft werden. Bei Kondenswasser die Uhr nicht weiter Wasser aussetzen und zeitnah fachkundige Hilfe organisieren; weder erhitzen noch selbst öffnen. Solange der Dichtungszustand unklar ist, genügt eine vorsichtige Reinigung mit einem weichen trockenen Tuch.'),
    b('Request an itemised estimate explaining movement work, sealing tests, proposed replacement parts and any cosmetic refinishing. Give instructions about preserving original components before authorising restoration. Keep the final invoice with the watch’s records; it is more informative than an undated “recently serviced” description.')),
  rolexMechanics: topic(
    b('Chronometer testing and real-world timekeeping', 'Chronometerprüfung und Gangverhalten im Alltag'),
    b('Rolex’s modern Superlative Chronometer designation includes testing after casing, with the stated −2/+2 seconds per day precision criterion for the watches covered by that standard. It is not a promise that every vintage Rolex was tested to today’s specification, nor a substitute for measuring the condition of a used movement.', 'Rolex’ moderne Bezeichnung Superlative Chronometer umfasst Prüfungen nach dem Einschalen mit dem angegebenen Ganggenauigkeitskriterium von −2/+2 Sekunden pro Tag für entsprechend zertifizierte Uhren. Sie bedeutet weder, dass jede Vintage-Rolex nach dem heutigen Standard geprüft wurde, noch ersetzt sie die Zustandsprüfung eines gebrauchten Werks.'),
    b('Distinguish the movement’s chronometer certification from the complete-watch checks and from a seller’s present-day timekeeping report. Test conditions, winding state, position and temperature can influence a reading. A single photograph of a timing machine is therefore useful context, not a full condition certificate.', 'Unterscheiden Sie Werk-Chronometerzertifizierung, Prüfungen der kompletten Uhr und den aktuellen Gangbericht eines Verkäufers. Prüfbedingungen, Aufzugszustand, Lage und Temperatur beeinflussen Messungen. Ein einzelnes Zeitwaagenfoto ist deshalb ein Hinweis, kein vollständiges Zustandszertifikat.'),
    b('Identify the calibre and ask whether service work has changed components. For everyday ownership, reliable operation, correct setting and documented sealing matter alongside precision. Use the reference manual rather than assuming the same winding and setting procedure applies to every Rolex complication.', 'Identifizieren Sie das Kaliber und fragen Sie nach ersetzten Komponenten. Im Alltag zählen neben Genauigkeit zuverlässige Funktion, korrekte Bedienung und dokumentierte Dichtheit. Nutzen Sie die Referenzanleitung, statt für jede Rolex-Komplikation dasselbe Einstellverfahren anzunehmen.'),
    ['rolexPrecision']),
  patekMechanics: topic(
    b('Understand the complication before choosing it', 'Die Komplikation vor dem Kauf verstehen'),
    b('Patek Philippe’s collection spans simple time displays, calendar functions and highly complicated watches. More complicated is not automatically more suitable. Think about how frequently you will wear the watch and whether you are comfortable resetting its functions after it has stopped.', 'Patek Philippes Kollektion reicht von einfachen Zeitanzeigen über Kalender bis zu hochkomplizierten Uhren. Komplizierter bedeutet nicht automatisch geeigneter. Überlegen Sie, wie oft Sie die Uhr tragen und ob Sie ihre Funktionen nach Stillstand sicher neu einstellen können.'),
    b('Read the exact calibre instructions for crown positions and correctors. Calendar mechanisms can have restricted adjustment periods, and these cannot safely be reduced to one universal rule for all movements. A travel-time display, annual calendar and perpetual calendar involve different setting and maintenance considerations.', 'Lesen Sie für das genaue Kaliber die Vorgaben zu Kronenstellungen und Korrektoren. Kalenderwerke können gesperrte Einstellzeiträume haben; dafür gibt es keine sichere Universalregel für alle Werke. Reisezeit, Jahreskalender und ewiger Kalender stellen unterschiedliche Anforderungen an Bedienung und Wartung.'),
    b('Ask for a complete functional demonstration, not just a movement photograph. Establish whether the correct stylus, instructions and original clasp are included. If service is due, obtain a specialist estimate before purchase; complex work should not be priced as a routine battery change or simple adjustment.', 'Verlangen Sie eine vollständige Funktionsvorführung statt nur eines Werkfotos. Prüfen Sie Einstellstift, Anleitung und Originalschließe im Lieferumfang. Bei fälliger Wartung sollte vor dem Kauf ein fachkundiger Kostenvoranschlag vorliegen; komplexe Arbeiten sind kein gewöhnlicher Batteriewechsel oder eine einfache Regulierung.'),
    ['patekCollection', 'patekService']),
  metas: topic(
    b('What Master Chronometer actually tests', 'Was Master Chronometer tatsächlich prüft'),
    b('Master Chronometer is a certification framework for the completed watch overseen by Switzerland’s METAS. It addresses precision, magnetic resistance, power reserve and water resistance. The requirements include exposure to a 15,000-gauss magnetic field; this is more than a movement-only chronometer test.', 'Master Chronometer ist ein von der Schweizer METAS beaufsichtigtes Zertifizierungsverfahren für die vollständige Uhr. Es umfasst Präzision, Magnetfeldbeständigkeit, Gangreserve und Wasserdichtigkeit. Die Anforderungen enthalten eine Prüfung bei 15.000 Gauß; das geht über eine reine Werk-Chronometerprüfung hinaus.'),
    b('Omega began using the certification in 2015. METAS makes the framework available to qualifying Swiss-made watches from other manufacturers too, so it is not simply another name for Omega’s Co-Axial escapement. A watch can have a Co-Axial movement without being a Master Chronometer.', 'Omega nutzt die Zertifizierung seit 2015. METAS öffnet das Verfahren auch qualifizierten Swiss-Made-Uhren anderer Hersteller. Es ist daher keine andere Bezeichnung für Omegas Co-Axial-Hemmung. Eine Uhr kann ein Co-Axial-Werk besitzen, ohne Master Chronometer zu sein.'),
    b('Verify the exact reference and supplied certification details. For a used watch, factory certification and present condition are separate questions: a later impact, wear or compromised seal can still require service. Treat certification as information about the tested design and process, not immunity from maintenance.', 'Prüfen Sie Referenz und mitgelieferte Zertifizierungsangaben. Bei gebrauchten Uhren sind Werksprüfung und heutiger Zustand getrennte Fragen: Spätere Stöße, Verschleiß oder beschädigte Dichtungen können Wartung erfordern. Zertifizierung beschreibt Prüfung und Standard, nicht Wartungsfreiheit.'),
    ['metas', 'metasStandard', 'omegaCertification']),
  coaxial: topic(
    b('Co-Axial is an escapement, not a collection', 'Co-Axial ist eine Hemmung, keine Kollektion'),
    b('The escapement regulates the release of energy from a mechanical watch’s mainspring. Omega’s Co-Axial designation identifies an escapement architecture, while Master Chronometer refers to a certification programme. These labels answer different questions and should not be treated as interchangeable.', 'Die Hemmung steuert die Energieabgabe der Zugfeder einer mechanischen Uhr. Omegas Co-Axial bezeichnet eine Hemmungsarchitektur, Master Chronometer dagegen ein Zertifizierungsprogramm. Die Begriffe beantworten unterschiedliche Fragen und sind nicht austauschbar.'),
    b('Co-Axial appears in different calibre generations and watch families. It does not by itself tell you the winding system, complications, power reserve or magnetic-resistance specification. Nor does a technical improvement eliminate oils, seals, moving parts or the need for competent servicing.', 'Co-Axial kommt in verschiedenen Kalibergenerationen und Uhrenfamilien vor. Daraus ergeben sich allein weder Aufzugssystem, Komplikationen, Gangreserve noch Magnetfeldspezifikation. Technischer Fortschritt beseitigt auch nicht Schmierstoffe, Dichtungen, bewegliche Teile oder fachgerechte Wartung.'),
    b('Use the calibre number to compare two watches advertised as Co-Axial. Check service documentation and the instructions applicable to that movement. If certification matters to you, verify Master Chronometer status separately; do not infer it from the Co-Axial wording on an older dial.', 'Vergleichen Sie zwei als Co-Axial angebotene Uhren anhand der Kalibernummer. Prüfen Sie Wartungsbelege und die passende Bedienungsanleitung. Wenn Zertifizierung wichtig ist, bestätigen Sie Master-Chronometer-Status separat; die Aufschrift Co-Axial auf einem älteren Zifferblatt reicht dafür nicht.'),
    ['omegaTechnology', 'metas']),
  speedSeamaster: topic(
    b('Timing an event or choosing a water-oriented watch?', 'Ereignisse stoppen oder eine wasserorientierte Uhr wählen?'),
    b('Speedmaster versus Seamaster is not a comparison between two single watches. Begin with the task: a chronograph measures elapsed time with pushers and subdials, while a dive-style timing bezel provides a different way to track an interval. The exact reference determines the functions and water-resistance specification.', 'Speedmaster gegen Seamaster ist kein Vergleich zweier einzelner Uhren. Beginnen Sie mit der Aufgabe: Ein Chronograph misst Zeitabschnitte über Drücker und Hilfszifferblätter, eine Tauchzeitlünette auf andere Weise. Die genaue Referenz bestimmt Funktionen und Wasserdichtigkeitsangabe.'),
    b('Within Speedmaster, distinguish the Moonwatch from other automatic and specialist variants. Within Seamaster, separate Diver 300M, Planet Ocean and Aqua Terra before comparing wearability. Not every Seamaster is a rotating-bezel dive watch, and not every Speedmaster uses the same winding routine.', 'Unterscheiden Sie innerhalb Speedmaster die Moonwatch von automatischen und spezialisierten Varianten. Trennen Sie innerhalb Seamaster Diver 300M, Planet Ocean und Aqua Terra vor dem Tragevergleich. Nicht jede Seamaster hat eine Tauchlünette, und nicht jede Speedmaster wird gleich aufgezogen.'),
    b('Compare a specific pair on thickness, legibility, bracelet adjustment and servicing needs. If you swim, obtain confirmation of the reference’s intended use and present sealing condition. Do not operate chronograph pushers in water unless the exact manufacturer instructions explicitly permit it.', 'Vergleichen Sie ein konkretes Paar nach Höhe, Ablesbarkeit, Bandverstellung und Wartungsbedarf. Fürs Schwimmen müssen vorgesehene Nutzung und aktuelle Dichtheit bestätigt sein. Bedienen Sie Chronographendrücker unter Wasser nur, wenn die exakte Herstelleranleitung dies ausdrücklich erlaubt.')),
  springDrive: topic(
    b('Mainspring power with electronic regulation', 'Federkraft mit elektronischer Regelung'),
    b('Spring Drive uses a mainspring for power and a quartz oscillator with electronic control to regulate its release. It is not a conventional mechanical escapement and is not a battery-powered quartz movement. Its characteristic gliding seconds hand follows from this different regulation system.', 'Spring Drive nutzt eine Zugfeder als Energiequelle und einen Quarzoszillator mit elektronischer Regelung für die kontrollierte Abgabe. Es besitzt weder eine klassische mechanische Hemmung noch ist es ein batteriebetriebenes Quarzwerk. Daraus ergibt sich der charakteristisch gleitende Sekundenzeiger.'),
    b('Grand Seiko’s 9R Spring Drive arrived in 2004. Different Spring Drive calibres have different winding arrangements, accuracy claims and power reserves. Avoid transferring the specifications of a familiar Snowflake to every Spring Drive watch, particularly when comparing generations or complicated models.', 'Grand Seikos 9R Spring Drive kam 2004 hinzu. Spring-Drive-Kaliber unterscheiden sich bei Aufzug, Genauigkeitsangaben und Gangreserve. Übertragen Sie Snowflake-Daten nicht auf alle Spring-Drive-Uhren, besonders beim Vergleich verschiedener Generationen oder komplizierter Modelle.'),
    b('Decide whether the combination appeals to your ownership preferences. Check the precise calibre, observed running time, service record and where qualified service is available. “No battery” does not mean no maintenance, and a smooth seconds hand is not a substitute for testing all functions.', 'Entscheiden Sie, ob die Kombination zu Ihren Vorlieben passt. Prüfen Sie Kaliber, beobachtete Laufzeit, Wartungshistorie und geeignete Servicewege. „Ohne Batterie“ bedeutet nicht wartungsfrei; ein gleitender Sekundenzeiger ersetzt keine Funktionsprüfung.'),
    ['gs']),
  snowflakeShunbun: topic(
    b('SBGA211 and SBGA413: compare the actual references', 'SBGA211 und SBGA413: die konkreten Referenzen vergleichen'),
    b('For the familiar SBGA211 Snowflake and SBGA413 Shunbun, the decision is not principally about the movement: both use the 9R65 Spring Drive calibre. The SBGA211 has a white textured dial and a 41 mm case; the SBGA413 has a pink-toned dial and a 40 mm case. These specifications apply to those references, not every watch sharing a nickname.', 'Bei der bekannten SBGA211 Snowflake und SBGA413 Shunbun geht es nicht vorrangig um das Werk: Beide nutzen das 9R65-Spring-Drive-Kaliber. Die SBGA211 hat ein weißes Strukturzifferblatt und 41 mm Gehäuse, die SBGA413 ein rosafarbenes Zifferblatt und 40 mm. Das gilt für diese Referenzen, nicht für jede Uhr mit ähnlichem Spitznamen.'),
    b('Both use titanium, but their case outlines and dial effects differ. A one-millimetre diameter difference does not capture the full fit: compare lug span and case profile too. View the pink dial in neutral daylight rather than expecting every photograph’s saturation to match the watch on your wrist.', 'Beide verwenden Titan, unterscheiden sich aber in Gehäusekontur und Zifferblattwirkung. Ein Millimeter Durchmesserunterschied beschreibt die Passform nicht vollständig: Vergleichen Sie auch Hörnerabstand und Profil. Betrachten Sie das rosa Zifferblatt bei neutralem Tageslicht statt jede Fotosättigung am Handgelenk zu erwarten.'),
    b('Choose on fit and which dial you enjoy in ordinary lighting. Then compare condition, bracelet completeness, service history and the exact regional reference. If you already favour one design, a better-documented example may matter more than a small theoretical specification advantage.', 'Entscheiden Sie nach Sitz und dem Zifferblatt, das Ihnen bei normalem Licht gefällt. Vergleichen Sie danach Zustand, Bandvollständigkeit, Service und genaue regionale Referenz. Bei klarer Designvorliebe kann ein besser dokumentiertes Exemplar wichtiger sein als ein kleiner theoretischer Datenvorteil.'),
    ['snowflake', 'shunbun']),
  iwcAutomatic: topic(
    b('Automatic does not identify a single IWC calibre', 'Automatik bezeichnet nicht ein einzelnes IWC-Kaliber'),
    b('An automatic watch winds its mainspring through a moving rotor while it is worn. IWC uses different automatic calibres; Pellaton is a particular winding system, not a synonym for every automatic IWC. Establish the IW reference and calibre before comparing technical claims.', 'Eine Automatikuhr zieht ihre Zugfeder beim Tragen über einen beweglichen Rotor auf. IWC verwendet unterschiedliche Automatikkaliber; Pellaton ist ein bestimmtes Aufzugssystem, kein Synonym für jede automatische IWC. Ermitteln Sie IW-Referenz und Kaliber vor technischen Vergleichen.'),
    b('Wearing patterns influence how fully the watch is wound. Desk-based activity may not maintain the same reserve as more active use. A long advertised power reserve also does not mean the watch starts fully wound after a short period on the wrist. Follow the movement’s manual-winding instructions where provided.', 'Tragegewohnheiten beeinflussen den Aufzugszustand. Schreibtischarbeit hält die Reserve möglicherweise nicht so wie aktivere Nutzung. Eine lange angegebene Gangreserve bedeutet außerdem nicht, dass die Uhr nach kurzer Tragezeit voll aufgezogen ist. Beachten Sie die vorgesehenen Hinweise zum Handaufzug.'),
    b('When buying used, ask about running time after proper winding and any unusual rotor noise or winding resistance. Diagnose problems through a qualified service assessment, not guesses about a movement family. Check calendar-setting instructions separately before changing the date.', 'Fragen Sie beim Gebrauchtkauf nach Laufzeit nach korrektem Aufzug und ungewöhnlichen Rotorgeräuschen oder Widerständen. Lassen Sie Probleme fachkundig prüfen statt aus einer Werkfamilie zu diagnostizieren. Lesen Sie die Kalendervorgaben separat, bevor Sie das Datum verändern.'),
    ['iwcAutomatic']),
  pilot: topic(
    b('Choose legibility and fit before pilot-watch mythology', 'Ablesbarkeit und Sitz vor Fliegeruhren-Mythos wählen'),
    b('IWC’s Pilot’s Watch history reaches back to 1936, but modern pilot references differ in size, movement and function. Decide whether you want a simple instrument-style display, a chronograph or a travel function. A large dial can aid legibility while a large case may be uncomfortable on a smaller wrist.', 'IWCs Fliegeruhrengeschichte reicht bis 1936 zurück, moderne Referenzen unterscheiden sich jedoch bei Größe, Werk und Funktion. Entscheiden Sie zwischen einfacher Instrumentenanzeige, Chronograph und Reisefunktion. Ein großes Zifferblatt kann gut ablesbar sein, ein großes Gehäuse an einem kleinen Handgelenk trotzdem unbequem.'),
    b('Compare the entire case length, crown projection and strap stiffness. Photographs should show how the lugs sit rather than only a head-on dial. A pilot style does not automatically specify magnetic resistance, water resistance or professional suitability; confirm the individual reference’s documented features.', 'Vergleichen Sie gesamte Gehäuselänge, Kronenüberstand und Bandsteifigkeit. Fotos sollten die Auflage der Hörner zeigen statt nur das Zifferblatt frontal. Fliegerstil belegt nicht automatisch Magnetfeldschutz, Wasserdichtheit oder berufliche Eignung; entscheidend sind dokumentierte Referenzmerkmale.'),
    b('Before purchase, test the actual functions and confirm the included strap and buckle. If buying for travel, check whether the watch’s time-zone display meets your preferred setting method. Choose a watch that is comfortable and readable in daily life, not solely one associated with an aviation story.', 'Prüfen Sie vor dem Kauf Funktionen, Band und Schließe. Für Reisen sollte die Zeitzonenanzeige zur gewünschten Einstellmethode passen. Wählen Sie eine Uhr, die im Alltag bequem und lesbar ist, nicht nur eine mit Luftfahrtgeschichte.'),
    ['iwc']),
  ingenieur: topic(
    b('Original Ingenieur and Genta’s Ingenieur SL', 'Ursprüngliche Ingenieur und Gentas Ingenieur SL'),
    b('The Ingenieur family began in 1955. Gérald Genta’s Ingenieur SL reference 1832 followed in 1976, introducing the integrated-bracelet design associated with that chapter of the collection. Confusing those dates can lead to an inaccurate description of a vintage watch.', 'Die Ingenieur-Familie begann 1955. Gérald Gentas Ingenieur SL Referenz 1832 folgte 1976 mit dem integrierten Banddesign dieses Kollektionskapitels. Werden diese Daten verwechselt, entstehen unzutreffende Beschreibungen historischer Uhren.'),
    b('Modern Ingenieur references reinterpret the family rather than sharing one unchanged construction. Compare bracelet articulation, case thickness, dial treatment and movement for the specific generation. Do not infer a magnetic-resistance specification solely from the collection’s engineering heritage.', 'Moderne Ingenieur-Referenzen interpretieren die Familie neu, statt unverändert dieselbe Konstruktion zu besitzen. Vergleichen Sie Bandbeweglichkeit, Gehäusehöhe, Zifferblatt und Werk der konkreten Generation. Leiten Sie Magnetfeldspezifikationen nicht allein aus der technischen Tradition der Kollektion ab.'),
    b('With an integrated bracelet, missing links and over-refinished transitions are especially worth checking. Ask for side-on photographs and a measured wrist circumference range. On vintage examples, seek a specialist assessment of originality before paying a premium for the Genta association.', 'Bei integriertem Band verdienen fehlende Glieder und stark aufgearbeitete Übergänge besondere Beachtung. Fordern Sie Seitenfotos und den messbaren Handgelenkumfang an. Lassen Sie bei Vintage-Exemplaren die Originalität fachkundig beurteilen, bevor Sie einen Aufpreis für den Genta-Bezug zahlen.'),
    ['iwcGenta']),
  duoface: topic(
    b('Two faces, one travel-time idea', 'Zwei Seiten, ein Reisezeit-Konzept'),
    b('Jaeger-LeCoultre introduced the Duoface concept in 1994. It uses two faces to show different time displays from one movement. It must be distinguished from single-face Reverso watches and from other double-sided complications with different purposes.', 'Jaeger-LeCoultre führte das Duoface-Konzept 1994 ein. Es nutzt zwei Seiten für unterschiedliche Zeitanzeigen aus einem Werk. Es ist von einseitigen Reverso-Uhren und anderen doppelseitigen Komplikationen mit anderen Aufgaben zu unterscheiden.'),
    b('Identify the exact Duoface reference before assuming its calendar, day/night indication or setting procedure. A calendar-equipped version adds functions and thickness that may not suit someone seeking a simple travel watch. Both faces should be readable and useful to you, not merely attractive in separate product photographs.', 'Identifizieren Sie die genaue Duoface-Referenz, bevor Sie Kalender, Tag-Nacht-Anzeige oder Einstellverfahren voraussetzen. Eine Kalenderversion bringt Funktionen und Höhe mit, die nicht jedem Reisenden passen. Beide Seiten sollten für Sie lesbar und nützlich sein, nicht nur auf getrennten Produktfotos gefallen.'),
    b('Ask for a demonstration of reversing, locking and setting both displays. Check the carrier for looseness and confirm the correct manual is supplied or available. Never force the case or setting mechanism if it resists; a pre-purchase service opinion is preferable to discovering a fault later.', 'Lassen Sie Wenden, Verriegeln und Einstellen beider Anzeigen vorführen. Prüfen Sie den Träger auf Spiel und die Verfügbarkeit der passenden Anleitung. Erzwingen Sie keine Bewegung bei Widerstand; eine Serviceeinschätzung vor dem Kauf ist besser als ein später entdeckter Defekt.'),
    ['jlc']),
  masterChronograph: topic(
    b('Distinguish the Master reference and its functions', 'Master-Referenz und Funktionen unterscheiden'),
    b('“Master Chronograph” is not enough to identify a Jaeger-LeCoultre watch. Establish the exact Master collection, reference and calibre, then separate a chronograph from calendar or travel-time functions. The dial layout should support how you intend to use the watch, not merely maximise the number of displays.', '„Master Chronograph“ identifiziert eine Jaeger-LeCoultre nicht vollständig. Ermitteln Sie Master-Kollektion, Referenz und Kaliber und trennen Sie Chronograph von Kalender- oder Reisefunktionen. Das Zifferblatt sollte Ihre Nutzung unterstützen, nicht bloß möglichst viele Anzeigen vereinen.'),
    b('Testing language also needs a date and reference. Master Control is associated with the manufacturer’s 1,000 Hours Control, while the 2026 Master Control Chronometre generation introduces HPG testing. Do not retroactively attach the newest testing claim to an older chronograph listing.', 'Auch Prüfangaben benötigen Datum und Referenz. Master Control ist mit der herstellereigenen 1.000-Stunden-Prüfung verbunden; die Master-Control-Chronometre-Generation 2026 führt HPG-Prüfungen ein. Übertragen Sie den neuesten Prüfstandard nicht rückwirkend auf einen älteren Chronographen.'),
    b('Request operation of start, stop and reset, plus any calendar functions, by a person familiar with the calibre. Compare case thickness and pusher comfort under a cuff. A complication that is rarely used still requires maintenance, so include servicing in the decision rather than considering the purchase price alone.', 'Lassen Sie Start, Stopp, Rückstellung und gegebenenfalls Kalender von einer kaliberkundigen Person vorführen. Vergleichen Sie Gehäusehöhe und Drückerkomfort unter der Manschette. Auch selten genutzte Komplikationen brauchen Wartung; berücksichtigen Sie diese statt nur den Kaufpreis.'),
    ['jlcTesting']),
  carreraFormula: topic(
    b('Compare generations, not a prestige hierarchy', 'Generationen statt einer Prestige-Rangfolge vergleichen'),
    b('Carrera began in 1963, Formula 1 in 1986. Both names now cover many watches, so it is misleading to reduce the choice to “mechanical Carrera versus quartz Formula 1”. The exact reference determines movement, dimensions and chronograph functions.', 'Carrera begann 1963, Formula 1 1986. Beide Namen umfassen heute viele Uhren; „mechanische Carrera gegen Quarz-Formula-1“ greift daher zu kurz. Die konkrete Referenz bestimmt Werk, Maße und Chronographenfunktionen.'),
    b('Consider the display and case style you prefer, then compare two specific references within your budget. Quartz convenience and mechanical interest are different preferences, not automatic quality rankings. A busy timing dial can be enjoyable, but check ordinary time legibility and whether the watch sits comfortably.', 'Wählen Sie bevorzugte Anzeige und Gehäusestil und vergleichen Sie zwei konkrete Referenzen im Budget. Quarzkomfort und Freude an Mechanik sind unterschiedliche Vorlieben, keine automatische Qualitätsrangfolge. Ein detailreiches Stoppzifferblatt kann gefallen; normale Ablesbarkeit und bequemer Sitz bleiben wichtig.'),
    b('Use equivalent condition and accessory sets for the price comparison. Ask for service or battery records as appropriate, chronograph operation and correct bracelet length. Choose the reference that fits your routine instead of paying for a family name while overlooking a worn movement or missing parts.', 'Vergleichen Sie Preise bei gleichwertigem Zustand und Zubehör. Fragen Sie je nach Werk nach Service- oder Batteriebelegen, Chronographenfunktion und Bandlänge. Wählen Sie die passende Referenz statt einen Familiennamen zu bezahlen und dabei Verschleiß oder fehlende Teile zu übersehen.'),
    ['tag']),
  connected: topic(
    b('A smartwatch needs a software-and-battery checklist', 'Eine Smartwatch braucht eine Software- und Akkuprüfung'),
    b('TAG Heuer’s Connected Calibre E5 launched in 2025 in 40 mm and 45 mm versions. The E5 uses TAG Heuer OS and the TAG Heuer Connected app; it should not be described using the operating-system assumptions of an earlier Connected generation.', 'TAG Heuers Connected Calibre E5 erschien 2025 in Versionen mit 40 und 45 mm. Die E5 verwendet TAG Heuer OS und die TAG Heuer Connected App. Betriebssystemannahmen früherer Connected-Generationen dürfen nicht auf sie übertragen werden.'),
    b('Verify compatibility with your actual phone and current app requirements before buying. Test pairing, notifications, charging and the features you expect to use. Battery runtime depends on settings and activities; an undated headline figure does not establish the condition of a particular used battery.', 'Prüfen Sie vor dem Kauf die Kompatibilität mit Ihrem Telefon und den aktuellen App-Anforderungen. Testen Sie Kopplung, Benachrichtigungen, Laden und gewünschte Funktionen. Akkulaufzeit hängt von Einstellungen und Aktivitäten ab; eine undatierte Werbezahl bestätigt nicht den Zustand eines gebrauchten Akkus.'),
    b('Confirm the correct charger is included and that the seller removes their personal account and data through the supported reset process. Ask about battery service and current support rather than assuming indefinite software updates. A luxury case does not remove the normal lifecycle considerations of a connected device.', 'Bestätigen Sie das passende Ladegerät und dass der Verkäufer Konto und Daten über den vorgesehenen Rücksetzprozess entfernt. Fragen Sie nach Akkuservice und aktuellem Support statt unbegrenzte Updates vorauszusetzen. Ein Luxusgehäuse beseitigt nicht den üblichen Lebenszyklus eines vernetzten Geräts.'),
    ['tagConnected', 'tagOs']),
  blackBay: topic(
    b('Black Bay is a family, not a single dive-watch specification', 'Black Bay ist eine Familie, keine einzelne Tauchspezifikation'),
    b('Start by identifying which Black Bay you are considering. The family spans different sizes, movements and complications, so a name or dial colour is not enough to compare two listings. A GMT and a chronograph add different functions to a simple time-and-bezel watch.', 'Bestimmen Sie zuerst die konkrete Black Bay. Die Familie umfasst unterschiedliche Größen, Werke und Komplikationen; Name oder Zifferblattfarbe reichen nicht zum Angebotsvergleich. GMT und Chronograph bieten andere Funktionen als eine einfache Uhr mit Zeitlünette.'),
    b('Compare case thickness and bracelet or strap choice as carefully as diameter. A smaller number on the specification sheet does not guarantee a flatter fit. Certification and water-resistance claims must come from the exact reference rather than from another Black Bay advertisement.', 'Vergleichen Sie Höhe und Bandwahl ebenso sorgfältig wie den Durchmesser. Eine kleinere Zahl im Datenblatt garantiert keinen flacheren Sitz. Zertifizierung und Wasserdichtigkeit müssen von der konkreten Referenz stammen, nicht aus einer anderen Black-Bay-Werbung.'),
    b('Check bezel action, crown operation, clasp adjustment and spare links. Ask whether the watch has been refinished and whether the most recent service included sealing tests. Select the design you enjoy, then choose a documented example rather than assuming every watch in the family has identical capabilities.', 'Prüfen Sie Lünette, Krone, Schließenverstellung und zusätzliche Glieder. Fragen Sie nach Aufarbeitung und Dichtigkeitsprüfung beim letzten Service. Wählen Sie zuerst das gewünschte Design und danach ein dokumentiertes Exemplar, statt jeder Uhr der Familie dieselben Fähigkeiten zuzuschreiben.'),
    ['blackBay']),
  blackBayPelagos: topic(
    b('Heritage styling or a more technical diving emphasis?', 'Historischer Stil oder stärker technischer Tauchfokus?'),
    b('Black Bay and Pelagos are both broad Tudor families. Black Bay often appeals through historical design cues; Pelagos places a stronger emphasis on technical diving applications. That distinction is a starting point, not a substitute for comparing specific references.', 'Black Bay und Pelagos sind breite Tudor-Familien. Black Bay spricht oft durch historische Gestaltung an, Pelagos durch einen stärkeren technischen Tauchfokus. Das ist ein Ausgangspunkt, kein Ersatz für den Vergleich konkreter Referenzen.'),
    b('Pelagos, Pelagos 39, LHD, FXD and Ultra should not be assigned one universal size or depth rating. Strap attachment and bezel function can differ too. Likewise, Black Bay includes more than simple dive-style watches. Check metal, weight, clasp and wrist fit before making a choice based on the family reputation.', 'Pelagos, Pelagos 39, LHD, FXD und Ultra haben keine einheitliche Größe oder Tiefenangabe. Auch Bandanschluss und Lünettenfunktion können abweichen. Black Bay umfasst ebenfalls mehr als einfache tauchorientierte Uhren. Prüfen Sie Metall, Gewicht, Schließe und Sitz statt nur den Ruf der Familie.'),
    b('If the watch is for water use, verify intended use and present sealing condition. If it is primarily for daily wear, legibility and comfort may decide the comparison. An FXD’s fixed bars should be considered before assuming you can later fit a conventional bracelet.', 'Für Wassernutzung sind vorgesehener Einsatz und aktuelle Dichtheit zu bestätigen. Im Alltag entscheiden möglicherweise Ablesbarkeit und Komfort. Berücksichtigen Sie die festen FXD-Stege, bevor Sie eine spätere Montage eines gewöhnlichen Metallbands voraussetzen.'),
    ['blackBay', 'pelagos']),
  luminorRadiomir: topic(
    b('The crown and case shape change the experience', 'Krone und Gehäuseform verändern das Tragegefühl'),
    b('Luminor is associated with Panerai’s crown-protection bridge, while Radiomir uses a different crown-and-case outline. Historical Radiomir designs and later case variants also differ in lug construction. Do not assume the two families are the same watch with different names.', 'Luminor ist mit Panerais Kronenschutzbügel verbunden, Radiomir mit einer anderen Kronen- und Gehäusekontur. Historische Radiomir-Entwürfe und spätere Varianten unterscheiden sich auch bei den Hörnern. Beide Familien sind nicht dieselbe Uhr unter anderem Namen.'),
    b('Compare the exact PAM references by width, height, lug span and movement. A Radiomir can offer a less projecting crown-side profile, while the Luminor bridge creates a distinct visual and physical presence. Neither family name alone tells you whether the watch is manual-wind or automatic.', 'Vergleichen Sie genaue PAM-Referenzen nach Breite, Höhe, Hörnerabstand und Werk. Radiomir kann kronenseitig weniger ausladen; der Luminor-Bügel erzeugt eine eigene optische und körperliche Präsenz. Der Familienname allein sagt nicht, ob Handaufzug oder Automatik verbaut ist.'),
    b('Try a similar case on your wrist and inspect strap fit before buying online. For used examples, check the crown or bridge mechanism and strap fasteners without forcing them. Choose the shape you will enjoy wearing; a historical connection does not override practical comfort or a clear service history.', 'Probieren Sie eine ähnliche Gehäuseform und prüfen Sie den Bandsitz vor einem Onlinekauf. Kontrollieren Sie bei gebrauchten Exemplaren Krone beziehungsweise Bügel und Bandbefestigungen ohne Gewalt. Wählen Sie tragbaren Komfort; historische Bezüge ersetzen weder Passform noch nachvollziehbaren Service.'),
    ['panerai']),
  luminorSubmersible: topic(
    b('Do you need a rotating timing bezel?', 'Benötigen Sie eine drehbare Zeitlünette?'),
    b('The most useful starting distinction is Submersible’s rotating timing bezel versus the cleaner bezel treatment of many Luminor references. The additional timing interface changes both appearance and use. Do not infer the same water-resistance rating from a shared crown-protection shape.', 'Der nützlichste Ausgangspunkt ist Submersibles drehbare Zeitlünette gegenüber der ruhigeren Lünette vieler Luminor-Referenzen. Die zusätzliche Zeitmessung verändert Optik und Bedienung. Eine ähnliche Kronenschutzform bedeutet nicht dieselbe Wasserdichtigkeitsangabe.'),
    b('Compare the specific size, material and movement, including the way the strap meets the case. Submersible and Luminor each cover more than one specification, and Luminor Due should not be treated as a default diving option. A more purposeful appearance does not establish current sealing condition.', 'Vergleichen Sie konkrete Größe, Material, Werk und Bandanschluss. Submersible und Luminor umfassen jeweils mehrere Spezifikationen; Luminor Due ist keine pauschale Tauchoption. Ein funktionaleres Aussehen bestätigt außerdem keine heutige Dichtheit.'),
    b('If you want to use the timing bezel, ask for a demonstration and inspect its alignment and action. If you mostly wear the watch with long sleeves, compare thickness and crown-side clearance. For water exposure, follow the exact manual and arrange a current pressure assessment of a used example.', 'Lassen Sie bei geplanter Nutzung der Zeitlünette Funktion und Ausrichtung vorführen. Unter langen Ärmeln sind Höhe und Platz an der Kronenseite wichtig. Für Wasserkontakt beachten Sie die konkrete Anleitung und lassen ein gebrauchtes Exemplar aktuell prüfen.'),
    ['panerai']),
  serpenti: topic(
    b('A bracelet-led watch must fit before anything else', 'Eine bandgeprägte Uhr muss zuerst passen'),
    b('Serpenti is a design family, not one bracelet or movement specification. Bvlgari’s Tubogas watch history reaches back to 1948, but modern Serpenti references use different constructions, materials and mechanisms. Begin with the exact design and wrist size rather than assuming every example wraps or adjusts in the same way.', 'Serpenti ist eine Designfamilie, keine einzelne Band- oder Werkspezifikation. Bvlgaris Tubogas-Uhrengeschichte reicht bis 1948 zurück, moderne Serpenti-Referenzen unterscheiden sich aber bei Aufbau, Material und Mechanik. Beginnen Sie mit Design und Handgelenkgröße statt gleiche Wicklung oder Verstellung vorauszusetzen.'),
    b('A jewellery-style watch should be assessed for comfort and security as well as dial condition. Ask for the intended wrist-size range, the number of wraps where relevant, clasp operation and a complete description of stones or later alterations. Do not categorise every Serpenti as quartz; check the actual reference.', 'Eine schmuckartige Uhr sollte nach Komfort und Sicherheit ebenso wie nach Zifferblattzustand bewertet werden. Fragen Sie nach Handgelenkbereich, gegebenenfalls Windungen, Schließe sowie Steinen oder späteren Änderungen. Ordnen Sie nicht jede Serpenti Quarz zu; prüfen Sie die Referenz.'),
    b('Request close-ups of areas that flex and touch the wrist. Confirm what adjustments are possible and whether they need a specialist. Choose fit over an attractive photograph: a watch that is too loose, too tight or altered to fit someone else may require more than an ordinary strap change.', 'Fordern Sie Nahaufnahmen beweglicher und hautberührender Bereiche an. Klären Sie mögliche Anpassungen und ob Facharbeit nötig ist. Passform geht vor einem schönen Foto: Eine zu lockere, enge oder für jemand anderen veränderte Uhr benötigt möglicherweise mehr als einen gewöhnlichen Bandwechsel.'),
    ['bvlgari']),
  octo: topic(
    b('Ultra-thin does not mean one universal specification', 'Ultraflach bedeutet keine einheitliche Spezifikation'),
    b('Octo Finissimo combines a geometric case with a focus on thinness. As a concrete example, rose-gold reference 102912 uses the BVL 138 automatic calibre and has a stated 5.15 mm case thickness. Other Octo Finissimo references differ; the steel 103431 is listed at 6.4 mm.', 'Octo Finissimo verbindet ein geometrisches Gehäuse mit besonderer Flachheit. Als konkretes Beispiel nutzt die Roségold-Referenz 102912 das automatische Kaliber BVL 138 bei angegebenen 5,15 mm Gehäusehöhe. Andere Referenzen unterscheiden sich; die Stahlversion 103431 wird mit 6,4 mm geführt.'),
    b('Compare the full reference for material, surface finish, thickness and water resistance. A specification from an early thin dress reference must not be applied to every later steel model. The broad case outline also means a thin watch can still cover a substantial area of the wrist.', 'Vergleichen Sie Material, Oberflächen, Höhe und Wasserdichtigkeit anhand der vollständigen Referenz. Daten einer frühen flachen Dresswatch gelten nicht für jedes spätere Stahlmodell. Die breite Kontur bedeutet außerdem, dass auch eine flache Uhr viel Handgelenkfläche bedecken kann.'),
    b('Inspect case edges, bracelet joints and clasp condition, and obtain the correct operating instructions. Avoid treating thinness as evidence of impact resistance. Ask about servicing and any prior damage; a carefully documented example is a better basis for ownership than a record-thinness headline alone.', 'Prüfen Sie Gehäusekanten, Bandgelenke und Schließe und besorgen Sie die passende Anleitung. Flachheit ist kein Nachweis von Stoßfestigkeit. Fragen Sie nach Wartung und Vorschäden; ein gut dokumentiertes Exemplar ist wertvoller als allein eine Schlagzeile über Rekordhöhe.'),
    ['octo', 'octoSteel']),
  laureato: topic(
    b('Look at the whole integrated-bracelet design', 'Das gesamte integrierte Banddesign betrachten'),
    b('The Laureato began in 1975. Its appeal is not captured by a dial photograph alone: case, bezel and bracelet form a continuous design. Modern Laureato references vary in size, material and movement, so the collection name should begin the search rather than finish the specification.', 'Die Laureato begann 1975. Ihre Wirkung lässt sich nicht allein am Zifferblattfoto beurteilen: Gehäuse, Lünette und Band bilden ein zusammenhängendes Design. Moderne Referenzen variieren bei Größe, Material und Werk; der Kollektionsname beginnt daher die Suche, statt die Spezifikation abzuschließen.'),
    b('Compare case thickness, bracelet taper and articulation around your wrist. An integrated bracelet may not accept ordinary replacement straps, so confirm available alternatives rather than assuming a simple swap. Surface finishing is part of the design and deserves careful condition photographs.', 'Vergleichen Sie Gehäusehöhe, Bandverjüngung und Beweglichkeit am Handgelenk. Ein integriertes Band erlaubt nicht automatisch gewöhnliche Ersatzbänder; klären Sie Alternativen statt einen einfachen Wechsel vorauszusetzen. Oberflächenfinish gehört zum Design und verdient genaue Zustandsfotos.'),
    b('Ask for all spare links, clasp condition and a service history linked to the correct reference. If choosing an earlier example, distinguish it from a modern reissue rather than transferring current specifications. Assess the individual watch on its own merits, not just as an alternative to another brand’s integrated-bracelet model.', 'Fragen Sie nach zusätzlichen Gliedern, Schließenzustand und referenzbezogener Wartungshistorie. Unterscheiden Sie frühere Exemplare von modernen Neuinterpretationen, statt aktuelle Daten zu übertragen. Beurteilen Sie die Uhr eigenständig, nicht nur als Alternative zu einem integrierten Bandmodell einer anderen Marke.'),
    ['laureato']),
  jackpot: topic(
    b('A miniature mechanical performance, not an ordinary complication', 'Ein mechanisches Schauspiel, keine gewöhnliche Komplikation'),
    b('Girard-Perregaux’s Vintage 1945 Jackpot Tourbillon combines a tourbillon with a miniature slot-machine display and chiming mechanism. Christie’s documents reference 99720 and the model’s 2007 introduction. “Vintage 1945” is the design-family name here, not the production year of the auctioned watch.', 'Girard-Perregaux’ Vintage 1945 Jackpot Tourbillon verbindet ein Tourbillon mit einer Miniatur-Spielautomatenanzeige und einem Schlagmechanismus. Christie’s dokumentiert Referenz 99720 und die Einführung 2007. „Vintage 1945“ bezeichnet hier die Designfamilie, nicht das Produktionsjahr des versteigerten Exemplars.'),
    b('Treat an auction catalogue as evidence for the described lot, not as a current quotation for every Jackpot. Material, condition, accessories, sale date and fees all matter. The mechanism is a horological display; descriptions should not imply a financial payout or turn rarity into a promise of investment return.', 'Ein Auktionskatalog belegt das beschriebene Los, nicht einen aktuellen Preis für jede Jackpot. Material, Zustand, Zubehör, Verkaufsdatum und Gebühren zählen. Der Mechanismus ist eine uhrmacherische Anzeige; Beschreibungen sollten weder Geldgewinne noch garantierte Anlagerenditen suggerieren.'),
    b('For a purchase, require a specialist demonstration and a manufacturer or qualified specialist service opinion covering every mechanism. Clarify transport, insurance and parts support before agreeing a price. Exceptional complexity is part of the appeal, but it also makes a generic condition statement inadequate.', 'Verlangen Sie vor einem Kauf eine fachkundige Vorführung und eine Hersteller- oder Spezialisteneinschätzung für alle Mechanismen. Klären Sie Transport, Versicherung und Teileversorgung vor der Preisvereinbarung. Außergewöhnliche Komplexität ist reizvoll, macht aber eine allgemeine Zustandsfloskel unzureichend.'),
    ['jackpot']),
};

export function guideTopic(slug) {
  if (slug.endsWith('-story')) return 'story';
  if (slug.startsWith('welche-')) return 'choice';
  if (slug.endsWith('-neu-oder-gebraucht')) return 'newPreowned';
  if (slug.endsWith('-maintenance')) return 'maintenance';
  if (/(?:-uhr-preis|-uhren-preise)$/.test(slug) || slug.startsWith('was-kostet-')) return 'price';
  if (/(?:-alte-modelle)$/.test(slug) || slug === 'vintage-girard-perregaux-uhren') return 'vintage';
  return {
    'rolex-box-papers-guide': 'papers',
    'rolex-watchmaking': 'rolexMechanics',
    'patek-philippe-archives-extract-guide': 'archives',
    'patek-philippe-watchmaking': 'patekMechanics',
    'omega-watchmaking': 'coaxial',
    'omega-co-axial-guide': 'coaxial',
    'omega-master-chronometer-guide': 'metas',
    'omega-speedmaster-oder-seamaster': 'speedSeamaster',
    'audemars-piguet-teuerste-uhr': 'exceptional',
    'grand-seiko-spring-drive-guide': 'springDrive',
    'grand-seiko-snowflake-vs-shunbun': 'snowflakeShunbun',
    'iwc-schaffhausen-automatic-guide': 'iwcAutomatic',
    'iwc-schaffhausen-pilot-watch-guide': 'pilot',
    'iwc-schaffhausen-ingenieur-guide': 'ingenieur',
    'jaeger-lecoultre-reverso-duoface': 'duoface',
    'jaeger-lecoultre-master-chronograph': 'masterChronograph',
    'tag-heuer-carrera-vs-formula-1': 'carreraFormula',
    'tag-heuer-connected-calibre-e5-guide': 'connected',
    'tudor-black-bay-guide': 'blackBay',
    'tudor-black-bay-vs-pelagos': 'blackBayPelagos',
    'panerai-luminor-vs-radiomir': 'luminorRadiomir',
    'panerai-luminor-vs-submersible': 'luminorSubmersible',
    'bvlgari-serpenti-watch': 'serpenti',
    'bvlgari-serpenti-guide': 'serpenti',
    'bvlgari-octo-finissimo-guide': 'octo',
    'girard-perregaux-laureato-guide': 'laureato',
    'girard-perregaux-jackpot': 'jackpot',
  }[slug] || null;
}
